CREATE VIEW ODS.VW_ODS_FTO_DADOS_FLUXO 
AS
SELECT 
					 DF.CO_CURSO
					,DF.CO_MUNICIPIO					CO_MUNICIPIO
					,IES.TP_REDE
					,DF.CO_IES
					,C.CO_AREA
					,DF.TP_GRAU_ACADEMICO				TP_GRAU_ACADEMICO
					,DF.TP_MODALIDADE_ENSINO			TP_MODALIDADE_ENSINO
					,c.TP_NIVEL_ACADEMICO			TP_NIVEL_ACADEMICO
					,IES.TP_ORGANIZACAO_ACADEMICA		TP_ORGANIZACAO_ACADEMICA
					,IES.TP_CATEGORIA_ADMINISTRATIVA 	TP_CATEGORIA_ADMINISTRATIVA
					,DF.NU_ANO_CENSO					NU_ANO_CENSO
					,DF.NU_ANO_INGRESSO
					,DF.NU_PRAZO_INTEGRALIZACAO
					,DF.NU_ANO_INTEGRALIZACAO
					,DF.NU_PRAZO_ACOMPANHAMENTO
					,DF.NU_ANO_MAXIMO_ACOMPANHAMENTO
					,DF.QT_INGRESSANTE
					,DF.QT_PERMANENCIA
					,DF.QT_CONCLUINTE
					,DF.QT_DESISTENCIA
					,DF.QT_FALECIDO
					,DF.VL_TAP
					,DF.VL_TCA
					,DF.VL_TDA
					,DF.VL_TCAN
					,DF.VL_TDAN
			-- 		,DF.CO_CATALOGO
				FROM 		ODS.ODS_DADOS_FLUXO	DF 
				LEFT JOIN	ODS.ODS_CURSO		C		ON	DF.CO_CURSO		=	C.CO_CURSO
				LEFT  JOIN	ODS.ODS_IES			IES		ON	DF.CO_IES		=	IES.CO_IES