CREATE   PROCEDURE adm.SP_FLUXO_ETL as

BEGIN

	exec ods.SP_ODS_CINE_CURSO_AREA
	exec ods.sp_ODS_CINE_CURSO_GRANDE_AREA
	exec ods.SP_ODS_CURSO
	exec ods.SP_ODS_UNIDADE_FEDERATIVA
	exec ods.SP_ODS_MUNICIPIO
	exec ods.SP_ODS_MANTENEDORA
	exec ods.SP_ODS_IES
	exec ods.SP_ODS_DADOS_FLUXO
	exec DW.SP_DIM_IES
	exec DW.SP_DIM_CURSO
	exec DW.SP_DIM_CINE
	exec DW.SP_dim_REGIAO
	exec DW.SP_FTO_DADOS_FLUXO

END
