

CREATE      PROCEDURE [DW].[SP_DIM_CURSO]		AS
BEGIN 
	DECLARE @DTA_EXECUCAO DATETIME2(2) = GETDATE()
--	TEMPDB..SP_HELP '#ODS_CURSO'


	MERGE INTO 	[DW].[DIM_CURSO]	WITH (TABLOCK) AS DESTINO
	USING	(											
			SELECT 
				 CO_CURSO
				,NO_CURSO
			FROM ODS.ODS_CURSO 
		) AS ORIGEM
	ON 	(	
			DESTINO.CO_CURSO		=	ORIGEM.CO_CURSO 
		)
	WHEN NOT MATCHED THEN
		INSERT
			(	
				 CO_CURSO
				,NO_CURSO
			)	
			VALUES
			(	 
				 ORIGEM.CO_CURSO 
				,ORIGEM.NO_CURSO
			)																					
	WHEN MATCHED AND
	(    
		(ORIGEM.NO_CURSO			<>	DESTINO.NO_CURSO			OR	(ORIGEM.NO_CURSO			IS NULL AND DESTINO.NO_CURSO			IS NOT NULL)	OR	(ORIGEM.NO_CURSO			IS NOT NULL AND DESTINO.NO_CURSO		IS NULL))	
	)
	THEN UPDATE
		SET		
			 DESTINO.NO_CURSO			=	ORIGEM.NO_CURSO
	;	
END 
