

CREATE      PROCEDURE [DW].[SP_DIM_IES]		AS
BEGIN 
	MERGE INTO 	[DW].[DIM_IES]	WITH (TABLOCK) AS DESTINO
	USING	(											
			SELECT	IES.CO_IES, 
					IES.NO_IES, 
					IES.SG_IES, 
					IES.IN_CAPITAL,
					IES.TP_ORGANIZACAO_ACADEMICA, 
					IES.TP_CATEGORIA_ADMINISTRATIVA, 
					MI.CO_MANTENEDORA, 
					MI.NO_MANTENEDORA
			FROM ODS.ODS_IES IES
			left JOIN ODS.ODS_MANTENEDORA_IES MI
			ON IES.CO_MANTENEDORA = MI.CO_MANTENEDORA
		) AS ORIGEM
	ON 	(	
			DESTINO.CO_IES		=	ORIGEM.CO_IES 
		)
	WHEN NOT MATCHED THEN
		INSERT
			(	
				 CO_IES
				,NO_IES
				,SG_IES
				,IN_CAPITAL
				,TP_ORGANIZACAO_ACADEMICA
				,TP_CATEGORIA_ADMINISTRATIVA
				,CO_MANTENEDORA
				,NO_MANTENEDORA
			)	
			VALUES
			(	 
			 
				ORIGEM.CO_IES
				,ORIGEM.NO_IES
				,ORIGEM.SG_IES
				,ORIGEM.IN_CAPITAL
				,ORIGEM.TP_ORGANIZACAO_ACADEMICA
				,ORIGEM.TP_CATEGORIA_ADMINISTRATIVA
				,ORIGEM.CO_MANTENEDORA
				,ORIGEM.NO_MANTENEDORA
			)																					
	WHEN MATCHED AND
	(    
		(ORIGEM.NO_IES						<>	DESTINO.NO_IES							OR	(ORIGEM.NO_IES							IS NULL AND DESTINO.NO_IES							IS NOT NULL)	OR	(ORIGEM.NO_IES							IS NOT NULL AND DESTINO.NO_IES							IS NULL))	OR 
		(ORIGEM.SG_IES						<>	DESTINO.SG_IES							OR	(ORIGEM.SG_IES							IS NULL AND DESTINO.SG_IES							IS NOT NULL)	OR	(ORIGEM.SG_IES							IS NOT NULL AND DESTINO.SG_IES							IS NULL))	OR 
		(ORIGEM.IN_CAPITAL					<>	DESTINO.IN_CAPITAL						OR	(ORIGEM.IN_CAPITAL						IS NULL AND DESTINO.IN_CAPITAL						IS NOT NULL)	OR	(ORIGEM.IN_CAPITAL						IS NOT NULL AND DESTINO.IN_CAPITAL						IS NULL))	OR 
		(ORIGEM.TP_ORGANIZACAO_ACADEMICA	<>	DESTINO.TP_ORGANIZACAO_ACADEMICA		OR	(ORIGEM.TP_ORGANIZACAO_ACADEMICA		IS NULL AND DESTINO.TP_ORGANIZACAO_ACADEMICA		IS NOT NULL)	OR	(ORIGEM.TP_ORGANIZACAO_ACADEMICA		IS NOT NULL AND DESTINO.TP_ORGANIZACAO_ACADEMICA		IS NULL))	OR 
		(ORIGEM.TP_CATEGORIA_ADMINISTRATIVA	<>	DESTINO.TP_CATEGORIA_ADMINISTRATIVA		OR	(ORIGEM.TP_CATEGORIA_ADMINISTRATIVA		IS NULL AND DESTINO.TP_CATEGORIA_ADMINISTRATIVA		IS NOT NULL)	OR	(ORIGEM.TP_CATEGORIA_ADMINISTRATIVA		IS NOT NULL AND DESTINO.TP_CATEGORIA_ADMINISTRATIVA		IS NULL))	OR 
		(ORIGEM.CO_MANTENEDORA				<>	DESTINO.CO_MANTENEDORA					OR	(ORIGEM.CO_MANTENEDORA					IS NULL AND DESTINO.CO_MANTENEDORA					IS NOT NULL)	OR	(ORIGEM.CO_MANTENEDORA					IS NOT NULL AND DESTINO.CO_MANTENEDORA					IS NULL))	OR 
		(ORIGEM.NO_MANTENEDORA				<>	DESTINO.NO_MANTENEDORA					OR	(ORIGEM.NO_MANTENEDORA					IS NULL AND DESTINO.NO_MANTENEDORA					IS NOT NULL)	OR	(ORIGEM.NO_MANTENEDORA					IS NOT NULL AND DESTINO.NO_MANTENEDORA					IS NULL))	
	)
	THEN UPDATE
		SET		
		 DESTINO.NO_IES							 = ORIGEM.NO_IES						
		,DESTINO.SG_IES							 = ORIGEM.SG_IES						
		,DESTINO.IN_CAPITAL						 = ORIGEM.IN_CAPITAL					
		,DESTINO.TP_ORGANIZACAO_ACADEMICA		 = ORIGEM.TP_ORGANIZACAO_ACADEMICA	
		,DESTINO.TP_CATEGORIA_ADMINISTRATIVA	 = ORIGEM.TP_CATEGORIA_ADMINISTRATIVA	
		,DESTINO.CO_MANTENEDORA					 = ORIGEM.CO_MANTENEDORA				
		,DESTINO.NO_MANTENEDORA					 = ORIGEM.NO_MANTENEDORA				
	;	
END 


