create PROCEDURE [DW].[SP_dim_REGIAO]		AS
BEGIN 
	
	MERGE INTO 	[DW].[DIM_REGIAO]	WITH (TABLOCK) AS DESTINO
	USING	(											
		SELECT	
			MN.CO_MUNICIPIO, 
			MN.NO_MUNICIPIO, 
			UF.CO_UF, 
			UF.NO_UF, 
			UF.SG_UF,
			RG.CO_REGIAO,
			RG.NO_REGIAO, 
			CASE WHEN CPT.SG_UF IS NULL THEN 0  ELSE 1 END FL_CAPITAL 
		FROM 
						ODS.ODS_MUNICIPIO				MN 
		INNER	JOIN	ODS.ODS_UNIDADE_FEDERATIVA		UF	ON	UF.CO_UF			=	MN.CO_UF
		INNER	JOIN	ODS.VW_ODS_REGIAO				RG	ON	RG.CO_REGIAO		=	UF.CO_REGIAO
		LEFT	JOIN	ODS.VW_ODS_MUNICICIPIO_CAPITAL	CPT ON	CPT.NO_MUNICIPIO	=	MN.NO_MUNICIPIO	AND 
																CPT.SG_UF			=	UF.NO_UF
		) AS ORIGEM
	ON 	(	
			DESTINO.CO_MUNICIPIO		=	ORIGEM.CO_MUNICIPIO	AND 
			DESTINO.CO_UF				=	ORIGEM.CO_UF 
		)
	WHEN NOT MATCHED THEN
		INSERT
			(	
				CO_MUNICIPIO, 
				NO_MUNICIPIO, 
				CO_UF, 
				NO_UF, 
				SG_UF,
				CO_REGIAO,
				NO_REGIAO,
				FL_CAPITAL 
			)	
			VALUES
			(	 
				ORIGEM.CO_MUNICIPIO, 
				ORIGEM.NO_MUNICIPIO, 
				ORIGEM.CO_UF, 
				ORIGEM.NO_UF, 
				ORIGEM.SG_UF,
				ORIGEM.CO_REGIAO,
				ORIGEM.NO_REGIAO,
				FL_CAPITAL 
			)																					
	WHEN MATCHED AND
	(    
		(ORIGEM.NO_MUNICIPIO	<>	DESTINO.NO_MUNICIPIO	OR	(ORIGEM.NO_MUNICIPIO	IS NULL AND DESTINO.NO_MUNICIPIO	IS NOT NULL)	OR	(ORIGEM.NO_MUNICIPIO	IS NOT NULL AND DESTINO.NO_MUNICIPIO	IS NULL))	OR 
		(ORIGEM.CO_UF			<>	DESTINO.CO_UF			OR	(ORIGEM.CO_UF			IS NULL AND DESTINO.CO_UF			IS NOT NULL)	OR	(ORIGEM.CO_UF			IS NOT NULL AND DESTINO.CO_UF			IS NULL))	OR 
		(ORIGEM.NO_UF			<>	DESTINO.NO_UF			OR	(ORIGEM.NO_UF			IS NULL AND DESTINO.NO_UF			IS NOT NULL)	OR	(ORIGEM.NO_UF			IS NOT NULL AND DESTINO.NO_UF			IS NULL))	OR 
		(ORIGEM.SG_UF			<>	DESTINO.SG_UF			OR	(ORIGEM.SG_UF			IS NULL AND DESTINO.SG_UF			IS NOT NULL)	OR	(ORIGEM.SG_UF			IS NOT NULL AND DESTINO.SG_UF			IS NULL))	OR 
		(ORIGEM.CO_REGIAO		<>	DESTINO.CO_REGIAO		OR	(ORIGEM.CO_REGIAO		IS NULL AND DESTINO.CO_REGIAO		IS NOT NULL)	OR	(ORIGEM.CO_REGIAO		IS NOT NULL AND DESTINO.CO_REGIAO		IS NULL))	OR 
		(ORIGEM.NO_REGIAO		<>	DESTINO.NO_REGIAO		OR	(ORIGEM.NO_REGIAO		IS NULL AND DESTINO.NO_REGIAO		IS NOT NULL)	OR	(ORIGEM.NO_REGIAO		IS NOT NULL AND DESTINO.NO_REGIAO		IS NULL))	OR 
		(ORIGEM.FL_CAPITAL		<>	DESTINO.FL_CAPITAL		OR	(ORIGEM.FL_CAPITAL		IS NULL AND DESTINO.FL_CAPITAL		IS NOT NULL)	OR	(ORIGEM.FL_CAPITAL		IS NOT NULL AND DESTINO.FL_CAPITAL		IS NULL))	
	)
	THEN UPDATE
		SET		
		 DESTINO.NO_MUNICIPIO	 = ORIGEM.NO_MUNICIPIO
		,DESTINO.CO_UF			 = ORIGEM.CO_UF		
		,DESTINO.NO_UF			 = ORIGEM.NO_UF		
		,DESTINO.SG_UF			 = ORIGEM.SG_UF		
		,DESTINO.CO_REGIAO		 = ORIGEM.CO_REGIAO	
		,DESTINO.NO_REGIAO		 = ORIGEM.NO_REGIAO	
		,DESTINO.FL_CAPITAL		 = ORIGEM.FL_CAPITAL	
	;	
END 


