

CREATE      PROCEDURE [DW].[SP_DIM_CINE]		AS
BEGIN 
	DECLARE @DTA_EXECUCAO DATETIME2(2) = GETDATE()
--	TEMPDB..SP_HELP '#ODS_CURSO'


	MERGE INTO 	[DW].[DIM_CINE]	WITH (TABLOCK) AS DESTINO
	USING	(											
		select 
			CA.COD_AREA			CO_AREA, 
			CA.NME_AREA			NO_AREA,
			CGA.COD_GRANDE_AREA CO_GRANDE_AREA,
			CGA.NME_GRANDE_AREA NO_GRANDE_AREA
		from 
					ods.ODS_CINE_CURSO_AREA CA
		INNER JOIN	ods.ODS_CINE_CURSO_GRANDE_AREA CGA	ON	CA.COD_GRANDE_AREA	=	CGA.COD_GRANDE_AREA

		) AS ORIGEM
	ON 	(	
			DESTINO.CO_AREA		=	ORIGEM.CO_AREA	 
		)
	WHEN NOT MATCHED THEN
		INSERT
			(	
				 CO_AREA 
				,NO_AREA
				,CO_GRANDE_AREA
				,NO_GRANDE_AREA
			)	
			VALUES
			(	 
				 ORIGEM.CO_AREA 
				,ORIGEM.NO_AREA
				,ORIGEM.CO_GRANDE_AREA
				,ORIGEM.NO_GRANDE_AREA
			)																					
	WHEN MATCHED AND
	(    
		(ORIGEM.NO_AREA			<>	DESTINO.NO_AREA			OR	(ORIGEM.NO_AREA			IS NULL AND DESTINO.NO_AREA			IS NOT NULL)	OR	(ORIGEM.NO_AREA			IS NOT NULL AND DESTINO.NO_AREA		IS NULL))	OR
		(ORIGEM.CO_GRANDE_AREA		<>	DESTINO.CO_GRANDE_AREA		OR	(ORIGEM.CO_GRANDE_AREA		IS NULL AND DESTINO.CO_GRANDE_AREA		IS NOT NULL)	OR	(ORIGEM.CO_GRANDE_AREA		IS NOT NULL AND DESTINO.CO_GRANDE_AREA	IS NULL))	OR
		(ORIGEM.NO_GRANDE_AREA		<>	DESTINO.NO_GRANDE_AREA		OR	(ORIGEM.NO_GRANDE_AREA		IS NULL AND DESTINO.NO_GRANDE_AREA		IS NOT NULL)	OR	(ORIGEM.NO_GRANDE_AREA		IS NOT NULL AND DESTINO.NO_GRANDE_AREA	IS NULL))
	)
	THEN UPDATE
		SET		
			 DESTINO.NO_AREA			=	ORIGEM.NO_AREA		
			,DESTINO.CO_GRANDE_AREA	=	ORIGEM.CO_GRANDE_AREA	
			,DESTINO.NO_GRANDE_AREA	=	ORIGEM.NO_GRANDE_AREA	

	;	
END 
