
CREATE        PROCEDURE DW.[SP_FTO_DADOS_FLUXO]		AS
BEGIN 
	DECLARE @DTA_EXECUCAO DATETIME2(2) = GETDATE()

	MERGE INTO DW.FTO_DADOS_FLUXO		WITH (TABLOCK) AS DESTINO
	USING	(SELECT * FROM ODS.VW_ODS_FTO_DADOS_FLUXO ) AS ORIGEM
	ON 	(	origem.CO_IES			= destino.CO_IES				and 
			origem.CO_CURSO			= destino.CO_CURSO				and 
			origem.CO_MUNICIPIO		= destino.CO_MUNICIPIO			and 
			origem.NU_ANO_CENSO		= destino.NU_ANO_CENSO			and 
			origem.NU_ANO_INGRESSO	= destino.NU_ANO_INGRESSO		
		)
	WHEN NOT MATCHED THEN
		INSERT
			(	
			 CO_CURSO
			,CO_MUNICIPIO
			,TP_REDE
			,CO_IES
			,CO_AREA
			,TP_GRAU_ACADEMICO
			,TP_MODALIDADE_ENSINO
			,TP_NIVEL_ACADEMICO
			,TP_ORGANIZACAO_ACADEMICA
			,TP_CATEGORIA_ADMINISTRATIVA
			,NU_ANO_CENSO
			,NU_ANO_INGRESSO
			,NU_PRAZO_INTEGRALIZACAO
			,NU_ANO_INTEGRALIZACAO
			,NU_PRAZO_ACOMPANHAMENTO
			,NU_ANO_MAXIMO_ACOMPANHAMENTO
			,QT_INGRESSANTE
			,QT_PERMANENCIA
			,QT_CONCLUINTE
			,QT_DESISTENCIA
			,QT_FALECIDO
			,VL_TAP
			,VL_TCA
			,VL_TDA
			,VL_TCAN
			,VL_TDAN
			)	
			VALUES
			(	 
			 ORIGEM.CO_CURSO
			,ORIGEM.CO_MUNICIPIO
			,ORIGEM.TP_REDE
			,ORIGEM.CO_IES
			,ORIGEM.CO_AREA
			,ORIGEM.TP_GRAU_ACADEMICO
			,ORIGEM.TP_MODALIDADE_ENSINO
			,ORIGEM.TP_NIVEL_ACADEMICO
			,ORIGEM.TP_ORGANIZACAO_ACADEMICA
			,ORIGEM.TP_CATEGORIA_ADMINISTRATIVA
			,ORIGEM.NU_ANO_CENSO
			,ORIGEM.NU_ANO_INGRESSO
			,ORIGEM.NU_PRAZO_INTEGRALIZACAO
			,ORIGEM.NU_ANO_INTEGRALIZACAO
			,ORIGEM.NU_PRAZO_ACOMPANHAMENTO
			,ORIGEM.NU_ANO_MAXIMO_ACOMPANHAMENTO
			,ORIGEM.QT_INGRESSANTE
			,ORIGEM.QT_PERMANENCIA
			,ORIGEM.QT_CONCLUINTE
			,ORIGEM.QT_DESISTENCIA
			,ORIGEM.QT_FALECIDO
			,ORIGEM.VL_TAP
			,ORIGEM.VL_TCA
			,ORIGEM.VL_TDA
			,ORIGEM.VL_TCAN
			,ORIGEM.VL_TDAN
			)																					
	WHEN MATCHED AND
	(    
	--	(ORIGEM.CO_CURSO						IS NULL	OR (DESTINO.CO_CURSO						IS NULL AND DESTINO.CO_CURSO					 IS NOT NULL)	OR	(ORIGEM.CO_CURSO						IS NOT NULL AND DESTINO.DESTINO.CO_CURSO							IS NULL))	OR
	--	(ORIGEM.CO_MUNICIPIO					IS NULL	OR (DESTINO.CO_MUNICIPIO					IS NULL AND DESTINO.CO_MUNICIPIO				 IS NOT NULL)	OR	(ORIGEM.CO_MUNICIPIO					IS NOT NULL AND DESTINO.DESTINO.CO_MUNICIPIO						IS NULL))	OR
		(ORIGEM.TP_REDE							IS NULL	OR (DESTINO.TP_REDE							IS NULL AND DESTINO.TP_REDE						 IS NOT NULL)	OR	(ORIGEM.TP_REDE							IS NOT NULL AND DESTINO.TP_REDE								IS NULL))	OR
	--	(ORIGEM.CO_IES							IS NULL	OR (DESTINO.CO_IES							IS NULL AND DESTINO.CO_IES						 IS NOT NULL)	OR	(ORIGEM.CO_IES							IS NOT NULL AND DESTINO.CO_IES								IS NULL))	OR
		(ORIGEM.CO_AREA							IS NULL	OR (DESTINO.CO_AREA							IS NULL AND DESTINO.CO_AREA						 IS NOT NULL)	OR	(ORIGEM.CO_AREA							IS NOT NULL AND DESTINO.CO_AREA								IS NULL))	OR
		(ORIGEM.TP_GRAU_ACADEMICO				IS NULL	OR (DESTINO.TP_GRAU_ACADEMICO				IS NULL AND DESTINO.TP_GRAU_ACADEMICO			 IS NOT NULL)	OR	(ORIGEM.TP_GRAU_ACADEMICO				IS NOT NULL AND DESTINO.TP_GRAU_ACADEMICO					IS NULL))	OR
		(ORIGEM.TP_MODALIDADE_ENSINO			IS NULL	OR (DESTINO.TP_MODALIDADE_ENSINO			IS NULL AND DESTINO.TP_MODALIDADE_ENSINO		 IS NOT NULL)	OR	(ORIGEM.TP_MODALIDADE_ENSINO			IS NOT NULL AND DESTINO.TP_MODALIDADE_ENSINO				IS NULL))	OR
		(ORIGEM.TP_NIVEL_ACADEMICO				IS NULL	OR (DESTINO.TP_NIVEL_ACADEMICO				IS NULL AND DESTINO.TP_NIVEL_ACADEMICO			 IS NOT NULL)	OR	(ORIGEM.TP_NIVEL_ACADEMICO				IS NOT NULL AND DESTINO.TP_NIVEL_ACADEMICO					IS NULL))	OR
		(ORIGEM.TP_ORGANIZACAO_ACADEMICA		IS NULL	OR (DESTINO.TP_ORGANIZACAO_ACADEMICA		IS NULL AND DESTINO.TP_ORGANIZACAO_ACADEMICA	 IS NOT NULL)	OR	(ORIGEM.TP_ORGANIZACAO_ACADEMICA		IS NOT NULL AND DESTINO.TP_ORGANIZACAO_ACADEMICA			IS NULL))	OR
		(ORIGEM.TP_CATEGORIA_ADMINISTRATIVA		IS NULL	OR (DESTINO.TP_CATEGORIA_ADMINISTRATIVA		IS NULL AND DESTINO.TP_CATEGORIA_ADMINISTRATIVA	 IS NOT NULL)	OR	(ORIGEM.TP_CATEGORIA_ADMINISTRATIVA		IS NOT NULL AND DESTINO.TP_CATEGORIA_ADMINISTRATIVA			IS NULL))	OR
	--	(ORIGEM.NU_ANO_CENSO					IS NULL	OR (DESTINO.NU_ANO_CENSO					IS NULL AND DESTINO.NU_ANO_CENSO				 IS NOT NULL)	OR	(ORIGEM.NU_ANO_CENSO					IS NOT NULL AND DESTINO.NU_ANO_CENSO						IS NULL))	OR
	--	(ORIGEM.NU_ANO_INGRESSO					IS NULL	OR (DESTINO.NU_ANO_INGRESSO					IS NULL AND DESTINO.NU_ANO_INGRESSO				 IS NOT NULL)	OR	(ORIGEM.NU_ANO_INGRESSO					IS NOT NULL AND DESTINO.NU_ANO_INGRESSO						IS NULL))	OR
		(ORIGEM.NU_PRAZO_INTEGRALIZACAO			IS NULL	OR (DESTINO.NU_PRAZO_INTEGRALIZACAO			IS NULL AND DESTINO.NU_PRAZO_INTEGRALIZACAO		 IS NOT NULL)	OR	(ORIGEM.NU_PRAZO_INTEGRALIZACAO			IS NOT NULL AND DESTINO.NU_PRAZO_INTEGRALIZACAO				IS NULL))	OR
		(ORIGEM.NU_ANO_INTEGRALIZACAO			IS NULL	OR (DESTINO.NU_ANO_INTEGRALIZACAO			IS NULL AND DESTINO.NU_ANO_INTEGRALIZACAO		 IS NOT NULL)	OR	(ORIGEM.NU_ANO_INTEGRALIZACAO			IS NOT NULL AND DESTINO.NU_ANO_INTEGRALIZACAO				IS NULL))	OR
		(ORIGEM.NU_PRAZO_ACOMPANHAMENTO			IS NULL	OR (DESTINO.NU_PRAZO_ACOMPANHAMENTO			IS NULL AND DESTINO.NU_PRAZO_ACOMPANHAMENTO		 IS NOT NULL)	OR	(ORIGEM.NU_PRAZO_ACOMPANHAMENTO			IS NOT NULL AND DESTINO.NU_PRAZO_ACOMPANHAMENTO				IS NULL))	OR
		(ORIGEM.NU_ANO_MAXIMO_ACOMPANHAMENTO	IS NULL	OR (DESTINO.NU_ANO_MAXIMO_ACOMPANHAMENTO	IS NULL AND DESTINO.NU_ANO_MAXIMO_ACOMPANHAMENTO IS NOT NULL)	OR	(ORIGEM.NU_ANO_MAXIMO_ACOMPANHAMENTO	IS NOT NULL AND DESTINO.NU_ANO_MAXIMO_ACOMPANHAMENTO		IS NULL))	OR
		(ORIGEM.QT_INGRESSANTE					IS NULL OR (DESTINO.QT_INGRESSANTE					IS NULL AND DESTINO.QT_INGRESSANTE				 IS NOT NULL)	OR	(ORIGEM.QT_INGRESSANTE					IS NOT NULL AND DESTINO.QT_INGRESSANTE						IS NULL))	OR
		(ORIGEM.QT_PERMANENCIA					IS NULL OR (DESTINO.QT_PERMANENCIA					IS NULL AND DESTINO.QT_PERMANENCIA				 IS NOT NULL)	OR	(ORIGEM.QT_PERMANENCIA					IS NOT NULL AND DESTINO.QT_PERMANENCIA						IS NULL))	OR
		(ORIGEM.QT_CONCLUINTE					IS NULL OR (DESTINO.QT_CONCLUINTE					IS NULL AND DESTINO.QT_CONCLUINTE				 IS NOT NULL)	OR	(ORIGEM.QT_CONCLUINTE					IS NOT NULL AND DESTINO.QT_CONCLUINTE						IS NULL))	OR
		(ORIGEM.QT_DESISTENCIA					IS NULL OR (DESTINO.QT_DESISTENCIA					IS NULL AND DESTINO.QT_DESISTENCIA				 IS NOT NULL)	OR	(ORIGEM.QT_DESISTENCIA					IS NOT NULL AND DESTINO.QT_DESISTENCIA						IS NULL))	OR
		(ORIGEM.QT_FALECIDO						IS NULL OR (DESTINO.QT_FALECIDO						IS NULL AND DESTINO.QT_FALECIDO					 IS NOT NULL)	OR	(ORIGEM.QT_FALECIDO						IS NOT NULL AND DESTINO.QT_FALECIDO							IS NULL))	OR
		(ORIGEM.VL_TAP							IS NULL OR (DESTINO.VL_TAP							IS NULL AND DESTINO.VL_TAP						 IS NOT NULL)	OR	(ORIGEM.VL_TAP							IS NOT NULL AND DESTINO.VL_TAP								IS NULL))	OR
		(ORIGEM.VL_TCA							IS NULL OR (DESTINO.VL_TCA							IS NULL AND DESTINO.VL_TCA						 IS NOT NULL)	OR	(ORIGEM.VL_TCA							IS NOT NULL AND DESTINO.VL_TCA								IS NULL))	OR
		(ORIGEM.VL_TDA							IS NULL OR (DESTINO.VL_TDA							IS NULL AND DESTINO.VL_TDA						 IS NOT NULL)	OR	(ORIGEM.VL_TDA							IS NOT NULL AND DESTINO.VL_TDA								IS NULL))	OR
		(ORIGEM.VL_TCAN							IS NULL OR (DESTINO.VL_TCAN							IS NULL AND DESTINO.VL_TCAN						 IS NOT NULL)	OR	(ORIGEM.VL_TCAN							IS NOT NULL AND DESTINO.VL_TCAN								IS NULL))	OR
		(ORIGEM.VL_TDAN							IS NULL OR (DESTINO.VL_TDAN							IS NULL AND DESTINO.VL_TDAN						 IS NOT NULL)	OR	(ORIGEM.VL_TDAN							IS NOT NULL AND DESTINO.VL_TDAN								IS NULL))
	)
	THEN UPDATE
		SET
		 
	--	   DESTINO.CO_CURSO						= ORIGEM.CO_CURSO						
	--	 , DESTINO.CO_MUNICIPIO					= ORIGEM.CO_MUNICIPIO					
		  DESTINO.TP_REDE						= ORIGEM.TP_REDE						
	--	 , DESTINO.CO_IES						= ORIGEM.CO_IES						
		 , DESTINO.CO_AREA						= ORIGEM.CO_AREA						
		 , DESTINO.TP_GRAU_ACADEMICO			= ORIGEM.TP_GRAU_ACADEMICO			
		 , DESTINO.TP_MODALIDADE_ENSINO			= ORIGEM.TP_MODALIDADE_ENSINO			
		 , DESTINO.TP_NIVEL_ACADEMICO			= ORIGEM.TP_NIVEL_ACADEMICO			
		 , DESTINO.TP_ORGANIZACAO_ACADEMICA		= ORIGEM.TP_ORGANIZACAO_ACADEMICA		
		 , DESTINO.TP_CATEGORIA_ADMINISTRATIVA	= ORIGEM.TP_CATEGORIA_ADMINISTRATIVA	
	--	 , DESTINO.NU_ANO_CENSO					= ORIGEM.NU_ANO_CENSO					
	--	 , DESTINO.NU_ANO_INGRESSO				= ORIGEM.NU_ANO_INGRESSO				
		 , DESTINO.NU_PRAZO_INTEGRALIZACAO		= ORIGEM.NU_PRAZO_INTEGRALIZACAO		
		 , DESTINO.NU_ANO_INTEGRALIZACAO		= ORIGEM.NU_ANO_INTEGRALIZACAO		
		 , DESTINO.NU_PRAZO_ACOMPANHAMENTO		= ORIGEM.NU_PRAZO_ACOMPANHAMENTO		
		 , DESTINO.NU_ANO_MAXIMO_ACOMPANHAMENTO	= ORIGEM.NU_ANO_MAXIMO_ACOMPANHAMENTO	
		 , DESTINO.QT_INGRESSANTE				= ORIGEM.QT_INGRESSANTE				
		 , DESTINO.QT_PERMANENCIA				= ORIGEM.QT_PERMANENCIA				
		 , DESTINO.QT_CONCLUINTE				= ORIGEM.QT_CONCLUINTE				
		 , DESTINO.QT_DESISTENCIA				= ORIGEM.QT_DESISTENCIA				
		 , DESTINO.QT_FALECIDO					= ORIGEM.QT_FALECIDO					
		 , DESTINO.VL_TAP						= ORIGEM.VL_TAP						
		 , DESTINO.VL_TCA						= ORIGEM.VL_TCA						
		 , DESTINO.VL_TDA						= ORIGEM.VL_TDA						
		 , DESTINO.VL_TCAN						= ORIGEM.VL_TCAN						
		 , DESTINO.VL_TDAN						= ORIGEM.VL_TDAN						

	;	
END 
