CREATE TABLE [ods].[ODS_MUNICIPIO] (
    [CO_MUNICIPIO]    INT           NOT NULL,
    [NO_MUNICIPIO]    VARCHAR (100) NULL,
    [CO_MICRORREGIAO] INT           NULL,
    [CO_UF]           TINYINT       NULL,
    CONSTRAINT [PK_ODS_MUNICIPIO] PRIMARY KEY CLUSTERED ([CO_MUNICIPIO] ASC)
);



