CREATE TABLE [ods].[ODS_CATALOGO] (
    [CO_CATALOGO] INT          NOT NULL,
    [NO_CATALOGO] VARCHAR (50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NU_CATALOGO] INT          NULL,
    PRIMARY KEY CLUSTERED ([CO_CATALOGO] ASC)
);

