CREATE TABLE [ods].[ODS_IES] (
    [CO_IES]                      INT           NOT NULL,
    [NO_IES]                      VARCHAR (200) NULL,
    [SG_IES]                      VARCHAR (200) NULL,
    [NU_ANO_CENSO]                INT           NULL,
    [CO_MUNICIPIO]                INT           NULL,
    [IN_CAPITAL]                  BIT           NULL,
    [TP_ORGANIZACAO_ACADEMICA]    INT           NULL,
    [TP_CATEGORIA_ADMINISTRATIVA] INT           NULL,
    [CO_MANTENEDORA]              INT           NULL,
    [DS_ENDERECO_IES]             VARCHAR (200) NULL,
    [DS_NUMERO_ENDERECO_IES]      VARCHAR (200) NULL,
    [DS_COMPLEMENTO_ENDERECO_IES] VARCHAR (200) NULL,
    [NO_BAIRRO_IES]               VARCHAR (200) NULL,
    [NU_CEP_IES]                  INT           NULL,
    [NO_ORGANIZACAO_ACADEMICA]    AS            (case when [TP_ORGANIZACAO_ACADEMICA]=(1) then 'UNIVERSIDADE' when [TP_ORGANIZACAO_ACADEMICA]=(2) then 'CENTRO UNIVERSITÁRIO' when [TP_ORGANIZACAO_ACADEMICA]=(3) then 'FACULDADE' when [TP_ORGANIZACAO_ACADEMICA]=(4) then 'INSTITUTO FEDERAL DE EDUCAÇÃO, CIÊNCIA E TECNOLOGIA' when [TP_ORGANIZACAO_ACADEMICA]=(5) then 'CENTRO FEDERAL DE EDUCAÇÃO TECNOLÓGICA'  end),
    [NO_CATEGORIA_ADMINISTRATIVA] AS            (case when [TP_CATEGORIA_ADMINISTRATIVA]=(1) then 'PÚBLICA FEDERAL' when [TP_CATEGORIA_ADMINISTRATIVA]=(2) then 'PÚBLICA ESTADUAL' when [TP_CATEGORIA_ADMINISTRATIVA]=(3) then 'PÚBLICA MUNICIPAL' when [TP_CATEGORIA_ADMINISTRATIVA]=(4) then 'PRIVADA COM FINS LUCRATIVOS' when [TP_CATEGORIA_ADMINISTRATIVA]=(5) then 'PRIVADA SEM FINS LUCRATIVOS' when [TP_CATEGORIA_ADMINISTRATIVA]=(7) then 'ESPECIAL' when [TP_CATEGORIA_ADMINISTRATIVA]=(8) then 'PRIVADA COMUNITÁRIA' when [TP_CATEGORIA_ADMINISTRATIVA]=(9) then 'PRIVADA CONFESSIONAL'  end),
    [TP_REDE]                     TINYINT       NULL,
    CONSTRAINT [PK_ODS_IES] PRIMARY KEY CLUSTERED ([CO_IES] ASC)
);

