CREATE TABLE [ods].[ODS_MANTENEDORA_IES] (
    [CO_MANTENEDORA] INT           NULL,
    [NO_MANTENEDORA] VARCHAR (300) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NU_ANO_CENSO]   INT           NULL
);


GO
CREATE CLUSTERED INDEX [ixc_ODS_MANTENEDORA_IES]
    ON [ods].[ODS_MANTENEDORA_IES]([CO_MANTENEDORA] ASC);

