CREATE TABLE [ods].[ODS_CINE_AREA_ESPECIFICA] (
    [CO_CINE_AREA_ESPECIFICA] SMALLINT      NOT NULL,
    [NO_CINE_AREA_ESPECIFICA] VARCHAR (120) NULL,
    [CO_CINE_AREA_GERAL]      TINYINT       NULL,
    CONSTRAINT [PK_CINE_AREA_ESPECIFICA] PRIMARY KEY CLUSTERED ([CO_CINE_AREA_ESPECIFICA] ASC)
);



