CREATE TABLE [ods].[ODS_MICRORREGIAO] (
    [CO_MICRORREGIAO] INT           NULL,
    [NO_MICRORREGIAO] VARCHAR (100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CO_MESORREGIAO]  INT           NULL
);

