CREATE TABLE [ods].[ODS_MANTENEDORA_IES] (
    [CO_MANTENEDORA] INT           NOT NULL,
    [NO_MANTENEDORA] VARCHAR (100) NULL,
    [NU_ANO_CENSO]   SMALLINT      NULL,
    CONSTRAINT [PK_ODS_MANTENEDORA_IES] PRIMARY KEY CLUSTERED ([CO_MANTENEDORA] ASC)
);




GO


