CREATE TABLE [ods].[ODS_CINE_CURSO_GRANDE_AREA] (
    [COD_GRANDE_AREA] INT            NOT NULL,
    [NME_GRANDE_AREA] NVARCHAR (200) NULL,
    CONSTRAINT [PK_ODS_CINE_CURSO_GRANDE_AREA] PRIMARY KEY CLUSTERED ([COD_GRANDE_AREA] ASC)
);

