CREATE TABLE [ods].[ODS_CINE_AREA_DETALHADA] (
    [CO_CINE_AREA_DETALHADA]  SMALLINT      NOT NULL,
    [NO_CINE_AREA_DETALHADA]  VARCHAR (120) NULL,
    [CO_CINE_AREA_ESPECIFICA] SMALLINT      NULL,
    CONSTRAINT [PK_CINE_AREA_DETALHADA] PRIMARY KEY CLUSTERED ([CO_CINE_AREA_DETALHADA] ASC)
);



