CREATE TABLE [ods].[ODS_UNIDADE_FEDERATIVA] (
    [CO_UF] SMALLINT     NOT NULL,
    [NO_UF] VARCHAR (30) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [SG_UF] CHAR (2)     COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    CONSTRAINT [PK_ODS_UF_IES] PRIMARY KEY CLUSTERED ([CO_UF] ASC)
);

