CREATE TABLE [ods].[ODS_CINE_AREA_ESPECIFICA] (
    [CO_CINE_AREA_ESPECIFICA] INT           NULL,
    [NO_CINE_AREA_ESPECIFICA] VARCHAR (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CO_CINE_AREA_GERAL]      INT           NULL
);

