CREATE TABLE [ods].[ODS_MICRORREGIAO] (
    [CO_MICRORREGIAO] INT           NOT NULL,
    [NO_MICRORREGIAO] VARCHAR (100) NULL,
    [CO_MESORREGIAO]  SMALLINT      NULL,
    [CO_UF]           TINYINT       NOT NULL,
    CONSTRAINT [PK_ODS_MICRORREGIAO] PRIMARY KEY CLUSTERED ([CO_MICRORREGIAO] ASC, [CO_UF] ASC)
);





