CREATE TABLE [ods].[ODS_CINE_AREA_GERAL] (
    [CO_CINE_AREA_GERAL] TINYINT       NOT NULL,
    [NO_CINE_AREA_GERAL] VARCHAR (120) NULL,
    CONSTRAINT [PK_CINE_AREA_GERAL] PRIMARY KEY CLUSTERED ([CO_CINE_AREA_GERAL] ASC)
);



