CREATE TABLE [ods].[ODS_DADOS_IES] (
    [CO_IES]                         INT NULL,
    [NU_ANO_CENSO]                   INT NULL,
    [QT_TEC_TOTAL]                   INT NULL,
    [QT_TEC_FUNDAMENTAL_INCOMP_FEM]  INT NULL,
    [QT_TEC_FUNDAMENTAL_INCOMP_MASC] INT NULL,
    [QT_TEC_FUNDAMENTAL_COMP_FEM]    INT NULL,
    [QT_TEC_FUNDAMENTAL_COMP_MASC]   INT NULL,
    [QT_TEC_MEDIO_FEM]               INT NULL,
    [QT_TEC_MEDIO_MASC]              INT NULL,
    [QT_TEC_SUPERIOR_FEM]            INT NULL,
    [QT_TEC_SUPERIOR_MASC]           INT NULL,
    [QT_TEC_ESPECIALIZACAO_FEM]      INT NULL,
    [QT_TEC_ESPECIALIZACAO_MASC]     INT NULL,
    [QT_TEC_MESTRADO_FEM]            INT NULL,
    [QT_TEC_MESTRADO_MASC]           INT NULL,
    [QT_TEC_DOUTORADO_FEM]           INT NULL,
    [QT_TEC_DOUTORADO_MASC]          INT NULL,
    [IN_ACESSO_PORTAL_CAPES]         INT NULL,
    [IN_ACESSO_OUTRAS_BASES]         INT NULL,
    [IN_ASSINA_OUTRA_BASE]           INT NULL,
    [IN_REPOSITORIO_INSTITUCIONAL]   INT NULL,
    [IN_BUSCA_INTEGRADA]             INT NULL,
    [IN_SERVICO_INTERNET]            INT NULL,
    [IN_PARTICIPA_REDE_SOCIAL]       INT NULL,
    [IN_CATALOGO_ONLINE]             INT NULL,
    [QT_PERIODICO_ELETRONICO]        INT NULL,
    [QT_LIVRO_ELETRONICO]            INT NULL,
    [QT_DOC_TOTAL]                   INT NULL,
    [QT_DOC_EXE]                     INT NULL,
    [QT_DOC_EX_FEMI]                 INT NULL,
    [QT_DOC_EX_MASC]                 INT NULL,
    [QT_DOC_EX_SEM_GRAD]             INT NULL,
    [QT_DOC_EX_GRAD]                 INT NULL,
    [QT_DOC_EX_ESP]                  INT NULL,
    [QT_DOC_EX_MEST]                 INT NULL,
    [QT_DOC_EX_DOUT]                 INT NULL,
    [QT_DOC_EX_INT]                  INT NULL,
    [QT_DOC_EX_INT_DE]               INT NULL,
    [QT_DOC_EX_INT_SEM_DE]           INT NULL,
    [QT_DOC_EX_PARC]                 INT NULL,
    [QT_DOC_EX_HOR]                  INT NULL,
    [QT_DOC_EX_0_29]                 INT NULL,
    [QT_DOC_EX_30_34]                INT NULL,
    [QT_DOC_EX_35_39]                INT NULL,
    [QT_DOC_EX_40_44]                INT NULL,
    [QT_DOC_EX_45_49]                INT NULL,
    [QT_DOC_EX_50_54]                INT NULL,
    [QT_DOC_EX_55_59]                INT NULL,
    [QT_DOC_EX_60_MAIS]              INT NULL,
    [QT_DOC_EX_BRANCA]               INT NULL,
    [QT_DOC_EX_PRETA]                INT NULL,
    [QT_DOC_EX_PARDA]                INT NULL,
    [QT_DOC_EX_AMARELA]              INT NULL,
    [QT_DOC_EX_INDIGENA]             INT NULL,
    [QT_DOC_EX_COR_ND]               INT NULL,
    [QT_DOC_EX_BRA]                  INT NULL,
    [QT_DOC_EX_EST]                  INT NULL,
    [QT_DOC_EX_COM_DEFICIENCIA]      INT NULL
);


GO
CREATE CLUSTERED INDEX [IXC_ODS_DADOS_IES]
    ON [ods].[ODS_DADOS_IES]([CO_IES] ASC, [NU_ANO_CENSO] ASC);

