CREATE TABLE [ods].[ODS_MESORREGIAO] (
    [CO_MESORREGIAO] SMALLINT      NOT NULL,
    [NO_MESORREGIAO] VARCHAR (100) NULL,
    [CO_UF]          TINYINT       NOT NULL,
    CONSTRAINT [PK_ODS_MESORREGIAO] PRIMARY KEY CLUSTERED ([CO_MESORREGIAO] ASC, [CO_UF] ASC)
);





