CREATE TABLE [ods].[ODS_CATALOGO] (
    [CO_CATALOGO] INT          NOT NULL,
    [NO_CATALOGO] VARCHAR (50) NULL,
    [TP_CATALOGO] TINYINT      NULL,
    PRIMARY KEY CLUSTERED ([CO_CATALOGO] ASC)
);



