CREATE TABLE [ods].[ODS_CINE_ROTULO] (
    [CO_CINE_ROTULO]         VARCHAR (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NO_CINE_ROTULO]         VARCHAR (200)  COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CO_CINE_AREA_DETALHADA] INT            NULL
);

