CREATE TABLE [ods].[ODS_CINE] (
    [CO_CINE_ROTULO]          VARCHAR (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [NO_CINE_ROTULO]          VARCHAR (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CO_CINE_AREA_DETALHADA]  INT           NULL,
    [NO_CINE_AREA_DETALHADA]  VARCHAR (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CO_CINE_AREA_ESPECIFICA] INT           NULL,
    [NO_CINE_AREA_ESPECIFICA] VARCHAR (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [CO_CINE_AREA_GERAL]      INT           NULL,
    [NO_CINE_AREA_GERAL]      VARCHAR (200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
);

