
CREATE   VIEW DW.VW_DIM_TIPO_MODALIDADE_ENSINO		
WITH SCHEMABINDING AS 
	SELECT TP_MODALIDADE_ENSINO	, NO_MODALIDADE_ENSINO	 FROM 
		(
			VALUES
				(1,'Presencial'),
				(2,'Curso a distância')
		) AS DIM_TIPO_ALGUMA_COISA(TP_MODALIDADE_ENSINO	,NO_MODALIDADE_ENSINO	)