
CREATE   VIEW DW.VW_DIM_TIPO_NIVEL_ACADEMICO			
WITH SCHEMABINDING AS 
	SELECT TP_NIVEL_ACADEMICO, NO_NIVEL_ACADEMICO FROM 
		(
			VALUES
				(1,'Graduação'),
				(2,'Sequencial de Formação Específica')
		) AS DIM_TIPO_ALGUMA_COISA(TP_NIVEL_ACADEMICO,NO_NIVEL_ACADEMICO)