CREATE   VIEW [dw].[VW_FTO_DADOS_FLUXO]
as

SELECT 
 FTO.CO_CURSO
,C.NO_CURSO
,CINE.CO_CINE_ROTULO
,CINE.NO_CINE_ROTULO
,CINE.CO_CINE_AREA_DETALHADA
,CINE.NO_CINE_AREA_DETALHADA
,CINE.CO_CINE_AREA_ESPECIFICA
,CINE.NO_CINE_AREA_ESPECIFICA
,CINE.CO_CINE_AREA_GERAL
,CINE.NO_CINE_AREA_GERAL
,RG.CO_MUNICIPIO
,RG.NO_MUNICIPIO
,RG.CO_MICRORREGIAO
,RG.NO_MICRORREGIAO
,RG.CO_MESORREGIAO
,RG.NO_MESORREGIAO
,RG.CO_UF
,RG.NO_UF
,RG.SG_UF
,FTO.IN_CAPITAL
,TDM.TP_DIMENSAO
,TDM.NO_DIMENSAO
,TRD.TP_REDE
,TRD.NO_REDE
, IES.CO_IES
, IES.NO_IES
, IES.SG_IES
, IES.IN_CAPITAL_IES
, IES.TP_ORGANIZACAO_ACADEMICA
, IES.TP_CATEGORIA_ADMINISTRATIVA
, IES.CO_MANTENEDORA
, IES.NO_MANTENEDORA
,TGA.TP_GRAU_ACADEMICO
,TGA.NO_GRAU_ACADEMICO
,FTO.IN_GRATUITO
,TME.TP_MODALIDADE_ENSINO
,TME.NO_MODALIDADE_ENSINO
,TNA.TP_NIVEL_ACADEMICO
,TNA.NO_NIVEL_ACADEMICO
,FTO.NU_ANO_CENSO
,FTO.NU_ANO_INGRESSO
,FTO.NU_PRAZO_INTEGRALIZACAO
,FTO.NU_ANO_INTEGRALIZACAO
,FTO.NU_PRAZO_ACOMPANHAMENTO
,FTO.NU_ANO_MAXIMO_ACOMPANHAMENTO
,FTO.QT_INGRESSANTE
,FTO.QT_PERMANENCIA
,FTO.QT_CONCLUINTE
,FTO.QT_DESISTENCIA
,FTO.QT_FALECIDO
,FTO.VL_TAP
,FTO.VL_TCA
,FTO.VL_TDA
,FTO.VL_TCAN
,FTO.VL_TDAN
,CT.CO_CATALOGO
,CT.NO_CATALOGO
FROM 
			DW.FTO_DADOS_FLUXO				FTO		
LEFT JOIN	DW.DIM_CURSO					C		ON	FTO.CO_CURSO					=	C.CO_CURSO
LEFT JOIN	DW.DIM_REGIAO					RG		ON	FTO.CO_MUNICIPIO				=	RG.CO_MUNICIPIO
LEFT JOIN	DW.DIM_IES						IES		ON	FTO.CO_IES						=	IES.CO_IES
LEFT JOIN	DW.DIM_CINE						CINE	ON	FTO.CO_CINE_ROTULO				=	CINE.CO_CINE_ROTULO
LEFT JOIN	DW.DIM_TIPO_DIMENSAO			TDM		ON	FTO.TP_DIMENSAO					=	TDM.TP_DIMENSAO
LEFT JOIN	DW.DIM_TIPO_GRAU_ACADEMICO		TGA		ON	FTO.TP_GRAU_ACADEMICO			=	TGA.TP_GRAU_ACADEMICO
LEFT JOIN	DW.DIM_TIPO_REDE				TRD		ON	FTO.TP_REDE						=	TRD.TP_REDE
LEFT JOIN	DW.DIM_TIPO_MODALIDADE_ENSINO	TME		ON	FTO.TP_MODALIDADE_ENSINO		=	TME.TP_MODALIDADE_ENSINO
LEFT JOIN	DW.DIM_TIPO_NIVEL_ACADEMICO		TNA		ON	FTO.TP_NIVEL_ACADEMICO			=	TNA.TP_NIVEL_ACADEMICO
LEFT JOIN	ODS.ODS_CATALOGO				CT		ON	CT.CO_CATALOGO					=	FTO.CO_CATALOGO