CREATE TABLE [dw].[DIM_TIPO_ORGANIZACAO_ACADEMICA] (
    [TP_ORGANIZACAO_ACADEMICA] TINYINT      NOT NULL,
    [NO_ORGANIZACAO_ACADEMICA] VARCHAR (51) NOT NULL,
    CONSTRAINT [PK_DIM_TIPO_ORGANIZACAO_ACADEMICA] PRIMARY KEY CLUSTERED ([TP_ORGANIZACAO_ACADEMICA] ASC)
);

/*
INSERT INTO DW.DIM_TIPO_ORGANIZACAO_ACADEMICA		
(TP_ORGANIZACAO_ACADEMICA, NO_ORGANIZACAO_ACADEMICA)
VALUES
(0, 'Não informado')
*/