CREATE TABLE [DW].[DIM_TIPO_CATEGORIA_ADMINISTRATIVA] (
    [TP_CATEGORIA_ADMINISTRATIVA] TINYINT      NOT NULL,
    [NO_CATEGORIA_ADMINISTRATIVA] VARCHAR (39) NOT NULL,
    CONSTRAINT [PK_DIM_TIPO_CATEGORIA_ADMINISTRATIVA] PRIMARY KEY CLUSTERED ([TP_CATEGORIA_ADMINISTRATIVA] ASC)
);

