CREATE TABLE [dw].[DIM_TIPO_REDE] (
    [TP_REDE] TINYINT      NOT NULL,
    [NO_REDE] VARCHAR (15) NULL,
    CONSTRAINT [PK_DIM_TIPO_REDE] PRIMARY KEY CLUSTERED ([TP_REDE] ASC)
);

/*
INSERT INTO DW.DIM_TIPO_REDE						
(TP_REDE,NO_REDE)
VALUES(0, 'Não informado')
*/