CREATE TABLE [dw].[DIM_TIPO_CATEGORIA_ADMINISTRATIVA] (
    [TP_CATEGORIA_ADMINISTRATIVA] TINYINT      NOT NULL,
    [NO_CATEGORIA_ADMINISTRATIVA] VARCHAR (39) NOT NULL,
    CONSTRAINT [PK_DIM_TIPO_CATEGORIA_ADMINISTRATIVA] PRIMARY KEY CLUSTERED ([TP_CATEGORIA_ADMINISTRATIVA] ASC)
);

/*
INSERT INTO DW.DIM_TIPO_CATEGORIA_ADMINISTRATIVA	
(TP_CATEGORIA_ADMINISTRATIVA,NO_CATEGORIA_ADMINISTRATIVA)
VALUES
(0, 'Não informado')
*/