CREATE TABLE [dw].[DIM_TIPO_MODALIDADE_ENSINO] (
    [TP_MODALIDADE_ENSINO] TINYINT      NOT NULL,
    [NO_MODALIDADE_ENSINO] VARCHAR (17) NOT NULL,
    CONSTRAINT [PK_DIM_TIPO_MODALIDADE_ENSINO] PRIMARY KEY CLUSTERED ([TP_MODALIDADE_ENSINO] ASC)
);
/*
INSERT INTO DW.DIM_TIPO_MODALIDADE_ENSINO			
(TP_MODALIDADE_ENSINO, NO_MODALIDADE_ENSINO)
VALUES
(0, 'Não informado')
*/