CREATE TABLE [DW].[DIM_TIPO_GRAU_ACADEMICO] (
    [TP_GRAU_ACADEMICO] TINYINT      NOT NULL,
    [NO_GRAU_ACADEMICO] VARCHAR (26) NOT NULL,
    CONSTRAINT [PK_DIM_TIPO_GRAU_ACADEMICO] PRIMARY KEY CLUSTERED ([TP_GRAU_ACADEMICO] ASC)
);

