CREATE TABLE [dw].[DIM_CINE] (
    [CO_CINE_ROTULO]          CHAR (7)      NOT NULL,
    [NO_CINE_ROTULO]          VARCHAR (120) NULL,
    [CO_CINE_AREA_DETALHADA]  SMALLINT      NOT NULL,
    [NO_CINE_AREA_DETALHADA]  VARCHAR (120) NULL,
    [CO_CINE_AREA_ESPECIFICA] SMALLINT      NOT NULL,
    [NO_CINE_AREA_ESPECIFICA] VARCHAR (120) NULL,
    [CO_CINE_AREA_GERAL]      TINYINT       NOT NULL,
    [NO_CINE_AREA_GERAL]      VARCHAR (120) NULL,
    CONSTRAINT [PK_DIM_CINE] PRIMARY KEY CLUSTERED ([CO_CINE_ROTULO] ASC)
);

/*

insert into dw.DIM_CINE (
     CO_CINE_ROTULO
    ,NO_CINE_ROTULO
    ,CO_CINE_AREA_DETALHADA
    ,NO_CINE_AREA_DETALHADA
    ,CO_CINE_AREA_ESPECIFICA
    ,NO_CINE_AREA_ESPECIFICA
    ,CO_CINE_AREA_GERAL
    ,NO_CINE_AREA_GERAL
    )
values('0','Não informado', 0, 'Não informado',0,'Não informado',0,'Não informado')
*/

