CREATE TABLE [DW].[DIM_CINE] (
    [CO_AREA]        NVARCHAR (200) NULL,
    [NO_AREA]        NVARCHAR (200) NULL,
    [CO_GRANDE_AREA] INT            NOT NULL,
    [NO_GRANDE_AREA] NVARCHAR (200) NULL
);


GO
CREATE NONCLUSTERED INDEX [IXC_DIM_CINE]
    ON [DW].[DIM_CINE]([CO_AREA] ASC);

