CREATE TABLE [dw].[DIM_TIPO_NIVEL_ACADEMICO] (
    [TP_NIVEL_ACADEMICO] TINYINT      NOT NULL,
    [NO_NIVEL_ACADEMICO] VARCHAR (33) NOT NULL,
    CONSTRAINT [PK_DIM_TIPO_NIVEL_ACADEMICO] PRIMARY KEY CLUSTERED ([TP_NIVEL_ACADEMICO] ASC)
);
/*
INSERT INTO DW.DIM_TIPO_NIVEL_ACADEMICO				
(TP_NIVEL_ACADEMICO,NO_NIVEL_ACADEMICO)
VALUES
(0, 'Não informado')
*/
