CREATE TABLE [dw].[DIM_TIPO_DIMENSAO] (
    [TP_DIMENSAO] TINYINT      NOT NULL,
    [NO_DIMENSAO] VARCHAR (69) NOT NULL,
    CONSTRAINT [PK_DIM_TIPO_DIMENSAO] PRIMARY KEY CLUSTERED ([TP_DIMENSAO] ASC)
);

/*
INSERT INTO DW.DIM_TIPO_DIMENSAO					
(TP_DIMENSAO,NO_DIMENSAO)
VALUES
(0, 'Não informado')
*/