CREATE TABLE [dw].[DIM_TIPO_GRAU_ACADEMICO] (
    [TP_GRAU_ACADEMICO] TINYINT      NOT NULL,
    [NO_GRAU_ACADEMICO] VARCHAR (26) NOT NULL,
    CONSTRAINT [PK_DIM_TIPO_GRAU_ACADEMICO] PRIMARY KEY CLUSTERED ([TP_GRAU_ACADEMICO] ASC)
);
/*
INSERT INTO DW.DIM_TIPO_GRAU_ACADEMICO				
(TP_GRAU_ACADEMICO,NO_GRAU_ACADEMICO)
VALUES
(0, 'Não informado')
*/
