CREATE TABLE [DW].[DIM_TIPO_ORGANIZACAO_ACADEMICA] (
    [TP_ORGANIZACAO_ACADEMICA] TINYINT      NOT NULL,
    [NO_ORGANIZACAO_ACADEMICA] VARCHAR (51) NOT NULL,
    CONSTRAINT [PK_DIM_TIPO_ORGANIZACAO_ACADEMICA] PRIMARY KEY CLUSTERED ([TP_ORGANIZACAO_ACADEMICA] ASC)
);

