CREATE TABLE [DW].[FTO_DADOS_FLUXO] (
    [CO_CURSO]                     INT            NULL,
    [CO_MUNICIPIO]                 INT            NULL,
    [IN_CAPITAL]                   INT            NULL,
    [TP_DIMENSAO]                  INT            NULL,
    [TP_REDE]                      INT            NULL,
    [CO_IES]                       INT            NULL,
    [CO_CINE_ROTULO]               VARCHAR (8000) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
    [TP_GRAU_ACADEMICO]            INT            NULL,
    [IN_GRATUITO]                  INT            NULL,
    [TP_MODALIDADE_ENSINO]         INT            NULL,
    [TP_NIVEL_ACADEMICO]           INT            NULL,
    [NU_ANO_CENSO]                 INT            NULL,
    [NU_ANO_INGRESSO]              INT            NULL,
    [NU_PRAZO_INTEGRALIZACAO]      INT            NULL,
    [NU_ANO_INTEGRALIZACAO]        INT            NULL,
    [NU_PRAZO_ACOMPANHAMENTO]      INT            NULL,
    [NU_ANO_MAXIMO_ACOMPANHAMENTO] INT            NULL,
    [QT_INGRESSANTE]               INT            NULL,
    [QT_PERMANENCIA]               INT            NULL,
    [QT_CONCLUINTE]                INT            NULL,
    [QT_DESISTENCIA]               INT            NULL,
    [QT_FALECIDO]                  INT            NULL,
    [VL_TAP]                       FLOAT (53)     NULL,
    [VL_TCA]                       FLOAT (53)     NULL,
    [VL_TDA]                       FLOAT (53)     NULL,
    [VL_TCAN]                      FLOAT (53)     NULL,
    [VL_TDAN]                      FLOAT (53)     NULL,
    [CO_CATALOGO]                  INT            NULL
);

