CREATE TABLE [DW].[FTO_DADOS_FLUXO] (
    [CO_CURSO]                     INT        NULL,
    [CO_MUNICIPIO]                 INT        NULL,
    [TP_REDE]                      TINYINT    NULL,
    [CO_IES]                       INT        NULL,
    [CO_AREA]                      CHAR (7)   NULL,
    [TP_GRAU_ACADEMICO]            INT        NULL,
    [TP_MODALIDADE_ENSINO]         INT        NULL,
    [TP_NIVEL_ACADEMICO]           INT        NULL,
    [TP_ORGANIZACAO_ACADEMICA]     INT        NULL,
    [TP_CATEGORIA_ADMINISTRATIVA]  INT        NULL,
    [NU_ANO_CENSO]                 INT        NULL,
    [NU_ANO_INGRESSO]              INT        NULL,
    [NU_PRAZO_INTEGRALIZACAO]      INT        NULL,
    [NU_ANO_INTEGRALIZACAO]        INT        NULL,
    [NU_PRAZO_ACOMPANHAMENTO]      INT        NULL,
    [NU_ANO_MAXIMO_ACOMPANHAMENTO] INT        NULL,
    [QT_INGRESSANTE]               INT        NULL,
    [QT_PERMANENCIA]               INT        NULL,
    [QT_CONCLUINTE]                INT        NULL,
    [QT_DESISTENCIA]               INT        NULL,
    [QT_FALECIDO]                  INT        NULL,
    [VL_TAP]                       FLOAT (53) NULL,
    [VL_TCA]                       FLOAT (53) NULL,
    [VL_TDA]                       FLOAT (53) NULL,
    [VL_TCAN]                      FLOAT (53) NULL,
    [VL_TDAN]                      FLOAT (53) NULL
);

