
CREATE      PROCEDURE [ods].[SP_ODS_DADOS_FLUXO]		AS
BEGIN 
	DECLARE @DTA_EXECUCAO DATETIME2(2) = GETDATE()

	MERGE INTO ODS.ODS_DADOS_FLUXO		WITH (TABLOCK) AS DESTINO
	USING	(											
					SELECT 
					codigo_ies						CO_IES
				,	codigo_curso					CO_CURSO
				,	codigo_municipio				CO_MUNICIPIO
				,	ano_referencia					NU_ANO_CENSO
				,	ano_ingresso					NU_ANO_INGRESSO
				,	prazo_integralizacao_anos		NU_PRAZO_INTEGRALIZACAO
				,	ano_integralizacao_curso		NU_ANO_INTEGRALIZACAO
				,	prazo_acompanhamento_curso_anos	NU_PRAZO_ACOMPANHAMENTO
				,	ano_max_acompanhamento			NU_ANO_MAXIMO_ACOMPANHAMENTO
				,	grau_academico					TP_GRAU_ACADEMICO
				,	modalidade_ensino				TP_MODALIDADE_ENSINO
				,	qtd_ingressante_curso			QT_INGRESSANTE
				,	qtd_permanencia_curso			QT_PERMANENCIA
				,	qtd_concluinte_curso			QT_CONCLUINTE
				,	qtd_desistencia_curso			QT_DESISTENCIA
				,	qtd_falecimentos_curso			QT_FALECIDO	
				,	TAP								VL_TAP
				,	TCA								VL_TCA
				,	TDA								VL_TCAN
				,	TCAN							VL_TDA
				,	TDAN							VL_TDAN
				FROM [stg].[STG_DADOS_FLUXO]
			) AS ORIGEM
	ON 	(	origem.CO_IES			= destino.CO_IES				and 
			origem.CO_CURSO			= destino.CO_CURSO				and 
			origem.CO_MUNICIPIO		= destino.CO_MUNICIPIO			and 
			origem.NU_ANO_CENSO		= destino.NU_ANO_CENSO			and 
			origem.NU_ANO_INGRESSO	= destino.NU_ANO_INGRESSO		
		)
	WHEN NOT MATCHED THEN
		INSERT
			(	
				CO_IES
			,	CO_CURSO
			,	CO_MUNICIPIO
			,	NU_ANO_CENSO
			,	NU_ANO_INGRESSO
			,	NU_PRAZO_INTEGRALIZACAO
			,	NU_ANO_INTEGRALIZACAO
			,	NU_PRAZO_ACOMPANHAMENTO
			,	NU_ANO_MAXIMO_ACOMPANHAMENTO
			,	TP_GRAU_ACADEMICO
			,	TP_MODALIDADE_ENSINO
			,	QT_INGRESSANTE
			,	QT_PERMANENCIA
			,	QT_CONCLUINTE
			,	QT_DESISTENCIA
			,	QT_FALECIDO	
			,	VL_TAP
			,	VL_TCA
			,	VL_TCAN
			,	VL_TDA
			,	VL_TDAN
			)	
			VALUES
			(	 
				 ORIGEM.CO_IES
				,ORIGEM.CO_CURSO
				,ORIGEM.CO_MUNICIPIO
				,ORIGEM.NU_ANO_CENSO
				,ORIGEM.NU_ANO_INGRESSO
				,ORIGEM.NU_PRAZO_INTEGRALIZACAO
				,ORIGEM.NU_ANO_INTEGRALIZACAO
				,ORIGEM.NU_PRAZO_ACOMPANHAMENTO
				,ORIGEM.NU_ANO_MAXIMO_ACOMPANHAMENTO
				,ORIGEM.TP_GRAU_ACADEMICO
				,ORIGEM.TP_MODALIDADE_ENSINO
				,ORIGEM.QT_INGRESSANTE
				,ORIGEM.QT_PERMANENCIA
				,ORIGEM.QT_CONCLUINTE
				,ORIGEM.QT_DESISTENCIA
				,ORIGEM.QT_FALECIDO	
				,ORIGEM.VL_TAP
				,ORIGEM.VL_TCA
				,ORIGEM.VL_TCAN
				,ORIGEM.VL_TDA
				,ORIGEM.VL_TDAN
			)																					
	WHEN MATCHED AND
	(    
		(ORIGEM.NU_PRAZO_INTEGRALIZACAO			IS NULL	OR (DESTINO.NU_PRAZO_INTEGRALIZACAO			IS NULL AND DESTINO.NU_PRAZO_INTEGRALIZACAO			IS NOT NULL)	OR	(ORIGEM.NU_PRAZO_INTEGRALIZACAO			IS NOT NULL AND DESTINO.NU_PRAZO_INTEGRALIZACAO			IS NULL))	OR
		(ORIGEM.NU_ANO_INTEGRALIZACAO			IS NULL	OR (DESTINO.NU_ANO_INTEGRALIZACAO			IS NULL AND DESTINO.NU_ANO_INTEGRALIZACAO			IS NOT NULL)	OR	(ORIGEM.NU_ANO_INTEGRALIZACAO			IS NOT NULL AND DESTINO.NU_ANO_INTEGRALIZACAO			IS NULL))	OR
		(ORIGEM.NU_PRAZO_ACOMPANHAMENTO			IS NULL	OR (DESTINO.NU_PRAZO_ACOMPANHAMENTO			IS NULL AND DESTINO.NU_PRAZO_ACOMPANHAMENTO			IS NOT NULL)	OR	(ORIGEM.NU_PRAZO_ACOMPANHAMENTO			IS NOT NULL AND DESTINO.NU_PRAZO_ACOMPANHAMENTO			IS NULL))	OR
		(ORIGEM.NU_ANO_MAXIMO_ACOMPANHAMENTO	IS NULL	OR (DESTINO.NU_ANO_MAXIMO_ACOMPANHAMENTO	IS NULL AND DESTINO.NU_ANO_MAXIMO_ACOMPANHAMENTO	IS NOT NULL)	OR	(ORIGEM.NU_ANO_MAXIMO_ACOMPANHAMENTO	IS NOT NULL AND DESTINO.NU_ANO_MAXIMO_ACOMPANHAMENTO	IS NULL))	OR
		(ORIGEM.TP_GRAU_ACADEMICO				IS NULL	OR (DESTINO.TP_GRAU_ACADEMICO				IS NULL AND DESTINO.TP_GRAU_ACADEMICO				IS NOT NULL)	OR	(ORIGEM.TP_GRAU_ACADEMICO				IS NOT NULL AND DESTINO.TP_GRAU_ACADEMICO				IS NULL))	OR
		(ORIGEM.TP_MODALIDADE_ENSINO			IS NULL	OR (DESTINO.TP_MODALIDADE_ENSINO			IS NULL AND DESTINO.TP_MODALIDADE_ENSINO			IS NOT NULL)	OR	(ORIGEM.TP_MODALIDADE_ENSINO			IS NOT NULL AND DESTINO.TP_MODALIDADE_ENSINO			IS NULL))	OR
		(ORIGEM.QT_INGRESSANTE					IS NULL	OR (DESTINO.QT_INGRESSANTE					IS NULL AND DESTINO.QT_INGRESSANTE					IS NOT NULL)	OR	(ORIGEM.QT_INGRESSANTE					IS NOT NULL AND DESTINO.QT_INGRESSANTE					IS NULL))	OR
		(ORIGEM.QT_PERMANENCIA					IS NULL	OR (DESTINO.QT_PERMANENCIA					IS NULL AND DESTINO.QT_PERMANENCIA					IS NOT NULL)	OR	(ORIGEM.QT_PERMANENCIA					IS NOT NULL AND DESTINO.QT_PERMANENCIA					IS NULL))	OR
		(ORIGEM.QT_CONCLUINTE					IS NULL	OR (DESTINO.QT_CONCLUINTE					IS NULL AND DESTINO.QT_CONCLUINTE					IS NOT NULL)	OR	(ORIGEM.QT_CONCLUINTE					IS NOT NULL AND DESTINO.QT_CONCLUINTE					IS NULL))	OR
		(ORIGEM.QT_DESISTENCIA					IS NULL	OR (DESTINO.QT_DESISTENCIA					IS NULL AND DESTINO.QT_DESISTENCIA					IS NOT NULL)	OR	(ORIGEM.QT_DESISTENCIA					IS NOT NULL AND DESTINO.QT_DESISTENCIA					IS NULL))	OR
		(ORIGEM.QT_FALECIDO						IS NULL	OR (DESTINO.QT_FALECIDO						IS NULL AND DESTINO.QT_FALECIDO						IS NOT NULL)	OR	(ORIGEM.QT_FALECIDO						IS NOT NULL AND DESTINO.QT_FALECIDO						IS NULL))	OR
		(ORIGEM.VL_TAP							IS NULL	OR (DESTINO.VL_TAP							IS NULL AND DESTINO.VL_TAP							IS NOT NULL)	OR	(ORIGEM.VL_TAP							IS NOT NULL AND DESTINO.VL_TAP							IS NULL))	OR
		(ORIGEM.VL_TCA							IS NULL	OR (DESTINO.VL_TCA							IS NULL AND DESTINO.VL_TCA							IS NOT NULL)	OR	(ORIGEM.VL_TCA							IS NOT NULL AND DESTINO.VL_TCA							IS NULL))	OR
		(ORIGEM.VL_TCAN							IS NULL	OR (DESTINO.VL_TCAN							IS NULL AND DESTINO.VL_TCAN							IS NOT NULL)	OR	(ORIGEM.VL_TCAN							IS NOT NULL AND DESTINO.VL_TCAN							IS NULL))	OR
		(ORIGEM.VL_TDA							IS NULL	OR (DESTINO.VL_TDA							IS NULL AND DESTINO.VL_TDA							IS NOT NULL)	OR	(ORIGEM.VL_TDA							IS NOT NULL AND DESTINO.VL_TDA							IS NULL))	OR
		(ORIGEM.VL_TDAN							IS NULL	OR (DESTINO.VL_TDAN							IS NULL AND DESTINO.VL_TDAN							IS NOT NULL)	OR	(ORIGEM.VL_TDAN							IS NOT NULL AND DESTINO.VL_TDAN							IS NULL))
	)
	THEN UPDATE
		SET
		 DESTINO.NU_PRAZO_INTEGRALIZACAO		= DESTINO.NU_PRAZO_INTEGRALIZACAO			
		,DESTINO.NU_ANO_INTEGRALIZACAO			= DESTINO.NU_ANO_INTEGRALIZACAO			
		,DESTINO.NU_PRAZO_ACOMPANHAMENTO		= DESTINO.NU_PRAZO_ACOMPANHAMENTO			
		,DESTINO.NU_ANO_MAXIMO_ACOMPANHAMENTO	= DESTINO.NU_ANO_MAXIMO_ACOMPANHAMENTO	
		,DESTINO.TP_GRAU_ACADEMICO				= DESTINO.TP_GRAU_ACADEMICO			
		,DESTINO.TP_MODALIDADE_ENSINO			= DESTINO.TP_MODALIDADE_ENSINO		
		,DESTINO.QT_INGRESSANTE					= DESTINO.QT_INGRESSANTE					
		,DESTINO.QT_PERMANENCIA					= DESTINO.QT_PERMANENCIA					
		,DESTINO.QT_CONCLUINTE					= DESTINO.QT_CONCLUINTE					
		,DESTINO.QT_DESISTENCIA					= DESTINO.QT_DESISTENCIA					
		,DESTINO.QT_FALECIDO					= DESTINO.QT_FALECIDO						
		,DESTINO.VL_TAP							= DESTINO.VL_TAP							
		,DESTINO.VL_TCA							= DESTINO.VL_TCA							
		,DESTINO.VL_TCAN						= DESTINO.VL_TCAN							
		,DESTINO.VL_TDA							= DESTINO.VL_TDA							
		,DESTINO.VL_TDAN						= DESTINO.VL_TDAN							
	;	
END 
