

create    PROCEDURE [ods].[SP_ODS_UNIDADE_FEDERATIVA]		AS
BEGIN 
	DECLARE @DTA_EXECUCAO DATETIME2(2) = GETDATE()
--	TEMPDB..SP_HELP '#ODS_CURSO'
	
	MERGE INTO ODS.ODS_UNIDADE_FEDERATIVA		WITH (TABLOCK) AS DESTINO
	USING	(											
				SELECT DISTINCT CO_UF_IES CO_UF, NO_UF_IES   COLLATE Latin1_General_CI_Ai NO_UF ,SG_UF_IES  COLLATE Latin1_General_CI_Ai    SG_UF, CO_REGIAO_IES CO_REGIAO
				FROM 	DB_EVASAO..MICRODADOS_CADASTRO_IES_2010   UNION 
				SELECT CO_UF_IES, NO_UF_IES,SG_UF_IES, CO_REGIAO_IES  FROM	DB_EVASAO..MICRODADOS_CADASTRO_IES_2011 UNION 
				SELECT CO_UF_IES, NO_UF_IES,SG_UF_IES, CO_REGIAO_IES  FROM	DB_EVASAO..MICRODADOS_CADASTRO_IES_2012 UNION 
				SELECT CO_UF_IES, NO_UF_IES,SG_UF_IES, CO_REGIAO_IES  FROM	DB_EVASAO..MICRODADOS_CADASTRO_IES_2013 UNION 
				SELECT CO_UF_IES, NO_UF_IES,SG_UF_IES, CO_REGIAO_IES  FROM	DB_EVASAO..MICRODADOS_CADASTRO_IES_2014 UNION 
				SELECT CO_UF_IES, NO_UF_IES,SG_UF_IES, CO_REGIAO_IES  FROM	DB_EVASAO..MICRODADOS_CADASTRO_IES_2015 UNION 
				SELECT CO_UF_IES, NO_UF_IES,SG_UF_IES, CO_REGIAO_IES  FROM	DB_EVASAO..MICRODADOS_CADASTRO_IES_2016 UNION 
				SELECT CO_UF_IES, NO_UF_IES,SG_UF_IES, CO_REGIAO_IES  FROM	DB_EVASAO..MICRODADOS_CADASTRO_IES_2017 UNION 
				SELECT CO_UF_IES, NO_UF_IES,SG_UF_IES, CO_REGIAO_IES  FROM	DB_EVASAO..MICRODADOS_CADASTRO_IES_2018 UNION 
				SELECT CO_UF_IES, NO_UF_IES,SG_UF_IES, CO_REGIAO_IES  FROM	DB_EVASAO..MICRODADOS_CADASTRO_IES_2019 UNION 
				SELECT CO_UF_IES, NO_UF_IES,SG_UF_IES, CO_REGIAO_IES  FROM	DB_EVASAO..MICRODADOS_CADASTRO_IES_2020 UNION 
				SELECT CO_UF_IES, NO_UF_IES,SG_UF_IES, CO_REGIAO_IES  FROM	DB_EVASAO..MICRODADOS_CADASTRO_IES_2021 UNION
				SELECT CO_UF_IES, NO_UF_IES,SG_UF_IES, CO_REGIAO_IES  FROM	DB_EVASAO..MICRODADOS_CADASTRO_IES_2022 UNION
				SELECT CO_UF_IES, NO_UF_IES,SG_UF_IES, CO_REGIAO_IES  FROM	DB_EVASAO..MICRODADOS_CADASTRO_IES_2023 

			) AS ORIGEM
	ON 	(	
			DESTINO.CO_UF		=	ORIGEM.CO_UF	 
		)
	WHEN NOT MATCHED THEN
		INSERT
			(	
				 CO_UF
				,NO_UF
				,SG_UF
				,CO_REGIAO
			
			)	
			VALUES
			(	 
				 ORIGEM.CO_UF
				,ORIGEM.NO_UF
				,ORIGEM.SG_UF
				,ORIGEM.CO_REGIAO
				
			)																					
	WHEN MATCHED AND
	(    
		(ORIGEM.NO_UF		<>	DESTINO.NO_UF		OR	(ORIGEM.NO_UF		IS NULL AND DESTINO.NO_UF		IS NOT NULL)	OR	(ORIGEM.NO_UF		IS NOT NULL AND DESTINO.NO_UF		IS NULL))	OR
		(ORIGEM.SG_UF		<>	DESTINO.SG_UF		OR	(ORIGEM.SG_UF		IS NULL AND DESTINO.SG_UF		IS NOT NULL)	OR	(ORIGEM.SG_UF		IS NOT NULL AND DESTINO.SG_UF		IS NULL))	OR
		(ORIGEM.CO_REGIAO	<>	DESTINO.CO_REGIAO	OR	(ORIGEM.CO_REGIAO	IS NULL AND DESTINO.CO_REGIAO	IS NOT NULL)	OR	(ORIGEM.CO_REGIAO	IS NOT NULL AND DESTINO.CO_REGIAO	IS NULL))	
	)
	THEN UPDATE
		SET
		 DESTINO.NO_UF		= ORIGEM.NO_UF		
		,DESTINO.SG_UF		= ORIGEM.SG_UF		
		,DESTINO.CO_REGIAO	= ORIGEM.CO_REGIAO		
	;	
END 
