
CREATE      PROCEDURE [ods].[SP_ODS_CURSO]		AS
BEGIN 
	DECLARE @DTA_EXECUCAO DATETIME2(2) = GETDATE()
--	TEMPDB..SP_HELP '#ODS_CURSO'
	
	
	DROP TABLE IF EXISTS #ODS_CURSO
	SELECT DISTINCT CODIGO_CURSO CO_CURSO, ANO_REFERENCIA NU_ANO_REFERENCIA,
		NOME_CURSO NO_CURSO
		INTO #ODS_CURSO
	FROM [stg].[STG_DADOS_FLUXO] DF

	DROP TABLE IF EXISTS #ODS_CURSO_MX
	SELECT DISTINCT 
			CODIGO_CURSO CO_CURSO, 
			ANO_REFERENCIA NU_ANO_REFERENCIA, 
			CODIGO_AREA_CURSO_CINE CO_AREA,
			NOME_CURSO NO_CURSO
			INTO #ODS_CURSO_MX
	FROM [stg].[STG_DADOS_FLUXO] DF
	INNER JOIN (
		SELECT MAX(NU_ANO_REFERENCIA) NU_ANO_REFERENCIA, CO_CURSO
			FROM #ODS_CURSO
			GROUP BY CO_CURSO
		) MX ON 
		DF.codigo_curso = MX.CO_CURSO AND 
		DF.ano_referencia = MX.NU_ANO_REFERENCIA



	MERGE INTO ODS.ODS_CURSO		WITH (TABLOCK) AS DESTINO
	USING	(											
				SELECT 
					CO_CURSO
				,	UPPER(NO_CURSO)  COLLATE LATIN1_GENERAL_CI_AS AS NO_CURSO
				, CO_AREA
				FROM #ODS_CURSO_MX 
				
			) AS ORIGEM
	ON 	(	
			DESTINO.CO_CURSO		=	ORIGEM.CO_CURSO	 
		)
	WHEN NOT MATCHED THEN
		INSERT
			(	
				 CO_CURSO
				,NO_CURSO
				-- ,TP_DIMENSAO
				-- --,TPO_REDE
				 ,CO_AREA
				-- ,TP_GRAU_ACADEMICO
				-- ,FL_GRATUITO
				-- ,TP_MODALIDADE_ENSINO
				-- ,TP_NIVEL_ACADEMICO
				
			)	
			VALUES
			(	 
				 ORIGEM.CO_CURSO
				 ,ORIGEM.NO_CURSO
				-- ,ORIGEM.TP_DIMENSAO
				-- --,ORIGEM.TPO_REDE
				 ,ORIGEM.CO_AREA
				-- ,ORIGEM.TP_GRAU_ACADEMICO
				-- ,ORIGEM.FL_GRATUITO
				-- ,ORIGEM.TP_MODALIDADE_ENSINO
				-- ,ORIGEM.TP_NIVEL_ACADEMICO
			)																					
	WHEN MATCHED AND
	(    
		(ORIGEM.NO_CURSO				<>	DESTINO.NO_CURSO				OR	(ORIGEM.NO_CURSO				IS NULL AND DESTINO.NO_CURSO				IS NOT NULL)	OR	(ORIGEM.NO_CURSO				IS NOT NULL AND DESTINO.NO_CURSO				IS NULL))	OR
	-- 	(ORIGEM.TP_DIMENSAO				<>	DESTINO.TP_DIMENSAO				OR	(ORIGEM.TP_DIMENSAO				IS NULL AND DESTINO.TP_DIMENSAO				IS NOT NULL)	OR	(ORIGEM.TP_DIMENSAO				IS NOT NULL AND DESTINO.TP_DIMENSAO				IS NULL))	OR
	 	(ORIGEM.CO_AREA					<>	DESTINO.CO_AREA					OR	(ORIGEM.CO_AREA					IS NULL AND DESTINO.CO_AREA					IS NOT NULL)	OR	(ORIGEM.CO_AREA					IS NOT NULL AND DESTINO.CO_AREA					IS NULL))	
	-- --	(ORIGEM.TPO_REDE				<>	DESTINO.TP_REDE					OR	(ORIGEM.TP_REDE					IS NULL AND DESTINO.TP_REDE					IS NOT NULL)	OR	(ORIGEM.TP_REDE					IS NOT NULL AND DESTINO.TP_REDE					IS NULL))	OR
	-- 	(ORIGEM.TP_GRAU_ACADEMICO		<>	DESTINO.TP_GRAU_ACADEMICO		OR	(ORIGEM.TP_GRAU_ACADEMICO		IS NULL AND DESTINO.TP_GRAU_ACADEMICO		IS NOT NULL)	OR	(ORIGEM.TP_GRAU_ACADEMICO		IS NOT NULL AND DESTINO.TP_GRAU_ACADEMICO		IS NULL))	OR
	-- 	(ORIGEM.FL_GRATUITO				<>	DESTINO.FL_GRATUITO				OR	(ORIGEM.FL_GRATUITO				IS NULL AND DESTINO.FL_GRATUITO				IS NOT NULL)	OR	(ORIGEM.FL_GRATUITO				IS NOT NULL AND DESTINO.FL_GRATUITO				IS NULL))	OR
	-- 	(ORIGEM.TP_MODALIDADE_ENSINO	<>	DESTINO.TP_MODALIDADE_ENSINO	OR	(ORIGEM.TP_MODALIDADE_ENSINO	IS NULL AND DESTINO.TP_MODALIDADE_ENSINO	IS NOT NULL)	OR	(ORIGEM.TP_MODALIDADE_ENSINO	IS NOT NULL AND DESTINO.TP_MODALIDADE_ENSINO	IS NULL))	OR
	-- 	(ORIGEM.TP_NIVEL_ACADEMICO		<>	DESTINO.TP_NIVEL_ACADEMICO		OR	(ORIGEM.TP_NIVEL_ACADEMICO		IS NULL AND DESTINO.TP_NIVEL_ACADEMICO		IS NOT NULL)	OR	(ORIGEM.TP_NIVEL_ACADEMICO		IS NOT NULL AND DESTINO.TP_NIVEL_ACADEMICO		IS NULL))			
	)
	THEN UPDATE
		SET
			DESTINO.NO_CURSO				= 	ORIGEM.NO_CURSO				
--		,	DESTINO.TP_DIMENSAO				= 	ORIGEM.TP_DIMENSAO			
--	--	,	DESTINO.TP_REDE					= 	ORIGEM.TP_REDE				
		,	DESTINO.CO_AREA					= 	ORIGEM.CO_AREA			
--		,	DESTINO.TP_GRAU_ACADEMICO		= 	ORIGEM.TP_GRAU_ACADEMICO		
--		,	DESTINO.FL_GRATUITO				= 	ORIGEM.FL_GRATUITO			
--		,	DESTINO.TP_MODALIDADE_ENSINO	= 	ORIGEM.TP_MODALIDADE_ENSINO	
--		,	DESTINO.TP_NIVEL_ACADEMICO		= 	ORIGEM.TP_NIVEL_ACADEMICO		
	;	
END 
