

create      PROCEDURE [ods].[SP_ODS_IES]		AS
BEGIN 
	DECLARE @DTA_EXECUCAO DATETIME2(2) = GETDATE()
	
		DROP TABLE IF EXISTS #ODS_IES
		SELECT DISTINCT
		  CI.CO_IES									
		, CI.NO_IES									collate Latin1_General_CI_AS	as NO_IES									
		, CI.SG_IES									collate Latin1_General_CI_AS	as SG_IES									
		, CI.NU_ANO_CENSO							
		, CI.CO_MUNICIPIO_IES						CO_MUNICIPIO_IES
		, CI.IN_CAPITAL_IES							IN_CAPITAL_IES
		, CI.TP_ORGANIZACAO_ACADEMICA				
		, CI.TP_CATEGORIA_ADMINISTRATIVA			
		, CI.CO_MANTENEDORA							
		, CI.NU_CEP_IES								
		/*	
		1. Pública Federal
		2. Pública Estadual
		3. Pública Municipal
		4. Privada com fins lucrativos
		5. Privada sem fins lucrativos
		6. Privada - Particular em sentido estrito
		7. Especial
		8. Privada comunitária
		9. Privada confessional"
		*/

		/*, CASE 
			WHEN ies.NO_REDE = 'Publica' then 1 
			WHEN ies.NO_REDE = 'Privada' then 2
			END TP_REDE	
		*/
		INTO #ODS_IES
			FROM STG.[STG_MICRODADOS_CADASTRO_IES_COMPLETO] CI
			CREATE CLUSTERED INDEX IXC_TMP_ODS_IES ON #ODS_IES (CO_IES, NU_ANO_CENSO)


	MERGE INTO ODS.ODS_iES		WITH (TABLOCK) AS DESTINO
	USING	(											
				SELECT distinct 
				IES.CO_IES
			,	IES.NO_IES							collate Latin1_General_CI_AS	as NO_IES
			,	IES.SG_IES							collate Latin1_General_CI_AS	as SG_IES
			,	IES.NU_ANO_CENSO
			,	IES.CO_MUNICIPIO_ies	CO_MUNICIPIO
			,	IES.IN_CAPITAL_IES		IN_CAPITAL
			,	IES.TP_ORGANIZACAO_ACADEMICA
			,	IES.TP_CATEGORIA_ADMINISTRATIVA
			,	IES.CO_MANTENEDORA	
			,	IES.DS_ENDERECO_IES					collate Latin1_General_CI_AS as DS_ENDERECO_IES					
			,	IES.DS_NUMERO_ENDERECO_IES			collate Latin1_General_CI_AS as DS_NUMERO_ENDERECO_IES
			,	IES.DS_COMPLEMENTO_ENDERECO_IES		collate Latin1_General_CI_AS as DS_COMPLEMENTO_ENDERECO_IES
			,	IES.NO_BAIRRO_IES					collate Latin1_General_CI_AS as NO_BAIRRO_IES
			,	IES.NU_CEP_IES
			,	CASE 
				WHEN IES.TP_CATEGORIA_ADMINISTRATIVA IN (1,2,3,7) THEN 1
				WHEN IES.TP_CATEGORIA_ADMINISTRATIVA IN (4,5,6,8,9) THEN 2
				ELSE 0 END TP_REDE

			--INTO ODS.ODS_IES
			FROM STG.[STG_MICRODADOS_CADASTRO_IES_COMPLETO]	IES
				INNER JOIN 
				(SELECT CO_IES, MAX(NU_ANO_CENSO) NU_ANO_CENSO
					FROM #ODS_IES
					GROUP BY CO_IES
					) MX
				ON IES.CO_IES = MX.CO_IES AND 
					IES.NU_ANO_CENSO = MX.NU_ANO_CENSO
			) AS ORIGEM
	ON 	(	
			DESTINO.CO_IES		=	ORIGEM.CO_IES	 
		)
	WHEN NOT MATCHED THEN
		INSERT
			(	
					CO_IES
				,	NO_IES
				,	SG_IES
				,	NU_ANO_CENSO
				,	CO_MUNICIPIO
				,	IN_CAPITAL
				,	TP_ORGANIZACAO_ACADEMICA
				,	TP_CATEGORIA_ADMINISTRATIVA
				,	CO_MANTENEDORA
				,	DS_ENDERECO_IES
				,	DS_NUMERO_ENDERECO_IES
				,	DS_COMPLEMENTO_ENDERECO_IES
				,	NO_BAIRRO_IES
				,	NU_CEP_IES
				,	TP_REDE			
			)	
			VALUES
			(	 
					origem.CO_IES
				,	origem.NO_IES
				,	origem.SG_IES
				,	origem.NU_ANO_CENSO
				,	origem.CO_MUNICIPIO
				,	origem.IN_CAPITAL
				,	origem.TP_ORGANIZACAO_ACADEMICA
				,	origem.TP_CATEGORIA_ADMINISTRATIVA
				,	origem.CO_MANTENEDORA
				,	origem.DS_ENDERECO_IES
				,	origem.DS_NUMERO_ENDERECO_IES
				,	origem.DS_COMPLEMENTO_ENDERECO_IES
				,	origem.NO_BAIRRO_IES
				,	origem.NU_CEP_IES
				,	origem.tp_rede		
			)																					
	WHEN MATCHED AND
	(    
		(ORIGEM.NO_IES							<>	DESTINO.NO_IES							OR	(ORIGEM.NO_IES							IS NULL AND DESTINO.NO_IES						IS NOT NULL)	OR	(ORIGEM.NO_IES							IS NOT NULL AND DESTINO.NO_IES						IS NULL))	OR
		(ORIGEM.SG_IES							<>	DESTINO.SG_IES							OR	(ORIGEM.SG_IES							IS NULL AND DESTINO.SG_IES						IS NOT NULL)	OR	(ORIGEM.SG_IES							IS NOT NULL AND DESTINO.SG_IES						IS NULL))	OR
		(ORIGEM.NU_ANO_CENSO					<>	DESTINO.NU_ANO_CENSO					OR	(ORIGEM.NU_ANO_CENSO					IS NULL AND DESTINO.NU_ANO_CENSO				IS NOT NULL)	OR	(ORIGEM.NU_ANO_CENSO					IS NOT NULL AND DESTINO.NU_ANO_CENSO				IS NULL))	OR
		(ORIGEM.CO_MUNICIPIO					<>	DESTINO.CO_MUNICIPIO					OR	(ORIGEM.CO_MUNICIPIO					IS NULL AND DESTINO.CO_MUNICIPIO				IS NOT NULL)	OR	(ORIGEM.CO_MUNICIPIO					IS NOT NULL AND DESTINO.CO_MUNICIPIO				IS NULL))	OR
		(ORIGEM.IN_CAPITAL						<>	DESTINO.IN_CAPITAL						OR	(ORIGEM.IN_CAPITAL						IS NULL AND DESTINO.IN_CAPITAL					IS NOT NULL)	OR	(ORIGEM.IN_CAPITAL						IS NOT NULL AND DESTINO.IN_CAPITAL					IS NULL))	OR
		(ORIGEM.TP_ORGANIZACAO_ACADEMICA		<>	DESTINO.TP_ORGANIZACAO_ACADEMICA		OR	(ORIGEM.TP_ORGANIZACAO_ACADEMICA		IS NULL AND DESTINO.TP_ORGANIZACAO_ACADEMICA	IS NOT NULL)	OR	(ORIGEM.TP_ORGANIZACAO_ACADEMICA		IS NOT NULL AND DESTINO.TP_ORGANIZACAO_ACADEMICA	IS NULL))	OR
		(ORIGEM.TP_CATEGORIA_ADMINISTRATIVA		<>	DESTINO.TP_CATEGORIA_ADMINISTRATIVA		OR	(ORIGEM.TP_CATEGORIA_ADMINISTRATIVA		IS NULL AND DESTINO.TP_CATEGORIA_ADMINISTRATIVA	IS NOT NULL)	OR	(ORIGEM.TP_CATEGORIA_ADMINISTRATIVA		IS NOT NULL AND DESTINO.TP_CATEGORIA_ADMINISTRATIVA	IS NULL))	OR
		(ORIGEM.CO_MANTENEDORA					<>	DESTINO.CO_MANTENEDORA					OR	(ORIGEM.CO_MANTENEDORA					IS NULL AND DESTINO.CO_MANTENEDORA				IS NOT NULL)	OR	(ORIGEM.CO_MANTENEDORA					IS NOT NULL AND DESTINO.CO_MANTENEDORA				IS NULL))	OR
		(ORIGEM.DS_ENDERECO_IES					<>	DESTINO.DS_ENDERECO_IES					OR	(ORIGEM.DS_ENDERECO_IES					IS NULL AND DESTINO.DS_ENDERECO_IES				IS NOT NULL)	OR	(ORIGEM.DS_ENDERECO_IES					IS NOT NULL AND DESTINO.DS_ENDERECO_IES				IS NULL))	OR
		(ORIGEM.DS_NUMERO_ENDERECO_IES			<>	DESTINO.DS_NUMERO_ENDERECO_IES			OR	(ORIGEM.DS_NUMERO_ENDERECO_IES			IS NULL AND DESTINO.DS_NUMERO_ENDERECO_IES		IS NOT NULL)	OR	(ORIGEM.DS_NUMERO_ENDERECO_IES			IS NOT NULL AND DESTINO.DS_NUMERO_ENDERECO_IES		IS NULL))	OR
		(ORIGEM.DS_COMPLEMENTO_ENDERECO_IES		<>	DESTINO.DS_COMPLEMENTO_ENDERECO_IES		OR	(ORIGEM.DS_COMPLEMENTO_ENDERECO_IES		IS NULL AND DESTINO.DS_COMPLEMENTO_ENDERECO_IES	IS NOT NULL)	OR	(ORIGEM.DS_COMPLEMENTO_ENDERECO_IES		IS NOT NULL AND DESTINO.DS_COMPLEMENTO_ENDERECO_IES	IS NULL))	OR
		(ORIGEM.NO_BAIRRO_IES					<>	DESTINO.NO_BAIRRO_IES					OR	(ORIGEM.NO_BAIRRO_IES					IS NULL AND DESTINO.NO_BAIRRO_IES				IS NOT NULL)	OR	(ORIGEM.NO_BAIRRO_IES					IS NOT NULL AND DESTINO.NO_BAIRRO_IES				IS NULL))	OR
		(ORIGEM.NU_CEP_IES						<>	DESTINO.NU_CEP_IES						OR	(ORIGEM.NU_CEP_IES						IS NULL AND DESTINO.NU_CEP_IES					IS NOT NULL)	OR	(ORIGEM.NU_CEP_IES						IS NOT NULL AND DESTINO.NU_CEP_IES					IS NULL))	OR
		(ORIGEM.TP_REDE							<>	DESTINO.TP_REDE							OR	(ORIGEM.TP_REDE							IS NULL AND DESTINO.TP_REDE						IS NOT NULL)	OR	(ORIGEM.TP_REDE							IS NOT NULL AND DESTINO.TP_REDE						IS NULL))


	)
	THEN UPDATE
		SET
		 
			DESTINO.NO_IES							=	ORIGEM.NO_IES							
		 ,	DESTINO.SG_IES							=	ORIGEM.SG_IES							
		 ,	DESTINO.NU_ANO_CENSO					=	ORIGEM.NU_ANO_CENSO					
		 ,	DESTINO.CO_MUNICIPIO					=	ORIGEM.CO_MUNICIPIO					
		 ,	DESTINO.IN_CAPITAL						=	ORIGEM.IN_CAPITAL						
		 ,	DESTINO.TP_ORGANIZACAO_ACADEMICA		=	ORIGEM.TP_ORGANIZACAO_ACADEMICA		
		 ,	DESTINO.TP_CATEGORIA_ADMINISTRATIVA		= 	ORIGEM.TP_CATEGORIA_ADMINISTRATIVA		
		 ,	DESTINO.CO_MANTENEDORA					=	ORIGEM.CO_MANTENEDORA					
		 ,	DESTINO.DS_ENDERECO_IES					= 	ORIGEM.DS_ENDERECO_IES					
		 ,	DESTINO.DS_NUMERO_ENDERECO_IES			= 	ORIGEM.DS_NUMERO_ENDERECO_IES			
		 ,	DESTINO.DS_COMPLEMENTO_ENDERECO_IES		= 	ORIGEM.DS_COMPLEMENTO_ENDERECO_IES		
		 ,	DESTINO.NO_BAIRRO_IES					= 	ORIGEM.NO_BAIRRO_IES					
		 ,	DESTINO.NU_CEP_IES						= 	ORIGEM.NU_CEP_IES						
		 ,	DESTINO.TP_REDE							= 	ORIGEM.TP_REDE							
	;	
END 
