
CREATE      PROCEDURE [ods].[SP_ODS_MUNICIPIO]		AS
BEGIN 
	
	MERGE INTO ODS.ODS_MUNICIPIO		WITH (TABLOCK) AS DESTINO
	USING	(											
				select DISTINCT 
				  CO_MUNICIPIO_COMPLETO CO_MUNICIPIO
				, NO_MUNICIPIO
				, CO_UF
				from stg.STG_RELATORIO_DTB_BRASIL_DISTRITO

			) AS ORIGEM
	ON 	(	
			DESTINO.CO_MUNICIPIO	=	ORIGEM.CO_MUNICIPIO	 AND 
			DESTINO.CO_UF			=	ORIGEM.CO_UF 
		)
	WHEN NOT MATCHED THEN
		INSERT
			(	
				 CO_MUNICIPIO
				, NO_MUNICIPIO
				, CO_UF
			
			)	
			VALUES
			(	 
				 ORIGEM.CO_MUNICIPIO
				,ORIGEM.NO_MUNICIPIO
				,ORIGEM.CO_UF
			)																					
	WHEN MATCHED AND
	(    
		(ORIGEM.NO_MUNICIPIO	<>	DESTINO.NO_MUNICIPIO	OR	(ORIGEM.NO_MUNICIPIO	IS NULL AND DESTINO.NO_MUNICIPIO	IS NOT NULL)	OR	(ORIGEM.NO_MUNICIPIO	IS NOT NULL AND DESTINO.NO_MUNICIPIO	IS NULL))	OR
		(ORIGEM.CO_UF			<>	DESTINO.CO_UF			OR	(ORIGEM.CO_UF			IS NULL AND DESTINO.CO_UF			IS NOT NULL)	OR	(ORIGEM.CO_UF			IS NOT NULL AND DESTINO.CO_UF			IS NULL))	
		
	)
	THEN UPDATE
		SET
		  DESTINO.NO_MUNICIPIO	= ORIGEM.NO_MUNICIPIO	
		 ,DESTINO.CO_UF			= ORIGEM.CO_UF			
	;
END 


