CREATE    PROCEDURE ODS.sp_ODS_CINE_CURSO_GRANDE_AREA		AS
BEGIN 
	DECLARE @DTA_EXECUCAO DATETIME2(2) = GETDATE()
	MERGE INTO ODS.ODS_CINE_CURSO_GRANDE_AREA		WITH (TABLOCK) AS DESTINO
	USING	(											
				select distinct 
					CODIGO_GRANDE_AREA_CURSO_CINE AS COD_GRANDE_AREA
				,	NOME_GRANDE_AREA_CURSO_CINE	AS NME_GRANDE_AREA
			from [stg].[STG_DADOS_FLUXO]

			) AS ORIGEM
	ON 	(	
			DESTINO.COD_GRANDE_AREA		=	ORIGEM.COD_GRANDE_AREA	 
		)
	WHEN NOT MATCHED THEN
		INSERT
			(	
				 COD_GRANDE_AREA
				,NME_GRANDE_AREA
				
			)	
			VALUES
			(	
				 ORIGEM.COD_GRANDE_AREA
				,ORIGEM.NME_GRANDE_AREA
				
			)																					
	WHEN MATCHED AND
	(    
		(ORIGEM.NME_GRANDE_AREA		<>	DESTINO.NME_GRANDE_AREA		OR	(ORIGEM.NME_GRANDE_AREA		IS NULL AND DESTINO.NME_GRANDE_AREA		IS NOT NULL)	OR	(ORIGEM.NME_GRANDE_AREA		IS NOT NULL AND DESTINO.NME_GRANDE_AREA		IS NULL))	
	)
	THEN UPDATE
		SET
			DESTINO.NME_GRANDE_AREA		= ORIGEM.NME_GRANDE_AREA
	;	
END 
