
CREATE      PROCEDURE [ods].[SP_ODS_MANTENEDORA]		AS
BEGIN 
	DECLARE @DTA_EXECUCAO DATETIME2(2) = GETDATE()
	
	DROP TABLE IF EXISTS #ODS_MANTENEDORA_IES
	SELECT DISTINCT CO_MANTENEDORA,NO_MANTENEDORA, NU_ANO_CENSO 
	INTO #ODS_MANTENEDORA_IES
		FROM STG.[STG_MICRODADOS_CADASTRO_IES_COMPLETO] ies
	CREATE CLUSTERED INDEX IXC_ODS_MANTENEDORA_IES ON #ODS_MANTENEDORA_IES(CO_MANTENEDORA,NU_ANO_CENSO )

	MERGE INTO ODS.ODS_MANTENEDORA_IES		WITH (TABLOCK) AS DESTINO
	USING	(											
				SELECT 
					IES.CO_MANTENEDORA, 
					IES.NO_MANTENEDORA collate Latin1_General_CI_AI as NO_MANTENEDORA,
					IES.NU_ANO_CENSO
				FROM #ODS_MANTENEDORA_IES IES
				INNER JOIN (
					SELECT MAX(NU_ANO_CENSO) NU_ANO_CENSO, CO_MANTENEDORA
					FROM #ODS_MANTENEDORA_IES
					GROUP BY CO_MANTENEDORA
				) MX ON IES.CO_MANTENEDORA	=	MX.CO_MANTENEDORA AND 
						IES.NU_ANO_CENSO	=	MX.NU_ANO_CENSO

			) AS ORIGEM
	ON 	(	
			DESTINO.CO_MANTENEDORA		=	ORIGEM.CO_MANTENEDORA	 
		)
	WHEN NOT MATCHED THEN
		INSERT
			(	
				 CO_MANTENEDORA
				,NO_MANTENEDORA
				,NU_ANO_CENSO
			
			
			)	
			VALUES
			(	 
				 ORIGEM.CO_MANTENEDORA
				,ORIGEM.NO_MANTENEDORA
				,ORIGEM.NU_ANO_CENSO			
			)																					
	WHEN MATCHED AND
	(    
		(ORIGEM.NO_MANTENEDORA		<>	DESTINO.NO_MANTENEDORA		OR	(ORIGEM.NO_MANTENEDORA		IS NULL AND DESTINO.NO_MANTENEDORA		IS NOT NULL)	OR	(ORIGEM.NO_MANTENEDORA		IS NOT NULL AND DESTINO.NO_MANTENEDORA		IS NULL))	OR
		(ORIGEM.NU_ANO_CENSO		<>	DESTINO.NU_ANO_CENSO		OR	(ORIGEM.NU_ANO_CENSO		IS NULL AND DESTINO.NU_ANO_CENSO		IS NOT NULL)	OR	(ORIGEM.NU_ANO_CENSO		IS NOT NULL AND DESTINO.NU_ANO_CENSO		IS NULL))
	)
	THEN UPDATE
		SET
		 DESTINO.NO_MANTENEDORA		=	ORIGEM.NO_MANTENEDORA	
		 ,DESTINO.NU_ANO_CENSO		=	ORIGEM.NU_ANO_CENSO		
	;	
END 
