CREATE PROCEDURE ODS.SP_ODS_CINE_CURSO_AREA		AS
BEGIN 
	DECLARE @DTA_EXECUCAO DATETIME2(2) = GETDATE()
	MERGE INTO ODS.ODS_CINE_CURSO_AREA		WITH (TABLOCK) AS DESTINO
	USING	(											
				SELECT DISTINCT 
					CODIGO_AREA_CURSO_CINE					COD_AREA
				,	NOME_AREA_CURSO_CINE					NME_AREA
				,	CODIGO_GRANDE_AREA_CURSO_CINE	COD_GRANDE_AREA

				FROM [STG].[STG_DADOS_FLUXO]

			) AS ORIGEM
	ON 	(	
			DESTINO.COD_AREA		=	ORIGEM.COD_AREA	 
		)
	WHEN NOT MATCHED THEN
		INSERT
			(	
				 COD_AREA
				,NME_AREA
				,COD_GRANDE_AREA
			)	
			VALUES
			(	
				 ORIGEM.COD_AREA
				,ORIGEM.NME_AREA
				,ORIGEM.COD_GRANDE_AREA
			)																					
	WHEN MATCHED AND
	(    
		(ORIGEM.NME_AREA		<>	DESTINO.NME_AREA		OR	(ORIGEM.NME_AREA		IS NULL AND DESTINO.NME_AREA		IS NOT NULL)	OR	(ORIGEM.NME_AREA		IS NOT NULL AND DESTINO.NME_AREA		IS NULL))	OR 
		(ORIGEM.COD_GRANDE_AREA	<>	DESTINO.COD_GRANDE_AREA	OR	(ORIGEM.COD_GRANDE_AREA	IS NULL AND DESTINO.COD_GRANDE_AREA	IS NOT NULL)	OR	(ORIGEM.COD_GRANDE_AREA	IS NOT NULL AND DESTINO.COD_GRANDE_AREA	IS NULL))	
	)
	THEN UPDATE
		SET
			DESTINO.NME_AREA		= ORIGEM.NME_AREA		,
			DESTINO.COD_GRANDE_AREA	= ORIGEM.COD_GRANDE_AREA	
	;	
END 
