use tcc_evasao
SELECT file_id,
       name,
       CAST(FILEPROPERTY(name, 'SpaceUsed') AS bigint) * 8 / 1024. AS space_used_mb,
       CAST(size AS bigint) * 8 / 1024. AS space_allocated_mb,
       CAST(max_size AS bigint) * 8 / 1024. AS max_file_size_mb
FROM sys.database_files
WHERE type_desc IN ('ROWS','LOG');



SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME LIKE 'MICRODADOS_CADASTRO_CURSOS%'

CREATE CLUSTERED INDEX IXC_MICRODADOS_CADASTRO_CURSOS_2010 ON MICRODADOS_CADASTRO_CURSOS_2010 (CO_CURSO)
CREATE CLUSTERED INDEX IXC_MICRODADOS_CADASTRO_CURSOS_2011 ON MICRODADOS_CADASTRO_CURSOS_2011 (CO_CURSO)
CREATE CLUSTERED INDEX IXC_MICRODADOS_CADASTRO_CURSOS_2012 ON MICRODADOS_CADASTRO_CURSOS_2012 (CO_CURSO)
CREATE CLUSTERED INDEX IXC_MICRODADOS_CADASTRO_CURSOS_2013 ON MICRODADOS_CADASTRO_CURSOS_2013 (CO_CURSO)
CREATE CLUSTERED INDEX IXC_MICRODADOS_CADASTRO_CURSOS_2014 ON MICRODADOS_CADASTRO_CURSOS_2014 (CO_CURSO)
CREATE CLUSTERED INDEX IXC_MICRODADOS_CADASTRO_CURSOS_2015 ON MICRODADOS_CADASTRO_CURSOS_2015 (CO_CURSO)
CREATE CLUSTERED INDEX IXC_MICRODADOS_CADASTRO_CURSOS_2016 ON MICRODADOS_CADASTRO_CURSOS_2016 (CO_CURSO)
CREATE CLUSTERED INDEX IXC_MICRODADOS_CADASTRO_CURSOS_2017 ON MICRODADOS_CADASTRO_CURSOS_2017 (CO_CURSO)
CREATE CLUSTERED INDEX IXC_MICRODADOS_CADASTRO_CURSOS_2018 ON MICRODADOS_CADASTRO_CURSOS_2018 (CO_CURSO)
CREATE CLUSTERED INDEX IXC_MICRODADOS_CADASTRO_CURSOS_2019 ON MICRODADOS_CADASTRO_CURSOS_2019 (CO_CURSO)
CREATE CLUSTERED INDEX IXC_MICRODADOS_CADASTRO_CURSOS_2020 ON MICRODADOS_CADASTRO_CURSOS_2020 (CO_CURSO)
CREATE CLUSTERED INDEX IXC_MICRODADOS_CADASTRO_CURSOS_2021 ON MICRODADOS_CADASTRO_CURSOS_2021 (CO_CURSO)



DROP TABLE IF EXISTS STG.STG_MICRODADOS_CADASTRO_CURSOS_SP
SELECT * INTO stg.STG_MICRODADOS_CADASTRO_CURSOS_SP
		 FROM  MICRODADOS_CADASTRO_CURSOS_2010 WHERE SG_UF = 'SP' UNION 
SELECT * FROM  MICRODADOS_CADASTRO_CURSOS_2011 WHERE SG_UF = 'SP' UNION 
SELECT * FROM  MICRODADOS_CADASTRO_CURSOS_2012 WHERE SG_UF = 'SP' UNION 
SELECT * FROM  MICRODADOS_CADASTRO_CURSOS_2013 WHERE SG_UF = 'SP' UNION 
SELECT * FROM  MICRODADOS_CADASTRO_CURSOS_2014 WHERE SG_UF = 'SP' UNION 
SELECT * FROM  MICRODADOS_CADASTRO_CURSOS_2015 WHERE SG_UF = 'SP' UNION 
SELECT * FROM  MICRODADOS_CADASTRO_CURSOS_2016 WHERE SG_UF = 'SP' UNION 
SELECT * FROM  MICRODADOS_CADASTRO_CURSOS_2017 WHERE SG_UF = 'SP' UNION 
SELECT * FROM  MICRODADOS_CADASTRO_CURSOS_2018 WHERE SG_UF = 'SP' UNION 
SELECT * FROM  MICRODADOS_CADASTRO_CURSOS_2019 WHERE SG_UF = 'SP' UNION 
SELECT * FROM  MICRODADOS_CADASTRO_CURSOS_2020 WHERE SG_UF = 'SP' UNION 
SELECT * FROM  MICRODADOS_CADASTRO_CURSOS_2021 WHERE SG_UF = 'SP' 

CREATE CLUSTERED INDEX IXC_STG_MICRODADOS_CADASTRO_CURSO_SP ON STG.STG_MICRODADOS_CADASTRO_CURSOS_SP(NU_ANO_CENSO, co_curso, co_ies)


SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME LIKE 'MICRODADOS_CADASTRO_IES%'


drop table if exists stg.STG_MICRODADOS_CADASTRO_IES_SP
SELECT NU_ANO_CENSO,NO_REGIAO_IES,CO_REGIAO_IES,NO_UF_IES,SG_UF_IES,CO_UF_IES,NO_MUNICIPIO_IES,CO_MUNICIPIO_IES,IN_CAPITAL_IES,NO_MESORREGIAO_IES,CO_MESORREGIAO_IES,NO_MICRORREGIAO_IES,CO_MICRORREGIAO_IES,TP_ORGANIZACAO_ACADEMICA,TP_CATEGORIA_ADMINISTRATIVA,NO_MANTENEDORA,CO_MANTENEDORA,CO_IES,NO_IES,SG_IES,DS_ENDERECO_IES,DS_NUMERO_ENDERECO_IES,DS_COMPLEMENTO_ENDERECO_IES,NO_BAIRRO_IES,NU_CEP_IES,QT_TEC_TOTAL,QT_TEC_FUNDAMENTAL_INCOMP_FEM,QT_TEC_FUNDAMENTAL_INCOMP_MASC,QT_TEC_FUNDAMENTAL_COMP_FEM,QT_TEC_FUNDAMENTAL_COMP_MASC,QT_TEC_MEDIO_FEM,QT_TEC_MEDIO_MASC,QT_TEC_SUPERIOR_FEM,QT_TEC_SUPERIOR_MASC,QT_TEC_ESPECIALIZACAO_FEM,QT_TEC_ESPECIALIZACAO_MASC,QT_TEC_MESTRADO_FEM,QT_TEC_MESTRADO_MASC,QT_TEC_DOUTORADO_FEM,QT_TEC_DOUTORADO_MASC,IN_ACESSO_PORTAL_CAPES,IN_ACESSO_OUTRAS_BASES,IN_ASSINA_OUTRA_BASE,IN_REPOSITORIO_INSTITUCIONAL,IN_BUSCA_INTEGRADA,IN_SERVICO_INTERNET,IN_PARTICIPA_REDE_SOCIAL,IN_CATALOGO_ONLINE,QT_PERIODICO_ELETRONICO,QT_LIVRO_ELETRONICO,QT_DOC_TOTAL,QT_DOC_EXE,QT_DOC_EX_FEMI,QT_DOC_EX_MASC,QT_DOC_EX_SEM_GRAD,QT_DOC_EX_GRAD,QT_DOC_EX_ESP,QT_DOC_EX_MEST,QT_DOC_EX_DOUT,QT_DOC_EX_INT,QT_DOC_EX_INT_DE,QT_DOC_EX_INT_SEM_DE,QT_DOC_EX_PARC,QT_DOC_EX_HOR,QT_DOC_EX_0_29,QT_DOC_EX_30_34,QT_DOC_EX_35_39,QT_DOC_EX_40_44,QT_DOC_EX_45_49,QT_DOC_EX_50_54,QT_DOC_EX_55_59,QT_DOC_EX_60_MAIS,QT_DOC_EX_BRANCA,QT_DOC_EX_PRETA,QT_DOC_EX_PARDA,QT_DOC_EX_AMARELA,QT_DOC_EX_INDIGENA,QT_DOC_EX_COR_ND,QT_DOC_EX_BRA,QT_DOC_EX_EST,QT_DOC_EX_COM_DEFICIENCIA
INTO   stg.MICRODADOS_CADASTRO_IES_SP
		 FROM 	MICRODADOS_CADASTRO_IES_2010 WHERE SG_UF_IES = 'SP' UNION 
SELECT NU_ANO_CENSO,NO_REGIAO_IES,CO_REGIAO_IES,NO_UF_IES,SG_UF_IES,CO_UF_IES,NO_MUNICIPIO_IES,CO_MUNICIPIO_IES,IN_CAPITAL_IES,NO_MESORREGIAO_IES,CO_MESORREGIAO_IES,NO_MICRORREGIAO_IES,CO_MICRORREGIAO_IES,TP_ORGANIZACAO_ACADEMICA,TP_CATEGORIA_ADMINISTRATIVA,NO_MANTENEDORA,CO_MANTENEDORA,CO_IES,NO_IES,SG_IES,DS_ENDERECO_IES,DS_NUMERO_ENDERECO_IES,DS_COMPLEMENTO_ENDERECO_IES,NO_BAIRRO_IES,NU_CEP_IES,QT_TEC_TOTAL,QT_TEC_FUNDAMENTAL_INCOMP_FEM,QT_TEC_FUNDAMENTAL_INCOMP_MASC,QT_TEC_FUNDAMENTAL_COMP_FEM,QT_TEC_FUNDAMENTAL_COMP_MASC,QT_TEC_MEDIO_FEM,QT_TEC_MEDIO_MASC,QT_TEC_SUPERIOR_FEM,QT_TEC_SUPERIOR_MASC,QT_TEC_ESPECIALIZACAO_FEM,QT_TEC_ESPECIALIZACAO_MASC,QT_TEC_MESTRADO_FEM,QT_TEC_MESTRADO_MASC,QT_TEC_DOUTORADO_FEM,QT_TEC_DOUTORADO_MASC,IN_ACESSO_PORTAL_CAPES,IN_ACESSO_OUTRAS_BASES,IN_ASSINA_OUTRA_BASE,IN_REPOSITORIO_INSTITUCIONAL,IN_BUSCA_INTEGRADA,IN_SERVICO_INTERNET,IN_PARTICIPA_REDE_SOCIAL,IN_CATALOGO_ONLINE,QT_PERIODICO_ELETRONICO,QT_LIVRO_ELETRONICO,QT_DOC_TOTAL,QT_DOC_EXE,QT_DOC_EX_FEMI,QT_DOC_EX_MASC,QT_DOC_EX_SEM_GRAD,QT_DOC_EX_GRAD,QT_DOC_EX_ESP,QT_DOC_EX_MEST,QT_DOC_EX_DOUT,QT_DOC_EX_INT,QT_DOC_EX_INT_DE,QT_DOC_EX_INT_SEM_DE,QT_DOC_EX_PARC,QT_DOC_EX_HOR,QT_DOC_EX_0_29,QT_DOC_EX_30_34,QT_DOC_EX_35_39,QT_DOC_EX_40_44,QT_DOC_EX_45_49,QT_DOC_EX_50_54,QT_DOC_EX_55_59,QT_DOC_EX_60_MAIS,QT_DOC_EX_BRANCA,QT_DOC_EX_PRETA,QT_DOC_EX_PARDA,QT_DOC_EX_AMARELA,QT_DOC_EX_INDIGENA,QT_DOC_EX_COR_ND,QT_DOC_EX_BRA,QT_DOC_EX_EST,QT_DOC_EX_COM_DEFICIENCIA FROM	MICRODADOS_CADASTRO_IES_2011 WHERE SG_UF_IES = 'SP' UNION 
SELECT NU_ANO_CENSO,NO_REGIAO_IES,CO_REGIAO_IES,NO_UF_IES,SG_UF_IES,CO_UF_IES,NO_MUNICIPIO_IES,CO_MUNICIPIO_IES,IN_CAPITAL_IES,NO_MESORREGIAO_IES,CO_MESORREGIAO_IES,NO_MICRORREGIAO_IES,CO_MICRORREGIAO_IES,TP_ORGANIZACAO_ACADEMICA,TP_CATEGORIA_ADMINISTRATIVA,NO_MANTENEDORA,CO_MANTENEDORA,CO_IES,NO_IES,SG_IES,DS_ENDERECO_IES,DS_NUMERO_ENDERECO_IES,DS_COMPLEMENTO_ENDERECO_IES,NO_BAIRRO_IES,NU_CEP_IES,QT_TEC_TOTAL,QT_TEC_FUNDAMENTAL_INCOMP_FEM,QT_TEC_FUNDAMENTAL_INCOMP_MASC,QT_TEC_FUNDAMENTAL_COMP_FEM,QT_TEC_FUNDAMENTAL_COMP_MASC,QT_TEC_MEDIO_FEM,QT_TEC_MEDIO_MASC,QT_TEC_SUPERIOR_FEM,QT_TEC_SUPERIOR_MASC,QT_TEC_ESPECIALIZACAO_FEM,QT_TEC_ESPECIALIZACAO_MASC,QT_TEC_MESTRADO_FEM,QT_TEC_MESTRADO_MASC,QT_TEC_DOUTORADO_FEM,QT_TEC_DOUTORADO_MASC,IN_ACESSO_PORTAL_CAPES,IN_ACESSO_OUTRAS_BASES,IN_ASSINA_OUTRA_BASE,IN_REPOSITORIO_INSTITUCIONAL,IN_BUSCA_INTEGRADA,IN_SERVICO_INTERNET,IN_PARTICIPA_REDE_SOCIAL,IN_CATALOGO_ONLINE,QT_PERIODICO_ELETRONICO,QT_LIVRO_ELETRONICO,QT_DOC_TOTAL,QT_DOC_EXE,QT_DOC_EX_FEMI,QT_DOC_EX_MASC,QT_DOC_EX_SEM_GRAD,QT_DOC_EX_GRAD,QT_DOC_EX_ESP,QT_DOC_EX_MEST,QT_DOC_EX_DOUT,QT_DOC_EX_INT,QT_DOC_EX_INT_DE,QT_DOC_EX_INT_SEM_DE,QT_DOC_EX_PARC,QT_DOC_EX_HOR,QT_DOC_EX_0_29,QT_DOC_EX_30_34,QT_DOC_EX_35_39,QT_DOC_EX_40_44,QT_DOC_EX_45_49,QT_DOC_EX_50_54,QT_DOC_EX_55_59,QT_DOC_EX_60_MAIS,QT_DOC_EX_BRANCA,QT_DOC_EX_PRETA,QT_DOC_EX_PARDA,QT_DOC_EX_AMARELA,QT_DOC_EX_INDIGENA,QT_DOC_EX_COR_ND,QT_DOC_EX_BRA,QT_DOC_EX_EST,QT_DOC_EX_COM_DEFICIENCIA FROM	MICRODADOS_CADASTRO_IES_2012 WHERE SG_UF_IES = 'SP' UNION 
SELECT NU_ANO_CENSO,NO_REGIAO_IES,CO_REGIAO_IES,NO_UF_IES,SG_UF_IES,CO_UF_IES,NO_MUNICIPIO_IES,CO_MUNICIPIO_IES,IN_CAPITAL_IES,NO_MESORREGIAO_IES,CO_MESORREGIAO_IES,NO_MICRORREGIAO_IES,CO_MICRORREGIAO_IES,TP_ORGANIZACAO_ACADEMICA,TP_CATEGORIA_ADMINISTRATIVA,NO_MANTENEDORA,CO_MANTENEDORA,CO_IES,NO_IES,SG_IES,DS_ENDERECO_IES,DS_NUMERO_ENDERECO_IES,DS_COMPLEMENTO_ENDERECO_IES,NO_BAIRRO_IES,NU_CEP_IES,QT_TEC_TOTAL,QT_TEC_FUNDAMENTAL_INCOMP_FEM,QT_TEC_FUNDAMENTAL_INCOMP_MASC,QT_TEC_FUNDAMENTAL_COMP_FEM,QT_TEC_FUNDAMENTAL_COMP_MASC,QT_TEC_MEDIO_FEM,QT_TEC_MEDIO_MASC,QT_TEC_SUPERIOR_FEM,QT_TEC_SUPERIOR_MASC,QT_TEC_ESPECIALIZACAO_FEM,QT_TEC_ESPECIALIZACAO_MASC,QT_TEC_MESTRADO_FEM,QT_TEC_MESTRADO_MASC,QT_TEC_DOUTORADO_FEM,QT_TEC_DOUTORADO_MASC,IN_ACESSO_PORTAL_CAPES,IN_ACESSO_OUTRAS_BASES,IN_ASSINA_OUTRA_BASE,IN_REPOSITORIO_INSTITUCIONAL,IN_BUSCA_INTEGRADA,IN_SERVICO_INTERNET,IN_PARTICIPA_REDE_SOCIAL,IN_CATALOGO_ONLINE,QT_PERIODICO_ELETRONICO,QT_LIVRO_ELETRONICO,QT_DOC_TOTAL,QT_DOC_EXE,QT_DOC_EX_FEMI,QT_DOC_EX_MASC,QT_DOC_EX_SEM_GRAD,QT_DOC_EX_GRAD,QT_DOC_EX_ESP,QT_DOC_EX_MEST,QT_DOC_EX_DOUT,QT_DOC_EX_INT,QT_DOC_EX_INT_DE,QT_DOC_EX_INT_SEM_DE,QT_DOC_EX_PARC,QT_DOC_EX_HOR,QT_DOC_EX_0_29,QT_DOC_EX_30_34,QT_DOC_EX_35_39,QT_DOC_EX_40_44,QT_DOC_EX_45_49,QT_DOC_EX_50_54,QT_DOC_EX_55_59,QT_DOC_EX_60_MAIS,QT_DOC_EX_BRANCA,QT_DOC_EX_PRETA,QT_DOC_EX_PARDA,QT_DOC_EX_AMARELA,QT_DOC_EX_INDIGENA,QT_DOC_EX_COR_ND,QT_DOC_EX_BRA,QT_DOC_EX_EST,QT_DOC_EX_COM_DEFICIENCIA FROM	MICRODADOS_CADASTRO_IES_2013 WHERE SG_UF_IES = 'SP' UNION 
SELECT NU_ANO_CENSO,NO_REGIAO_IES,CO_REGIAO_IES,NO_UF_IES,SG_UF_IES,CO_UF_IES,NO_MUNICIPIO_IES,CO_MUNICIPIO_IES,IN_CAPITAL_IES,NO_MESORREGIAO_IES,CO_MESORREGIAO_IES,NO_MICRORREGIAO_IES,CO_MICRORREGIAO_IES,TP_ORGANIZACAO_ACADEMICA,TP_CATEGORIA_ADMINISTRATIVA,NO_MANTENEDORA,CO_MANTENEDORA,CO_IES,NO_IES,SG_IES,DS_ENDERECO_IES,DS_NUMERO_ENDERECO_IES,DS_COMPLEMENTO_ENDERECO_IES,NO_BAIRRO_IES,NU_CEP_IES,QT_TEC_TOTAL,QT_TEC_FUNDAMENTAL_INCOMP_FEM,QT_TEC_FUNDAMENTAL_INCOMP_MASC,QT_TEC_FUNDAMENTAL_COMP_FEM,QT_TEC_FUNDAMENTAL_COMP_MASC,QT_TEC_MEDIO_FEM,QT_TEC_MEDIO_MASC,QT_TEC_SUPERIOR_FEM,QT_TEC_SUPERIOR_MASC,QT_TEC_ESPECIALIZACAO_FEM,QT_TEC_ESPECIALIZACAO_MASC,QT_TEC_MESTRADO_FEM,QT_TEC_MESTRADO_MASC,QT_TEC_DOUTORADO_FEM,QT_TEC_DOUTORADO_MASC,IN_ACESSO_PORTAL_CAPES,IN_ACESSO_OUTRAS_BASES,IN_ASSINA_OUTRA_BASE,IN_REPOSITORIO_INSTITUCIONAL,IN_BUSCA_INTEGRADA,IN_SERVICO_INTERNET,IN_PARTICIPA_REDE_SOCIAL,IN_CATALOGO_ONLINE,QT_PERIODICO_ELETRONICO,QT_LIVRO_ELETRONICO,QT_DOC_TOTAL,QT_DOC_EXE,QT_DOC_EX_FEMI,QT_DOC_EX_MASC,QT_DOC_EX_SEM_GRAD,QT_DOC_EX_GRAD,QT_DOC_EX_ESP,QT_DOC_EX_MEST,QT_DOC_EX_DOUT,QT_DOC_EX_INT,QT_DOC_EX_INT_DE,QT_DOC_EX_INT_SEM_DE,QT_DOC_EX_PARC,QT_DOC_EX_HOR,QT_DOC_EX_0_29,QT_DOC_EX_30_34,QT_DOC_EX_35_39,QT_DOC_EX_40_44,QT_DOC_EX_45_49,QT_DOC_EX_50_54,QT_DOC_EX_55_59,QT_DOC_EX_60_MAIS,QT_DOC_EX_BRANCA,QT_DOC_EX_PRETA,QT_DOC_EX_PARDA,QT_DOC_EX_AMARELA,QT_DOC_EX_INDIGENA,QT_DOC_EX_COR_ND,QT_DOC_EX_BRA,QT_DOC_EX_EST,QT_DOC_EX_COM_DEFICIENCIA FROM	MICRODADOS_CADASTRO_IES_2014 WHERE SG_UF_IES = 'SP' UNION 
SELECT NU_ANO_CENSO,NO_REGIAO_IES,CO_REGIAO_IES,NO_UF_IES,SG_UF_IES,CO_UF_IES,NO_MUNICIPIO_IES,CO_MUNICIPIO_IES,IN_CAPITAL_IES,NO_MESORREGIAO_IES,CO_MESORREGIAO_IES,NO_MICRORREGIAO_IES,CO_MICRORREGIAO_IES,TP_ORGANIZACAO_ACADEMICA,TP_CATEGORIA_ADMINISTRATIVA,NO_MANTENEDORA,CO_MANTENEDORA,CO_IES,NO_IES,SG_IES,DS_ENDERECO_IES,DS_NUMERO_ENDERECO_IES,DS_COMPLEMENTO_ENDERECO_IES,NO_BAIRRO_IES,NU_CEP_IES,QT_TEC_TOTAL,QT_TEC_FUNDAMENTAL_INCOMP_FEM,QT_TEC_FUNDAMENTAL_INCOMP_MASC,QT_TEC_FUNDAMENTAL_COMP_FEM,QT_TEC_FUNDAMENTAL_COMP_MASC,QT_TEC_MEDIO_FEM,QT_TEC_MEDIO_MASC,QT_TEC_SUPERIOR_FEM,QT_TEC_SUPERIOR_MASC,QT_TEC_ESPECIALIZACAO_FEM,QT_TEC_ESPECIALIZACAO_MASC,QT_TEC_MESTRADO_FEM,QT_TEC_MESTRADO_MASC,QT_TEC_DOUTORADO_FEM,QT_TEC_DOUTORADO_MASC,IN_ACESSO_PORTAL_CAPES,IN_ACESSO_OUTRAS_BASES,IN_ASSINA_OUTRA_BASE,IN_REPOSITORIO_INSTITUCIONAL,IN_BUSCA_INTEGRADA,IN_SERVICO_INTERNET,IN_PARTICIPA_REDE_SOCIAL,IN_CATALOGO_ONLINE,QT_PERIODICO_ELETRONICO,QT_LIVRO_ELETRONICO,QT_DOC_TOTAL,QT_DOC_EXE,QT_DOC_EX_FEMI,QT_DOC_EX_MASC,QT_DOC_EX_SEM_GRAD,QT_DOC_EX_GRAD,QT_DOC_EX_ESP,QT_DOC_EX_MEST,QT_DOC_EX_DOUT,QT_DOC_EX_INT,QT_DOC_EX_INT_DE,QT_DOC_EX_INT_SEM_DE,QT_DOC_EX_PARC,QT_DOC_EX_HOR,QT_DOC_EX_0_29,QT_DOC_EX_30_34,QT_DOC_EX_35_39,QT_DOC_EX_40_44,QT_DOC_EX_45_49,QT_DOC_EX_50_54,QT_DOC_EX_55_59,QT_DOC_EX_60_MAIS,QT_DOC_EX_BRANCA,QT_DOC_EX_PRETA,QT_DOC_EX_PARDA,QT_DOC_EX_AMARELA,QT_DOC_EX_INDIGENA,QT_DOC_EX_COR_ND,QT_DOC_EX_BRA,QT_DOC_EX_EST,QT_DOC_EX_COM_DEFICIENCIA FROM	MICRODADOS_CADASTRO_IES_2015 WHERE SG_UF_IES = 'SP' UNION 
SELECT NU_ANO_CENSO,NO_REGIAO_IES,CO_REGIAO_IES,NO_UF_IES,SG_UF_IES,CO_UF_IES,NO_MUNICIPIO_IES,CO_MUNICIPIO_IES,IN_CAPITAL_IES,NO_MESORREGIAO_IES,CO_MESORREGIAO_IES,NO_MICRORREGIAO_IES,CO_MICRORREGIAO_IES,TP_ORGANIZACAO_ACADEMICA,TP_CATEGORIA_ADMINISTRATIVA,NO_MANTENEDORA,CO_MANTENEDORA,CO_IES,NO_IES,SG_IES,DS_ENDERECO_IES,DS_NUMERO_ENDERECO_IES,DS_COMPLEMENTO_ENDERECO_IES,NO_BAIRRO_IES,NU_CEP_IES,QT_TEC_TOTAL,QT_TEC_FUNDAMENTAL_INCOMP_FEM,QT_TEC_FUNDAMENTAL_INCOMP_MASC,QT_TEC_FUNDAMENTAL_COMP_FEM,QT_TEC_FUNDAMENTAL_COMP_MASC,QT_TEC_MEDIO_FEM,QT_TEC_MEDIO_MASC,QT_TEC_SUPERIOR_FEM,QT_TEC_SUPERIOR_MASC,QT_TEC_ESPECIALIZACAO_FEM,QT_TEC_ESPECIALIZACAO_MASC,QT_TEC_MESTRADO_FEM,QT_TEC_MESTRADO_MASC,QT_TEC_DOUTORADO_FEM,QT_TEC_DOUTORADO_MASC,IN_ACESSO_PORTAL_CAPES,IN_ACESSO_OUTRAS_BASES,IN_ASSINA_OUTRA_BASE,IN_REPOSITORIO_INSTITUCIONAL,IN_BUSCA_INTEGRADA,IN_SERVICO_INTERNET,IN_PARTICIPA_REDE_SOCIAL,IN_CATALOGO_ONLINE,QT_PERIODICO_ELETRONICO,QT_LIVRO_ELETRONICO,QT_DOC_TOTAL,QT_DOC_EXE,QT_DOC_EX_FEMI,QT_DOC_EX_MASC,QT_DOC_EX_SEM_GRAD,QT_DOC_EX_GRAD,QT_DOC_EX_ESP,QT_DOC_EX_MEST,QT_DOC_EX_DOUT,QT_DOC_EX_INT,QT_DOC_EX_INT_DE,QT_DOC_EX_INT_SEM_DE,QT_DOC_EX_PARC,QT_DOC_EX_HOR,QT_DOC_EX_0_29,QT_DOC_EX_30_34,QT_DOC_EX_35_39,QT_DOC_EX_40_44,QT_DOC_EX_45_49,QT_DOC_EX_50_54,QT_DOC_EX_55_59,QT_DOC_EX_60_MAIS,QT_DOC_EX_BRANCA,QT_DOC_EX_PRETA,QT_DOC_EX_PARDA,QT_DOC_EX_AMARELA,QT_DOC_EX_INDIGENA,QT_DOC_EX_COR_ND,QT_DOC_EX_BRA,QT_DOC_EX_EST,QT_DOC_EX_COM_DEFICIENCIA FROM	MICRODADOS_CADASTRO_IES_2016 WHERE SG_UF_IES = 'SP' UNION 
SELECT NU_ANO_CENSO,NO_REGIAO_IES,CO_REGIAO_IES,NO_UF_IES,SG_UF_IES,CO_UF_IES,NO_MUNICIPIO_IES,CO_MUNICIPIO_IES,IN_CAPITAL_IES,NO_MESORREGIAO_IES,CO_MESORREGIAO_IES,NO_MICRORREGIAO_IES,CO_MICRORREGIAO_IES,TP_ORGANIZACAO_ACADEMICA,TP_CATEGORIA_ADMINISTRATIVA,NO_MANTENEDORA,CO_MANTENEDORA,CO_IES,NO_IES,SG_IES,DS_ENDERECO_IES,DS_NUMERO_ENDERECO_IES,DS_COMPLEMENTO_ENDERECO_IES,NO_BAIRRO_IES,NU_CEP_IES,QT_TEC_TOTAL,QT_TEC_FUNDAMENTAL_INCOMP_FEM,QT_TEC_FUNDAMENTAL_INCOMP_MASC,QT_TEC_FUNDAMENTAL_COMP_FEM,QT_TEC_FUNDAMENTAL_COMP_MASC,QT_TEC_MEDIO_FEM,QT_TEC_MEDIO_MASC,QT_TEC_SUPERIOR_FEM,QT_TEC_SUPERIOR_MASC,QT_TEC_ESPECIALIZACAO_FEM,QT_TEC_ESPECIALIZACAO_MASC,QT_TEC_MESTRADO_FEM,QT_TEC_MESTRADO_MASC,QT_TEC_DOUTORADO_FEM,QT_TEC_DOUTORADO_MASC,IN_ACESSO_PORTAL_CAPES,IN_ACESSO_OUTRAS_BASES,IN_ASSINA_OUTRA_BASE,IN_REPOSITORIO_INSTITUCIONAL,IN_BUSCA_INTEGRADA,IN_SERVICO_INTERNET,IN_PARTICIPA_REDE_SOCIAL,IN_CATALOGO_ONLINE,QT_PERIODICO_ELETRONICO,QT_LIVRO_ELETRONICO,QT_DOC_TOTAL,QT_DOC_EXE,QT_DOC_EX_FEMI,QT_DOC_EX_MASC,QT_DOC_EX_SEM_GRAD,QT_DOC_EX_GRAD,QT_DOC_EX_ESP,QT_DOC_EX_MEST,QT_DOC_EX_DOUT,QT_DOC_EX_INT,QT_DOC_EX_INT_DE,QT_DOC_EX_INT_SEM_DE,QT_DOC_EX_PARC,QT_DOC_EX_HOR,QT_DOC_EX_0_29,QT_DOC_EX_30_34,QT_DOC_EX_35_39,QT_DOC_EX_40_44,QT_DOC_EX_45_49,QT_DOC_EX_50_54,QT_DOC_EX_55_59,QT_DOC_EX_60_MAIS,QT_DOC_EX_BRANCA,QT_DOC_EX_PRETA,QT_DOC_EX_PARDA,QT_DOC_EX_AMARELA,QT_DOC_EX_INDIGENA,QT_DOC_EX_COR_ND,QT_DOC_EX_BRA,QT_DOC_EX_EST,QT_DOC_EX_COM_DEFICIENCIA FROM	MICRODADOS_CADASTRO_IES_2017 WHERE SG_UF_IES = 'SP' UNION 
SELECT NU_ANO_CENSO,NO_REGIAO_IES,CO_REGIAO_IES,NO_UF_IES,SG_UF_IES,CO_UF_IES,NO_MUNICIPIO_IES,CO_MUNICIPIO_IES,IN_CAPITAL_IES,NO_MESORREGIAO_IES,CO_MESORREGIAO_IES,NO_MICRORREGIAO_IES,CO_MICRORREGIAO_IES,TP_ORGANIZACAO_ACADEMICA,TP_CATEGORIA_ADMINISTRATIVA,NO_MANTENEDORA,CO_MANTENEDORA,CO_IES,NO_IES,SG_IES,DS_ENDERECO_IES,DS_NUMERO_ENDERECO_IES,DS_COMPLEMENTO_ENDERECO_IES,NO_BAIRRO_IES,NU_CEP_IES,QT_TEC_TOTAL,QT_TEC_FUNDAMENTAL_INCOMP_FEM,QT_TEC_FUNDAMENTAL_INCOMP_MASC,QT_TEC_FUNDAMENTAL_COMP_FEM,QT_TEC_FUNDAMENTAL_COMP_MASC,QT_TEC_MEDIO_FEM,QT_TEC_MEDIO_MASC,QT_TEC_SUPERIOR_FEM,QT_TEC_SUPERIOR_MASC,QT_TEC_ESPECIALIZACAO_FEM,QT_TEC_ESPECIALIZACAO_MASC,QT_TEC_MESTRADO_FEM,QT_TEC_MESTRADO_MASC,QT_TEC_DOUTORADO_FEM,QT_TEC_DOUTORADO_MASC,IN_ACESSO_PORTAL_CAPES,IN_ACESSO_OUTRAS_BASES,IN_ASSINA_OUTRA_BASE,IN_REPOSITORIO_INSTITUCIONAL,IN_BUSCA_INTEGRADA,IN_SERVICO_INTERNET,IN_PARTICIPA_REDE_SOCIAL,IN_CATALOGO_ONLINE,QT_PERIODICO_ELETRONICO,QT_LIVRO_ELETRONICO,QT_DOC_TOTAL,QT_DOC_EXE,QT_DOC_EX_FEMI,QT_DOC_EX_MASC,QT_DOC_EX_SEM_GRAD,QT_DOC_EX_GRAD,QT_DOC_EX_ESP,QT_DOC_EX_MEST,QT_DOC_EX_DOUT,QT_DOC_EX_INT,QT_DOC_EX_INT_DE,QT_DOC_EX_INT_SEM_DE,QT_DOC_EX_PARC,QT_DOC_EX_HOR,QT_DOC_EX_0_29,QT_DOC_EX_30_34,QT_DOC_EX_35_39,QT_DOC_EX_40_44,QT_DOC_EX_45_49,QT_DOC_EX_50_54,QT_DOC_EX_55_59,QT_DOC_EX_60_MAIS,QT_DOC_EX_BRANCA,QT_DOC_EX_PRETA,QT_DOC_EX_PARDA,QT_DOC_EX_AMARELA,QT_DOC_EX_INDIGENA,QT_DOC_EX_COR_ND,QT_DOC_EX_BRA,QT_DOC_EX_EST,QT_DOC_EX_COM_DEFICIENCIA FROM	MICRODADOS_CADASTRO_IES_2018 WHERE SG_UF_IES = 'SP' UNION 
SELECT NU_ANO_CENSO,NO_REGIAO_IES,CO_REGIAO_IES,NO_UF_IES,SG_UF_IES,CO_UF_IES,NO_MUNICIPIO_IES,CO_MUNICIPIO_IES,IN_CAPITAL_IES,NO_MESORREGIAO_IES,CO_MESORREGIAO_IES,NO_MICRORREGIAO_IES,CO_MICRORREGIAO_IES,TP_ORGANIZACAO_ACADEMICA,TP_CATEGORIA_ADMINISTRATIVA,NO_MANTENEDORA,CO_MANTENEDORA,CO_IES,NO_IES,SG_IES,DS_ENDERECO_IES,DS_NUMERO_ENDERECO_IES,DS_COMPLEMENTO_ENDERECO_IES,NO_BAIRRO_IES,NU_CEP_IES,QT_TEC_TOTAL,QT_TEC_FUNDAMENTAL_INCOMP_FEM,QT_TEC_FUNDAMENTAL_INCOMP_MASC,QT_TEC_FUNDAMENTAL_COMP_FEM,QT_TEC_FUNDAMENTAL_COMP_MASC,QT_TEC_MEDIO_FEM,QT_TEC_MEDIO_MASC,QT_TEC_SUPERIOR_FEM,QT_TEC_SUPERIOR_MASC,QT_TEC_ESPECIALIZACAO_FEM,QT_TEC_ESPECIALIZACAO_MASC,QT_TEC_MESTRADO_FEM,QT_TEC_MESTRADO_MASC,QT_TEC_DOUTORADO_FEM,QT_TEC_DOUTORADO_MASC,IN_ACESSO_PORTAL_CAPES,IN_ACESSO_OUTRAS_BASES,IN_ASSINA_OUTRA_BASE,IN_REPOSITORIO_INSTITUCIONAL,IN_BUSCA_INTEGRADA,IN_SERVICO_INTERNET,IN_PARTICIPA_REDE_SOCIAL,IN_CATALOGO_ONLINE,QT_PERIODICO_ELETRONICO,QT_LIVRO_ELETRONICO,QT_DOC_TOTAL,QT_DOC_EXE,QT_DOC_EX_FEMI,QT_DOC_EX_MASC,QT_DOC_EX_SEM_GRAD,QT_DOC_EX_GRAD,QT_DOC_EX_ESP,QT_DOC_EX_MEST,QT_DOC_EX_DOUT,QT_DOC_EX_INT,QT_DOC_EX_INT_DE,QT_DOC_EX_INT_SEM_DE,QT_DOC_EX_PARC,QT_DOC_EX_HOR,QT_DOC_EX_0_29,QT_DOC_EX_30_34,QT_DOC_EX_35_39,QT_DOC_EX_40_44,QT_DOC_EX_45_49,QT_DOC_EX_50_54,QT_DOC_EX_55_59,QT_DOC_EX_60_MAIS,QT_DOC_EX_BRANCA,QT_DOC_EX_PRETA,QT_DOC_EX_PARDA,QT_DOC_EX_AMARELA,QT_DOC_EX_INDIGENA,QT_DOC_EX_COR_ND,QT_DOC_EX_BRA,QT_DOC_EX_EST,QT_DOC_EX_COM_DEFICIENCIA FROM	MICRODADOS_CADASTRO_IES_2019 WHERE SG_UF_IES = 'SP' UNION 
SELECT NU_ANO_CENSO,NO_REGIAO_IES,CO_REGIAO_IES,NO_UF_IES,SG_UF_IES,CO_UF_IES,NO_MUNICIPIO_IES,CO_MUNICIPIO_IES,IN_CAPITAL_IES,NO_MESORREGIAO_IES,CO_MESORREGIAO_IES,NO_MICRORREGIAO_IES,CO_MICRORREGIAO_IES,TP_ORGANIZACAO_ACADEMICA,TP_CATEGORIA_ADMINISTRATIVA,NO_MANTENEDORA,CO_MANTENEDORA,CO_IES,NO_IES,SG_IES,DS_ENDERECO_IES,DS_NUMERO_ENDERECO_IES,DS_COMPLEMENTO_ENDERECO_IES,NO_BAIRRO_IES,NU_CEP_IES,QT_TEC_TOTAL,QT_TEC_FUNDAMENTAL_INCOMP_FEM,QT_TEC_FUNDAMENTAL_INCOMP_MASC,QT_TEC_FUNDAMENTAL_COMP_FEM,QT_TEC_FUNDAMENTAL_COMP_MASC,QT_TEC_MEDIO_FEM,QT_TEC_MEDIO_MASC,QT_TEC_SUPERIOR_FEM,QT_TEC_SUPERIOR_MASC,QT_TEC_ESPECIALIZACAO_FEM,QT_TEC_ESPECIALIZACAO_MASC,QT_TEC_MESTRADO_FEM,QT_TEC_MESTRADO_MASC,QT_TEC_DOUTORADO_FEM,QT_TEC_DOUTORADO_MASC,IN_ACESSO_PORTAL_CAPES,IN_ACESSO_OUTRAS_BASES,IN_ASSINA_OUTRA_BASE,IN_REPOSITORIO_INSTITUCIONAL,IN_BUSCA_INTEGRADA,IN_SERVICO_INTERNET,IN_PARTICIPA_REDE_SOCIAL,IN_CATALOGO_ONLINE,QT_PERIODICO_ELETRONICO,QT_LIVRO_ELETRONICO,QT_DOC_TOTAL,QT_DOC_EXE,QT_DOC_EX_FEMI,QT_DOC_EX_MASC,QT_DOC_EX_SEM_GRAD,QT_DOC_EX_GRAD,QT_DOC_EX_ESP,QT_DOC_EX_MEST,QT_DOC_EX_DOUT,QT_DOC_EX_INT,QT_DOC_EX_INT_DE,QT_DOC_EX_INT_SEM_DE,QT_DOC_EX_PARC,QT_DOC_EX_HOR,QT_DOC_EX_0_29,QT_DOC_EX_30_34,QT_DOC_EX_35_39,QT_DOC_EX_40_44,QT_DOC_EX_45_49,QT_DOC_EX_50_54,QT_DOC_EX_55_59,QT_DOC_EX_60_MAIS,QT_DOC_EX_BRANCA,QT_DOC_EX_PRETA,QT_DOC_EX_PARDA,QT_DOC_EX_AMARELA,QT_DOC_EX_INDIGENA,QT_DOC_EX_COR_ND,QT_DOC_EX_BRA,QT_DOC_EX_EST,QT_DOC_EX_COM_DEFICIENCIA FROM	MICRODADOS_CADASTRO_IES_2020 WHERE SG_UF_IES = 'SP' UNION 
SELECT NU_ANO_CENSO,NO_REGIAO_IES,CO_REGIAO_IES,NO_UF_IES,SG_UF_IES,CO_UF_IES,NO_MUNICIPIO_IES,CO_MUNICIPIO_IES,IN_CAPITAL_IES,NO_MESORREGIAO_IES,CO_MESORREGIAO_IES,NO_MICRORREGIAO_IES,CO_MICRORREGIAO_IES,TP_ORGANIZACAO_ACADEMICA,TP_CATEGORIA_ADMINISTRATIVA,NO_MANTENEDORA,CO_MANTENEDORA,CO_IES,NO_IES,SG_IES,DS_ENDERECO_IES,DS_NUMERO_ENDERECO_IES,DS_COMPLEMENTO_ENDERECO_IES,NO_BAIRRO_IES,NU_CEP_IES,QT_TEC_TOTAL,QT_TEC_FUNDAMENTAL_INCOMP_FEM,QT_TEC_FUNDAMENTAL_INCOMP_MASC,QT_TEC_FUNDAMENTAL_COMP_FEM,QT_TEC_FUNDAMENTAL_COMP_MASC,QT_TEC_MEDIO_FEM,QT_TEC_MEDIO_MASC,QT_TEC_SUPERIOR_FEM,QT_TEC_SUPERIOR_MASC,QT_TEC_ESPECIALIZACAO_FEM,QT_TEC_ESPECIALIZACAO_MASC,QT_TEC_MESTRADO_FEM,QT_TEC_MESTRADO_MASC,QT_TEC_DOUTORADO_FEM,QT_TEC_DOUTORADO_MASC,IN_ACESSO_PORTAL_CAPES,IN_ACESSO_OUTRAS_BASES,IN_ASSINA_OUTRA_BASE,IN_REPOSITORIO_INSTITUCIONAL,IN_BUSCA_INTEGRADA,IN_SERVICO_INTERNET,IN_PARTICIPA_REDE_SOCIAL,IN_CATALOGO_ONLINE,QT_PERIODICO_ELETRONICO,QT_LIVRO_ELETRONICO,QT_DOC_TOTAL,QT_DOC_EXE,QT_DOC_EX_FEMI,QT_DOC_EX_MASC,QT_DOC_EX_SEM_GRAD,QT_DOC_EX_GRAD,QT_DOC_EX_ESP,QT_DOC_EX_MEST,QT_DOC_EX_DOUT,QT_DOC_EX_INT,QT_DOC_EX_INT_DE,QT_DOC_EX_INT_SEM_DE,QT_DOC_EX_PARC,QT_DOC_EX_HOR,QT_DOC_EX_0_29,QT_DOC_EX_30_34,QT_DOC_EX_35_39,QT_DOC_EX_40_44,QT_DOC_EX_45_49,QT_DOC_EX_50_54,QT_DOC_EX_55_59,QT_DOC_EX_60_MAIS,QT_DOC_EX_BRANCA,QT_DOC_EX_PRETA,QT_DOC_EX_PARDA,QT_DOC_EX_AMARELA,QT_DOC_EX_INDIGENA,QT_DOC_EX_COR_ND,QT_DOC_EX_BRA,QT_DOC_EX_EST,QT_DOC_EX_COM_DEFICIENCIA FROM	MICRODADOS_CADASTRO_IES_2021 WHERE SG_UF_IES = 'SP' 

CREATE CLUSTERED INDEX IXC_STG_MICRODADOS_CADASTRO_IES_SP ON STG.STG_MICRODADOS_CADASTRO_IES_SP(NU_ANO_CENSO, CO_IES)


SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME LIKE 'indicadores_trajetoria_educacao_superior%'

DROP TABLE IF EXISTS STG.STG_INDICADORES_TRAJETORIA_EDUCACAO_SUPERIOR_SP
select T.*,	1  CO_CATALOGO
		into STG.STG_INDICADORES_TRAJETORIA_EDUCACAO_SUPERIOR_SP
			from indicadores_trajetoria_educacao_superior_2011_2020 t inner join stg.STG_MICRODADOS_CADASTRO_IES_SP ies on ies.co_ies = t.[Código_da_Instituição] union
select T.*, 2 from indicadores_trajetoria_educacao_superior_2012_2021 t inner join stg.STG_MICRODADOS_CADASTRO_IES_SP ies on ies.co_ies = t.[Código_da_Instituição] union
select T.*, 3 from indicadores_trajetoria_educacao_superior_2013_2021 t inner join stg.STG_MICRODADOS_CADASTRO_IES_SP ies on ies.co_ies = t.[Código_da_Instituição] union
select T.*, 4 from indicadores_trajetoria_educacao_superior_2014_2021 t inner join stg.STG_MICRODADOS_CADASTRO_IES_SP ies on ies.co_ies = t.[Código_da_Instituição] union
select T.*, 5 from indicadores_trajetoria_educacao_superior_2015_2021 t inner join stg.STG_MICRODADOS_CADASTRO_IES_SP ies on ies.co_ies = t.[Código_da_Instituição] union
select T.*, 6 from indicadores_trajetoria_educacao_superior_2016_2021 t inner join stg.STG_MICRODADOS_CADASTRO_IES_SP ies on ies.co_ies = t.[Código_da_Instituição] union
select T.*, 7 from indicadores_trajetoria_educacao_superior_2017_2021 t inner join stg.STG_MICRODADOS_CADASTRO_IES_SP ies on ies.co_ies = t.[Código_da_Instituição]

CREATE CLUSTERED INDEX IXC_STG_INDICADORES_TRAJETORIA_EDUCACAO_SUPERIOR_SP ON [stg].[STG_INDICADORES_TRAJETORIA_EDUCACAO_SUPERIOR_SP](Código_da_Instituição, Código_do_Curso_de_Graduação, Código_do_Município_do_Curso)
select * from [stg].[STG_MICRODADOS_CADASTRO_IES_SP]
select * from [stg].[STG_MICRODADOS_CADASTRO_CURSOS_SP]
select * from [stg].[STG_INDICADORES_TRAJETORIA_EDUCACAO_SUPERIOR_SP]


----------------------------------------------------------------------------------------

-- LOGICA DE CRIAÇÃO DAS TABELAS 
-- 1 - DROPAR TABELA SE EXISTIR 
-- 2 - CRIAR TABELA A PARTIR DE SELECT DISTINCT (SELECT INTO)
-- 3 - ALTERAR COLUNA DE CODIGO PARA NOT NULL 
-- 4 - CRIAR CHAVE PRIMARIA NA TABELA 


--- HIERARQUIA DE REGIÃO - REGIÃO -> UF -> MESORREGIAO -> _MICRORREGIAO -> MUNICIPIO
--- OBS.: TABELAS CRIADAS INICIALMENTE SEM PK E FK

-- TABELAS COM DADOS DE TODAS OS ESTADOS 
DROP TABLE IF EXISTS ODS.ODS_REGIAO_IES
SELECT DISTINCT CO_REGIAO_IES, NO_REGIAO_IES INTO ODS.ODS_REGIAO_IES
FROM 	MICRODADOS_CADASTRO_IES_2010   UNION 
SELECT CO_REGIAO_IES, NO_REGIAO_IES FROM	MICRODADOS_CADASTRO_IES_2011 UNION 
SELECT CO_REGIAO_IES, NO_REGIAO_IES FROM	MICRODADOS_CADASTRO_IES_2012 UNION 
SELECT CO_REGIAO_IES, NO_REGIAO_IES FROM	MICRODADOS_CADASTRO_IES_2013 UNION 
SELECT CO_REGIAO_IES, NO_REGIAO_IES FROM	MICRODADOS_CADASTRO_IES_2014 UNION 
SELECT CO_REGIAO_IES, NO_REGIAO_IES FROM	MICRODADOS_CADASTRO_IES_2015 UNION 
SELECT CO_REGIAO_IES, NO_REGIAO_IES FROM	MICRODADOS_CADASTRO_IES_2016 UNION 
SELECT CO_REGIAO_IES, NO_REGIAO_IES FROM	MICRODADOS_CADASTRO_IES_2017 UNION 
SELECT CO_REGIAO_IES, NO_REGIAO_IES FROM	MICRODADOS_CADASTRO_IES_2018 UNION 
SELECT CO_REGIAO_IES, NO_REGIAO_IES FROM	MICRODADOS_CADASTRO_IES_2019 UNION 
SELECT CO_REGIAO_IES, NO_REGIAO_IES FROM	MICRODADOS_CADASTRO_IES_2020 UNION 
SELECT CO_REGIAO_IES, NO_REGIAO_IES FROM	MICRODADOS_CADASTRO_IES_2021 

CREATE CLUSTERED INDEX IXC_ODS_REGIAO_IES ON ODS.ODS_REGIAO_IES (CO_REGIAO_IES)


DROP TABLE IF EXISTS ODS.ODS_UF_IES
SELECT DISTINCT CO_UF_IES, NO_UF_IES,SG_UF_IES
INTO ODS.ODS_UF_IES
FROM 	MICRODADOS_CADASTRO_IES_2010   UNION 
SELECT CO_UF_IES, NO_UF_IES,SG_UF_IES FROM	MICRODADOS_CADASTRO_IES_2011 UNION 
SELECT CO_UF_IES, NO_UF_IES,SG_UF_IES FROM	MICRODADOS_CADASTRO_IES_2012 UNION 
SELECT CO_UF_IES, NO_UF_IES,SG_UF_IES FROM	MICRODADOS_CADASTRO_IES_2013 UNION 
SELECT CO_UF_IES, NO_UF_IES,SG_UF_IES FROM	MICRODADOS_CADASTRO_IES_2014 UNION 
SELECT CO_UF_IES, NO_UF_IES,SG_UF_IES FROM	MICRODADOS_CADASTRO_IES_2015 UNION 
SELECT CO_UF_IES, NO_UF_IES,SG_UF_IES FROM	MICRODADOS_CADASTRO_IES_2016 UNION 
SELECT CO_UF_IES, NO_UF_IES,SG_UF_IES FROM	MICRODADOS_CADASTRO_IES_2017 UNION 
SELECT CO_UF_IES, NO_UF_IES,SG_UF_IES FROM	MICRODADOS_CADASTRO_IES_2018 UNION 
SELECT CO_UF_IES, NO_UF_IES,SG_UF_IES FROM	MICRODADOS_CADASTRO_IES_2019 UNION 
SELECT CO_UF_IES, NO_UF_IES,SG_UF_IES FROM	MICRODADOS_CADASTRO_IES_2020 UNION 
SELECT CO_UF_IES, NO_UF_IES,SG_UF_IES FROM	MICRODADOS_CADASTRO_IES_2021 


ALTER TABLE ODS.ODS_UF_IES ALTER COLUMN CO_UF_IES SMALLINT NOT NULL
ALTER TABLE ODS.ODS_UF_IES ADD CONSTRAINT PK_ODS_UF_IES  PRIMARY KEY (CO_UF_IES)
ALTER TABLE ODS.ODS_UF_IES ALTER COLUMN NO_UF_IES VARCHAR(30) 
ALTER TABLE ODS.ODS_UF_IES ALTER COLUMN SG_UF_IES CHAR(2) 

-----------------------------------------------------------------------------------------------

-- -- TABELAS COM DADOS DE REGIÃO SOMENTE DO ESTADO DE SP
/*
DROP TABLE IF EXISTS  ODS.ODS_MESORREGIAO_IES
SELECT DISTINCT CO_MESORREGIAO_IES, NO_MESORREGIAO_IES
INTO ODS.ODS_MESORREGIAO_IES
	FROM STG.[STG_MICRODADOS_CADASTRO_IES_SP]
ALTER TABLE ODS.ODS_MESORREGIAO_IES ALTER COLUMN CO_MESORREGIAO_IES INT NOT NULL
ALTER TABLE ODS.ODS_MESORREGIAO_IES ADD CONSTRAINT PK_ODS_MESORREGIAO_IES  PRIMARY KEY (CO_MESORREGIAO_IES)


DROP TABLE IF EXISTS ODS.ODS_MICRORREGIAO_IES
SELECT DISTINCT CO_MICRORREGIAO_IES, NO_MICRORREGIAO_IES, CO_MESORREGIAO_IES, CO_UF_IES
 INTO ODS.ODS_MICRORREGIAO_IES
	FROM STG.[STG_MICRODADOS_CADASTRO_IES_SP]
ALTER TABLE ODS.ODS_MICRORREGIAO_IES ALTER COLUMN CO_MICRORREGIAO_IES INT NOT NULL
ALTER TABLE ODS.ODS_MICRORREGIAO_IES ADD CONSTRAINT PK_ODS_MICRORREGIAO_IES  PRIMARY KEY (CO_MICRORREGIAO_IES)

DROP TABLE IF EXISTS  ODS.ODS_MUNICIPIO_IES
SELECT DISTINCT CO_MUNICIPIO_IES, NO_MUNICIPIO_IES,CO_MESORREGIAO_IES
INTO ODS.ODS_MUNICIPIO_IES
	FROM STG.[STG_MICRODADOS_CADASTRO_IES_SP]
ALTER TABLE ODS.ODS_MUNICIPIO_IES ALTER COLUMN CO_MUNICIPIO_IES INT NOT NULL
ALTER TABLE ODS.ODS_MUNICIPIO_IES ADD CONSTRAINT PK_ODS_MUNICIPIO_IES  PRIMARY KEY (CO_MUNICIPIO_IES)



DROP TABLE IF EXISTS  ODS.ODS_MUNICIPIO
SELECT DISTINCT 
	Código_Município_Completo	CO_MUNICIPIO,
	Nome_Município NO_MUNICIPIO,
	Mesorregião_Geográfica CO_MESORREGIAO_IES
INTO ODS.ODS_MUNICIPIO
	FROM [RELATORIO_DTB_BRASIL_DISTRITO]
	where uf = 35 /*São Paulo*/



select * from ODS.ODS_MESORREGIAO_IES
SELECT distinct 
      [Mesorregião_Geográfica]
      ,[Nome_Mesorregião]     
  FROM [tcc_evasao].[dbo].[RELATORIO_DTB_BRASIL_DISTRITO]
  where uf = 35

  select co_microrregiao_ies, no_microrregiao_ies from ODS.ODS_MICRORREGIAO_IES
  except 
SELECT distinct 
      [Microrregião_Geográfica]
      ,[Nome_Microrregião]
	  ,[Mesorregião_Geográfica]
  FROM [tcc_evasao].[dbo].[RELATORIO_DTB_BRASIL_DISTRITO]
  where uf = 35


 SELECT distinct 
      [Microrregião_Geográfica]
      ,[Nome_Microrregião]
  FROM [tcc_evasao].[dbo].[RELATORIO_DTB_BRASIL_DISTRITO]
  where uf = 35
  except 
  select co_microrregiao_ies, no_microrregiao_ies from ODS.ODS_MICRORREGIAO_IES
*/

 DROP TABLE IF EXISTS  ODS.ODS_MESORREGIAO
  SELECT distinct
       [Mesorregião_Geográfica]		CO_MESORREGIAO
      ,[Nome_Mesorregião]			NO_MESORREGIAO
		, [UF]						CO_UF
		 INTO ODS.ODS_MESORREGIAO

  FROM [tcc_evasao].[dbo].[RELATORIO_DTB_BRASIL_DISTRITO]
  where uf = 35
  /* -- SEM DUPLICIDADE
  SELECT COUNT(1), CO_MESORREGIAO
  FROM ODS.ODS_MESORREGIAO
  GROUP BY CO_MESORREGIAO
  HAVING COUNT(1) > 1
  */


  /*
	 https://www.ibge.gov.br/geociencias/organizacao-do-territorio/divisao-regional/23701-divisao-territorial-brasileira.html?=&t=downloads
  */
DROP TABLE IF EXISTS ODS.ODS_MICRORREGIAO
SELECT DISTINCT 
       [Microrregião_Geográfica]	CO_MICRORREGIAO
      ,[Nome_Microrregião]			NO_MICRORREGIAO
	  ,[Mesorregião_Geográfica]		CO_MESORREGIAO
      INTO ODS.ODS_MICRORREGIAO

  FROM [tcc_evasao].[dbo].[RELATORIO_DTB_BRASIL_DISTRITO]
  where uf = 35
  
  /* -- SEM DUPLICIDADE
  SELECT COUNT(1), CO_MICRORREGIAO
  FROM ODS.ODS_MICRORREGIAO
  GROUP BY CO_MICRORREGIAO
  HAVING COUNT(1) > 1
  */


  DROP TABLE IF EXISTS  ODS.ODS_MUNICIPIO
  SELECT DISTINCT 
		 [Código_Município_Completo]	CO_MUNICIPIO
		,[Nome_Município]				NO_MUNICIPIO_IES
		,[Microrregião_Geográfica]		CO_MICRORREGIAO
		INTO ODS.ODS_MUNICIPIO
  FROM [tcc_evasao].[dbo].[RELATORIO_DTB_BRASIL_DISTRITO]
  where uf = 35

    /* -- SEM DUPLICIDADE
  SELECT COUNT(1), CO_MUNICIPIO
  FROM ODS.ODS_MUNICIPIO
  GROUP BY CO_MUNICIPIO
  HAVING COUNT(1) > 1
  */
------------------------------------------------------------------------------------------
-- INSTITUIÇÃO MANTENEDORA DA IES

-- TABELA AUXILIAR PARA PEGAR TODAS AS VERSÕES DE NOMENCLATURA DA MANTENEDORA AO LONGO DOS ANOS
DROP TABLE IF EXISTS #ODS_MANTENEDORA_IES
SELECT DISTINCT CO_MANTENEDORA,NO_MANTENEDORA, NU_ANO_CENSO 
INTO #ODS_MANTENEDORA_IES
	FROM STG.[STG_MICRODADOS_CADASTRO_IES_SP]

-- SALVA NA TABELA NOME DA MANTENEDORA DO ULTIMO CENSO EM QUE APARECEU
DROP TABLE IF EXISTS ODS.ODS_MANTENEDORA_IES
SELECT	IES.CO_MANTENEDORA, 
		IES.NO_MANTENEDORA, 
		IES.NU_ANO_CENSO
INTO ODS.ODS_MANTENEDORA_IES
	FROM #ODS_MANTENEDORA_IES IES
	INNER JOIN (
		select CO_MANTENEDORA, MAX(NU_ANO_CENSO)NU_ANO_CENSO FROM  
			#ODS_MANTENEDORA_IES
			GROUP BY CO_MANTENEDORA
		) MX ON IES.CO_MANTENEDORA = MX.CO_MANTENEDORA AND 
				IES.NU_ANO_CENSO = MX.NU_ANO_CENSO
    /* -- SEM DUPLICIDADE
  SELECT COUNT(1), CO_MANTENEDORA
  FROM ODS.ODS_MANTENEDORA_IES
  GROUP BY CO_MANTENEDORA
  HAVING COUNT(1) > 1
  */

DROP TABLE IF EXISTS #ODS_IES
SELECT DISTINCT
 CO_IES
, NO_IES
, SG_IES
, NU_ANO_CENSO
, CO_MUNICIPIO_IES
, IN_CAPITAL_IES
, TP_ORGANIZACAO_ACADEMICA
, TP_CATEGORIA_ADMINISTRATIVA
, CO_MANTENEDORA
, DS_ENDERECO_IES
, DS_NUMERO_ENDERECO_IES
, DS_COMPLEMENTO_ENDERECO_IES
, NO_BAIRRO_IES
, NU_CEP_IES
INTO #ODS_IES
	FROM STG.[STG_MICRODADOS_CADASTRO_IES_SP]


/*  --112 IES em cursos que não existem 
SELECT 
	co_ies
 FROM [stg].[STG_MICRODADOS_CADASTRO_CURSOS_SP]
except 
SELECT 
 CO_IES
 	FROM STG.[STG_MICRODADOS_CADASTRO_IES_SP]
*/

CREATE CLUSTERED INDEX IXC_TMP_ODS_IES ON #ODS_IES (CO_IES, NU_ANO_CENSO)

DROP TABLE IF EXISTS ODS.ODS_IES
SELECT 
	IES.CO_IES
,	IES.NO_IES
,	IES.SG_IES
,	IES.NU_ANO_CENSO
,	IES.CO_MUNICIPIO_IES
,	IES.IN_CAPITAL_IES
,	IES.TP_ORGANIZACAO_ACADEMICA
,	IES.TP_CATEGORIA_ADMINISTRATIVA
,	IES.CO_MANTENEDORA
,	IES.DS_ENDERECO_IES
,	IES.DS_NUMERO_ENDERECO_IES
,	IES.DS_COMPLEMENTO_ENDERECO_IES
,	IES.NO_BAIRRO_IES
,	IES.NU_CEP_IES
INTO ODS.ODS_IES
FROM STG.[STG_MICRODADOS_CADASTRO_IES_SP]	IES
	INNER JOIN 
	(SELECT CO_IES, MAX(NU_ANO_CENSO) NU_ANO_CENSO
		FROM #ODS_IES
		GROUP BY CO_IES
		) MX
	ON IES.CO_IES = MX.CO_IES AND 
		IES.NU_ANO_CENSO = MX.NU_ANO_CENSO

/* -- SEM DUPLICIDADE
  SELECT COUNT(1), CO_IES
  FROM ODS.ODS_IES
  GROUP BY CO_IES
  HAVING COUNT(1) > 1
*/
 
ALTER TABLE ODS.ODS_IES ADD NO_CATEGORIA_ADMINISTRATIVA AS  
	CASE 
		WHEN TP_CATEGORIA_ADMINISTRATIVA = 1 THEN 'Pública Federal'
		WHEN TP_CATEGORIA_ADMINISTRATIVA = 2 THEN 'Pública Estadual'
		WHEN TP_CATEGORIA_ADMINISTRATIVA = 3 THEN 'Pública Municipal'
		WHEN TP_CATEGORIA_ADMINISTRATIVA = 4 THEN 'Privada com fins lucrativos'
		WHEN TP_CATEGORIA_ADMINISTRATIVA = 5 THEN 'Privada sem fins lucrativos'
		WHEN TP_CATEGORIA_ADMINISTRATIVA = 7 THEN 'Especial'
		WHEN TP_CATEGORIA_ADMINISTRATIVA = 8 THEN 'Privada comunitária'
		WHEN TP_CATEGORIA_ADMINISTRATIVA = 9 THEN 'Privada confessional'
	END 

alter table ODS.ODS_IES  add NO_ORGANIZACAO_ACADEMICA AS 
	CASE 
		WHEN TP_ORGANIZACAO_ACADEMICA = 1 THEN 'Universidade'
		WHEN TP_ORGANIZACAO_ACADEMICA = 2 THEN 'Centro Universitário'
		WHEN TP_ORGANIZACAO_ACADEMICA = 3 THEN 'Faculdade'
		WHEN TP_ORGANIZACAO_ACADEMICA = 4 THEN 'Instituto Federal de Educação, Ciência e Tecnologia'
		WHEN TP_ORGANIZACAO_ACADEMICA = 5 THEN 'Centro Federal de Educação Tecnológica'
	END 

----------------------------------------------------------------------------------------------
--- ODS_CINE 

DROP TABLE IF EXISTS ODS.ODS_CINE_ROTULO
SELECT REPLACE(CO_CINE_ROTULO, '"','') CO_CINE_ROTULO, NO_CINE_ROTULO, CO_CINE_AREA_DETALHADA INTO ODS.ODS_CINE_ROTULO FROM [MICRODADOS_CADASTRO_CURSOS_2010]  UNION
SELECT REPLACE(CO_CINE_ROTULO, '"','') CO_CINE_ROTULO, NO_CINE_ROTULO, CO_CINE_AREA_DETALHADA FROM [MICRODADOS_CADASTRO_CURSOS_2011]  UNION
SELECT REPLACE(CO_CINE_ROTULO, '"','') CO_CINE_ROTULO, NO_CINE_ROTULO, CO_CINE_AREA_DETALHADA FROM [MICRODADOS_CADASTRO_CURSOS_2012]  UNION
SELECT REPLACE(CO_CINE_ROTULO, '"','') CO_CINE_ROTULO, NO_CINE_ROTULO, CO_CINE_AREA_DETALHADA FROM [MICRODADOS_CADASTRO_CURSOS_2013]  UNION
SELECT REPLACE(CO_CINE_ROTULO, '"','') CO_CINE_ROTULO, NO_CINE_ROTULO, CO_CINE_AREA_DETALHADA FROM [MICRODADOS_CADASTRO_CURSOS_2014]  UNION
SELECT REPLACE(CO_CINE_ROTULO, '"','') CO_CINE_ROTULO, NO_CINE_ROTULO, CO_CINE_AREA_DETALHADA FROM [MICRODADOS_CADASTRO_CURSOS_2015]  UNION
SELECT REPLACE(CO_CINE_ROTULO, '"','') CO_CINE_ROTULO, NO_CINE_ROTULO, CO_CINE_AREA_DETALHADA FROM [MICRODADOS_CADASTRO_CURSOS_2016]  UNION
SELECT REPLACE(CO_CINE_ROTULO, '"','') CO_CINE_ROTULO, NO_CINE_ROTULO, CO_CINE_AREA_DETALHADA FROM [MICRODADOS_CADASTRO_CURSOS_2017]  UNION
SELECT REPLACE(CO_CINE_ROTULO, '"','') CO_CINE_ROTULO, NO_CINE_ROTULO, CO_CINE_AREA_DETALHADA FROM [MICRODADOS_CADASTRO_CURSOS_2018]  UNION
SELECT REPLACE(CO_CINE_ROTULO, '"','') CO_CINE_ROTULO, NO_CINE_ROTULO, CO_CINE_AREA_DETALHADA FROM [MICRODADOS_CADASTRO_CURSOS_2019]  UNION
SELECT REPLACE(CO_CINE_ROTULO, '"','') CO_CINE_ROTULO, NO_CINE_ROTULO, CO_CINE_AREA_DETALHADA FROM [MICRODADOS_CADASTRO_CURSOS_2020]  UNION
SELECT REPLACE(CO_CINE_ROTULO, '"','') CO_CINE_ROTULO, NO_CINE_ROTULO, CO_CINE_AREA_DETALHADA FROM [MICRODADOS_CADASTRO_CURSOS_2021] 


/* SEM DUPLICIDADE
SELECT COUNT(1), CO_CINE_ROTULO
FROM ODS.ODS_CINE_ROTULO
GROUP BY CO_CINE_ROTULO
HAVING COUNT(1) > 1
*/


DROP TABLE IF EXISTS ODS.ODS_CINE_AREA_DETALHADA

SELECT CO_CINE_AREA_DETALHADA, NO_CINE_AREA_DETALHADA, CO_CINE_AREA_ESPECIFICA INTO ODS.ODS_CINE_AREA_DETALHADA FROM [MICRODADOS_CADASTRO_CURSOS_2010]  UNION
SELECT CO_CINE_AREA_DETALHADA, NO_CINE_AREA_DETALHADA, CO_CINE_AREA_ESPECIFICA FROM [MICRODADOS_CADASTRO_CURSOS_2011]  UNION
SELECT CO_CINE_AREA_DETALHADA, NO_CINE_AREA_DETALHADA, CO_CINE_AREA_ESPECIFICA FROM [MICRODADOS_CADASTRO_CURSOS_2012]  UNION
SELECT CO_CINE_AREA_DETALHADA, NO_CINE_AREA_DETALHADA, CO_CINE_AREA_ESPECIFICA FROM [MICRODADOS_CADASTRO_CURSOS_2013]  UNION
SELECT CO_CINE_AREA_DETALHADA, NO_CINE_AREA_DETALHADA, CO_CINE_AREA_ESPECIFICA FROM [MICRODADOS_CADASTRO_CURSOS_2014]  UNION
SELECT CO_CINE_AREA_DETALHADA, NO_CINE_AREA_DETALHADA, CO_CINE_AREA_ESPECIFICA FROM [MICRODADOS_CADASTRO_CURSOS_2015]  UNION
SELECT CO_CINE_AREA_DETALHADA, NO_CINE_AREA_DETALHADA, CO_CINE_AREA_ESPECIFICA FROM [MICRODADOS_CADASTRO_CURSOS_2016]  UNION
SELECT CO_CINE_AREA_DETALHADA, NO_CINE_AREA_DETALHADA, CO_CINE_AREA_ESPECIFICA FROM [MICRODADOS_CADASTRO_CURSOS_2017]  UNION
SELECT CO_CINE_AREA_DETALHADA, NO_CINE_AREA_DETALHADA, CO_CINE_AREA_ESPECIFICA FROM [MICRODADOS_CADASTRO_CURSOS_2018]  UNION
SELECT CO_CINE_AREA_DETALHADA, NO_CINE_AREA_DETALHADA, CO_CINE_AREA_ESPECIFICA FROM [MICRODADOS_CADASTRO_CURSOS_2019]  UNION
SELECT CO_CINE_AREA_DETALHADA, NO_CINE_AREA_DETALHADA, CO_CINE_AREA_ESPECIFICA FROM [MICRODADOS_CADASTRO_CURSOS_2020]  UNION
SELECT CO_CINE_AREA_DETALHADA, NO_CINE_AREA_DETALHADA, CO_CINE_AREA_ESPECIFICA FROM [MICRODADOS_CADASTRO_CURSOS_2021] 

/* -- SEM DUPLICIDADE
SELECT COUNT(1), CO_CINE_AREA_DETALHADA FROM ODS.ODS_CINE_AREA_DETALHADA
GROUP BY CO_CINE_AREA_DETALHADA
HAVING COUNT(1)> 1
*/

DROP TABLE IF EXISTS ODS.ODS_CINE_AREA_ESPECIFICA
SELECT CO_CINE_AREA_ESPECIFICA, NO_CINE_AREA_ESPECIFICA, CO_CINE_AREA_GERAL INTO ODS.ODS_CINE_AREA_ESPECIFICA FROM [MICRODADOS_CADASTRO_CURSOS_2010]  UNION
SELECT CO_CINE_AREA_ESPECIFICA, NO_CINE_AREA_ESPECIFICA, CO_CINE_AREA_GERAL FROM [MICRODADOS_CADASTRO_CURSOS_2011]  UNION
SELECT CO_CINE_AREA_ESPECIFICA, NO_CINE_AREA_ESPECIFICA, CO_CINE_AREA_GERAL FROM [MICRODADOS_CADASTRO_CURSOS_2012]  UNION
SELECT CO_CINE_AREA_ESPECIFICA, NO_CINE_AREA_ESPECIFICA, CO_CINE_AREA_GERAL FROM [MICRODADOS_CADASTRO_CURSOS_2013]  UNION
SELECT CO_CINE_AREA_ESPECIFICA, NO_CINE_AREA_ESPECIFICA, CO_CINE_AREA_GERAL FROM [MICRODADOS_CADASTRO_CURSOS_2014]  UNION
SELECT CO_CINE_AREA_ESPECIFICA, NO_CINE_AREA_ESPECIFICA, CO_CINE_AREA_GERAL FROM [MICRODADOS_CADASTRO_CURSOS_2015]  UNION
SELECT CO_CINE_AREA_ESPECIFICA, NO_CINE_AREA_ESPECIFICA, CO_CINE_AREA_GERAL FROM [MICRODADOS_CADASTRO_CURSOS_2016]  UNION
SELECT CO_CINE_AREA_ESPECIFICA, NO_CINE_AREA_ESPECIFICA, CO_CINE_AREA_GERAL FROM [MICRODADOS_CADASTRO_CURSOS_2017]  UNION
SELECT CO_CINE_AREA_ESPECIFICA, NO_CINE_AREA_ESPECIFICA, CO_CINE_AREA_GERAL FROM [MICRODADOS_CADASTRO_CURSOS_2018]  UNION
SELECT CO_CINE_AREA_ESPECIFICA, NO_CINE_AREA_ESPECIFICA, CO_CINE_AREA_GERAL FROM [MICRODADOS_CADASTRO_CURSOS_2019]  UNION
SELECT CO_CINE_AREA_ESPECIFICA, NO_CINE_AREA_ESPECIFICA, CO_CINE_AREA_GERAL FROM [MICRODADOS_CADASTRO_CURSOS_2020]  UNION
SELECT CO_CINE_AREA_ESPECIFICA, NO_CINE_AREA_ESPECIFICA, CO_CINE_AREA_GERAL FROM [MICRODADOS_CADASTRO_CURSOS_2021] 

/* -- SEM DUPLICIDADE
SELECT COUNT(1), CO_CINE_AREA_ESPECIFICA
FROM ODS.ODS_CINE_AREA_ESPECIFICA
GROUP BY CO_CINE_AREA_ESPECIFICA
HAVING COUNT(1)> 1
*/



DROP TABLE IF EXISTS ODS.ODS_CINE_AREA_GERAL
SELECT CO_CINE_AREA_GERAL , NO_CINE_AREA_GERAL INTO ODS.ODS_CINE_AREA_GERAL FROM [MICRODADOS_CADASTRO_CURSOS_2010]  UNION
SELECT CO_CINE_AREA_GERAL , NO_CINE_AREA_GERAL FROM [MICRODADOS_CADASTRO_CURSOS_2011]  UNION
SELECT CO_CINE_AREA_GERAL , NO_CINE_AREA_GERAL FROM [MICRODADOS_CADASTRO_CURSOS_2012]  UNION
SELECT CO_CINE_AREA_GERAL , NO_CINE_AREA_GERAL FROM [MICRODADOS_CADASTRO_CURSOS_2013]  UNION
SELECT CO_CINE_AREA_GERAL , NO_CINE_AREA_GERAL FROM [MICRODADOS_CADASTRO_CURSOS_2014]  UNION
SELECT CO_CINE_AREA_GERAL , NO_CINE_AREA_GERAL FROM [MICRODADOS_CADASTRO_CURSOS_2015]  UNION
SELECT CO_CINE_AREA_GERAL , NO_CINE_AREA_GERAL FROM [MICRODADOS_CADASTRO_CURSOS_2016]  UNION
SELECT CO_CINE_AREA_GERAL , NO_CINE_AREA_GERAL FROM [MICRODADOS_CADASTRO_CURSOS_2017]  UNION
SELECT CO_CINE_AREA_GERAL , NO_CINE_AREA_GERAL FROM [MICRODADOS_CADASTRO_CURSOS_2018]  UNION
SELECT CO_CINE_AREA_GERAL , NO_CINE_AREA_GERAL FROM [MICRODADOS_CADASTRO_CURSOS_2019]  UNION
SELECT CO_CINE_AREA_GERAL , NO_CINE_AREA_GERAL FROM [MICRODADOS_CADASTRO_CURSOS_2020]  UNION
SELECT CO_CINE_AREA_GERAL , NO_CINE_AREA_GERAL FROM [MICRODADOS_CADASTRO_CURSOS_2021] 

/* -- SEM DUPLICIDADE
SELECT COUNT(1), CO_CINE_AREA_GERAL
FROM ODS.ODS_CINE_AREA_GERAL
GROUP BY CO_CINE_AREA_GERAL
HAVING COUNT(1)> 1
*/



SELECT DISTINCT
  CO_CURSO
 , NO_CURSO
 --, REPLACE (CO_CINE_ROTULO, '"', '')CO_CINE_ROTULO
 --, TP_GRAU_ACADEMICO
 --, TP_NIVEL_ACADEMICO
FROM [stg].[STG_MICRODADOS_CADASTRO_CURSOS_SP]
ORDER BY 2
SELECT * FROM [stg].[STG_MICRODADOS_CADASTRO_CURSOS_SP]
WHERE CO_CURSO = 5001026


SELECT   CO_CURSO
 , NO_CURSO, 
 CO_CINE_ROTULO
 FROM [stg].[STG_MICRODADOS_CADASTRO_CURSOS_SP]
where no_curso like 'Ciência%d%Computação'

select * from [stg].[STG_MICRODADOS_CADASTRO_CURSOS_SP]
where co_curso = 48503
order by nu_ano_censo

SELECT   DISTINCT 
		NO_CURSO,
		 CO_CINE_ROTULO, 
		 NO_CINE_ROTULO
 FROM [stg].[STG_MICRODADOS_CADASTRO_CURSOS_SP]

SELECT * FROM ODS.ODS_CINE_ROTULO WHERE CO_CINE_ROTULO = '0614C01'

select * from ods.ods_curso where no_curso like 'Ciência%d%Computação'



drop table if exists #ODS_CURSO
SELECT DISTINCT
   NU_ANO_CENSO
 , CO_CURSO
 , NO_CURSO
 , CO_MUNICIPIO
 , IN_CAPITAL
 , TP_DIMENSAO
 , TP_REDE
 , CO_IES
 , REPLACE (CO_CINE_ROTULO, '"', '')CO_CINE_ROTULO
 , TP_GRAU_ACADEMICO
 , IN_GRATUITO
 , TP_MODALIDADE_ENSINO
 , TP_NIVEL_ACADEMICO
 INTO #ods_curso
FROM [stg].[STG_MICRODADOS_CADASTRO_CURSOS_SP]
CREATE CLUSTERED INDEX IXC_ODS_CURSO ON #ODS_CURSO(CO_CURSO, CO_MUNICIPIO, CO_IES, NU_ANO_CENSO)

DROP TABLE IF EXISTS ODS.ODS_CURSO
SELECT DISTINCT  
    C.CO_CURSO
,	TRIM(UPPER(C.NO_CURSO))NO_CURSO
,	C.CO_MUNICIPIO
,	C.IN_CAPITAL
,	C.TP_DIMENSAO
,	C.TP_REDE
,	C.CO_IES
,	C.CO_CINE_ROTULO
,	C.TP_GRAU_ACADEMICO
,	C.IN_GRATUITO
,	C.TP_MODALIDADE_ENSINO
,	C.TP_NIVEL_ACADEMICO
INTO ODS.ODS_CURSO
FROM #ODS_CURSO C

INNER JOIN (SELECT CO_CURSO, CO_MUNICIPIO, CO_IES, MAX(NU_ANO_CENSO) NU_ANO_CENSO
				FROM #ODS_CURSO
				GROUP BY CO_CURSO, CO_MUNICIPIO, CO_IES
)MX ON 
		C.CO_CURSO		=	MX.CO_CURSO		AND 
		C.CO_MUNICIPIO	=	MX.CO_MUNICIPIO	AND 
		C.CO_IES		=	MX.CO_IES		AND
	 	C.NU_ANO_CENSO	=	MX.NU_ANO_CENSO

/*

select * FROM [stg].[STG_MICRODADOS_CADASTRO_CURSOS_SP]
where co_curso = 1286528

select * from ods.ods_curso
where co_curso = 1286528

-- SEM DUPLICIDADE
select count(1),     CO_CURSO, CO_MUNICIPIO, CO_IES
FROM  ods.ods_curso
GROUP BY CO_CURSO, CO_MUNICIPIO, CO_IES
HAVING COUNT(1) > 1

SELECT * FROM ods.ods_curso
WHERE CO_CURSO = 52199	AND CO_MUNICIPIO  = 3509502	AND CO_IES = 19
SELECT * FROM #ODS_CURSO C
WHERE CO_CURSO = 52199	AND CO_MUNICIPIO  = 3509502	AND CO_IES = 19
*/

DROP TABLE IF EXISTS ODS.ODS_DADOS_CURSO
SELECT CO_CURSO, CO_MUNICIPIO, CO_IES, NU_ANO_CENSO,
	QT_CURSO,QT_VG_TOTAL,QT_VG_TOTAL_DIURNO,QT_VG_TOTAL_NOTURNO,QT_VG_TOTAL_EAD,QT_VG_NOVA,QT_VG_PROC_SELETIVO,QT_VG_REMANESC,QT_VG_PROG_ESPECIAL,QT_INSCRITO_TOTAL,QT_INSCRITO_TOTAL_DIURNO,QT_INSCRITO_TOTAL_NOTURNO,QT_INSCRITO_TOTAL_EAD,QT_INSC_VG_NOVA,QT_INSC_PROC_SELETIVO,QT_INSC_VG_REMANESC,QT_INSC_VG_PROG_ESPECIAL,QT_ING,QT_ING_FEM,QT_ING_MASC,QT_ING_DIURNO,QT_ING_NOTURNO,QT_ING_VG_NOVA,QT_ING_VESTIBULAR,QT_ING_ENEM,QT_ING_AVALIACAO_SERIADA,QT_ING_SELECAO_SIMPLIFICA,QT_ING_EGR,QT_ING_OUTRO_TIPO_SELECAO,QT_ING_PROC_SELETIVO,QT_ING_VG_REMANESC,QT_ING_VG_PROG_ESPECIAL,QT_ING_OUTRA_FORMA,QT_ING_0_17,QT_ING_18_24,QT_ING_25_29,QT_ING_30_34,QT_ING_35_39,QT_ING_40_49,QT_ING_50_59,QT_ING_60_MAIS,QT_ING_BRANCA,QT_ING_PRETA,QT_ING_PARDA,QT_ING_AMARELA,QT_ING_INDIGENA,QT_ING_CORND,QT_MAT,QT_MAT_FEM,QT_MAT_MASC,QT_MAT_DIURNO,QT_MAT_NOTURNO,QT_MAT_0_17,QT_MAT_18_24,QT_MAT_25_29,QT_MAT_30_34,QT_MAT_35_39,QT_MAT_40_49,QT_MAT_50_59,QT_MAT_60_MAIS,QT_MAT_BRANCA,QT_MAT_PRETA,QT_MAT_PARDA,QT_MAT_AMARELA,QT_MAT_INDIGENA,QT_MAT_CORND,QT_CONC,QT_CONC_FEM,QT_CONC_MASC,QT_CONC_DIURNO,QT_CONC_NOTURNO,QT_CONC_0_17,QT_CONC_18_24,QT_CONC_25_29,QT_CONC_30_34,QT_CONC_35_39,QT_CONC_40_49,QT_CONC_50_59,QT_CONC_60_MAIS,QT_CONC_BRANCA,QT_CONC_PRETA,QT_CONC_PARDA,QT_CONC_AMARELA,QT_CONC_INDIGENA,QT_CONC_CORND,QT_ING_NACBRAS,QT_ING_NACESTRANG,QT_MAT_NACBRAS,QT_MAT_NACESTRANG,QT_CONC_NACBRAS,QT_CONC_NACESTRANG,QT_ALUNO_DEFICIENTE,QT_ING_DEFICIENTE,QT_MAT_DEFICIENTE,QT_CONC_DEFICIENTE,QT_ING_FINANC,QT_ING_FINANC_REEMB,QT_ING_FIES,QT_ING_RPFIES,QT_ING_FINANC_REEMB_OUTROS,QT_ING_FINANC_NREEMB,QT_ING_PROUNII,QT_ING_PROUNIP,QT_ING_NRPFIES,QT_ING_FINANC_NREEMB_OUTROS,QT_MAT_FINANC,QT_MAT_FINANC_REEMB,QT_MAT_FIES,QT_MAT_RPFIES,QT_MAT_FINANC_REEMB_OUTROS,QT_MAT_FINANC_NREEMB,QT_MAT_PROUNII,QT_MAT_PROUNIP,QT_MAT_NRPFIES,QT_MAT_FINANC_NREEMB_OUTROS,QT_CONC_FINANC,QT_CONC_FINANC_REEMB,QT_CONC_FIES,QT_CONC_RPFIES,QT_CONC_FINANC_REEMB_OUTROS,QT_CONC_FINANC_NREEMB,QT_CONC_PROUNII,QT_CONC_PROUNIP,QT_CONC_NRPFIES,QT_CONC_FINANC_NREEMB_OUTROS,QT_ING_RESERVA_VAGA,QT_ING_RVREDEPUBLICA,QT_ING_RVETNICO,QT_ING_RVPDEF,QT_ING_RVSOCIAL_RF,QT_ING_RVOUTROS,QT_MAT_RESERVA_VAGA,QT_MAT_RVREDEPUBLICA,QT_MAT_RVETNICO,QT_MAT_RVPDEF,QT_MAT_RVSOCIAL_RF,QT_MAT_RVOUTROS,QT_CONC_RESERVA_VAGA,QT_CONC_RVREDEPUBLICA,QT_CONC_RVETNICO,QT_CONC_RVPDEF,QT_CONC_RVSOCIAL_RF,QT_CONC_RVOUTROS,QT_SIT_TRANCADA,QT_SIT_DESVINCULADO,QT_SIT_TRANSFERIDO,QT_SIT_FALECIDO,QT_ING_PROCESCPUBLICA,QT_ING_PROCESCPRIVADA,QT_ING_PROCNAOINFORMADA,QT_MAT_PROCESCPUBLICA,QT_MAT_PROCESCPRIVADA,QT_MAT_PROCNAOINFORMADA,QT_CONC_PROCESCPUBLICA,QT_CONC_PROCESCPRIVADA,QT_CONC_PROCNAOINFORMADA,QT_PARFOR,QT_ING_PARFOR,QT_MAT_PARFOR,QT_CONC_PARFOR,QT_APOIO_SOCIAL,QT_ING_APOIO_SOCIAL,QT_MAT_APOIO_SOCIAL,QT_CONC_APOIO_SOCIAL,QT_ATIV_EXTRACURRICULAR,QT_ING_ATIV_EXTRACURRICULAR,QT_MAT_ATIV_EXTRACURRICULAR,QT_CONC_ATIV_EXTRACURRICULAR,QT_MOB_ACADEMICA,QT_ING_MOB_ACADEMICA,QT_MAT_MOB_ACADEMICA,QT_CONC_MOB_ACADEMICA
	INTO ODS.ODS_DADOS_CURSO
FROM [stg].[STG_MICRODADOS_CADASTRO_CURSOS_SP]

CREATE CLUSTERED INDEX IXC_ODS_DADOS_CURSO ON ODS.ODS_DADOS_CURSO (CO_CURSO, CO_MUNICIPIO, CO_IES, NU_ANO_CENSO)

SELECT CO_IES, NU_ANO_CENSO, 
		QT_TEC_TOTAL,QT_TEC_FUNDAMENTAL_INCOMP_FEM,QT_TEC_FUNDAMENTAL_INCOMP_MASC,QT_TEC_FUNDAMENTAL_COMP_FEM,QT_TEC_FUNDAMENTAL_COMP_MASC,QT_TEC_MEDIO_FEM,QT_TEC_MEDIO_MASC,QT_TEC_SUPERIOR_FEM,QT_TEC_SUPERIOR_MASC,QT_TEC_ESPECIALIZACAO_FEM,QT_TEC_ESPECIALIZACAO_MASC,QT_TEC_MESTRADO_FEM,QT_TEC_MESTRADO_MASC,QT_TEC_DOUTORADO_FEM,QT_TEC_DOUTORADO_MASC,IN_ACESSO_PORTAL_CAPES,IN_ACESSO_OUTRAS_BASES,IN_ASSINA_OUTRA_BASE,IN_REPOSITORIO_INSTITUCIONAL,IN_BUSCA_INTEGRADA,IN_SERVICO_INTERNET,IN_PARTICIPA_REDE_SOCIAL,IN_CATALOGO_ONLINE,QT_PERIODICO_ELETRONICO,QT_LIVRO_ELETRONICO,QT_DOC_TOTAL,QT_DOC_EXE,QT_DOC_EX_FEMI,QT_DOC_EX_MASC,QT_DOC_EX_SEM_GRAD,QT_DOC_EX_GRAD,QT_DOC_EX_ESP,QT_DOC_EX_MEST,QT_DOC_EX_DOUT,QT_DOC_EX_INT,QT_DOC_EX_INT_DE,QT_DOC_EX_INT_SEM_DE,QT_DOC_EX_PARC,QT_DOC_EX_HOR,QT_DOC_EX_0_29,QT_DOC_EX_30_34,QT_DOC_EX_35_39,QT_DOC_EX_40_44,QT_DOC_EX_45_49,QT_DOC_EX_50_54,QT_DOC_EX_55_59,QT_DOC_EX_60_MAIS,QT_DOC_EX_BRANCA,QT_DOC_EX_PRETA,QT_DOC_EX_PARDA,QT_DOC_EX_AMARELA,QT_DOC_EX_INDIGENA,QT_DOC_EX_COR_ND,QT_DOC_EX_BRA,QT_DOC_EX_EST,QT_DOC_EX_COM_DEFICIENCIA
INTO ODS.ODS_DADOS_IES
FROM [stg].[STG_MICRODADOS_CADASTRO_IES_SP]

CREATE CLUSTERED INDEX IXC_ODS_DADOS_IES ON ODS.ODS_DADOS_IES (CO_IES, NU_ANO_CENSO )

DROP TABLE IF EXISTS ODS.ODS_DADOS_FLUXO
SELECT 
	  ANO_DE_REFERÊNCIA											NU_ANO_CENSO
	, CÓDIGO_DA_INSTITUIÇÃO										CO_IES
	, CÓDIGO_DO_CURSO_DE_GRADUAÇÃO								CO_CURSO
	, CÓDIGO_DO_MUNICÍPIO_DO_CURSO								CO_MUNICIPIO
	, ANO_DE_INGRESSO											NU_ANO_INGRESSO
	, PRAZO_DE_INTEGRALIZAÇÃO_EM_ANOS							NU_PRAZO_INTEGRALIZACAO
	, ANO_DE_INTEGRALIZAÇÃO_DO_CURSO							NU_ANO_INTEGRALIZACAO
	, PRAZO_DE_ACOMPANHAMENTO_DO_CURSO_EM_ANOS					NU_PRAZO_ACOMPANHAMENTO
	, ANO_MÁXIMO_DE_ACOMPANHAMENTO_DO_CURSO						NU_ANO_MAXIMO_ACOMPANHAMENTO
	, QUANTIDADE_DE_INGRESSANTES_NO_CURSO						QT_INGRESSANTE
	, QUANTIDADE_DE_PERMANÊNCIA_NO_CURSO_NO_ANO_DE_REFERÊNCIA	QT_PERMANENCIA	
	, QUANTIDADE_DE_CONCLUINTES_NO_CURSO_NO_ANO_DE_REFERÊNCIA	QT_CONCLUINTE
	, QUANTIDADE_DE_DESISTÊNCIA_NO_CURSO_NO_ANO_DE_REFERÊNCIA	QT_DESISTENCIA
	, QUANTIDADE_DE_FALECIMENTOS_NO_CURSO_NO_ANO_DE_REFERÊNCIA	QT_FALECIDO
	, TAXA_DE_PERMANÊNCIA_TAP									VL_TAP
	, TAXA_DE_CONCLUSÃO_ACUMULADA_TCA							VL_TCA
	, TAXA_DE_DESISTÊNCIA_ACUMULADA_TDA							VL_TDA
	, TAXA_DE_CONCLUSÃO_ANUAL_TCAN								VL_TCAN
	, TAXA_DE_DESISTÊNCIA_ANUAL_TDAN							VL_TDAN
	, CO_CATALOGO												CO_CATALOGO
	INTO ODS.ODS_DADOS_FLUXO
FROM [STG].[STG_INDICADORES_TRAJETORIA_EDUCACAO_SUPERIOR_SP]

CREATE CLUSTERED INDEX IXC_ODS_DADOS_FLUXO ON ODS.ODS_DADOS_FLUXO (NU_ANO_CENSO, CO_IES, CO_CURSO, CO_MUNICIPIO)



