use tcc_evasao
SELECT file_id,
       name,
       CAST(FILEPROPERTY(name, 'SpaceUsed') AS bigint) * 8 / 1024. AS space_used_mb,
       CAST(size AS bigint) * 8 / 1024. AS space_allocated_mb,
       CAST(max_size AS bigint) * 8 / 1024. AS max_file_size_mb
FROM sys.database_files
WHERE type_desc IN ('ROWS','LOG');



SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME LIKE 'MICRODADOS_CADASTRO_CURSOS%'

CREATE CLUSTERED INDEX IXC_MICRODADOS_CADASTRO_CURSOS_2010 ON MICRODADOS_CADASTRO_CURSOS_2010 (CO_CURSO)
CREATE CLUSTERED INDEX IXC_MICRODADOS_CADASTRO_CURSOS_2011 ON MICRODADOS_CADASTRO_CURSOS_2011 (CO_CURSO)
CREATE CLUSTERED INDEX IXC_MICRODADOS_CADASTRO_CURSOS_2012 ON MICRODADOS_CADASTRO_CURSOS_2012 (CO_CURSO)
CREATE CLUSTERED INDEX IXC_MICRODADOS_CADASTRO_CURSOS_2013 ON MICRODADOS_CADASTRO_CURSOS_2013 (CO_CURSO)
CREATE CLUSTERED INDEX IXC_MICRODADOS_CADASTRO_CURSOS_2014 ON MICRODADOS_CADASTRO_CURSOS_2014 (CO_CURSO)
CREATE CLUSTERED INDEX IXC_MICRODADOS_CADASTRO_CURSOS_2015 ON MICRODADOS_CADASTRO_CURSOS_2015 (CO_CURSO)
CREATE CLUSTERED INDEX IXC_MICRODADOS_CADASTRO_CURSOS_2016 ON MICRODADOS_CADASTRO_CURSOS_2016 (CO_CURSO)
CREATE CLUSTERED INDEX IXC_MICRODADOS_CADASTRO_CURSOS_2017 ON MICRODADOS_CADASTRO_CURSOS_2017 (CO_CURSO)
CREATE CLUSTERED INDEX IXC_MICRODADOS_CADASTRO_CURSOS_2018 ON MICRODADOS_CADASTRO_CURSOS_2018 (CO_CURSO)
CREATE CLUSTERED INDEX IXC_MICRODADOS_CADASTRO_CURSOS_2019 ON MICRODADOS_CADASTRO_CURSOS_2019 (CO_CURSO)
CREATE CLUSTERED INDEX IXC_MICRODADOS_CADASTRO_CURSOS_2020 ON MICRODADOS_CADASTRO_CURSOS_2020 (CO_CURSO)
CREATE CLUSTERED INDEX IXC_MICRODADOS_CADASTRO_CURSOS_2021 ON MICRODADOS_CADASTRO_CURSOS_2021 (CO_CURSO)



DROP TABLE IF EXISTS STG.STG_MICRODADOS_CADASTRO_CURSOS_SP
SELECT * INTO stg.STG_MICRODADOS_CADASTRO_CURSOS_SP
		 FROM  MICRODADOS_CADASTRO_CURSOS_2010 WHERE SG_UF = 'SP' UNION 
SELECT * FROM  MICRODADOS_CADASTRO_CURSOS_2011 WHERE SG_UF = 'SP' UNION 
SELECT * FROM  MICRODADOS_CADASTRO_CURSOS_2012 WHERE SG_UF = 'SP' UNION 
SELECT * FROM  MICRODADOS_CADASTRO_CURSOS_2013 WHERE SG_UF = 'SP' UNION 
SELECT * FROM  MICRODADOS_CADASTRO_CURSOS_2014 WHERE SG_UF = 'SP' UNION 
SELECT * FROM  MICRODADOS_CADASTRO_CURSOS_2015 WHERE SG_UF = 'SP' UNION 
SELECT * FROM  MICRODADOS_CADASTRO_CURSOS_2016 WHERE SG_UF = 'SP' UNION 
SELECT * FROM  MICRODADOS_CADASTRO_CURSOS_2017 WHERE SG_UF = 'SP' UNION 
SELECT * FROM  MICRODADOS_CADASTRO_CURSOS_2018 WHERE SG_UF = 'SP' UNION 
SELECT * FROM  MICRODADOS_CADASTRO_CURSOS_2019 WHERE SG_UF = 'SP' UNION 
SELECT * FROM  MICRODADOS_CADASTRO_CURSOS_2020 WHERE SG_UF = 'SP' UNION 
SELECT * FROM  MICRODADOS_CADASTRO_CURSOS_2021 WHERE SG_UF = 'SP' 

CREATE CLUSTERED INDEX IXC_STG_MICRODADOS_CADASTRO_CURSO_SP ON STG.STG_MICRODADOS_CADASTRO_CURSOS_SP(NU_ANO_CENSO, co_curso, co_ies)


SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME LIKE 'MICRODADOS_CADASTRO_IES%'


drop table if exists stg.STG_MICRODADOS_CADASTRO_IES_SP
SELECT NU_ANO_CENSO,NO_REGIAO_IES,CO_REGIAO_IES,NO_UF_IES,SG_UF_IES,CO_UF_IES,NO_MUNICIPIO_IES,CO_MUNICIPIO_IES,IN_CAPITAL_IES,NO_MESORREGIAO_IES,CO_MESORREGIAO_IES,NO_MICRORREGIAO_IES,CO_MICRORREGIAO_IES,TP_ORGANIZACAO_ACADEMICA,TP_CATEGORIA_ADMINISTRATIVA,NO_MANTENEDORA,CO_MANTENEDORA,CO_IES,NO_IES,SG_IES,DS_ENDERECO_IES,DS_NUMERO_ENDERECO_IES,DS_COMPLEMENTO_ENDERECO_IES,NO_BAIRRO_IES,NU_CEP_IES,QT_TEC_TOTAL,QT_TEC_FUNDAMENTAL_INCOMP_FEM,QT_TEC_FUNDAMENTAL_INCOMP_MASC,QT_TEC_FUNDAMENTAL_COMP_FEM,QT_TEC_FUNDAMENTAL_COMP_MASC,QT_TEC_MEDIO_FEM,QT_TEC_MEDIO_MASC,QT_TEC_SUPERIOR_FEM,QT_TEC_SUPERIOR_MASC,QT_TEC_ESPECIALIZACAO_FEM,QT_TEC_ESPECIALIZACAO_MASC,QT_TEC_MESTRADO_FEM,QT_TEC_MESTRADO_MASC,QT_TEC_DOUTORADO_FEM,QT_TEC_DOUTORADO_MASC,IN_ACESSO_PORTAL_CAPES,IN_ACESSO_OUTRAS_BASES,IN_ASSINA_OUTRA_BASE,IN_REPOSITORIO_INSTITUCIONAL,IN_BUSCA_INTEGRADA,IN_SERVICO_INTERNET,IN_PARTICIPA_REDE_SOCIAL,IN_CATALOGO_ONLINE,QT_PERIODICO_ELETRONICO,QT_LIVRO_ELETRONICO,QT_DOC_TOTAL,QT_DOC_EXE,QT_DOC_EX_FEMI,QT_DOC_EX_MASC,QT_DOC_EX_SEM_GRAD,QT_DOC_EX_GRAD,QT_DOC_EX_ESP,QT_DOC_EX_MEST,QT_DOC_EX_DOUT,QT_DOC_EX_INT,QT_DOC_EX_INT_DE,QT_DOC_EX_INT_SEM_DE,QT_DOC_EX_PARC,QT_DOC_EX_HOR,QT_DOC_EX_0_29,QT_DOC_EX_30_34,QT_DOC_EX_35_39,QT_DOC_EX_40_44,QT_DOC_EX_45_49,QT_DOC_EX_50_54,QT_DOC_EX_55_59,QT_DOC_EX_60_MAIS,QT_DOC_EX_BRANCA,QT_DOC_EX_PRETA,QT_DOC_EX_PARDA,QT_DOC_EX_AMARELA,QT_DOC_EX_INDIGENA,QT_DOC_EX_COR_ND,QT_DOC_EX_BRA,QT_DOC_EX_EST,QT_DOC_EX_COM_DEFICIENCIA
INTO   stg.MICRODADOS_CADASTRO_IES_SP
		 FROM 	MICRODADOS_CADASTRO_IES_2010 WHERE SG_UF_IES = 'SP' UNION 
SELECT NU_ANO_CENSO,NO_REGIAO_IES,CO_REGIAO_IES,NO_UF_IES,SG_UF_IES,CO_UF_IES,NO_MUNICIPIO_IES,CO_MUNICIPIO_IES,IN_CAPITAL_IES,NO_MESORREGIAO_IES,CO_MESORREGIAO_IES,NO_MICRORREGIAO_IES,CO_MICRORREGIAO_IES,TP_ORGANIZACAO_ACADEMICA,TP_CATEGORIA_ADMINISTRATIVA,NO_MANTENEDORA,CO_MANTENEDORA,CO_IES,NO_IES,SG_IES,DS_ENDERECO_IES,DS_NUMERO_ENDERECO_IES,DS_COMPLEMENTO_ENDERECO_IES,NO_BAIRRO_IES,NU_CEP_IES,QT_TEC_TOTAL,QT_TEC_FUNDAMENTAL_INCOMP_FEM,QT_TEC_FUNDAMENTAL_INCOMP_MASC,QT_TEC_FUNDAMENTAL_COMP_FEM,QT_TEC_FUNDAMENTAL_COMP_MASC,QT_TEC_MEDIO_FEM,QT_TEC_MEDIO_MASC,QT_TEC_SUPERIOR_FEM,QT_TEC_SUPERIOR_MASC,QT_TEC_ESPECIALIZACAO_FEM,QT_TEC_ESPECIALIZACAO_MASC,QT_TEC_MESTRADO_FEM,QT_TEC_MESTRADO_MASC,QT_TEC_DOUTORADO_FEM,QT_TEC_DOUTORADO_MASC,IN_ACESSO_PORTAL_CAPES,IN_ACESSO_OUTRAS_BASES,IN_ASSINA_OUTRA_BASE,IN_REPOSITORIO_INSTITUCIONAL,IN_BUSCA_INTEGRADA,IN_SERVICO_INTERNET,IN_PARTICIPA_REDE_SOCIAL,IN_CATALOGO_ONLINE,QT_PERIODICO_ELETRONICO,QT_LIVRO_ELETRONICO,QT_DOC_TOTAL,QT_DOC_EXE,QT_DOC_EX_FEMI,QT_DOC_EX_MASC,QT_DOC_EX_SEM_GRAD,QT_DOC_EX_GRAD,QT_DOC_EX_ESP,QT_DOC_EX_MEST,QT_DOC_EX_DOUT,QT_DOC_EX_INT,QT_DOC_EX_INT_DE,QT_DOC_EX_INT_SEM_DE,QT_DOC_EX_PARC,QT_DOC_EX_HOR,QT_DOC_EX_0_29,QT_DOC_EX_30_34,QT_DOC_EX_35_39,QT_DOC_EX_40_44,QT_DOC_EX_45_49,QT_DOC_EX_50_54,QT_DOC_EX_55_59,QT_DOC_EX_60_MAIS,QT_DOC_EX_BRANCA,QT_DOC_EX_PRETA,QT_DOC_EX_PARDA,QT_DOC_EX_AMARELA,QT_DOC_EX_INDIGENA,QT_DOC_EX_COR_ND,QT_DOC_EX_BRA,QT_DOC_EX_EST,QT_DOC_EX_COM_DEFICIENCIA FROM	MICRODADOS_CADASTRO_IES_2011 WHERE SG_UF_IES = 'SP' UNION 
SELECT NU_ANO_CENSO,NO_REGIAO_IES,CO_REGIAO_IES,NO_UF_IES,SG_UF_IES,CO_UF_IES,NO_MUNICIPIO_IES,CO_MUNICIPIO_IES,IN_CAPITAL_IES,NO_MESORREGIAO_IES,CO_MESORREGIAO_IES,NO_MICRORREGIAO_IES,CO_MICRORREGIAO_IES,TP_ORGANIZACAO_ACADEMICA,TP_CATEGORIA_ADMINISTRATIVA,NO_MANTENEDORA,CO_MANTENEDORA,CO_IES,NO_IES,SG_IES,DS_ENDERECO_IES,DS_NUMERO_ENDERECO_IES,DS_COMPLEMENTO_ENDERECO_IES,NO_BAIRRO_IES,NU_CEP_IES,QT_TEC_TOTAL,QT_TEC_FUNDAMENTAL_INCOMP_FEM,QT_TEC_FUNDAMENTAL_INCOMP_MASC,QT_TEC_FUNDAMENTAL_COMP_FEM,QT_TEC_FUNDAMENTAL_COMP_MASC,QT_TEC_MEDIO_FEM,QT_TEC_MEDIO_MASC,QT_TEC_SUPERIOR_FEM,QT_TEC_SUPERIOR_MASC,QT_TEC_ESPECIALIZACAO_FEM,QT_TEC_ESPECIALIZACAO_MASC,QT_TEC_MESTRADO_FEM,QT_TEC_MESTRADO_MASC,QT_TEC_DOUTORADO_FEM,QT_TEC_DOUTORADO_MASC,IN_ACESSO_PORTAL_CAPES,IN_ACESSO_OUTRAS_BASES,IN_ASSINA_OUTRA_BASE,IN_REPOSITORIO_INSTITUCIONAL,IN_BUSCA_INTEGRADA,IN_SERVICO_INTERNET,IN_PARTICIPA_REDE_SOCIAL,IN_CATALOGO_ONLINE,QT_PERIODICO_ELETRONICO,QT_LIVRO_ELETRONICO,QT_DOC_TOTAL,QT_DOC_EXE,QT_DOC_EX_FEMI,QT_DOC_EX_MASC,QT_DOC_EX_SEM_GRAD,QT_DOC_EX_GRAD,QT_DOC_EX_ESP,QT_DOC_EX_MEST,QT_DOC_EX_DOUT,QT_DOC_EX_INT,QT_DOC_EX_INT_DE,QT_DOC_EX_INT_SEM_DE,QT_DOC_EX_PARC,QT_DOC_EX_HOR,QT_DOC_EX_0_29,QT_DOC_EX_30_34,QT_DOC_EX_35_39,QT_DOC_EX_40_44,QT_DOC_EX_45_49,QT_DOC_EX_50_54,QT_DOC_EX_55_59,QT_DOC_EX_60_MAIS,QT_DOC_EX_BRANCA,QT_DOC_EX_PRETA,QT_DOC_EX_PARDA,QT_DOC_EX_AMARELA,QT_DOC_EX_INDIGENA,QT_DOC_EX_COR_ND,QT_DOC_EX_BRA,QT_DOC_EX_EST,QT_DOC_EX_COM_DEFICIENCIA FROM	MICRODADOS_CADASTRO_IES_2012 WHERE SG_UF_IES = 'SP' UNION 
SELECT NU_ANO_CENSO,NO_REGIAO_IES,CO_REGIAO_IES,NO_UF_IES,SG_UF_IES,CO_UF_IES,NO_MUNICIPIO_IES,CO_MUNICIPIO_IES,IN_CAPITAL_IES,NO_MESORREGIAO_IES,CO_MESORREGIAO_IES,NO_MICRORREGIAO_IES,CO_MICRORREGIAO_IES,TP_ORGANIZACAO_ACADEMICA,TP_CATEGORIA_ADMINISTRATIVA,NO_MANTENEDORA,CO_MANTENEDORA,CO_IES,NO_IES,SG_IES,DS_ENDERECO_IES,DS_NUMERO_ENDERECO_IES,DS_COMPLEMENTO_ENDERECO_IES,NO_BAIRRO_IES,NU_CEP_IES,QT_TEC_TOTAL,QT_TEC_FUNDAMENTAL_INCOMP_FEM,QT_TEC_FUNDAMENTAL_INCOMP_MASC,QT_TEC_FUNDAMENTAL_COMP_FEM,QT_TEC_FUNDAMENTAL_COMP_MASC,QT_TEC_MEDIO_FEM,QT_TEC_MEDIO_MASC,QT_TEC_SUPERIOR_FEM,QT_TEC_SUPERIOR_MASC,QT_TEC_ESPECIALIZACAO_FEM,QT_TEC_ESPECIALIZACAO_MASC,QT_TEC_MESTRADO_FEM,QT_TEC_MESTRADO_MASC,QT_TEC_DOUTORADO_FEM,QT_TEC_DOUTORADO_MASC,IN_ACESSO_PORTAL_CAPES,IN_ACESSO_OUTRAS_BASES,IN_ASSINA_OUTRA_BASE,IN_REPOSITORIO_INSTITUCIONAL,IN_BUSCA_INTEGRADA,IN_SERVICO_INTERNET,IN_PARTICIPA_REDE_SOCIAL,IN_CATALOGO_ONLINE,QT_PERIODICO_ELETRONICO,QT_LIVRO_ELETRONICO,QT_DOC_TOTAL,QT_DOC_EXE,QT_DOC_EX_FEMI,QT_DOC_EX_MASC,QT_DOC_EX_SEM_GRAD,QT_DOC_EX_GRAD,QT_DOC_EX_ESP,QT_DOC_EX_MEST,QT_DOC_EX_DOUT,QT_DOC_EX_INT,QT_DOC_EX_INT_DE,QT_DOC_EX_INT_SEM_DE,QT_DOC_EX_PARC,QT_DOC_EX_HOR,QT_DOC_EX_0_29,QT_DOC_EX_30_34,QT_DOC_EX_35_39,QT_DOC_EX_40_44,QT_DOC_EX_45_49,QT_DOC_EX_50_54,QT_DOC_EX_55_59,QT_DOC_EX_60_MAIS,QT_DOC_EX_BRANCA,QT_DOC_EX_PRETA,QT_DOC_EX_PARDA,QT_DOC_EX_AMARELA,QT_DOC_EX_INDIGENA,QT_DOC_EX_COR_ND,QT_DOC_EX_BRA,QT_DOC_EX_EST,QT_DOC_EX_COM_DEFICIENCIA FROM	MICRODADOS_CADASTRO_IES_2013 WHERE SG_UF_IES = 'SP' UNION 
SELECT NU_ANO_CENSO,NO_REGIAO_IES,CO_REGIAO_IES,NO_UF_IES,SG_UF_IES,CO_UF_IES,NO_MUNICIPIO_IES,CO_MUNICIPIO_IES,IN_CAPITAL_IES,NO_MESORREGIAO_IES,CO_MESORREGIAO_IES,NO_MICRORREGIAO_IES,CO_MICRORREGIAO_IES,TP_ORGANIZACAO_ACADEMICA,TP_CATEGORIA_ADMINISTRATIVA,NO_MANTENEDORA,CO_MANTENEDORA,CO_IES,NO_IES,SG_IES,DS_ENDERECO_IES,DS_NUMERO_ENDERECO_IES,DS_COMPLEMENTO_ENDERECO_IES,NO_BAIRRO_IES,NU_CEP_IES,QT_TEC_TOTAL,QT_TEC_FUNDAMENTAL_INCOMP_FEM,QT_TEC_FUNDAMENTAL_INCOMP_MASC,QT_TEC_FUNDAMENTAL_COMP_FEM,QT_TEC_FUNDAMENTAL_COMP_MASC,QT_TEC_MEDIO_FEM,QT_TEC_MEDIO_MASC,QT_TEC_SUPERIOR_FEM,QT_TEC_SUPERIOR_MASC,QT_TEC_ESPECIALIZACAO_FEM,QT_TEC_ESPECIALIZACAO_MASC,QT_TEC_MESTRADO_FEM,QT_TEC_MESTRADO_MASC,QT_TEC_DOUTORADO_FEM,QT_TEC_DOUTORADO_MASC,IN_ACESSO_PORTAL_CAPES,IN_ACESSO_OUTRAS_BASES,IN_ASSINA_OUTRA_BASE,IN_REPOSITORIO_INSTITUCIONAL,IN_BUSCA_INTEGRADA,IN_SERVICO_INTERNET,IN_PARTICIPA_REDE_SOCIAL,IN_CATALOGO_ONLINE,QT_PERIODICO_ELETRONICO,QT_LIVRO_ELETRONICO,QT_DOC_TOTAL,QT_DOC_EXE,QT_DOC_EX_FEMI,QT_DOC_EX_MASC,QT_DOC_EX_SEM_GRAD,QT_DOC_EX_GRAD,QT_DOC_EX_ESP,QT_DOC_EX_MEST,QT_DOC_EX_DOUT,QT_DOC_EX_INT,QT_DOC_EX_INT_DE,QT_DOC_EX_INT_SEM_DE,QT_DOC_EX_PARC,QT_DOC_EX_HOR,QT_DOC_EX_0_29,QT_DOC_EX_30_34,QT_DOC_EX_35_39,QT_DOC_EX_40_44,QT_DOC_EX_45_49,QT_DOC_EX_50_54,QT_DOC_EX_55_59,QT_DOC_EX_60_MAIS,QT_DOC_EX_BRANCA,QT_DOC_EX_PRETA,QT_DOC_EX_PARDA,QT_DOC_EX_AMARELA,QT_DOC_EX_INDIGENA,QT_DOC_EX_COR_ND,QT_DOC_EX_BRA,QT_DOC_EX_EST,QT_DOC_EX_COM_DEFICIENCIA FROM	MICRODADOS_CADASTRO_IES_2014 WHERE SG_UF_IES = 'SP' UNION 
SELECT NU_ANO_CENSO,NO_REGIAO_IES,CO_REGIAO_IES,NO_UF_IES,SG_UF_IES,CO_UF_IES,NO_MUNICIPIO_IES,CO_MUNICIPIO_IES,IN_CAPITAL_IES,NO_MESORREGIAO_IES,CO_MESORREGIAO_IES,NO_MICRORREGIAO_IES,CO_MICRORREGIAO_IES,TP_ORGANIZACAO_ACADEMICA,TP_CATEGORIA_ADMINISTRATIVA,NO_MANTENEDORA,CO_MANTENEDORA,CO_IES,NO_IES,SG_IES,DS_ENDERECO_IES,DS_NUMERO_ENDERECO_IES,DS_COMPLEMENTO_ENDERECO_IES,NO_BAIRRO_IES,NU_CEP_IES,QT_TEC_TOTAL,QT_TEC_FUNDAMENTAL_INCOMP_FEM,QT_TEC_FUNDAMENTAL_INCOMP_MASC,QT_TEC_FUNDAMENTAL_COMP_FEM,QT_TEC_FUNDAMENTAL_COMP_MASC,QT_TEC_MEDIO_FEM,QT_TEC_MEDIO_MASC,QT_TEC_SUPERIOR_FEM,QT_TEC_SUPERIOR_MASC,QT_TEC_ESPECIALIZACAO_FEM,QT_TEC_ESPECIALIZACAO_MASC,QT_TEC_MESTRADO_FEM,QT_TEC_MESTRADO_MASC,QT_TEC_DOUTORADO_FEM,QT_TEC_DOUTORADO_MASC,IN_ACESSO_PORTAL_CAPES,IN_ACESSO_OUTRAS_BASES,IN_ASSINA_OUTRA_BASE,IN_REPOSITORIO_INSTITUCIONAL,IN_BUSCA_INTEGRADA,IN_SERVICO_INTERNET,IN_PARTICIPA_REDE_SOCIAL,IN_CATALOGO_ONLINE,QT_PERIODICO_ELETRONICO,QT_LIVRO_ELETRONICO,QT_DOC_TOTAL,QT_DOC_EXE,QT_DOC_EX_FEMI,QT_DOC_EX_MASC,QT_DOC_EX_SEM_GRAD,QT_DOC_EX_GRAD,QT_DOC_EX_ESP,QT_DOC_EX_MEST,QT_DOC_EX_DOUT,QT_DOC_EX_INT,QT_DOC_EX_INT_DE,QT_DOC_EX_INT_SEM_DE,QT_DOC_EX_PARC,QT_DOC_EX_HOR,QT_DOC_EX_0_29,QT_DOC_EX_30_34,QT_DOC_EX_35_39,QT_DOC_EX_40_44,QT_DOC_EX_45_49,QT_DOC_EX_50_54,QT_DOC_EX_55_59,QT_DOC_EX_60_MAIS,QT_DOC_EX_BRANCA,QT_DOC_EX_PRETA,QT_DOC_EX_PARDA,QT_DOC_EX_AMARELA,QT_DOC_EX_INDIGENA,QT_DOC_EX_COR_ND,QT_DOC_EX_BRA,QT_DOC_EX_EST,QT_DOC_EX_COM_DEFICIENCIA FROM	MICRODADOS_CADASTRO_IES_2015 WHERE SG_UF_IES = 'SP' UNION 
SELECT NU_ANO_CENSO,NO_REGIAO_IES,CO_REGIAO_IES,NO_UF_IES,SG_UF_IES,CO_UF_IES,NO_MUNICIPIO_IES,CO_MUNICIPIO_IES,IN_CAPITAL_IES,NO_MESORREGIAO_IES,CO_MESORREGIAO_IES,NO_MICRORREGIAO_IES,CO_MICRORREGIAO_IES,TP_ORGANIZACAO_ACADEMICA,TP_CATEGORIA_ADMINISTRATIVA,NO_MANTENEDORA,CO_MANTENEDORA,CO_IES,NO_IES,SG_IES,DS_ENDERECO_IES,DS_NUMERO_ENDERECO_IES,DS_COMPLEMENTO_ENDERECO_IES,NO_BAIRRO_IES,NU_CEP_IES,QT_TEC_TOTAL,QT_TEC_FUNDAMENTAL_INCOMP_FEM,QT_TEC_FUNDAMENTAL_INCOMP_MASC,QT_TEC_FUNDAMENTAL_COMP_FEM,QT_TEC_FUNDAMENTAL_COMP_MASC,QT_TEC_MEDIO_FEM,QT_TEC_MEDIO_MASC,QT_TEC_SUPERIOR_FEM,QT_TEC_SUPERIOR_MASC,QT_TEC_ESPECIALIZACAO_FEM,QT_TEC_ESPECIALIZACAO_MASC,QT_TEC_MESTRADO_FEM,QT_TEC_MESTRADO_MASC,QT_TEC_DOUTORADO_FEM,QT_TEC_DOUTORADO_MASC,IN_ACESSO_PORTAL_CAPES,IN_ACESSO_OUTRAS_BASES,IN_ASSINA_OUTRA_BASE,IN_REPOSITORIO_INSTITUCIONAL,IN_BUSCA_INTEGRADA,IN_SERVICO_INTERNET,IN_PARTICIPA_REDE_SOCIAL,IN_CATALOGO_ONLINE,QT_PERIODICO_ELETRONICO,QT_LIVRO_ELETRONICO,QT_DOC_TOTAL,QT_DOC_EXE,QT_DOC_EX_FEMI,QT_DOC_EX_MASC,QT_DOC_EX_SEM_GRAD,QT_DOC_EX_GRAD,QT_DOC_EX_ESP,QT_DOC_EX_MEST,QT_DOC_EX_DOUT,QT_DOC_EX_INT,QT_DOC_EX_INT_DE,QT_DOC_EX_INT_SEM_DE,QT_DOC_EX_PARC,QT_DOC_EX_HOR,QT_DOC_EX_0_29,QT_DOC_EX_30_34,QT_DOC_EX_35_39,QT_DOC_EX_40_44,QT_DOC_EX_45_49,QT_DOC_EX_50_54,QT_DOC_EX_55_59,QT_DOC_EX_60_MAIS,QT_DOC_EX_BRANCA,QT_DOC_EX_PRETA,QT_DOC_EX_PARDA,QT_DOC_EX_AMARELA,QT_DOC_EX_INDIGENA,QT_DOC_EX_COR_ND,QT_DOC_EX_BRA,QT_DOC_EX_EST,QT_DOC_EX_COM_DEFICIENCIA FROM	MICRODADOS_CADASTRO_IES_2016 WHERE SG_UF_IES = 'SP' UNION 
SELECT NU_ANO_CENSO,NO_REGIAO_IES,CO_REGIAO_IES,NO_UF_IES,SG_UF_IES,CO_UF_IES,NO_MUNICIPIO_IES,CO_MUNICIPIO_IES,IN_CAPITAL_IES,NO_MESORREGIAO_IES,CO_MESORREGIAO_IES,NO_MICRORREGIAO_IES,CO_MICRORREGIAO_IES,TP_ORGANIZACAO_ACADEMICA,TP_CATEGORIA_ADMINISTRATIVA,NO_MANTENEDORA,CO_MANTENEDORA,CO_IES,NO_IES,SG_IES,DS_ENDERECO_IES,DS_NUMERO_ENDERECO_IES,DS_COMPLEMENTO_ENDERECO_IES,NO_BAIRRO_IES,NU_CEP_IES,QT_TEC_TOTAL,QT_TEC_FUNDAMENTAL_INCOMP_FEM,QT_TEC_FUNDAMENTAL_INCOMP_MASC,QT_TEC_FUNDAMENTAL_COMP_FEM,QT_TEC_FUNDAMENTAL_COMP_MASC,QT_TEC_MEDIO_FEM,QT_TEC_MEDIO_MASC,QT_TEC_SUPERIOR_FEM,QT_TEC_SUPERIOR_MASC,QT_TEC_ESPECIALIZACAO_FEM,QT_TEC_ESPECIALIZACAO_MASC,QT_TEC_MESTRADO_FEM,QT_TEC_MESTRADO_MASC,QT_TEC_DOUTORADO_FEM,QT_TEC_DOUTORADO_MASC,IN_ACESSO_PORTAL_CAPES,IN_ACESSO_OUTRAS_BASES,IN_ASSINA_OUTRA_BASE,IN_REPOSITORIO_INSTITUCIONAL,IN_BUSCA_INTEGRADA,IN_SERVICO_INTERNET,IN_PARTICIPA_REDE_SOCIAL,IN_CATALOGO_ONLINE,QT_PERIODICO_ELETRONICO,QT_LIVRO_ELETRONICO,QT_DOC_TOTAL,QT_DOC_EXE,QT_DOC_EX_FEMI,QT_DOC_EX_MASC,QT_DOC_EX_SEM_GRAD,QT_DOC_EX_GRAD,QT_DOC_EX_ESP,QT_DOC_EX_MEST,QT_DOC_EX_DOUT,QT_DOC_EX_INT,QT_DOC_EX_INT_DE,QT_DOC_EX_INT_SEM_DE,QT_DOC_EX_PARC,QT_DOC_EX_HOR,QT_DOC_EX_0_29,QT_DOC_EX_30_34,QT_DOC_EX_35_39,QT_DOC_EX_40_44,QT_DOC_EX_45_49,QT_DOC_EX_50_54,QT_DOC_EX_55_59,QT_DOC_EX_60_MAIS,QT_DOC_EX_BRANCA,QT_DOC_EX_PRETA,QT_DOC_EX_PARDA,QT_DOC_EX_AMARELA,QT_DOC_EX_INDIGENA,QT_DOC_EX_COR_ND,QT_DOC_EX_BRA,QT_DOC_EX_EST,QT_DOC_EX_COM_DEFICIENCIA FROM	MICRODADOS_CADASTRO_IES_2017 WHERE SG_UF_IES = 'SP' UNION 
SELECT NU_ANO_CENSO,NO_REGIAO_IES,CO_REGIAO_IES,NO_UF_IES,SG_UF_IES,CO_UF_IES,NO_MUNICIPIO_IES,CO_MUNICIPIO_IES,IN_CAPITAL_IES,NO_MESORREGIAO_IES,CO_MESORREGIAO_IES,NO_MICRORREGIAO_IES,CO_MICRORREGIAO_IES,TP_ORGANIZACAO_ACADEMICA,TP_CATEGORIA_ADMINISTRATIVA,NO_MANTENEDORA,CO_MANTENEDORA,CO_IES,NO_IES,SG_IES,DS_ENDERECO_IES,DS_NUMERO_ENDERECO_IES,DS_COMPLEMENTO_ENDERECO_IES,NO_BAIRRO_IES,NU_CEP_IES,QT_TEC_TOTAL,QT_TEC_FUNDAMENTAL_INCOMP_FEM,QT_TEC_FUNDAMENTAL_INCOMP_MASC,QT_TEC_FUNDAMENTAL_COMP_FEM,QT_TEC_FUNDAMENTAL_COMP_MASC,QT_TEC_MEDIO_FEM,QT_TEC_MEDIO_MASC,QT_TEC_SUPERIOR_FEM,QT_TEC_SUPERIOR_MASC,QT_TEC_ESPECIALIZACAO_FEM,QT_TEC_ESPECIALIZACAO_MASC,QT_TEC_MESTRADO_FEM,QT_TEC_MESTRADO_MASC,QT_TEC_DOUTORADO_FEM,QT_TEC_DOUTORADO_MASC,IN_ACESSO_PORTAL_CAPES,IN_ACESSO_OUTRAS_BASES,IN_ASSINA_OUTRA_BASE,IN_REPOSITORIO_INSTITUCIONAL,IN_BUSCA_INTEGRADA,IN_SERVICO_INTERNET,IN_PARTICIPA_REDE_SOCIAL,IN_CATALOGO_ONLINE,QT_PERIODICO_ELETRONICO,QT_LIVRO_ELETRONICO,QT_DOC_TOTAL,QT_DOC_EXE,QT_DOC_EX_FEMI,QT_DOC_EX_MASC,QT_DOC_EX_SEM_GRAD,QT_DOC_EX_GRAD,QT_DOC_EX_ESP,QT_DOC_EX_MEST,QT_DOC_EX_DOUT,QT_DOC_EX_INT,QT_DOC_EX_INT_DE,QT_DOC_EX_INT_SEM_DE,QT_DOC_EX_PARC,QT_DOC_EX_HOR,QT_DOC_EX_0_29,QT_DOC_EX_30_34,QT_DOC_EX_35_39,QT_DOC_EX_40_44,QT_DOC_EX_45_49,QT_DOC_EX_50_54,QT_DOC_EX_55_59,QT_DOC_EX_60_MAIS,QT_DOC_EX_BRANCA,QT_DOC_EX_PRETA,QT_DOC_EX_PARDA,QT_DOC_EX_AMARELA,QT_DOC_EX_INDIGENA,QT_DOC_EX_COR_ND,QT_DOC_EX_BRA,QT_DOC_EX_EST,QT_DOC_EX_COM_DEFICIENCIA FROM	MICRODADOS_CADASTRO_IES_2018 WHERE SG_UF_IES = 'SP' UNION 
SELECT NU_ANO_CENSO,NO_REGIAO_IES,CO_REGIAO_IES,NO_UF_IES,SG_UF_IES,CO_UF_IES,NO_MUNICIPIO_IES,CO_MUNICIPIO_IES,IN_CAPITAL_IES,NO_MESORREGIAO_IES,CO_MESORREGIAO_IES,NO_MICRORREGIAO_IES,CO_MICRORREGIAO_IES,TP_ORGANIZACAO_ACADEMICA,TP_CATEGORIA_ADMINISTRATIVA,NO_MANTENEDORA,CO_MANTENEDORA,CO_IES,NO_IES,SG_IES,DS_ENDERECO_IES,DS_NUMERO_ENDERECO_IES,DS_COMPLEMENTO_ENDERECO_IES,NO_BAIRRO_IES,NU_CEP_IES,QT_TEC_TOTAL,QT_TEC_FUNDAMENTAL_INCOMP_FEM,QT_TEC_FUNDAMENTAL_INCOMP_MASC,QT_TEC_FUNDAMENTAL_COMP_FEM,QT_TEC_FUNDAMENTAL_COMP_MASC,QT_TEC_MEDIO_FEM,QT_TEC_MEDIO_MASC,QT_TEC_SUPERIOR_FEM,QT_TEC_SUPERIOR_MASC,QT_TEC_ESPECIALIZACAO_FEM,QT_TEC_ESPECIALIZACAO_MASC,QT_TEC_MESTRADO_FEM,QT_TEC_MESTRADO_MASC,QT_TEC_DOUTORADO_FEM,QT_TEC_DOUTORADO_MASC,IN_ACESSO_PORTAL_CAPES,IN_ACESSO_OUTRAS_BASES,IN_ASSINA_OUTRA_BASE,IN_REPOSITORIO_INSTITUCIONAL,IN_BUSCA_INTEGRADA,IN_SERVICO_INTERNET,IN_PARTICIPA_REDE_SOCIAL,IN_CATALOGO_ONLINE,QT_PERIODICO_ELETRONICO,QT_LIVRO_ELETRONICO,QT_DOC_TOTAL,QT_DOC_EXE,QT_DOC_EX_FEMI,QT_DOC_EX_MASC,QT_DOC_EX_SEM_GRAD,QT_DOC_EX_GRAD,QT_DOC_EX_ESP,QT_DOC_EX_MEST,QT_DOC_EX_DOUT,QT_DOC_EX_INT,QT_DOC_EX_INT_DE,QT_DOC_EX_INT_SEM_DE,QT_DOC_EX_PARC,QT_DOC_EX_HOR,QT_DOC_EX_0_29,QT_DOC_EX_30_34,QT_DOC_EX_35_39,QT_DOC_EX_40_44,QT_DOC_EX_45_49,QT_DOC_EX_50_54,QT_DOC_EX_55_59,QT_DOC_EX_60_MAIS,QT_DOC_EX_BRANCA,QT_DOC_EX_PRETA,QT_DOC_EX_PARDA,QT_DOC_EX_AMARELA,QT_DOC_EX_INDIGENA,QT_DOC_EX_COR_ND,QT_DOC_EX_BRA,QT_DOC_EX_EST,QT_DOC_EX_COM_DEFICIENCIA FROM	MICRODADOS_CADASTRO_IES_2019 WHERE SG_UF_IES = 'SP' UNION 
SELECT NU_ANO_CENSO,NO_REGIAO_IES,CO_REGIAO_IES,NO_UF_IES,SG_UF_IES,CO_UF_IES,NO_MUNICIPIO_IES,CO_MUNICIPIO_IES,IN_CAPITAL_IES,NO_MESORREGIAO_IES,CO_MESORREGIAO_IES,NO_MICRORREGIAO_IES,CO_MICRORREGIAO_IES,TP_ORGANIZACAO_ACADEMICA,TP_CATEGORIA_ADMINISTRATIVA,NO_MANTENEDORA,CO_MANTENEDORA,CO_IES,NO_IES,SG_IES,DS_ENDERECO_IES,DS_NUMERO_ENDERECO_IES,DS_COMPLEMENTO_ENDERECO_IES,NO_BAIRRO_IES,NU_CEP_IES,QT_TEC_TOTAL,QT_TEC_FUNDAMENTAL_INCOMP_FEM,QT_TEC_FUNDAMENTAL_INCOMP_MASC,QT_TEC_FUNDAMENTAL_COMP_FEM,QT_TEC_FUNDAMENTAL_COMP_MASC,QT_TEC_MEDIO_FEM,QT_TEC_MEDIO_MASC,QT_TEC_SUPERIOR_FEM,QT_TEC_SUPERIOR_MASC,QT_TEC_ESPECIALIZACAO_FEM,QT_TEC_ESPECIALIZACAO_MASC,QT_TEC_MESTRADO_FEM,QT_TEC_MESTRADO_MASC,QT_TEC_DOUTORADO_FEM,QT_TEC_DOUTORADO_MASC,IN_ACESSO_PORTAL_CAPES,IN_ACESSO_OUTRAS_BASES,IN_ASSINA_OUTRA_BASE,IN_REPOSITORIO_INSTITUCIONAL,IN_BUSCA_INTEGRADA,IN_SERVICO_INTERNET,IN_PARTICIPA_REDE_SOCIAL,IN_CATALOGO_ONLINE,QT_PERIODICO_ELETRONICO,QT_LIVRO_ELETRONICO,QT_DOC_TOTAL,QT_DOC_EXE,QT_DOC_EX_FEMI,QT_DOC_EX_MASC,QT_DOC_EX_SEM_GRAD,QT_DOC_EX_GRAD,QT_DOC_EX_ESP,QT_DOC_EX_MEST,QT_DOC_EX_DOUT,QT_DOC_EX_INT,QT_DOC_EX_INT_DE,QT_DOC_EX_INT_SEM_DE,QT_DOC_EX_PARC,QT_DOC_EX_HOR,QT_DOC_EX_0_29,QT_DOC_EX_30_34,QT_DOC_EX_35_39,QT_DOC_EX_40_44,QT_DOC_EX_45_49,QT_DOC_EX_50_54,QT_DOC_EX_55_59,QT_DOC_EX_60_MAIS,QT_DOC_EX_BRANCA,QT_DOC_EX_PRETA,QT_DOC_EX_PARDA,QT_DOC_EX_AMARELA,QT_DOC_EX_INDIGENA,QT_DOC_EX_COR_ND,QT_DOC_EX_BRA,QT_DOC_EX_EST,QT_DOC_EX_COM_DEFICIENCIA FROM	MICRODADOS_CADASTRO_IES_2020 WHERE SG_UF_IES = 'SP' UNION 
SELECT NU_ANO_CENSO,NO_REGIAO_IES,CO_REGIAO_IES,NO_UF_IES,SG_UF_IES,CO_UF_IES,NO_MUNICIPIO_IES,CO_MUNICIPIO_IES,IN_CAPITAL_IES,NO_MESORREGIAO_IES,CO_MESORREGIAO_IES,NO_MICRORREGIAO_IES,CO_MICRORREGIAO_IES,TP_ORGANIZACAO_ACADEMICA,TP_CATEGORIA_ADMINISTRATIVA,NO_MANTENEDORA,CO_MANTENEDORA,CO_IES,NO_IES,SG_IES,DS_ENDERECO_IES,DS_NUMERO_ENDERECO_IES,DS_COMPLEMENTO_ENDERECO_IES,NO_BAIRRO_IES,NU_CEP_IES,QT_TEC_TOTAL,QT_TEC_FUNDAMENTAL_INCOMP_FEM,QT_TEC_FUNDAMENTAL_INCOMP_MASC,QT_TEC_FUNDAMENTAL_COMP_FEM,QT_TEC_FUNDAMENTAL_COMP_MASC,QT_TEC_MEDIO_FEM,QT_TEC_MEDIO_MASC,QT_TEC_SUPERIOR_FEM,QT_TEC_SUPERIOR_MASC,QT_TEC_ESPECIALIZACAO_FEM,QT_TEC_ESPECIALIZACAO_MASC,QT_TEC_MESTRADO_FEM,QT_TEC_MESTRADO_MASC,QT_TEC_DOUTORADO_FEM,QT_TEC_DOUTORADO_MASC,IN_ACESSO_PORTAL_CAPES,IN_ACESSO_OUTRAS_BASES,IN_ASSINA_OUTRA_BASE,IN_REPOSITORIO_INSTITUCIONAL,IN_BUSCA_INTEGRADA,IN_SERVICO_INTERNET,IN_PARTICIPA_REDE_SOCIAL,IN_CATALOGO_ONLINE,QT_PERIODICO_ELETRONICO,QT_LIVRO_ELETRONICO,QT_DOC_TOTAL,QT_DOC_EXE,QT_DOC_EX_FEMI,QT_DOC_EX_MASC,QT_DOC_EX_SEM_GRAD,QT_DOC_EX_GRAD,QT_DOC_EX_ESP,QT_DOC_EX_MEST,QT_DOC_EX_DOUT,QT_DOC_EX_INT,QT_DOC_EX_INT_DE,QT_DOC_EX_INT_SEM_DE,QT_DOC_EX_PARC,QT_DOC_EX_HOR,QT_DOC_EX_0_29,QT_DOC_EX_30_34,QT_DOC_EX_35_39,QT_DOC_EX_40_44,QT_DOC_EX_45_49,QT_DOC_EX_50_54,QT_DOC_EX_55_59,QT_DOC_EX_60_MAIS,QT_DOC_EX_BRANCA,QT_DOC_EX_PRETA,QT_DOC_EX_PARDA,QT_DOC_EX_AMARELA,QT_DOC_EX_INDIGENA,QT_DOC_EX_COR_ND,QT_DOC_EX_BRA,QT_DOC_EX_EST,QT_DOC_EX_COM_DEFICIENCIA FROM	MICRODADOS_CADASTRO_IES_2021 WHERE SG_UF_IES = 'SP' 

CREATE CLUSTERED INDEX IXC_STG_MICRODADOS_CADASTRO_IES_SP ON STG.STG_MICRODADOS_CADASTRO_IES_SP(NU_ANO_CENSO, CO_IES)


SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME LIKE 'indicadores_trajetoria_educacao_superior%'

DROP TABLE IF EXISTS STG.STG_INDICADORES_TRAJETORIA_EDUCACAO_SUPERIOR_SP
select T.*,	1  CO_CATALOGO
		into STG.STG_INDICADORES_TRAJETORIA_EDUCACAO_SUPERIOR_SP
			from indicadores_trajetoria_educacao_superior_2011_2020 t inner join stg.STG_MICRODADOS_CADASTRO_IES_SP ies on ies.co_ies = t.[Código_da_Instituição] union
select T.*, 2 from indicadores_trajetoria_educacao_superior_2012_2021 t inner join stg.STG_MICRODADOS_CADASTRO_IES_SP ies on ies.co_ies = t.[Código_da_Instituição] union
select T.*, 3 from indicadores_trajetoria_educacao_superior_2013_2021 t inner join stg.STG_MICRODADOS_CADASTRO_IES_SP ies on ies.co_ies = t.[Código_da_Instituição] union
select T.*, 4 from indicadores_trajetoria_educacao_superior_2014_2021 t inner join stg.STG_MICRODADOS_CADASTRO_IES_SP ies on ies.co_ies = t.[Código_da_Instituição] union
select T.*, 5 from indicadores_trajetoria_educacao_superior_2015_2021 t inner join stg.STG_MICRODADOS_CADASTRO_IES_SP ies on ies.co_ies = t.[Código_da_Instituição] union
select T.*, 6 from indicadores_trajetoria_educacao_superior_2016_2021 t inner join stg.STG_MICRODADOS_CADASTRO_IES_SP ies on ies.co_ies = t.[Código_da_Instituição] union
select T.*, 7 from indicadores_trajetoria_educacao_superior_2017_2021 t inner join stg.STG_MICRODADOS_CADASTRO_IES_SP ies on ies.co_ies = t.[Código_da_Instituição]

CREATE CLUSTERED INDEX IXC_STG_INDICADORES_TRAJETORIA_EDUCACAO_SUPERIOR_SP ON [stg].[STG_INDICADORES_TRAJETORIA_EDUCACAO_SUPERIOR_SP](Código_da_Instituição, Código_do_Curso_de_Graduação, Código_do_Município_do_Curso)
select * from [stg].[STG_MICRODADOS_CADASTRO_IES_SP]
select * from [stg].[STG_MICRODADOS_CADASTRO_CURSOS_SP]
select * from [stg].[STG_INDICADORES_TRAJETORIA_EDUCACAO_SUPERIOR_SP]


----------------------------------------------------------------------------------------

-- LOGICA DE CRIAÇÃO DAS TABELAS 
-- 1 - DROPAR TABELA SE EXISTIR 
-- 2 - CRIAR TABELA A PARTIR DE SELECT DISTINCT (SELECT INTO)
-- 3 - ALTERAR COLUNA DE CODIGO PARA NOT NULL 
-- 4 - CRIAR CHAVE PRIMARIA NA TABELA 


--- HIERARQUIA DE REGIÃO - REGIÃO -> UF -> MESORREGIAO -> _MICRORREGIAO -> MUNICIPIO
--- OBS.: TABELAS CRIADAS INICIALMENTE SEM PK E FK

-- TABELAS COM DADOS DE TODAS OS ESTADOS 
DROP TABLE IF EXISTS ODS.ODS_REGIAO_IES
SELECT DISTINCT CO_REGIAO_IES, NO_REGIAO_IES INTO ODS.ODS_REGIAO_IES
FROM 	MICRODADOS_CADASTRO_IES_2010   UNION 
SELECT CO_REGIAO_IES, NO_REGIAO_IES FROM	MICRODADOS_CADASTRO_IES_2011 UNION 
SELECT CO_REGIAO_IES, NO_REGIAO_IES FROM	MICRODADOS_CADASTRO_IES_2012 UNION 
SELECT CO_REGIAO_IES, NO_REGIAO_IES FROM	MICRODADOS_CADASTRO_IES_2013 UNION 
SELECT CO_REGIAO_IES, NO_REGIAO_IES FROM	MICRODADOS_CADASTRO_IES_2014 UNION 
SELECT CO_REGIAO_IES, NO_REGIAO_IES FROM	MICRODADOS_CADASTRO_IES_2015 UNION 
SELECT CO_REGIAO_IES, NO_REGIAO_IES FROM	MICRODADOS_CADASTRO_IES_2016 UNION 
SELECT CO_REGIAO_IES, NO_REGIAO_IES FROM	MICRODADOS_CADASTRO_IES_2017 UNION 
SELECT CO_REGIAO_IES, NO_REGIAO_IES FROM	MICRODADOS_CADASTRO_IES_2018 UNION 
SELECT CO_REGIAO_IES, NO_REGIAO_IES FROM	MICRODADOS_CADASTRO_IES_2019 UNION 
SELECT CO_REGIAO_IES, NO_REGIAO_IES FROM	MICRODADOS_CADASTRO_IES_2020 UNION 
SELECT CO_REGIAO_IES, NO_REGIAO_IES FROM	MICRODADOS_CADASTRO_IES_2021 

CREATE CLUSTERED INDEX IXC_ODS_REGIAO_IES ON ODS.ODS_REGIAO_IES (CO_REGIAO_IES)


DROP TABLE IF EXISTS ODS.ODS_UNIDADE_FEDERATIVA
SELECT DISTINCT CO_UF_IES, NO_UF_IES,SG_UF_IES
INTO ODS.ODS_UNIDADE_FEDERATIVA
FROM 	MICRODADOS_CADASTRO_IES_2010   UNION 
SELECT CO_UF_IES, NO_UF_IES,SG_UF_IES FROM	MICRODADOS_CADASTRO_IES_2011 UNION 
SELECT CO_UF_IES, NO_UF_IES,SG_UF_IES FROM	MICRODADOS_CADASTRO_IES_2012 UNION 
SELECT CO_UF_IES, NO_UF_IES,SG_UF_IES FROM	MICRODADOS_CADASTRO_IES_2013 UNION 
SELECT CO_UF_IES, NO_UF_IES,SG_UF_IES FROM	MICRODADOS_CADASTRO_IES_2014 UNION 
SELECT CO_UF_IES, NO_UF_IES,SG_UF_IES FROM	MICRODADOS_CADASTRO_IES_2015 UNION 
SELECT CO_UF_IES, NO_UF_IES,SG_UF_IES FROM	MICRODADOS_CADASTRO_IES_2016 UNION 
SELECT CO_UF_IES, NO_UF_IES,SG_UF_IES FROM	MICRODADOS_CADASTRO_IES_2017 UNION 
SELECT CO_UF_IES, NO_UF_IES,SG_UF_IES FROM	MICRODADOS_CADASTRO_IES_2018 UNION 
SELECT CO_UF_IES, NO_UF_IES,SG_UF_IES FROM	MICRODADOS_CADASTRO_IES_2019 UNION 
SELECT CO_UF_IES, NO_UF_IES,SG_UF_IES FROM	MICRODADOS_CADASTRO_IES_2020 UNION 
SELECT CO_UF_IES, NO_UF_IES,SG_UF_IES FROM	MICRODADOS_CADASTRO_IES_2021 

ALTER TABLE ODS.ODS_UNIDADE_FEDERATIVA ALTER COLUMN CO_UF_IES SMALLINT NOT NULL
ALTER TABLE ODS.ODS_UNIDADE_FEDERATIVA ADD CONSTRAINT PK_ODS_UNIDADE_FEDERATIVA  PRIMARY KEY (CO_UF)
ALTER TABLE ODS.ODS_UNIDADE_FEDERATIVA ALTER COLUMN NO_UF_IES VARCHAR(30) 
ALTER TABLE ODS.ODS_UNIDADE_FEDERATIVA ALTER COLUMN SG_UF_IES CHAR(2) 

-----------------------------------------------------------------------------------------------

-- -- TABELAS COM DADOS DE REGIÃO SOMENTE DO ESTADO DE SP
/*
DROP TABLE IF EXISTS  ODS.ODS_MESORREGIAO_IES
SELECT DISTINCT CO_MESORREGIAO_IES, NO_MESORREGIAO_IES
INTO ODS.ODS_MESORREGIAO_IES
	FROM STG.[STG_MICRODADOS_CADASTRO_IES_SP]
ALTER TABLE ODS.ODS_MESORREGIAO_IES ALTER COLUMN CO_MESORREGIAO_IES INT NOT NULL
ALTER TABLE ODS.ODS_MESORREGIAO_IES ADD CONSTRAINT PK_ODS_MESORREGIAO_IES  PRIMARY KEY (CO_MESORREGIAO_IES)


DROP TABLE IF EXISTS ODS.ODS_MICRORREGIAO_IES
SELECT DISTINCT CO_MICRORREGIAO_IES, NO_MICRORREGIAO_IES, CO_MESORREGIAO_IES, CO_UF_IES
 INTO ODS.ODS_MICRORREGIAO_IES
	FROM STG.[STG_MICRODADOS_CADASTRO_IES_SP]
ALTER TABLE ODS.ODS_MICRORREGIAO_IES ALTER COLUMN CO_MICRORREGIAO_IES INT NOT NULL
ALTER TABLE ODS.ODS_MICRORREGIAO_IES ADD CONSTRAINT PK_ODS_MICRORREGIAO_IES  PRIMARY KEY (CO_MICRORREGIAO_IES)

DROP TABLE IF EXISTS  ODS.ODS_MUNICIPIO_IES
SELECT DISTINCT CO_MUNICIPIO_IES, NO_MUNICIPIO_IES,CO_MESORREGIAO_IES
INTO ODS.ODS_MUNICIPIO_IES
	FROM STG.[STG_MICRODADOS_CADASTRO_IES_SP]
ALTER TABLE ODS.ODS_MUNICIPIO_IES ALTER COLUMN CO_MUNICIPIO_IES INT NOT NULL
ALTER TABLE ODS.ODS_MUNICIPIO_IES ADD CONSTRAINT PK_ODS_MUNICIPIO_IES  PRIMARY KEY (CO_MUNICIPIO_IES)



DROP TABLE IF EXISTS  ODS.ODS_MUNICIPIO
SELECT DISTINCT 
	Código_Município_Completo	CO_MUNICIPIO,
	Nome_Município NO_MUNICIPIO,
	Mesorregião_Geográfica CO_MESORREGIAO_IES
INTO ODS.ODS_MUNICIPIO
	FROM [RELATORIO_DTB_BRASIL_DISTRITO]
	where uf = 35 /*São Paulo*/



select * from ODS.ODS_MESORREGIAO_IES
SELECT distinct 
      [Mesorregião_Geográfica]
      ,[Nome_Mesorregião]     
  FROM [tcc_evasao].[dbo].[RELATORIO_DTB_BRASIL_DISTRITO]
  where uf = 35

  select co_microrregiao_ies, no_microrregiao_ies from ODS.ODS_MICRORREGIAO_IES
  except 
SELECT distinct 
      [Microrregião_Geográfica]
      ,[Nome_Microrregião]
	  ,[Mesorregião_Geográfica]
  FROM [tcc_evasao].[dbo].[RELATORIO_DTB_BRASIL_DISTRITO]
  where uf = 35


 SELECT distinct 
      [Microrregião_Geográfica]
      ,[Nome_Microrregião]
  FROM [tcc_evasao].[dbo].[RELATORIO_DTB_BRASIL_DISTRITO]
  where uf = 35
  except 
  select co_microrregiao_ies, no_microrregiao_ies from ODS.ODS_MICRORREGIAO_IES
*/

 DROP TABLE IF EXISTS  ODS.ODS_MESORREGIAO
  SELECT distinct
       [Mesorregião_Geográfica]		CO_MESORREGIAO
      ,[Nome_Mesorregião]			NO_MESORREGIAO
		, [UF]						CO_UF
		 INTO ODS.ODS_MESORREGIAO

  FROM [tcc_evasao].[dbo].[RELATORIO_DTB_BRASIL_DISTRITO]
  where uf = 35
  /* -- SEM DUPLICIDADE
  SELECT COUNT(1), CO_MESORREGIAO
  FROM ODS.ODS_MESORREGIAO
  GROUP BY CO_MESORREGIAO
  HAVING COUNT(1) > 1
  */


  /*
	 https://www.ibge.gov.br/geociencias/organizacao-do-territorio/divisao-regional/23701-divisao-territorial-brasileira.html?=&t=downloads
  */
DROP TABLE IF EXISTS ODS.ODS_MICRORREGIAO
SELECT DISTINCT 
       [Microrregião_Geográfica]	CO_MICRORREGIAO
      ,[Nome_Microrregião]			NO_MICRORREGIAO
	  ,[Mesorregião_Geográfica]		CO_MESORREGIAO
      INTO ODS.ODS_MICRORREGIAO

  FROM [tcc_evasao].[dbo].[RELATORIO_DTB_BRASIL_DISTRITO]
  where uf = 35
  
  /* -- SEM DUPLICIDADE
  SELECT COUNT(1), CO_MICRORREGIAO
  FROM ODS.ODS_MICRORREGIAO
  GROUP BY CO_MICRORREGIAO
  HAVING COUNT(1) > 1
  */


  DROP TABLE IF EXISTS  ODS.ODS_MUNICIPIO
  SELECT DISTINCT 
		 [Código_Município_Completo]	CO_MUNICIPIO
		,[Nome_Município]				NO_MUNICIPIO
		,[Microrregião_Geográfica]		CO_MICRORREGIAO
		INTO ODS.ODS_MUNICIPIO
  FROM [tcc_evasao].[dbo].[RELATORIO_DTB_BRASIL_DISTRITO]
  WHERE UF = 35
  ALTER TABLE ODS.ODS_MUNICIPIO ALTER COLUMN CO_MUNICIPIO INT NOT NULL
  ALTER TABLE ODS.ODS_MUNICIPIO ADD CONSTRAINT PK_ODS_MUNICIPIO PRIMARY KEY(CO_MUNICIPIO)

    /* -- SEM DUPLICIDADE
  SELECT COUNT(1), CO_MUNICIPIO
  FROM ODS.ODS_MUNICIPIO
  GROUP BY CO_MUNICIPIO
  HAVING COUNT(1) > 1
  */
------------------------------------------------------------------------------------------
-- INSTITUIÇÃO MANTENEDORA DA IES

-- TABELA AUXILIAR PARA PEGAR TODAS AS VERSÕES DE NOMENCLATURA DA MANTENEDORA AO LONGO DOS ANOS
DROP TABLE IF EXISTS #ODS_MANTENEDORA_IES
SELECT DISTINCT CO_MANTENEDORA,NO_MANTENEDORA, NU_ANO_CENSO 
INTO #ODS_MANTENEDORA_IES
	FROM STG.[STG_MICRODADOS_CADASTRO_IES_SP]

-- SALVA NA TABELA NOME DA MANTENEDORA DO ULTIMO CENSO EM QUE APARECEU
DROP TABLE IF EXISTS ODS.ODS_MANTENEDORA_IES
SELECT	IES.CO_MANTENEDORA, 
		IES.NO_MANTENEDORA, 
		IES.NU_ANO_CENSO
INTO ODS.ODS_MANTENEDORA_IES
	FROM #ODS_MANTENEDORA_IES IES
	INNER JOIN (
		select CO_MANTENEDORA, MAX(NU_ANO_CENSO)NU_ANO_CENSO FROM  
			#ODS_MANTENEDORA_IES
			GROUP BY CO_MANTENEDORA
		) MX ON IES.CO_MANTENEDORA = MX.CO_MANTENEDORA AND 
				IES.NU_ANO_CENSO = MX.NU_ANO_CENSO
    /* -- SEM DUPLICIDADE
  SELECT COUNT(1), CO_MANTENEDORA
  FROM ODS.ODS_MANTENEDORA_IES
  GROUP BY CO_MANTENEDORA
  HAVING COUNT(1) > 1
  */

  create clustered index ixc_ODS_MANTENEDORA_IES ON ODS.ODS_MANTENEDORA_IES (CO_MANTENEDORA)

DROP TABLE IF EXISTS #ODS_IES
SELECT DISTINCT
 CO_IES
, NO_IES
, SG_IES
, NU_ANO_CENSO
, CO_MUNICIPIO_IES
, IN_CAPITAL_IES
, TP_ORGANIZACAO_ACADEMICA
, TP_CATEGORIA_ADMINISTRATIVA
, CO_MANTENEDORA
, DS_ENDERECO_IES
, DS_NUMERO_ENDERECO_IES
, DS_COMPLEMENTO_ENDERECO_IES
, NO_BAIRRO_IES
, NU_CEP_IES
INTO #ODS_IES
	FROM STG.[STG_MICRODADOS_CADASTRO_IES_SP]


/*  --112 IES em cursos que não existem 
SELECT 
	co_ies
 FROM [stg].[STG_MICRODADOS_CADASTRO_CURSOS_SP]
except 
SELECT 
 CO_IES
 	FROM STG.[STG_MICRODADOS_CADASTRO_IES_SP]
*/

CREATE CLUSTERED INDEX IXC_TMP_ODS_IES ON #ODS_IES (CO_IES, NU_ANO_CENSO)

DROP TABLE IF EXISTS ODS.ODS_IES
SELECT 
	IES.CO_IES
,	IES.NO_IES
,	IES.SG_IES
,	IES.NU_ANO_CENSO
,	IES.CO_MUNICIPIO_IES
,	IES.IN_CAPITAL_IES
,	IES.TP_ORGANIZACAO_ACADEMICA
,	IES.TP_CATEGORIA_ADMINISTRATIVA
,	IES.CO_MANTENEDORA
,	IES.DS_ENDERECO_IES
,	IES.DS_NUMERO_ENDERECO_IES
,	IES.DS_COMPLEMENTO_ENDERECO_IES
,	IES.NO_BAIRRO_IES
,	IES.NU_CEP_IES
INTO ODS.ODS_IES
FROM STG.[STG_MICRODADOS_CADASTRO_IES_SP]	IES
	INNER JOIN 
	(SELECT CO_IES, MAX(NU_ANO_CENSO) NU_ANO_CENSO
		FROM #ODS_IES
		GROUP BY CO_IES
		) MX
	ON IES.CO_IES = MX.CO_IES AND 
		IES.NU_ANO_CENSO = MX.NU_ANO_CENSO

/* -- SEM DUPLICIDADE
  SELECT COUNT(1), CO_IES
  FROM ODS.ODS_IES
  GROUP BY CO_IES
  HAVING COUNT(1) > 1
*/
 
ALTER TABLE ODS.ODS_IES ADD NO_CATEGORIA_ADMINISTRATIVA AS  
	CASE 
		WHEN TP_CATEGORIA_ADMINISTRATIVA = 1 THEN 'Pública Federal'
		WHEN TP_CATEGORIA_ADMINISTRATIVA = 2 THEN 'Pública Estadual'
		WHEN TP_CATEGORIA_ADMINISTRATIVA = 3 THEN 'Pública Municipal'
		WHEN TP_CATEGORIA_ADMINISTRATIVA = 4 THEN 'Privada com fins lucrativos'
		WHEN TP_CATEGORIA_ADMINISTRATIVA = 5 THEN 'Privada sem fins lucrativos'
		WHEN TP_CATEGORIA_ADMINISTRATIVA = 7 THEN 'Especial'
		WHEN TP_CATEGORIA_ADMINISTRATIVA = 8 THEN 'Privada comunitária'
		WHEN TP_CATEGORIA_ADMINISTRATIVA = 9 THEN 'Privada confessional'
	END 

alter table ODS.ODS_IES  add NO_ORGANIZACAO_ACADEMICA AS 
	CASE 
		WHEN TP_ORGANIZACAO_ACADEMICA = 1 THEN 'Universidade'
		WHEN TP_ORGANIZACAO_ACADEMICA = 2 THEN 'Centro Universitário'
		WHEN TP_ORGANIZACAO_ACADEMICA = 3 THEN 'Faculdade'
		WHEN TP_ORGANIZACAO_ACADEMICA = 4 THEN 'Instituto Federal de Educação, Ciência e Tecnologia'
		WHEN TP_ORGANIZACAO_ACADEMICA = 5 THEN 'Centro Federal de Educação Tecnológica'
	END 

----------------------------------------------------------------------------------------------
--- ODS_CINE 

DROP TABLE IF EXISTS ODS.ODS_CINE_ROTULO
SELECT REPLACE(CO_CINE_ROTULO, '"','') CO_CINE_ROTULO, NO_CINE_ROTULO, CO_CINE_AREA_DETALHADA INTO ODS.ODS_CINE_ROTULO FROM [MICRODADOS_CADASTRO_CURSOS_2010]  UNION
SELECT REPLACE(CO_CINE_ROTULO, '"','') CO_CINE_ROTULO, NO_CINE_ROTULO, CO_CINE_AREA_DETALHADA FROM [MICRODADOS_CADASTRO_CURSOS_2011]  UNION
SELECT REPLACE(CO_CINE_ROTULO, '"','') CO_CINE_ROTULO, NO_CINE_ROTULO, CO_CINE_AREA_DETALHADA FROM [MICRODADOS_CADASTRO_CURSOS_2012]  UNION
SELECT REPLACE(CO_CINE_ROTULO, '"','') CO_CINE_ROTULO, NO_CINE_ROTULO, CO_CINE_AREA_DETALHADA FROM [MICRODADOS_CADASTRO_CURSOS_2013]  UNION
SELECT REPLACE(CO_CINE_ROTULO, '"','') CO_CINE_ROTULO, NO_CINE_ROTULO, CO_CINE_AREA_DETALHADA FROM [MICRODADOS_CADASTRO_CURSOS_2014]  UNION
SELECT REPLACE(CO_CINE_ROTULO, '"','') CO_CINE_ROTULO, NO_CINE_ROTULO, CO_CINE_AREA_DETALHADA FROM [MICRODADOS_CADASTRO_CURSOS_2015]  UNION
SELECT REPLACE(CO_CINE_ROTULO, '"','') CO_CINE_ROTULO, NO_CINE_ROTULO, CO_CINE_AREA_DETALHADA FROM [MICRODADOS_CADASTRO_CURSOS_2016]  UNION
SELECT REPLACE(CO_CINE_ROTULO, '"','') CO_CINE_ROTULO, NO_CINE_ROTULO, CO_CINE_AREA_DETALHADA FROM [MICRODADOS_CADASTRO_CURSOS_2017]  UNION
SELECT REPLACE(CO_CINE_ROTULO, '"','') CO_CINE_ROTULO, NO_CINE_ROTULO, CO_CINE_AREA_DETALHADA FROM [MICRODADOS_CADASTRO_CURSOS_2018]  UNION
SELECT REPLACE(CO_CINE_ROTULO, '"','') CO_CINE_ROTULO, NO_CINE_ROTULO, CO_CINE_AREA_DETALHADA FROM [MICRODADOS_CADASTRO_CURSOS_2019]  UNION
SELECT REPLACE(CO_CINE_ROTULO, '"','') CO_CINE_ROTULO, NO_CINE_ROTULO, CO_CINE_AREA_DETALHADA FROM [MICRODADOS_CADASTRO_CURSOS_2020]  UNION
SELECT REPLACE(CO_CINE_ROTULO, '"','') CO_CINE_ROTULO, NO_CINE_ROTULO, CO_CINE_AREA_DETALHADA FROM [MICRODADOS_CADASTRO_CURSOS_2021] 


/* SEM DUPLICIDADE
SELECT COUNT(1), CO_CINE_ROTULO
FROM ODS.ODS_CINE_ROTULO
GROUP BY CO_CINE_ROTULO
HAVING COUNT(1) > 1
*/


DROP TABLE IF EXISTS ODS.ODS_CINE_AREA_DETALHADA

SELECT CO_CINE_AREA_DETALHADA, NO_CINE_AREA_DETALHADA, CO_CINE_AREA_ESPECIFICA INTO ODS.ODS_CINE_AREA_DETALHADA FROM [MICRODADOS_CADASTRO_CURSOS_2010]  UNION
SELECT CO_CINE_AREA_DETALHADA, NO_CINE_AREA_DETALHADA, CO_CINE_AREA_ESPECIFICA FROM [MICRODADOS_CADASTRO_CURSOS_2011]  UNION
SELECT CO_CINE_AREA_DETALHADA, NO_CINE_AREA_DETALHADA, CO_CINE_AREA_ESPECIFICA FROM [MICRODADOS_CADASTRO_CURSOS_2012]  UNION
SELECT CO_CINE_AREA_DETALHADA, NO_CINE_AREA_DETALHADA, CO_CINE_AREA_ESPECIFICA FROM [MICRODADOS_CADASTRO_CURSOS_2013]  UNION
SELECT CO_CINE_AREA_DETALHADA, NO_CINE_AREA_DETALHADA, CO_CINE_AREA_ESPECIFICA FROM [MICRODADOS_CADASTRO_CURSOS_2014]  UNION
SELECT CO_CINE_AREA_DETALHADA, NO_CINE_AREA_DETALHADA, CO_CINE_AREA_ESPECIFICA FROM [MICRODADOS_CADASTRO_CURSOS_2015]  UNION
SELECT CO_CINE_AREA_DETALHADA, NO_CINE_AREA_DETALHADA, CO_CINE_AREA_ESPECIFICA FROM [MICRODADOS_CADASTRO_CURSOS_2016]  UNION
SELECT CO_CINE_AREA_DETALHADA, NO_CINE_AREA_DETALHADA, CO_CINE_AREA_ESPECIFICA FROM [MICRODADOS_CADASTRO_CURSOS_2017]  UNION
SELECT CO_CINE_AREA_DETALHADA, NO_CINE_AREA_DETALHADA, CO_CINE_AREA_ESPECIFICA FROM [MICRODADOS_CADASTRO_CURSOS_2018]  UNION
SELECT CO_CINE_AREA_DETALHADA, NO_CINE_AREA_DETALHADA, CO_CINE_AREA_ESPECIFICA FROM [MICRODADOS_CADASTRO_CURSOS_2019]  UNION
SELECT CO_CINE_AREA_DETALHADA, NO_CINE_AREA_DETALHADA, CO_CINE_AREA_ESPECIFICA FROM [MICRODADOS_CADASTRO_CURSOS_2020]  UNION
SELECT CO_CINE_AREA_DETALHADA, NO_CINE_AREA_DETALHADA, CO_CINE_AREA_ESPECIFICA FROM [MICRODADOS_CADASTRO_CURSOS_2021] 

/* -- SEM DUPLICIDADE
SELECT COUNT(1), CO_CINE_AREA_DETALHADA FROM ODS.ODS_CINE_AREA_DETALHADA
GROUP BY CO_CINE_AREA_DETALHADA
HAVING COUNT(1)> 1
*/

DROP TABLE IF EXISTS ODS.ODS_CINE_AREA_ESPECIFICA
SELECT CO_CINE_AREA_ESPECIFICA, NO_CINE_AREA_ESPECIFICA, CO_CINE_AREA_GERAL INTO ODS.ODS_CINE_AREA_ESPECIFICA FROM [MICRODADOS_CADASTRO_CURSOS_2010]  UNION
SELECT CO_CINE_AREA_ESPECIFICA, NO_CINE_AREA_ESPECIFICA, CO_CINE_AREA_GERAL FROM [MICRODADOS_CADASTRO_CURSOS_2011]  UNION
SELECT CO_CINE_AREA_ESPECIFICA, NO_CINE_AREA_ESPECIFICA, CO_CINE_AREA_GERAL FROM [MICRODADOS_CADASTRO_CURSOS_2012]  UNION
SELECT CO_CINE_AREA_ESPECIFICA, NO_CINE_AREA_ESPECIFICA, CO_CINE_AREA_GERAL FROM [MICRODADOS_CADASTRO_CURSOS_2013]  UNION
SELECT CO_CINE_AREA_ESPECIFICA, NO_CINE_AREA_ESPECIFICA, CO_CINE_AREA_GERAL FROM [MICRODADOS_CADASTRO_CURSOS_2014]  UNION
SELECT CO_CINE_AREA_ESPECIFICA, NO_CINE_AREA_ESPECIFICA, CO_CINE_AREA_GERAL FROM [MICRODADOS_CADASTRO_CURSOS_2015]  UNION
SELECT CO_CINE_AREA_ESPECIFICA, NO_CINE_AREA_ESPECIFICA, CO_CINE_AREA_GERAL FROM [MICRODADOS_CADASTRO_CURSOS_2016]  UNION
SELECT CO_CINE_AREA_ESPECIFICA, NO_CINE_AREA_ESPECIFICA, CO_CINE_AREA_GERAL FROM [MICRODADOS_CADASTRO_CURSOS_2017]  UNION
SELECT CO_CINE_AREA_ESPECIFICA, NO_CINE_AREA_ESPECIFICA, CO_CINE_AREA_GERAL FROM [MICRODADOS_CADASTRO_CURSOS_2018]  UNION
SELECT CO_CINE_AREA_ESPECIFICA, NO_CINE_AREA_ESPECIFICA, CO_CINE_AREA_GERAL FROM [MICRODADOS_CADASTRO_CURSOS_2019]  UNION
SELECT CO_CINE_AREA_ESPECIFICA, NO_CINE_AREA_ESPECIFICA, CO_CINE_AREA_GERAL FROM [MICRODADOS_CADASTRO_CURSOS_2020]  UNION
SELECT CO_CINE_AREA_ESPECIFICA, NO_CINE_AREA_ESPECIFICA, CO_CINE_AREA_GERAL FROM [MICRODADOS_CADASTRO_CURSOS_2021] 

/* -- SEM DUPLICIDADE
SELECT COUNT(1), CO_CINE_AREA_ESPECIFICA
FROM ODS.ODS_CINE_AREA_ESPECIFICA
GROUP BY CO_CINE_AREA_ESPECIFICA
HAVING COUNT(1)> 1
*/



DROP TABLE IF EXISTS ODS.ODS_CINE_AREA_GERAL
SELECT CO_CINE_AREA_GERAL , NO_CINE_AREA_GERAL INTO ODS.ODS_CINE_AREA_GERAL FROM [MICRODADOS_CADASTRO_CURSOS_2010]  UNION
SELECT CO_CINE_AREA_GERAL , NO_CINE_AREA_GERAL FROM [MICRODADOS_CADASTRO_CURSOS_2011]  UNION
SELECT CO_CINE_AREA_GERAL , NO_CINE_AREA_GERAL FROM [MICRODADOS_CADASTRO_CURSOS_2012]  UNION
SELECT CO_CINE_AREA_GERAL , NO_CINE_AREA_GERAL FROM [MICRODADOS_CADASTRO_CURSOS_2013]  UNION
SELECT CO_CINE_AREA_GERAL , NO_CINE_AREA_GERAL FROM [MICRODADOS_CADASTRO_CURSOS_2014]  UNION
SELECT CO_CINE_AREA_GERAL , NO_CINE_AREA_GERAL FROM [MICRODADOS_CADASTRO_CURSOS_2015]  UNION
SELECT CO_CINE_AREA_GERAL , NO_CINE_AREA_GERAL FROM [MICRODADOS_CADASTRO_CURSOS_2016]  UNION
SELECT CO_CINE_AREA_GERAL , NO_CINE_AREA_GERAL FROM [MICRODADOS_CADASTRO_CURSOS_2017]  UNION
SELECT CO_CINE_AREA_GERAL , NO_CINE_AREA_GERAL FROM [MICRODADOS_CADASTRO_CURSOS_2018]  UNION
SELECT CO_CINE_AREA_GERAL , NO_CINE_AREA_GERAL FROM [MICRODADOS_CADASTRO_CURSOS_2019]  UNION
SELECT CO_CINE_AREA_GERAL , NO_CINE_AREA_GERAL FROM [MICRODADOS_CADASTRO_CURSOS_2020]  UNION
SELECT CO_CINE_AREA_GERAL , NO_CINE_AREA_GERAL FROM [MICRODADOS_CADASTRO_CURSOS_2021] 

/* -- SEM DUPLICIDADE
SELECT COUNT(1), CO_CINE_AREA_GERAL
FROM ODS.ODS_CINE_AREA_GERAL
GROUP BY CO_CINE_AREA_GERAL
HAVING COUNT(1)> 1
*/



SELECT DISTINCT
  CO_CURSO
 , NO_CURSO
 --, REPLACE (CO_CINE_ROTULO, '"', '')CO_CINE_ROTULO
 --, TP_GRAU_ACADEMICO
 --, TP_NIVEL_ACADEMICO
FROM [stg].[STG_MICRODADOS_CADASTRO_CURSOS_SP]
ORDER BY 2
SELECT * FROM [stg].[STG_MICRODADOS_CADASTRO_CURSOS_SP]
WHERE CO_CURSO = 5001026


SELECT   CO_CURSO
 , NO_CURSO, 
 CO_CINE_ROTULO
 FROM [stg].[STG_MICRODADOS_CADASTRO_CURSOS_SP]
where no_curso like 'Ciência%d%Computação'

select * from [stg].[STG_MICRODADOS_CADASTRO_CURSOS_SP]
where co_curso = 48503
order by nu_ano_censo

SELECT   DISTINCT 
		NO_CURSO,
		 CO_CINE_ROTULO, 
		 NO_CINE_ROTULO
 FROM [stg].[STG_MICRODADOS_CADASTRO_CURSOS_SP]

SELECT * FROM ODS.ODS_CINE_ROTULO WHERE CO_CINE_ROTULO = '0614C01'

select * from ods.ods_curso where no_curso like 'Ciência%d%Computação'



drop table if exists #ODS_CURSO
SELECT DISTINCT
   NU_ANO_CENSO
 , CO_CURSO
 , NO_CURSO
 , CO_MUNICIPIO
 , IN_CAPITAL
 , TP_DIMENSAO
 , TP_REDE
 , CO_IES
 , REPLACE (CO_CINE_ROTULO, '"', '')CO_CINE_ROTULO
 , TP_GRAU_ACADEMICO
 , IN_GRATUITO
 , TP_MODALIDADE_ENSINO
 , TP_NIVEL_ACADEMICO
 INTO #ods_curso
FROM [stg].[STG_MICRODADOS_CADASTRO_CURSOS_SP] nolock
CREATE CLUSTERED INDEX IXC_ODS_CURSO ON #ODS_CURSO(CO_CURSO, CO_MUNICIPIO, CO_IES, NU_ANO_CENSO)

DROP TABLE IF EXISTS ODS.ODS_CURSO
SELECT DISTINCT  
    C.CO_CURSO
,	TRIM(UPPER(C.NO_CURSO))NO_CURSO
--,    C.CO_IES
,    C.CO_CINE_ROTULO
--,	C.CO_MUNICIPIO
INTO ODS.ODS_CURSO
FROM #ODS_CURSO C

INNER JOIN (SELECT CO_CURSO, /*CO_IES*/ MAX(NU_ANO_CENSO) NU_ANO_CENSO
				FROM #ODS_CURSO
				GROUP BY CO_CURSO--, CO_IES
)MX ON 
		C.CO_CURSO		=	MX.CO_CURSO		AND 
		-- C.CO_MUNICIPIO	=	MX.CO_MUNICIPIO	AND 
		-- C.CO_IES		=	MX.CO_IES		AND
	 	C.NU_ANO_CENSO	=	MX.NU_ANO_CENSO

CREATE CLUSTERED INDEX IXC_ODS_CURSO ON ODS.ODS_CURSO (CO_CURSO)--, CO_IES)
/*

SELECT COUNT(1), CO_CURSO, CO_MUNICIPIO, TP_DIMENSAO
FROM #ods_curso
GROUP BY CO_CURSO, CO_MUNICIPIO, TP_DIMENSAO
HAVING COUNT(1) > 1


SELECT * FROM #ods_curso WHERE CO_CURSO = 1315345 AND CO_MUNICIPIO = 3518701 AND TP_DIMENSAO = 2

SELECT	DISTINCT CO_CURSO,	NO_CURSO, CO_IES,
		TP_DIMENSAO 
FROM #ods_curso 
WHERE CO_CURSO = 1315345 AND CO_MUNICIPIO = 3518701 AND TP_DIMENSAO = 2
ORDER BY 2, 3, 4

select * FROM [stg].[STG_MICRODADOS_CADASTRO_CURSOS_SP]
where co_curso = 1286528

select * from ods.ods_curso
where co_curso = 1286528

-- SEM DUPLICIDADE
select count(1),     CO_CURSO, CO_MUNICIPIO, CO_IES
FROM  ods.ods_curso
GROUP BY CO_CURSO, CO_MUNICIPIO, CO_IES
HAVING COUNT(1) > 1

select count(1),     CO_CURSO --, CO_IES
FROM  ods.ods_curso
GROUP BY CO_CURSO--, CO_IES
HAVING COUNT(1) > 1

SELECT * FROM ods.ods_curso WHERE CO_CURSO  = 5725
SELECT * FROM ods.ods_curso WHERE CO_CURSO  = 26414
SELECT * FROM ods.ods_curso WHERE CO_CURSO  = 106829

SELECT CO_CURSO, CO_IES, MAX(NU_ANO_CENSO) NU_ANO_CENSO
				FROM #ODS_CURSO
				WHERE CO_CURSO = 68796 AND CO_IES = 54
				GROUP BY CO_CURSO, CO_MUNICIPIO, CO_IES

SELECT * FROM #ODS_CURSO C WHERE CO_CURSO = 68796 AND CO_IES = 54

SELECT * FROM ods.ods_curso WHERE CO_CURSO = 68796 AND CO_IES = 54

SELECT * FROM ods.ods_curso
WHERE CO_CURSO = 52199	AND CO_MUNICIPIO  = 3509502	AND CO_IES = 19
SELECT * FROM #ODS_CURSO C
WHERE CO_CURSO = 52199	AND CO_MUNICIPIO  = 3509502	AND CO_IES = 19
*/

DROP TABLE IF EXISTS ODS.ODS_DADOS_CURSO
SELECT CO_CURSO
	,CO_MUNICIPIO
	,CO_IES
	,NU_ANO_CENSO
	,IN_CAPITAL
	,TP_DIMENSAO
	,TP_REDE
	 , REPLACE (CO_CINE_ROTULO, '"', '')CO_CINE_ROTULO
 , TP_GRAU_ACADEMICO
 , IN_GRATUITO
 , TP_MODALIDADE_ENSINO
 , TP_NIVEL_ACADEMICO
, QT_CURSO,QT_VG_TOTAL,QT_VG_TOTAL_DIURNO,QT_VG_TOTAL_NOTURNO,QT_VG_TOTAL_EAD,QT_VG_NOVA,QT_VG_PROC_SELETIVO,QT_VG_REMANESC,QT_VG_PROG_ESPECIAL,QT_INSCRITO_TOTAL,QT_INSCRITO_TOTAL_DIURNO,QT_INSCRITO_TOTAL_NOTURNO,QT_INSCRITO_TOTAL_EAD,QT_INSC_VG_NOVA,QT_INSC_PROC_SELETIVO,QT_INSC_VG_REMANESC,QT_INSC_VG_PROG_ESPECIAL,QT_ING,QT_ING_FEM,QT_ING_MASC,QT_ING_DIURNO,QT_ING_NOTURNO,QT_ING_VG_NOVA,QT_ING_VESTIBULAR,QT_ING_ENEM,QT_ING_AVALIACAO_SERIADA,QT_ING_SELECAO_SIMPLIFICA,QT_ING_EGR,QT_ING_OUTRO_TIPO_SELECAO,QT_ING_PROC_SELETIVO,QT_ING_VG_REMANESC,QT_ING_VG_PROG_ESPECIAL,QT_ING_OUTRA_FORMA,QT_ING_0_17,QT_ING_18_24,QT_ING_25_29,QT_ING_30_34,QT_ING_35_39,QT_ING_40_49,QT_ING_50_59,QT_ING_60_MAIS,QT_ING_BRANCA,QT_ING_PRETA,QT_ING_PARDA,QT_ING_AMARELA,QT_ING_INDIGENA,QT_ING_CORND,QT_MAT,QT_MAT_FEM,QT_MAT_MASC,QT_MAT_DIURNO,QT_MAT_NOTURNO,QT_MAT_0_17,QT_MAT_18_24,QT_MAT_25_29,QT_MAT_30_34,QT_MAT_35_39,QT_MAT_40_49,QT_MAT_50_59,QT_MAT_60_MAIS,QT_MAT_BRANCA,QT_MAT_PRETA,QT_MAT_PARDA,QT_MAT_AMARELA,QT_MAT_INDIGENA,QT_MAT_CORND,QT_CONC,QT_CONC_FEM,QT_CONC_MASC,QT_CONC_DIURNO,QT_CONC_NOTURNO,QT_CONC_0_17,QT_CONC_18_24,QT_CONC_25_29,QT_CONC_30_34,QT_CONC_35_39,QT_CONC_40_49,QT_CONC_50_59,QT_CONC_60_MAIS,QT_CONC_BRANCA,QT_CONC_PRETA,QT_CONC_PARDA,QT_CONC_AMARELA,QT_CONC_INDIGENA,QT_CONC_CORND,QT_ING_NACBRAS,QT_ING_NACESTRANG,QT_MAT_NACBRAS,QT_MAT_NACESTRANG,QT_CONC_NACBRAS,QT_CONC_NACESTRANG,QT_ALUNO_DEFICIENTE,QT_ING_DEFICIENTE,QT_MAT_DEFICIENTE,QT_CONC_DEFICIENTE,QT_ING_FINANC,QT_ING_FINANC_REEMB,QT_ING_FIES,QT_ING_RPFIES,QT_ING_FINANC_REEMB_OUTROS,QT_ING_FINANC_NREEMB,QT_ING_PROUNII,QT_ING_PROUNIP,QT_ING_NRPFIES,QT_ING_FINANC_NREEMB_OUTROS,QT_MAT_FINANC,QT_MAT_FINANC_REEMB,QT_MAT_FIES,QT_MAT_RPFIES,QT_MAT_FINANC_REEMB_OUTROS,QT_MAT_FINANC_NREEMB,QT_MAT_PROUNII,QT_MAT_PROUNIP,QT_MAT_NRPFIES,QT_MAT_FINANC_NREEMB_OUTROS,QT_CONC_FINANC,QT_CONC_FINANC_REEMB,QT_CONC_FIES,QT_CONC_RPFIES,QT_CONC_FINANC_REEMB_OUTROS,QT_CONC_FINANC_NREEMB,QT_CONC_PROUNII,QT_CONC_PROUNIP,QT_CONC_NRPFIES,QT_CONC_FINANC_NREEMB_OUTROS,QT_ING_RESERVA_VAGA,QT_ING_RVREDEPUBLICA,QT_ING_RVETNICO,QT_ING_RVPDEF,QT_ING_RVSOCIAL_RF,QT_ING_RVOUTROS,QT_MAT_RESERVA_VAGA,QT_MAT_RVREDEPUBLICA,QT_MAT_RVETNICO,QT_MAT_RVPDEF,QT_MAT_RVSOCIAL_RF,QT_MAT_RVOUTROS,QT_CONC_RESERVA_VAGA,QT_CONC_RVREDEPUBLICA,QT_CONC_RVETNICO,QT_CONC_RVPDEF,QT_CONC_RVSOCIAL_RF,QT_CONC_RVOUTROS,QT_SIT_TRANCADA,QT_SIT_DESVINCULADO,QT_SIT_TRANSFERIDO,QT_SIT_FALECIDO,QT_ING_PROCESCPUBLICA,QT_ING_PROCESCPRIVADA,QT_ING_PROCNAOINFORMADA,QT_MAT_PROCESCPUBLICA,QT_MAT_PROCESCPRIVADA,QT_MAT_PROCNAOINFORMADA,QT_CONC_PROCESCPUBLICA,QT_CONC_PROCESCPRIVADA,QT_CONC_PROCNAOINFORMADA,QT_PARFOR,QT_ING_PARFOR,QT_MAT_PARFOR,QT_CONC_PARFOR,QT_APOIO_SOCIAL,QT_ING_APOIO_SOCIAL,QT_MAT_APOIO_SOCIAL,QT_CONC_APOIO_SOCIAL,QT_ATIV_EXTRACURRICULAR,QT_ING_ATIV_EXTRACURRICULAR,QT_MAT_ATIV_EXTRACURRICULAR,QT_CONC_ATIV_EXTRACURRICULAR,QT_MOB_ACADEMICA,QT_ING_MOB_ACADEMICA,QT_MAT_MOB_ACADEMICA,QT_CONC_MOB_ACADEMICA
	INTO ODS.ODS_DADOS_CURSO
FROM [stg].[STG_MICRODADOS_CADASTRO_CURSOS_SP]

CREATE CLUSTERED INDEX IXC_ODS_DADOS_CURSO ON ODS.ODS_DADOS_CURSO (CO_CURSO, NU_ANO_CENSO, CO_MUNICIPIO, CO_IES )


SELECT CO_IES, NU_ANO_CENSO, 
		QT_TEC_TOTAL,QT_TEC_FUNDAMENTAL_INCOMP_FEM,QT_TEC_FUNDAMENTAL_INCOMP_MASC,QT_TEC_FUNDAMENTAL_COMP_FEM,QT_TEC_FUNDAMENTAL_COMP_MASC,QT_TEC_MEDIO_FEM,QT_TEC_MEDIO_MASC,QT_TEC_SUPERIOR_FEM,QT_TEC_SUPERIOR_MASC,QT_TEC_ESPECIALIZACAO_FEM,QT_TEC_ESPECIALIZACAO_MASC,QT_TEC_MESTRADO_FEM,QT_TEC_MESTRADO_MASC,QT_TEC_DOUTORADO_FEM,QT_TEC_DOUTORADO_MASC,IN_ACESSO_PORTAL_CAPES,IN_ACESSO_OUTRAS_BASES,IN_ASSINA_OUTRA_BASE,IN_REPOSITORIO_INSTITUCIONAL,IN_BUSCA_INTEGRADA,IN_SERVICO_INTERNET,IN_PARTICIPA_REDE_SOCIAL,IN_CATALOGO_ONLINE,QT_PERIODICO_ELETRONICO,QT_LIVRO_ELETRONICO,QT_DOC_TOTAL,QT_DOC_EXE,QT_DOC_EX_FEMI,QT_DOC_EX_MASC,QT_DOC_EX_SEM_GRAD,QT_DOC_EX_GRAD,QT_DOC_EX_ESP,QT_DOC_EX_MEST,QT_DOC_EX_DOUT,QT_DOC_EX_INT,QT_DOC_EX_INT_DE,QT_DOC_EX_INT_SEM_DE,QT_DOC_EX_PARC,QT_DOC_EX_HOR,QT_DOC_EX_0_29,QT_DOC_EX_30_34,QT_DOC_EX_35_39,QT_DOC_EX_40_44,QT_DOC_EX_45_49,QT_DOC_EX_50_54,QT_DOC_EX_55_59,QT_DOC_EX_60_MAIS,QT_DOC_EX_BRANCA,QT_DOC_EX_PRETA,QT_DOC_EX_PARDA,QT_DOC_EX_AMARELA,QT_DOC_EX_INDIGENA,QT_DOC_EX_COR_ND,QT_DOC_EX_BRA,QT_DOC_EX_EST,QT_DOC_EX_COM_DEFICIENCIA
INTO ODS.ODS_DADOS_IES
FROM [stg].[STG_MICRODADOS_CADASTRO_IES_SP]

CREATE CLUSTERED INDEX IXC_ODS_DADOS_IES ON ODS.ODS_DADOS_IES (CO_IES, NU_ANO_CENSO )

DROP TABLE IF EXISTS ODS.ODS_DADOS_FLUXO
SELECT 
	  ANO_DE_REFERÊNCIA											NU_ANO_CENSO
	, CÓDIGO_DA_INSTITUIÇÃO										CO_IES
	, CÓDIGO_DO_CURSO_DE_GRADUAÇÃO								CO_CURSO
	, CÓDIGO_DO_MUNICÍPIO_DO_CURSO								CO_MUNICIPIO
	, ANO_DE_INGRESSO											NU_ANO_INGRESSO
	, PRAZO_DE_INTEGRALIZAÇÃO_EM_ANOS							NU_PRAZO_INTEGRALIZACAO
	, ANO_DE_INTEGRALIZAÇÃO_DO_CURSO							NU_ANO_INTEGRALIZACAO
	, PRAZO_DE_ACOMPANHAMENTO_DO_CURSO_EM_ANOS					NU_PRAZO_ACOMPANHAMENTO
	, ANO_MÁXIMO_DE_ACOMPANHAMENTO_DO_CURSO						NU_ANO_MAXIMO_ACOMPANHAMENTO
	, QUANTIDADE_DE_INGRESSANTES_NO_CURSO						QT_INGRESSANTE
	, QUANTIDADE_DE_PERMANÊNCIA_NO_CURSO_NO_ANO_DE_REFERÊNCIA	QT_PERMANENCIA	
	, QUANTIDADE_DE_CONCLUINTES_NO_CURSO_NO_ANO_DE_REFERÊNCIA	QT_CONCLUINTE
	, QUANTIDADE_DE_DESISTÊNCIA_NO_CURSO_NO_ANO_DE_REFERÊNCIA	QT_DESISTENCIA
	, QUANTIDADE_DE_FALECIMENTOS_NO_CURSO_NO_ANO_DE_REFERÊNCIA	QT_FALECIDO
	, TAXA_DE_PERMANÊNCIA_TAP									VL_TAP
	, TAXA_DE_CONCLUSÃO_ACUMULADA_TCA							VL_TCA
	, TAXA_DE_DESISTÊNCIA_ACUMULADA_TDA							VL_TDA
	, TAXA_DE_CONCLUSÃO_ANUAL_TCAN								VL_TCAN
	, TAXA_DE_DESISTÊNCIA_ANUAL_TDAN							VL_TDAN
	, CO_CATALOGO												CO_CATALOGO
	INTO ODS.ODS_DADOS_FLUXO
FROM [STG].[STG_INDICADORES_TRAJETORIA_EDUCACAO_SUPERIOR_SP]


--DROP INDEX IXC_ODS_DADOS_FLUXO ON ODS.ODS_DADOS_FLUXO 
CREATE CLUSTERED INDEX IXC_ODS_DADOS_FLUXO ON ODS.ODS_DADOS_FLUXO (NU_ANO_CENSO, CO_IES, CO_CURSO, CO_MUNICIPIO, NU_ANO_INGRESSO)
/*
SELECT COUNT(1), NU_ANO_CENSO, CO_IES, CO_CURSO, CO_MUNICIPIO
FROM ODS.ODS_DADOS_FLUXO
GROUP BY NU_ANO_CENSO, CO_IES, CO_CURSO, CO_MUNICIPIO
HAVING COUNT(1) > 1

SELECT COUNT(1), NU_ANO_CENSO, CO_IES, CO_CURSO, CO_MUNICIPIO, NU_ANO_INGRESSO
FROM ODS.ODS_DADOS_FLUXO
GROUP BY NU_ANO_CENSO, CO_IES, CO_CURSO, CO_MUNICIPIO, NU_ANO_INGRESSO
HAVING COUNT(1) > 1
*/

SELECT * FROM ODS.ODS_DADOS_FLUXO

WHERE NU_ANO_CENSO  = 2012	
	AND CO_IES = 7	
	AND CO_CURSO = 614	
	AND CO_MUNICIPIO = 3548906



select * from INFORMATION_SCHEMA.tables 
order by 1, 2, 3



select TOP 10 * from ods.ODS_DADOS_FLUXO
select TOP 10 * from ods.ODS_DADOS_IES
select TOP 10 * from ods.ODS_DADOS_CURSO


select * from ods.ods_ies i
inner join ods.ODS_DADOS_IES DI
on di.CO_IES = i.co_ies



--------------------------------------------------------------------------------------------------------------------------------
-- CREATE SCHEMA DW

DROP TABLE IF EXISTS DW.DIM_IES
SELECT	IES.CO_IES, 
		IES.NO_IES, 
		IES.SG_IES, 
		IES.IN_CAPITAL_IES,
		IES.TP_ORGANIZACAO_ACADEMICA, 
		IES.TP_CATEGORIA_ADMINISTRATIVA, 
		MI.CO_MANTENEDORA, 
		MI.NO_MANTENEDORA
 		INTO DW.DIM_IES
FROM ODS.ODS_IES IES
INNER JOIN ODS.ODS_MANTENEDORA_IES MI
ON IES.CO_MANTENEDORA = MI.CO_MANTENEDORA
-- ADD FLG_ATIVO

DROP TABLE IF EXISTS DW.DIM_REGIAO
SELECT	MN.CO_MUNICIPIO, 
		MN.NO_MUNICIPIO, 
		MC.CO_MICRORREGIAO, 
		MC.NO_MICRORREGIAO,
		MS.CO_MESORREGIAO, 
		MS.NO_MESORREGIAO, 
		UF.CO_UF, 
		UF.NO_UF, 
		UF.SG_UF
		INTO DW.DIM_REGIAO
FROM ODS.ODS_MUNICIPIO MN 
INNER JOIN ODS.ODS_MICRORREGIAO MC
ON MN.CO_MICRORREGIAO = MC.CO_MICRORREGIAO
INNER JOIN ODS.ODS_MESORREGIAO MS
ON MS.CO_MESORREGIAO = MC.CO_MESORREGIAO
INNER JOIN ODS.ODS_UNIDADE_FEDERATIVA UF ON 
UF.CO_UF = MS.CO_UF
inner join ods.ods_regiao rg
on rg.co_regiao = uf.co_regiao
-- ADD FLG_ATIVO

/*
select count(1),CO_CURSO,  TP_DIMENSAO
from DW.DIM_CURSO
group by CO_CURSO,  TP_DIMENSAO
having count(1) > 1
select * from DW.DIM_CURSO where co_curso = 98104	and tp_dimensao = 2

select * from ods.ods_CURSO where co_curso = 98104	and tp_dimensao = 2 order by 1, 2, 3, 4, 5, 6, 7, 8
*/
DROP TABLE IF EXISTS DW.DIM_CURSO

SELECT  DISTINCT 
		CO_CURSO
		, NO_CURSO
-- 		, CO_IES
-- 		, IN_CAPITAL
-- 		, TP_DIMENSAO
-- 		, TP_REDE
-- 		, TP_GRAU_ACADEMICO
-- 		, IN_GRATUITO 
-- 		, TP_MODALIDADE_ENSINO
 		INTO DW.DIM_CURSO
FROM ODS.ODS_CURSO


DROP TABLE IF EXISTS DW.DIM_CINE
SELECT	CR.CO_CINE_ROTULO, 
		CR.NO_CINE_ROTULO, 
		CAD.CO_CINE_AREA_DETALHADA, 
		CAD.NO_CINE_AREA_DETALHADA,
		CAE.CO_CINE_AREA_ESPECIFICA, 
		CAE.NO_CINE_AREA_ESPECIFICA,
		CAG.CO_CINE_AREA_GERAL, 
		CAG.NO_CINE_AREA_GERAL
		INTO DW.DIM_CINE
FROM ODS.ODS_CINE_ROTULO CR
INNER JOIN ODS.ODS_CINE_AREA_DETALHADA CAD
ON CR.CO_CINE_AREA_DETALHADA = CAD.CO_CINE_AREA_DETALHADA
INNER JOIN ODS.ODS_CINE_AREA_ESPECIFICA CAE
ON CAE.CO_CINE_AREA_ESPECIFICA = CAD.CO_CINE_AREA_ESPECIFICA
INNER JOIN ODS.ODS_CINE_AREA_GERAL CAG
ON CAG.CO_CINE_AREA_GERAL =  CAE.CO_CINE_AREA_GERAL

GO
--Expressão de tabela com valores constantes
-- CREATE OR ALTER VIEW DW.VW_DIM_TIPO_REDE 
-- WITH SCHEMABINDING AS 
SELECT TP_REDE, NO_REDE -- INTO DW.DIM_TIPO_REDE 
FROM (
	VALUES 
		(1, 'Pública'),
		(2, 'Privada')
) AS DIM_TIPO_REDE (TP_REDE, NO_REDE  )
GO

-- CREATE or alter VIEW DW.VW_DIM_TIPO_DIMENSAO 
-- WITH SCHEMABINDING AS 
SELECT TP_DIMENSAO, NO_DIMENSAO  -- INTO DW.DIM_TIPO_DIMENSAO 
FROM (
	VALUES 
		(1, 'Cursos presenciais ofertados no Brasil'),
		(2, 'Cursos a distância ofertados no Brasil'),
		(3, 'Cursos a distância com dimensão de dados somente a nível Brasil'),
		(4, 'Cursos a distância ofertados por instituições brasileiras no exterior')
) AS DIM_TIPO_DIMENSAO (TP_DIMENSAO, NO_DIMENSAO  )

GO
-- CREATE OR ALTER VIEW DW.VW_DIM_TIPO_ORGANIZACAO_ACADEMICA	
-- WITH SCHEMABINDING AS
	SELECT TP_ORGANIZACAO_ACADEMICA,NO_ORGANIZACAO_ACADEMICA  --INTO DW.DIM_TIPO_ORGANIZACAO_ACADEMICA 
	FROM 
		(
			VALUES
				(1,'Universidade'),
				(2,'Centro Universitário'),
				(3,'Faculdade'),
				(4,'Instituto Federal de Educação, Ciência e Tecnologia'),
				(5,'Centro Federal de Educação Tecnológica')
			) AS DIM_TIPO_ALGUMA_COISA	(TP_ORGANIZACAO_ACADEMICA,NO_ORGANIZACAO_ACADEMICA)
GO
-- CREATE OR ALTER VIEW DW.VW_DIM_TIPO_CATEGORIA_ADMINISTRATIVA	
-- WITH SCHEMABINDING AS  
	SELECT TP_CATEGORIA_ADMINISTRATIVA, NO_CATEGORIA_ADMINISTRATIVA --INTO DW.DIM_TIPO_CATEGORIA_ADMINISTRATIVA	
	FROM 
		(
			VALUES
				(1,'Pública Federal'),
				(2,'Pública Estadual'),
				(3,'Pública Municipal'),
				(4,'Privada com fins lucrativos'),
				(5,'Privada sem fins lucrativos'),
				(6,'Privada - Particular em sentido estrito'),
				(7,'Especial'),
				(8,'Privada comunitária'),
				(9,'Privada confessional')
		) AS DIM_TIPO_ALGUMA_COISA(TP_CATEGORIA_ADMINISTRATIVA,NO_CATEGORIA_ADMINISTRATIVA)
GO

-- CREATE OR ALTER VIEW DW.VW_DIM_TIPO_GRAU_ACADEMICO			
-- WITH SCHEMABINDING AS 
	SELECT TP_GRAU_ACADEMICO, NO_GRAU_ACADEMICO --INTO DW.DIM_TIPO_GRAU_ACADEMICO
	FROM 
		(
			VALUES
				(1,'Bacharelado'),
				(2,'Licenciatura'),
				(3,'Tecnológico'),
				(4,'Bacharelado e Licenciatura')
		) AS DIM_TIPO_ALGUMA_COISA(TP_GRAU_ACADEMICO,NO_GRAU_ACADEMICO)
GO

--CREATE OR ALTER VIEW DW.VW_DIM_TIPO_MODALIDADE_ENSINO		
--WITH SCHEMABINDING AS 
	SELECT TP_MODALIDADE_ENSINO	, NO_MODALIDADE_ENSINO	 --INTO DW.DIM_TIPO_MODALIDADE_ENSINO		
	FROM 
		(
			VALUES
				(1,'Presencial'),
				(2,'Curso a distância')
		) AS DIM_TIPO_ALGUMA_COISA(TP_MODALIDADE_ENSINO	,NO_MODALIDADE_ENSINO	)
GO

--CREATE OR ALTER VIEW DW.VW_DIM_TIPO_NIVEL_ACADEMICO			
--WITH SCHEMABINDING AS 
	SELECT TP_NIVEL_ACADEMICO, NO_NIVEL_ACADEMICO --INTO DW.DIM_TIPO_NIVEL_ACADEMICO	
	FROM 
		(
			VALUES
				(1,'Graduação'),
				(2,'Sequencial de Formação Específica')
		) AS DIM_TIPO_ALGUMA_COISA(TP_NIVEL_ACADEMICO,NO_NIVEL_ACADEMICO)
GO

/*
	select * from INFORMATION_SCHEMA.COLUMNS where table_schema = 'ODS' AND COLUMN_NAME = 'TP_REDE'					
	select * from INFORMATION_SCHEMA.COLUMNS where table_schema = 'ODS' AND COLUMN_NAME = 'TP_DIMENSAO'				
	select * from INFORMATION_SCHEMA.COLUMNS where table_schema = 'ODS' AND COLUMN_NAME = 'TP_ORGANIZACAO_ACADEMICA'	
	select * from INFORMATION_SCHEMA.COLUMNS where table_schema = 'ODS' AND COLUMN_NAME = 'TP_CATEGORIA_ADMINISTRATIVA'
	select * from INFORMATION_SCHEMA.COLUMNS where table_schema = 'ODS' AND COLUMN_NAME = 'TP_GRAU_ACADEMICO'			
	select * from INFORMATION_SCHEMA.COLUMNS where table_schema = 'ODS' AND COLUMN_NAME = 'TP_MODALIDADE_ENSINO'		
	select * from INFORMATION_SCHEMA.COLUMNS where table_schema = 'ODS' AND COLUMN_NAME = 'TP_NIVEL_ACADEMICO'			
*/

SELECT	  IES.CO_IES
		, IES.CO_MUNICIPIO_IES				CO_MUNICIPIO
		, IES.TP_ORGANIZACAO_ACADEMICA
		, IES.TP_CATEGORIA_ADMINISTRATIVA
		, DI.NU_ANO_CENSO
		, DI.QT_TEC_TOTAL
		, DI.QT_TEC_FUNDAMENTAL_INCOMP_FEM
		, DI.QT_TEC_FUNDAMENTAL_INCOMP_MASC
		, DI.QT_TEC_FUNDAMENTAL_COMP_FEM
		, DI.QT_TEC_FUNDAMENTAL_COMP_MASC
		, DI.QT_TEC_MEDIO_FEM
		, DI.QT_TEC_MEDIO_MASC
		, DI.QT_TEC_SUPERIOR_FEM
		, DI.QT_TEC_SUPERIOR_MASC
		, DI.QT_TEC_ESPECIALIZACAO_FEM
		, DI.QT_TEC_ESPECIALIZACAO_MASC
		, DI.QT_TEC_MESTRADO_FEM
		, DI.QT_TEC_MESTRADO_MASC
		, DI.QT_TEC_DOUTORADO_FEM
		, DI.QT_TEC_DOUTORADO_MASC
		, DI.IN_ACESSO_PORTAL_CAPES
		, DI.IN_ACESSO_OUTRAS_BASES
		, DI.IN_ASSINA_OUTRA_BASE
		, DI.IN_REPOSITORIO_INSTITUCIONAL
		, DI.IN_BUSCA_INTEGRADA
		, DI.IN_SERVICO_INTERNET
		, DI.IN_PARTICIPA_REDE_SOCIAL
		, DI.IN_CATALOGO_ONLINE
		, DI.QT_PERIODICO_ELETRONICO
		, DI.QT_LIVRO_ELETRONICO
		, DI.QT_DOC_TOTAL
		, DI.QT_DOC_EXE
		, DI.QT_DOC_EX_FEMI
		, DI.QT_DOC_EX_MASC
		, DI.QT_DOC_EX_SEM_GRAD
		, DI.QT_DOC_EX_GRAD
		, DI.QT_DOC_EX_ESP
		, DI.QT_DOC_EX_MEST
		, DI.QT_DOC_EX_DOUT
		, DI.QT_DOC_EX_INT
		, DI.QT_DOC_EX_INT_DE
		, DI.QT_DOC_EX_INT_SEM_DE
		, DI.QT_DOC_EX_PARC
		, DI.QT_DOC_EX_HOR
		, DI.QT_DOC_EX_0_29
		, DI.QT_DOC_EX_30_34
		, DI.QT_DOC_EX_35_39
		, DI.QT_DOC_EX_40_44
		, DI.QT_DOC_EX_45_49
		, DI.QT_DOC_EX_50_54
		, DI.QT_DOC_EX_55_59
		, DI.QT_DOC_EX_60_MAIS
		, DI.QT_DOC_EX_BRANCA
		, DI.QT_DOC_EX_PRETA
		, DI.QT_DOC_EX_PARDA
		, DI.QT_DOC_EX_AMARELA
		, DI.QT_DOC_EX_INDIGENA
		, DI.QT_DOC_EX_COR_ND
		, DI.QT_DOC_EX_BRA
		, DI.QT_DOC_EX_EST
		, DI.QT_DOC_EX_COM_DEFICIENCIA
		INTO DW.FTO_DADOS_IES
	FROM ODS.ODS_DADOS_IES DI
	INNER JOIN ODS.ODS_IES IES 
	ON DI.CO_IES = IES.CO_IES


-- ADD PKS PARA CRIAR FKS	
--ALTER TABLE DW.FTO_DADOS_IES ADD CONSTRAINT FK_FTO_DADOS_IES_DIM_IES							FOREIGN KEY (CO_IES						)REFERENCES DW.DIM_IES
--ALTER TABLE DW.FTO_DADOS_IES ADD CONSTRAINT FK_FTO_DADOS_IES_DIM_REGIAO							FOREIGN KEY (CO_MUNICIPIO_IES			)REFERENCES DW.DIM_REGIAO



DROP TABLE IF EXISTS DW.FTO_DADOS_CURSO
SELECT 
	 DC.NU_ANO_CENSO
	,DC.CO_CURSO
	,DC.CO_MUNICIPIO
	,DC.IN_CAPITAL
	,DC.TP_DIMENSAO
	,DC.TP_REDE
	,DC.CO_IES
	,DC.CO_CINE_ROTULO
	,DC.TP_GRAU_ACADEMICO
	,DC.IN_GRATUITO
	,DC.TP_MODALIDADE_ENSINO
	,DC.TP_NIVEL_ACADEMICO
	,DC.QT_CURSO
	,DC.QT_VG_TOTAL
	,DC.QT_VG_TOTAL_DIURNO
	,DC.QT_VG_TOTAL_NOTURNO
	,DC.QT_VG_TOTAL_EAD
	,DC.QT_VG_NOVA
	,DC.QT_VG_PROC_SELETIVO
	,DC.QT_VG_REMANESC
	,DC.QT_VG_PROG_ESPECIAL
	,DC.QT_INSCRITO_TOTAL
	,DC.QT_INSCRITO_TOTAL_DIURNO
	,DC.QT_INSCRITO_TOTAL_NOTURNO
	,DC.QT_INSCRITO_TOTAL_EAD
	,DC.QT_INSC_VG_NOVA
	,DC.QT_INSC_PROC_SELETIVO
	,DC.QT_INSC_VG_REMANESC
	,DC.QT_INSC_VG_PROG_ESPECIAL
	,DC.QT_ING
	,DC.QT_ING_FEM
	,DC.QT_ING_MASC
	,DC.QT_ING_DIURNO
	,DC.QT_ING_NOTURNO
	,DC.QT_ING_VG_NOVA
	,DC.QT_ING_VESTIBULAR
	,DC.QT_ING_ENEM
	,DC.QT_ING_AVALIACAO_SERIADA
	,DC.QT_ING_SELECAO_SIMPLIFICA
	,DC.QT_ING_EGR
	,DC.QT_ING_OUTRO_TIPO_SELECAO
	,DC.QT_ING_PROC_SELETIVO
	,DC.QT_ING_VG_REMANESC
	,DC.QT_ING_VG_PROG_ESPECIAL
	,DC.QT_ING_OUTRA_FORMA
	,DC.QT_ING_0_17
	,DC.QT_ING_18_24
	,DC.QT_ING_25_29
	,DC.QT_ING_30_34
	,DC.QT_ING_35_39
	,DC.QT_ING_40_49
	,DC.QT_ING_50_59
	,DC.QT_ING_60_MAIS
	,DC.QT_ING_BRANCA
	,DC.QT_ING_PRETA
	,DC.QT_ING_PARDA
	,DC.QT_ING_AMARELA
	,DC.QT_ING_INDIGENA
	,DC.QT_ING_CORND
	,DC.QT_MAT
	,DC.QT_MAT_FEM
	,DC.QT_MAT_MASC
	,DC.QT_MAT_DIURNO
	,DC.QT_MAT_NOTURNO
	,DC.QT_MAT_0_17
	,DC.QT_MAT_18_24
	,DC.QT_MAT_25_29
	,DC.QT_MAT_30_34
	,DC.QT_MAT_35_39
	,DC.QT_MAT_40_49
	,DC.QT_MAT_50_59
	,DC.QT_MAT_60_MAIS
	,DC.QT_MAT_BRANCA
	,DC.QT_MAT_PRETA
	,DC.QT_MAT_PARDA
	,DC.QT_MAT_AMARELA
	,DC.QT_MAT_INDIGENA
	,DC.QT_MAT_CORND
	,DC.QT_CONC
	,DC.QT_CONC_FEM
	,DC.QT_CONC_MASC
	,DC.QT_CONC_DIURNO
	,DC.QT_CONC_NOTURNO
	,DC.QT_CONC_0_17
	,DC.QT_CONC_18_24
	,DC.QT_CONC_25_29
	,DC.QT_CONC_30_34
	,DC.QT_CONC_35_39
	,DC.QT_CONC_40_49
	,DC.QT_CONC_50_59
	,DC.QT_CONC_60_MAIS
	,DC.QT_CONC_BRANCA
	,DC.QT_CONC_PRETA
	,DC.QT_CONC_PARDA
	,DC.QT_CONC_AMARELA
	,DC.QT_CONC_INDIGENA
	,DC.QT_CONC_CORND
	,DC.QT_ING_NACBRAS
	,DC.QT_ING_NACESTRANG
	,DC.QT_MAT_NACBRAS
	,DC.QT_MAT_NACESTRANG
	,DC.QT_CONC_NACBRAS
	,DC.QT_CONC_NACESTRANG
	,DC.QT_ALUNO_DEFICIENTE
	,DC.QT_ING_DEFICIENTE
	,DC.QT_MAT_DEFICIENTE
	,DC.QT_CONC_DEFICIENTE
	,DC.QT_ING_FINANC
	,DC.QT_ING_FINANC_REEMB
	,DC.QT_ING_FIES
	,DC.QT_ING_RPFIES
	,DC.QT_ING_FINANC_REEMB_OUTROS
	,DC.QT_ING_FINANC_NREEMB
	,DC.QT_ING_PROUNII
	,DC.QT_ING_PROUNIP
	,DC.QT_ING_NRPFIES
	,DC.QT_ING_FINANC_NREEMB_OUTROS
	,DC.QT_MAT_FINANC
	,DC.QT_MAT_FINANC_REEMB
	,DC.QT_MAT_FIES
	,DC.QT_MAT_RPFIES
	,DC.QT_MAT_FINANC_REEMB_OUTROS
	,DC.QT_MAT_FINANC_NREEMB
	,DC.QT_MAT_PROUNII
	,DC.QT_MAT_PROUNIP
	,DC.QT_MAT_NRPFIES
	,DC.QT_MAT_FINANC_NREEMB_OUTROS
	,DC.QT_CONC_FINANC
	,DC.QT_CONC_FINANC_REEMB
	,DC.QT_CONC_FIES
	,DC.QT_CONC_RPFIES
	,DC.QT_CONC_FINANC_REEMB_OUTROS
	,DC.QT_CONC_FINANC_NREEMB
	,DC.QT_CONC_PROUNII
	,DC.QT_CONC_PROUNIP
	,DC.QT_CONC_NRPFIES
	,DC.QT_CONC_FINANC_NREEMB_OUTROS
	,DC.QT_ING_RESERVA_VAGA
	,DC.QT_ING_RVREDEPUBLICA
	,DC.QT_ING_RVETNICO
	,DC.QT_ING_RVPDEF
	,DC.QT_ING_RVSOCIAL_RF
	,DC.QT_ING_RVOUTROS
	,DC.QT_MAT_RESERVA_VAGA
	,DC.QT_MAT_RVREDEPUBLICA
	,DC.QT_MAT_RVETNICO
	,DC.QT_MAT_RVPDEF
	,DC.QT_MAT_RVSOCIAL_RF
	,DC.QT_MAT_RVOUTROS
	,DC.QT_CONC_RESERVA_VAGA
	,DC.QT_CONC_RVREDEPUBLICA
	,DC.QT_CONC_RVETNICO
	,DC.QT_CONC_RVPDEF
	,DC.QT_CONC_RVSOCIAL_RF
	,DC.QT_CONC_RVOUTROS
	,DC.QT_SIT_TRANCADA
	,DC.QT_SIT_DESVINCULADO
	,DC.QT_SIT_TRANSFERIDO
	,DC.QT_SIT_FALECIDO
	,DC.QT_ING_PROCESCPUBLICA
	,DC.QT_ING_PROCESCPRIVADA
	,DC.QT_ING_PROCNAOINFORMADA
	,DC.QT_MAT_PROCESCPUBLICA
	,DC.QT_MAT_PROCESCPRIVADA
	,DC.QT_MAT_PROCNAOINFORMADA
	,DC.QT_CONC_PROCESCPUBLICA
	,DC.QT_CONC_PROCESCPRIVADA
	,DC.QT_CONC_PROCNAOINFORMADA
	,DC.QT_PARFOR
	,DC.QT_ING_PARFOR
	,DC.QT_MAT_PARFOR
	,DC.QT_CONC_PARFOR
	,DC.QT_APOIO_SOCIAL
	,DC.QT_ING_APOIO_SOCIAL
	,DC.QT_MAT_APOIO_SOCIAL
	,DC.QT_CONC_APOIO_SOCIAL
	,DC.QT_ATIV_EXTRACURRICULAR
	,DC.QT_ING_ATIV_EXTRACURRICULAR
	,DC.QT_MAT_ATIV_EXTRACURRICULAR
	,DC.QT_CONC_ATIV_EXTRACURRICULAR
	,DC.QT_MOB_ACADEMICA
	,DC.QT_ING_MOB_ACADEMICA
	,DC.QT_MAT_MOB_ACADEMICA
	,DC.QT_CONC_MOB_ACADEMICA
/*	,DF.NU_ANO_INGRESSO
	,DF.NU_PRAZO_INTEGRALIZACAO
	,DF.NU_ANO_INTEGRALIZACAO
	,DF.NU_PRAZO_ACOMPANHAMENTO
	,DF.NU_ANO_MAXIMO_ACOMPANHAMENTO
	,DF.QT_INGRESSANTE
	,DF.QT_PERMANENCIA
	,DF.QT_CONCLUINTE
	,DF.QT_DESISTENCIA
	,DF.QT_FALECIDO
	,DF.VL_TAP
	,DF.VL_TCA
	,DF.VL_TDA
	,DF.VL_TCAN
	,DF.VL_TDAN
	,DF.CO_CATALOGO
*/
	INTO DW.FTO_DADOS_CURSO
FROM 	ODS.ODS_DADOS_CURSO		dc					
/*
ODS.ODS_CURSO						C
	INNER JOIN	ODS.ODS_DADOS_CURSO							DC	ON	C.CO_CURSO			=	DC.CO_CURSO		AND 
																	C.CO_MUNICIPIO		=	DC.CO_MUNICIPIO AND 
																	C.CO_IES			=	DC.CO_IES
*/
/*
-- NÃO É POSSÍVEL JUNTAR DADOS DE CURSO E FLUXO NA MESMA TABELA FATO POR HAVER DADOS DE FLUXO PARA O MESMO CURSO COM DIFERENTES ANOS DE INGRESSO; 
-- FAZER UM JOIN ENTRE AS TABELAS DE DADOS DE CURSO E DADOS DE FLUXO PROVOCARIA DUPLICIDADE NOS DADOS DE CURSO
LEFT JOIN ODS.ODS_DADOS_FLUXO								DF ON	DC.NU_ANO_CENSO		=	DF.NU_ANO_CENSO	AND
																	DC.CO_IES			=	DF.CO_IES		AND
																	DC.CO_CURSO			=	DF.CO_CURSO		AND
																	DC.CO_MUNICIPIO		=	DF.CO_MUNICIPIO	


SELECT * FROM	ODS.ODS_DADOS_CURSO		DC	
LEFT JOIN		ODS.ODS_DADOS_FLUXO		DF ON	DC.NU_ANO_CENSO		=	DF.NU_ANO_CENSO	AND
												DC.CO_IES			=	DF.CO_IES		AND
												DC.CO_CURSO			=	DF.CO_CURSO		AND
												DC.CO_MUNICIPIO		=	DF.CO_MUNICIPIO	
WHERE DF.CO_MUNICIPIO IS NULL

SELECT * FROM ODS.ODS_DADOS_CURSO		DC
LEFT JOIN		ODS.ODS_DADOS_FLUXO		DF ON	DC.NU_ANO_CENSO		=	DF.NU_ANO_CENSO	AND
												DC.CO_IES			=	DF.CO_IES		AND
												DC.CO_CURSO			=	DF.CO_CURSO		AND
												DC.CO_MUNICIPIO		=	DF.CO_MUNICIPIO	
 WHERE	DC.CO_CURSO		=	614			AND 
		DC.CO_MUNICIPIO	=	3548906		AND 
		DC.CO_IES		=	7			AND 
		DC.NU_ANO_CENSO	=	2010		

SELECT COUNT(1),  
DC.CO_CURSO,		
DC.CO_MUNICIPIO	,
DC.CO_IES	,	
DC.NU_ANO_CENSO	
FROM ODS.ODS_DADOS_CURSO		DC
LEFT JOIN		ODS.ODS_DADOS_FLUXO		DF ON	DC.NU_ANO_CENSO		=	DF.NU_ANO_CENSO	AND
												DC.CO_IES			=	DF.CO_IES		AND
												DC.CO_CURSO			=	DF.CO_CURSO		AND
												DC.CO_MUNICIPIO		=	DF.CO_MUNICIPIO	
GROUP BY DC.CO_CURSO,		
DC.CO_MUNICIPIO	,
DC.CO_IES,	
DC.NU_ANO_CENSO	*/



DROP TABLE IF EXISTS DW.FTO_DADOS_FLUXO
SELECT 
	 C.CO_CURSO

	,C.CO_MUNICIPIO
	,C.IN_CAPITAL
	,C.TP_DIMENSAO
	,C.TP_REDE
	,C.CO_IES
	,C.CO_CINE_ROTULO
	,C.TP_GRAU_ACADEMICO
	,C.IN_GRATUITO
	,C.TP_MODALIDADE_ENSINO
	,C.TP_NIVEL_ACADEMICO
	,df.NU_ANO_CENSO
	,DF.NU_ANO_INGRESSO
	,DF.NU_PRAZO_INTEGRALIZACAO
	,DF.NU_ANO_INTEGRALIZACAO
	,DF.NU_PRAZO_ACOMPANHAMENTO
	,DF.NU_ANO_MAXIMO_ACOMPANHAMENTO
	,DF.QT_INGRESSANTE
	,DF.QT_PERMANENCIA
	,DF.QT_CONCLUINTE
	,DF.QT_DESISTENCIA
	,DF.QT_FALECIDO
	,DF.VL_TAP
	,DF.VL_TCA
	,DF.VL_TDA
	,DF.VL_TCAN
	,DF.VL_TDAN
	,DF.CO_CATALOGO
	INTO DW.FTO_DADOS_FLUXO
FROM 			ODS.ODS_CURSO	C
LEFT JOIN ODS.ODS_DADOS_FLUXO	DF ON	C.CO_IES			=	DF.CO_IES		AND
										C.CO_CURSO			=	DF.CO_CURSO		AND
										C.CO_MUNICIPIO		=	DF.CO_MUNICIPIO	
/*
select count(1)
,CO_IES			
,CO_CURSO			
,CO_MUNICIPIO, 
NU_ANO_CENSO
from DW.FTO_DADOS_FLUXO
group by 
 CO_IES			
,CO_CURSO			
,CO_MUNICIPIO
, NU_ANO_CENSO
having count(1) > 1

select * from DW.FTO_DADOS_FLUXO  
where co_ies  = 263	
and co_curso = 6330	
and co_municipio = 3550308
and NU_ANO_CENSO = 2017
order by NU_ANO_INGRESSO
*/

-- select * from information_schema.tables where table_schema = 'dw'--DW.FTO_DADOS_FLUXO


ALTER TABLE dw.DIM_REGIAO							ALTER COLUMN CO_MUNICIPIO					INT NOT NULL	
ALTER TABLE dw.DIM_CURSO							ALTER COLUMN CO_CURSO						INT NOT NULL	
ALTER TABLE dw.DIM_TIPO_REDE						ALTER COLUMN TP_REDE						INT NOT NULL	
ALTER TABLE dw.DIM_TIPO_DIMENSAO					ALTER COLUMN TP_DIMENSAO					INT NOT NULL	
ALTER TABLE dw.DIM_TIPO_ORGANIZACAO_ACADEMICA		ALTER COLUMN TP_ORGANIZACAO_ACADEMICA		tinyint NOT NULL	
ALTER TABLE dw.DIM_TIPO_CATEGORIA_ADMINISTRATIVA	ALTER COLUMN TP_CATEGORIA_ADMINISTRATIVA	tinyint NOT NULL	
ALTER TABLE dw.DIM_TIPO_GRAU_ACADEMICO				ALTER COLUMN TP_GRAU_ACADEMICO				INT NOT NULL	
ALTER TABLE dw.DIM_TIPO_MODALIDADE_ENSINO			ALTER COLUMN TP_MODALIDADE_ENSINO			INT NOT NULL	
ALTER TABLE dw.DIM_TIPO_NIVEL_ACADEMICO				ALTER COLUMN TP_NIVEL_ACADEMICO				INT NOT NULL	
ALTER TABLE dw.DIM_IES								ALTER COLUMN CO_IES							INT NOT NULL	
ALTER TABLE dw.DIM_CINE								ALTER COLUMN CO_CINE_ROTULO					CHAR(7) NOT NULL	

SELECT MAX(LEN(CO_CINE_ROTULO)) FROM dw.DIM_CINE								

ALTER TABLE dw.DIM_REGIAO							ADD CONSTRAINT PK_DIM_REGIAO							PRIMARY KEY (CO_MUNICIPIO				)
ALTER TABLE DW.DIM_CINE								ADD CONSTRAINT PK_DIM_CINE								PRIMARY KEY (CO_CINE_ROTULO				)
ALTER TABLE dw.DIM_CURSO							ADD CONSTRAINT PK_DIM_CURSO								PRIMARY KEY (CO_CURSO					)
ALTER TABLE dw.DIM_TIPO_REDE						ADD CONSTRAINT PK_DIM_TIPO_REDE							PRIMARY KEY (TP_REDE					)
ALTER TABLE dw.DIM_TIPO_DIMENSAO					ADD CONSTRAINT PK_DIM_TIPO_DIMENSAO						PRIMARY KEY (TP_DIMENSAO				)
ALTER TABLE dw.DIM_TIPO_ORGANIZACAO_ACADEMICA		ADD CONSTRAINT PK_DIM_TIPO_ORGANIZACAO_ACADEMICA		PRIMARY KEY (TP_ORGANIZACAO_ACADEMICA	)
ALTER TABLE dw.DIM_TIPO_CATEGORIA_ADMINISTRATIVA	ADD CONSTRAINT PK_DIM_TIPO_CATEGORIA_ADMINISTRATIVA		PRIMARY KEY (TP_CATEGORIA_ADMINISTRATIVA)
ALTER TABLE dw.DIM_TIPO_GRAU_ACADEMICO				ADD CONSTRAINT PK_DIM_TIPO_GRAU_ACADEMICO				PRIMARY KEY (TP_GRAU_ACADEMICO			)
ALTER TABLE dw.DIM_TIPO_MODALIDADE_ENSINO			ADD CONSTRAINT PK_DIM_TIPO_MODALIDADE_ENSINO			PRIMARY KEY (TP_MODALIDADE_ENSINO		)
ALTER TABLE dw.DIM_TIPO_NIVEL_ACADEMICO				ADD CONSTRAINT PK_DIM_TIPO_NIVEL_ACADEMICO				PRIMARY KEY (TP_NIVEL_ACADEMICO			)
ALTER TABLE dw.DIM_IES								ADD CONSTRAINT PK_DIM_IES								PRIMARY KEY (CO_IES						)

select * from dw.DIM_CURSO where co_curso = 26414
select * from ods.ods_CURSO where co_curso = 26414


ALTER TABLE DW.FTO_DADOS_IES	ADD CONSTRAINT FK_FTO_DADOS_IES_DIM_IES								FOREIGN KEY (CO_IES						)	REFERENCES	DW.DIM_IES								(CO_IES						)
ALTER TABLE DW.FTO_DADOS_IES	ADD CONSTRAINT FK_FTO_DADOS_IES_DIM_REGIAO							FOREIGN KEY (CO_MUNICIPIO				)	REFERENCES	DW.DIM_REGIAO							(CO_MUNICIPIO				)
ALTER TABLE DW.FTO_DADOS_IES	ADD CONSTRAINT FK_FTO_DADOS_IES_DIM_TIPO_ORGANIZACAO_ACADEMICA		FOREIGN KEY (TP_ORGANIZACAO_ACADEMICA	)	REFERENCES	DW.DIM_TIPO_ORGANIZACAO_ACADEMICA		(TP_ORGANIZACAO_ACADEMICA	)
ALTER TABLE DW.FTO_DADOS_IES	ADD CONSTRAINT FK_FTO_DADOS_IES_DIM_TIPO_CATEGORIA_ADMINISTRATIVA	FOREIGN KEY (TP_CATEGORIA_ADMINISTRATIVA)	REFERENCES	DW.DIM_TIPO_CATEGORIA_ADMINISTRATIVA	(TP_CATEGORIA_ADMINISTRATIVA)	

CREATE CLUSTERED INDEX IXC_FTO_DADOS_IES	ON DW.FTO_DADOS_IES (CO_IES,CO_MUNICIPIO,TP_ORGANIZACAO_ACADEMICA,TP_CATEGORIA_ADMINISTRATIVA,NU_ANO_CENSO)
CREATE CLUSTERED INDEX IXC_FTO_DADOS_CURSO	ON DW.FTO_DADOS_CURSO (NU_ANO_CENSO, CO_CURSO, CO_CINE_ROTULO, CO_IES, CO_MUNICIPIO, TP_MODALIDADE_ENSINO, TP_NIVEL_ACADEMICO, TP_DIMENSAO, TP_REDE, TP_GRAU_ACADEMICo)
DROP INDEX IXC_FTO_DADOS_CURSO	ON DW.FTO_DADOS_CURSO 

ALTER TABLE DW.FTO_DADOS_CURSO ALTER COLUMN IN_GRATUITO BIT
ALTER TABLE DW.FTO_DADOS_CURSO ALTER COLUMN IN_CAPITAL BIT
ALTER TABLE DW.FTO_DADOS_CURSO ALTER COLUMN CO_CINE_ROTULO	CHAR(7)
--ALTER TABLE DW.FTO_DADOS_CURSO ALTER COLUMN TP_MODALIDADE_ENSINO	tinyint
--ALTER TABLE DW.FTO_DADOS_CURSO ALTER COLUMN TP_NIVEL_ACADEMICO		tinyint
--ALTER TABLE DW.FTO_DADOS_CURSO ALTER COLUMN TP_DIMENSAO				tinyint
--ALTER TABLE DW.FTO_DADOS_CURSO ALTER COLUMN TP_REDE					tinyint
--ALTER TABLE DW.FTO_DADOS_CURSO ALTER COLUMN TP_GRAU_ACADEMICO		tinyint


ALTER TABLE DW.FTO_DADOS_CURSO	ADD CONSTRAINT FK_FTO_DADOS_CURSO_DIM_CURSO							FOREIGN KEY (CO_CURSO					)	REFERENCES	DW.DIM_CURSO							(CO_CURSO				)
ALTER TABLE DW.FTO_DADOS_CURSO	ADD CONSTRAINT FK_FTO_DADOS_CURSO_DIM_REGIAO						FOREIGN KEY (CO_MUNICIPIO				)	REFERENCES	DW.DIM_REGIAO							(CO_MUNICIPIO			)
ALTER TABLE DW.FTO_DADOS_CURSO	ADD CONSTRAINT FK_FTO_DADOS_CURSO_DIM_TIPO_DIMENSAO					FOREIGN KEY (TP_DIMENSAO				)	REFERENCES	DW.DIM_TIPO_DIMENSAO					(TP_DIMENSAO			)
ALTER TABLE DW.FTO_DADOS_CURSO	ADD CONSTRAINT FK_FTO_DADOS_CURSO_DIM_TIPO_REDE						FOREIGN KEY (TP_REDE					)	REFERENCES	DW.DIM_TIPO_REDE						(TP_REDE				)
ALTER TABLE DW.FTO_DADOS_CURSO	ADD CONSTRAINT FK_FTO_DADOS_CURSO_DIM_CINE							FOREIGN KEY (CO_CINE_ROTULO				)	REFERENCES	DW.DIM_CINE								(CO_CINE_ROTULO			)
ALTER TABLE DW.FTO_DADOS_CURSO	ADD CONSTRAINT FK_FTO_DADOS_CURSO_DIM_TIPO_GRAU_ACADEMICO			FOREIGN KEY (TP_GRAU_ACADEMICO			)	REFERENCES	DW.DIM_TIPO_GRAU_ACADEMICO				(TP_GRAU_ACADEMICO		)
ALTER TABLE DW.FTO_DADOS_CURSO	ADD CONSTRAINT FK_FTO_DADOS_CURSO_DIM_TIPO_MODALIDADE_ENSINO		FOREIGN KEY (TP_MODALIDADE_ENSINO		)	REFERENCES	DW.DIM_TIPO_MODALIDADE_ENSINO			(TP_MODALIDADE_ENSINO	)
ALTER TABLE DW.FTO_DADOS_CURSO	ADD CONSTRAINT FK_FTO_DADOS_CURSO_DIM_TIPO_NIVEL_ACADEMICO			FOREIGN KEY (TP_NIVEL_ACADEMICO			)	REFERENCES	DW.DIM_TIPO_NIVEL_ACADEMICO				(TP_NIVEL_ACADEMICO		)

-- analisar membro inferido
--ALTER TABLE DW.FTO_DADOS_CURSO	ADD CONSTRAINT FK_FTO_DADOS_CURSO_DIM_IES							FOREIGN KEY (CO_IES						)	REFERENCES	DW.DIM_IES								(CO_IES					)


/*ALTER TABLE DW.FTO_DADOS_FLUXO 	
CO_CURSO
CO_MUNICIPIO
IN_CAPITAL
TP_DIMENSAO
TP_REDE
CO_IES
CO_CINE_ROTULO
TP_GRAU_ACADEMICO
TP_MODALIDADE_ENSINO
TP_NIVEL_ACADEMICO
NU_ANO_CENSO
NU_ANO_CENSO
*/

/*metadados das tabelas do DW*/
SELECT C.TABLE_SCHEMA, C.TABLE_NAME, C.COLUMN_NAME, C.ORDINAL_POSITION, C.DATA_TYPE, C.CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS C
INNER JOIN INFORMATION_SCHEMA.TABLES T ON C.TABLE_SCHEMA = T.TABLE_SCHEMA AND T.TABLE_NAME = C.TABLE_NAME AND C.TABLE_CATALOG =  T.TABLE_CATALOG
WHERE C.TABLE_SCHEMA = 'DW' AND 
T.TABLE_TYPE = 'BASE TABLE'
and column_name like 'tp_%'


GO
CREATE OR ALTER VIEW DW.VW_FTO_DADOS_IES AS 
SELECT 
 FTO.NU_ANO_CENSO
,IES.CO_IES
,IES.NO_IES
,IES.SG_IES
,IES.IN_CAPITAL_IES
,IES.CO_MANTENEDORA
,IES.NO_MANTENEDORA
,RG.CO_MUNICIPIO
,RG.NO_MUNICIPIO
,RG.CO_MICRORREGIAO
,RG.NO_MICRORREGIAO
,RG.CO_MESORREGIAO
,RG.NO_MESORREGIAO
,RG.CO_UF
,RG.NO_UF
,RG.SG_UF
,TOA.TP_ORGANIZACAO_ACADEMICA
,TOA.NO_ORGANIZACAO_ACADEMICA
,TCA.TP_CATEGORIA_ADMINISTRATIVA
,TCA.NO_CATEGORIA_ADMINISTRATIVA
,FTO.QT_TEC_TOTAL
,FTO.QT_TEC_FUNDAMENTAL_INCOMP_FEM
,FTO.QT_TEC_FUNDAMENTAL_INCOMP_MASC
,FTO.QT_TEC_FUNDAMENTAL_COMP_FEM
,FTO.QT_TEC_FUNDAMENTAL_COMP_MASC
,FTO.QT_TEC_MEDIO_FEM
,FTO.QT_TEC_MEDIO_MASC
,FTO.QT_TEC_SUPERIOR_FEM
,FTO.QT_TEC_SUPERIOR_MASC
,FTO.QT_TEC_ESPECIALIZACAO_FEM
,FTO.QT_TEC_ESPECIALIZACAO_MASC
,FTO.QT_TEC_MESTRADO_FEM
,FTO.QT_TEC_MESTRADO_MASC
,FTO.QT_TEC_DOUTORADO_FEM
,FTO.QT_TEC_DOUTORADO_MASC
,FTO.IN_ACESSO_PORTAL_CAPES
,FTO.IN_ACESSO_OUTRAS_BASES
,FTO.IN_ASSINA_OUTRA_BASE
,FTO.IN_REPOSITORIO_INSTITUCIONAL
,FTO.IN_BUSCA_INTEGRADA
,FTO.IN_SERVICO_INTERNET
,FTO.IN_PARTICIPA_REDE_SOCIAL
,FTO.IN_CATALOGO_ONLINE
,FTO.QT_PERIODICO_ELETRONICO
,FTO.QT_LIVRO_ELETRONICO
,FTO.QT_DOC_TOTAL
,FTO.QT_DOC_EXE
,FTO.QT_DOC_EX_FEMI
,FTO.QT_DOC_EX_MASC
,FTO.QT_DOC_EX_SEM_GRAD
,FTO.QT_DOC_EX_GRAD
,FTO.QT_DOC_EX_ESP
,FTO.QT_DOC_EX_MEST
,FTO.QT_DOC_EX_DOUT
,FTO.QT_DOC_EX_INT
,FTO.QT_DOC_EX_INT_DE
,FTO.QT_DOC_EX_INT_SEM_DE
,FTO.QT_DOC_EX_PARC
,FTO.QT_DOC_EX_HOR
,FTO.QT_DOC_EX_0_29
,FTO.QT_DOC_EX_30_34
,FTO.QT_DOC_EX_35_39
,FTO.QT_DOC_EX_40_44
,FTO.QT_DOC_EX_45_49
,FTO.QT_DOC_EX_50_54
,FTO.QT_DOC_EX_55_59
,FTO.QT_DOC_EX_60_MAIS
,FTO.QT_DOC_EX_BRANCA
,FTO.QT_DOC_EX_PRETA
,FTO.QT_DOC_EX_PARDA
,FTO.QT_DOC_EX_AMARELA
,FTO.QT_DOC_EX_INDIGENA
,FTO.QT_DOC_EX_COR_ND
,FTO.QT_DOC_EX_BRA
,FTO.QT_DOC_EX_EST
,FTO.QT_DOC_EX_COM_DEFICIENCIA
FROM 
			DW.FTO_DADOS_IES						FTO
LEFT JOIN	DW.DIM_REGIAO							RG		ON	FTO.CO_MUNICIPIO				=	RG.CO_MUNICIPIO
LEFT JOIN	DW.DIM_TIPO_ORGANIZACAO_ACADEMICA		TOA		ON	FTO.TP_ORGANIZACAO_ACADEMICA	=	TOA.TP_ORGANIZACAO_ACADEMICA
LEFT JOIN	DW.DIM_TIPO_CATEGORIA_ADMINISTRATIVA	TCA		ON	FTO.TP_CATEGORIA_ADMINISTRATIVA	=	TCA.TP_CATEGORIA_ADMINISTRATIVA
LEFT JOIN	DW.DIM_IES								IES		ON	FTO.CO_IES						=	IES.CO_IES






go
CREATE OR ALTER VIEW DW.VW_FTO_DADOS_CURSO AS 
SELECT 
 FTO.NU_ANO_CENSO
,RG.CO_MUNICIPIO
,RG.NO_MUNICIPIO
,RG.CO_MICRORREGIAO
,RG.NO_MICRORREGIAO
,RG.CO_MESORREGIAO
,RG.NO_MESORREGIAO
,RG.CO_UF
,RG.NO_UF
,RG.SG_UF
,FTO.IN_CAPITAL
,TDM.TP_DIMENSAO
,TDM.NO_DIMENSAO
,TRD.TP_REDE
,TRD.NO_REDE
,IES.CO_IES
,IES.NO_IES
,IES.SG_IES
,IES.IN_CAPITAL_IES
,IES.CO_MANTENEDORA
,IES.NO_MANTENEDORA
,FTO.CO_CURSO
,C.NO_CURSO
,CINE.CO_CINE_ROTULO
,CINE.NO_CINE_ROTULO
,CINE.CO_CINE_AREA_DETALHADA
,CINE.NO_CINE_AREA_DETALHADA
,CINE.CO_CINE_AREA_ESPECIFICA
,CINE.NO_CINE_AREA_ESPECIFICA
,CINE.CO_CINE_AREA_GERAL
,CINE.NO_CINE_AREA_GERAL
,TGA.TP_GRAU_ACADEMICO
,TGA.NO_GRAU_ACADEMICO
,FTO.IN_GRATUITO
,TME.TP_MODALIDADE_ENSINO
,TME.NO_MODALIDADE_ENSINO
,TNA.TP_NIVEL_ACADEMICO
,TNA.NO_NIVEL_ACADEMICO
,FTO.QT_CURSO
,FTO.QT_VG_TOTAL
,FTO.QT_VG_TOTAL_DIURNO
,FTO.QT_VG_TOTAL_NOTURNO
,FTO.QT_VG_TOTAL_EAD
,FTO.QT_VG_NOVA
,FTO.QT_VG_PROC_SELETIVO
,FTO.QT_VG_REMANESC
,FTO.QT_VG_PROG_ESPECIAL
,FTO.QT_INSCRITO_TOTAL
,FTO.QT_INSCRITO_TOTAL_DIURNO
,FTO.QT_INSCRITO_TOTAL_NOTURNO
,FTO.QT_INSCRITO_TOTAL_EAD
,FTO.QT_INSC_VG_NOVA
,FTO.QT_INSC_PROC_SELETIVO
,FTO.QT_INSC_VG_REMANESC
,FTO.QT_INSC_VG_PROG_ESPECIAL
,FTO.QT_ING
,FTO.QT_ING_FEM
,FTO.QT_ING_MASC
,FTO.QT_ING_DIURNO
,FTO.QT_ING_NOTURNO
,FTO.QT_ING_VG_NOVA
,FTO.QT_ING_VESTIBULAR
,FTO.QT_ING_ENEM
,FTO.QT_ING_AVALIACAO_SERIADA
,FTO.QT_ING_SELECAO_SIMPLIFICA
,FTO.QT_ING_EGR
,FTO.QT_ING_OUTRO_TIPO_SELECAO
,FTO.QT_ING_PROC_SELETIVO
,FTO.QT_ING_VG_REMANESC
,FTO.QT_ING_VG_PROG_ESPECIAL
,FTO.QT_ING_OUTRA_FORMA
,FTO.QT_ING_0_17
,FTO.QT_ING_18_24
,FTO.QT_ING_25_29
,FTO.QT_ING_30_34
,FTO.QT_ING_35_39
,FTO.QT_ING_40_49
,FTO.QT_ING_50_59
,FTO.QT_ING_60_MAIS
,FTO.QT_ING_BRANCA
,FTO.QT_ING_PRETA
,FTO.QT_ING_PARDA
,FTO.QT_ING_AMARELA
,FTO.QT_ING_INDIGENA
,FTO.QT_ING_CORND
,FTO.QT_MAT
,FTO.QT_MAT_FEM
,FTO.QT_MAT_MASC
,FTO.QT_MAT_DIURNO
,FTO.QT_MAT_NOTURNO
,FTO.QT_MAT_0_17
,FTO.QT_MAT_18_24
,FTO.QT_MAT_25_29
,FTO.QT_MAT_30_34
,FTO.QT_MAT_35_39
,FTO.QT_MAT_40_49
,FTO.QT_MAT_50_59
,FTO.QT_MAT_60_MAIS
,FTO.QT_MAT_BRANCA
,FTO.QT_MAT_PRETA
,FTO.QT_MAT_PARDA
,FTO.QT_MAT_AMARELA
,FTO.QT_MAT_INDIGENA
,FTO.QT_MAT_CORND
,FTO.QT_CONC
,FTO.QT_CONC_FEM
,FTO.QT_CONC_MASC
,FTO.QT_CONC_DIURNO
,FTO.QT_CONC_NOTURNO
,FTO.QT_CONC_0_17
,FTO.QT_CONC_18_24
,FTO.QT_CONC_25_29
,FTO.QT_CONC_30_34
,FTO.QT_CONC_35_39
,FTO.QT_CONC_40_49
,FTO.QT_CONC_50_59
,FTO.QT_CONC_60_MAIS
,FTO.QT_CONC_BRANCA
,FTO.QT_CONC_PRETA
,FTO.QT_CONC_PARDA
,FTO.QT_CONC_AMARELA
,FTO.QT_CONC_INDIGENA
,FTO.QT_CONC_CORND
,FTO.QT_ING_NACBRAS
,FTO.QT_ING_NACESTRANG
,FTO.QT_MAT_NACBRAS
,FTO.QT_MAT_NACESTRANG
,FTO.QT_CONC_NACBRAS
,FTO.QT_CONC_NACESTRANG
,FTO.QT_ALUNO_DEFICIENTE
,FTO.QT_ING_DEFICIENTE
,FTO.QT_MAT_DEFICIENTE
,FTO.QT_CONC_DEFICIENTE
,FTO.QT_ING_FINANC
,FTO.QT_ING_FINANC_REEMB
,FTO.QT_ING_FIES
,FTO.QT_ING_RPFIES
,FTO.QT_ING_FINANC_REEMB_OUTROS
,FTO.QT_ING_FINANC_NREEMB
,FTO.QT_ING_PROUNII
,FTO.QT_ING_PROUNIP
,FTO.QT_ING_NRPFIES
,FTO.QT_ING_FINANC_NREEMB_OUTROS
,FTO.QT_MAT_FINANC
,FTO.QT_MAT_FINANC_REEMB
,FTO.QT_MAT_FIES
,FTO.QT_MAT_RPFIES
,FTO.QT_MAT_FINANC_REEMB_OUTROS
,FTO.QT_MAT_FINANC_NREEMB
,FTO.QT_MAT_PROUNII
,FTO.QT_MAT_PROUNIP
,FTO.QT_MAT_NRPFIES
,FTO.QT_MAT_FINANC_NREEMB_OUTROS
,FTO.QT_CONC_FINANC
,FTO.QT_CONC_FINANC_REEMB
,FTO.QT_CONC_FIES
,FTO.QT_CONC_RPFIES
,FTO.QT_CONC_FINANC_REEMB_OUTROS
,FTO.QT_CONC_FINANC_NREEMB
,FTO.QT_CONC_PROUNII
,FTO.QT_CONC_PROUNIP
,FTO.QT_CONC_NRPFIES
,FTO.QT_CONC_FINANC_NREEMB_OUTROS
,FTO.QT_ING_RESERVA_VAGA
,FTO.QT_ING_RVREDEPUBLICA
,FTO.QT_ING_RVETNICO
,FTO.QT_ING_RVPDEF
,FTO.QT_ING_RVSOCIAL_RF
,FTO.QT_ING_RVOUTROS
,FTO.QT_MAT_RESERVA_VAGA
,FTO.QT_MAT_RVREDEPUBLICA
,FTO.QT_MAT_RVETNICO
,FTO.QT_MAT_RVPDEF
,FTO.QT_MAT_RVSOCIAL_RF
,FTO.QT_MAT_RVOUTROS
,FTO.QT_CONC_RESERVA_VAGA
,FTO.QT_CONC_RVREDEPUBLICA
,FTO.QT_CONC_RVETNICO
,FTO.QT_CONC_RVPDEF
,FTO.QT_CONC_RVSOCIAL_RF
,FTO.QT_CONC_RVOUTROS
,FTO.QT_SIT_TRANCADA
,FTO.QT_SIT_DESVINCULADO
,FTO.QT_SIT_TRANSFERIDO
,FTO.QT_SIT_FALECIDO
,FTO.QT_ING_PROCESCPUBLICA
,FTO.QT_ING_PROCESCPRIVADA
,FTO.QT_ING_PROCNAOINFORMADA
,FTO.QT_MAT_PROCESCPUBLICA
,FTO.QT_MAT_PROCESCPRIVADA
,FTO.QT_MAT_PROCNAOINFORMADA
,FTO.QT_CONC_PROCESCPUBLICA
,FTO.QT_CONC_PROCESCPRIVADA
,FTO.QT_CONC_PROCNAOINFORMADA
,FTO.QT_PARFOR
,FTO.QT_ING_PARFOR
,FTO.QT_MAT_PARFOR
,FTO.QT_CONC_PARFOR
,FTO.QT_APOIO_SOCIAL
,FTO.QT_ING_APOIO_SOCIAL
,FTO.QT_MAT_APOIO_SOCIAL
,FTO.QT_CONC_APOIO_SOCIAL
,FTO.QT_ATIV_EXTRACURRICULAR
,FTO.QT_ING_ATIV_EXTRACURRICULAR
,FTO.QT_MAT_ATIV_EXTRACURRICULAR
,FTO.QT_CONC_ATIV_EXTRACURRICULAR
,FTO.QT_MOB_ACADEMICA
,FTO.QT_ING_MOB_ACADEMICA
,FTO.QT_MAT_MOB_ACADEMICA
,FTO.QT_CONC_MOB_ACADEMICA
FROM		DW.FTO_DADOS_CURSO						FTO		
LEFT JOIN	DW.DIM_CURSO							C		ON	FTO.CO_CURSO					=	C.CO_CURSO
LEFT JOIN	DW.DIM_REGIAO							RG		ON	FTO.CO_MUNICIPIO				=	RG.CO_MUNICIPIO
LEFT JOIN	DW.DIM_IES								IES		ON	FTO.CO_IES						=	IES.CO_IES
LEFT JOIN	DW.DIM_CINE								CINE	ON	FTO.CO_CINE_ROTULO				=	CINE.CO_CINE_ROTULO
LEFT JOIN	DW.DIM_TIPO_DIMENSAO					TDM		ON	FTO.TP_DIMENSAO					=	TDM.TP_DIMENSAO
LEFT JOIN	DW.DIM_TIPO_GRAU_ACADEMICO				TGA		ON	FTO.TP_GRAU_ACADEMICO			=	TGA.TP_GRAU_ACADEMICO
LEFT JOIN	DW.DIM_TIPO_REDE						TRD		ON	FTO.TP_REDE						=	TRD.TP_REDE
LEFT JOIN	DW.DIM_TIPO_MODALIDADE_ENSINO			TME		ON	FTO.TP_MODALIDADE_ENSINO		=	TME.TP_MODALIDADE_ENSINO
LEFT JOIN	DW.DIM_TIPO_NIVEL_ACADEMICO				TNA		ON	FTO.TP_NIVEL_ACADEMICO			=	TNA.TP_NIVEL_ACADEMICO

GO
CREATE OR ALTER VIEW DW.VW_FTO_DADOS_FLUXO
as

SELECT 
 FTO.CO_CURSO
,C.NO_CURSO
,CINE.CO_CINE_ROTULO
,CINE.NO_CINE_ROTULO
,CINE.CO_CINE_AREA_DETALHADA
,CINE.NO_CINE_AREA_DETALHADA
,CINE.CO_CINE_AREA_ESPECIFICA
,CINE.NO_CINE_AREA_ESPECIFICA
,CINE.CO_CINE_AREA_GERAL
,CINE.NO_CINE_AREA_GERAL
,RG.CO_MUNICIPIO
,RG.NO_MUNICIPIO
,RG.CO_MICRORREGIAO
,RG.NO_MICRORREGIAO
,RG.CO_MESORREGIAO
,RG.NO_MESORREGIAO
,RG.CO_UF
,RG.NO_UF
,RG.SG_UF
,FTO.IN_CAPITAL
,TDM.TP_DIMENSAO
,TDM.NO_DIMENSAO
,TRD.TP_REDE
,TRD.NO_REDE
,FTO.CO_IES
,TGA.TP_GRAU_ACADEMICO
,TGA.NO_GRAU_ACADEMICO
,FTO.IN_GRATUITO
,TME.TP_MODALIDADE_ENSINO
,TME.NO_MODALIDADE_ENSINO
,TNA.TP_NIVEL_ACADEMICO
,TNA.NO_NIVEL_ACADEMICO
,FTO.NU_ANO_CENSO
,FTO.NU_ANO_INGRESSO
,FTO.NU_PRAZO_INTEGRALIZACAO
,FTO.NU_ANO_INTEGRALIZACAO
,FTO.NU_PRAZO_ACOMPANHAMENTO
,FTO.NU_ANO_MAXIMO_ACOMPANHAMENTO
,FTO.QT_INGRESSANTE
,FTO.QT_PERMANENCIA
,FTO.QT_CONCLUINTE
,FTO.QT_DESISTENCIA
,FTO.QT_FALECIDO
,FTO.VL_TAP
,FTO.VL_TCA
,FTO.VL_TDA
,FTO.VL_TCAN
,FTO.VL_TDAN
,FTO.CO_CATALOGO
FROM 
			DW.FTO_DADOS_FLUXO				FTO		
LEFT JOIN	DW.DIM_CURSO					C		ON	FTO.CO_CURSO					=	C.CO_CURSO
LEFT JOIN	DW.DIM_REGIAO					RG		ON	FTO.CO_MUNICIPIO				=	RG.CO_MUNICIPIO
LEFT JOIN	DW.DIM_IES						IES		ON	FTO.CO_IES						=	IES.CO_IES
LEFT JOIN	DW.DIM_CINE						CINE	ON	FTO.CO_CINE_ROTULO				=	CINE.CO_CINE_ROTULO
LEFT JOIN	DW.DIM_TIPO_DIMENSAO			TDM		ON	FTO.TP_DIMENSAO					=	TDM.TP_DIMENSAO
LEFT JOIN	DW.DIM_TIPO_GRAU_ACADEMICO		TGA		ON	FTO.TP_GRAU_ACADEMICO			=	TGA.TP_GRAU_ACADEMICO
LEFT JOIN	DW.DIM_TIPO_REDE				TRD		ON	FTO.TP_REDE						=	TRD.TP_REDE
LEFT JOIN	DW.DIM_TIPO_MODALIDADE_ENSINO	TME		ON	FTO.TP_MODALIDADE_ENSINO		=	TME.TP_MODALIDADE_ENSINO
LEFT JOIN	DW.DIM_TIPO_NIVEL_ACADEMICO		TNA		ON	FTO.TP_NIVEL_ACADEMICO			=	TNA.TP_NIVEL_ACADEMICO


-- SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'DW' AND TABLE_NAME LIKE 'dIM%'
-- SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'DW' AND TABLE_NAME LIKE 'dIM%'

-- registros de exceção
INSERT INTO DW.DIM_CINE								
(CO_CINE_ROTULO, NO_CINE_ROTULO, CO_CINE_AREA_DETALHADA, NO_CINE_AREA_DETALHADA, CO_CINE_AREA_ESPECIFICA, NO_CINE_AREA_ESPECIFICA, CO_CINE_AREA_GERAL, NO_CINE_AREA_GERAL)
VALUES
('-1', 'Não informado', -1, 'Não informado', -1, 'Não informado', -1, 'Não informado'),
('-2', 'Não se aplica', -2, 'Não se aplica', -2, 'Não se aplica', -2, 'Não se aplica')

INSERT INTO DW.DIM_CURSO							
(CO_CURSO, NO_CURSO) 
VALUES(-1, 'Não informado'), (-2, 'Não se aplica')

INSERT INTO DW.DIM_IES								
(CO_IES,NO_IES,SG_IES,IN_CAPITAL_IES,TP_ORGANIZACAO_ACADEMICA,TP_CATEGORIA_ADMINISTRATIVA,CO_MANTENEDORA,NO_MANTENEDORA)
VALUES
(-1, 'NÃO INFORMADO', 'NI',0,-1,-1,-1,'Não informado' ),
(-2, 'NÃO SE APLICA', 'NA',0,-2,-2,-2,'Não se aplica' )

INSERT INTO DW.DIM_REGIAO							
(CO_MUNICIPIO,NO_MUNICIPIO,CO_MICRORREGIAO,NO_MICRORREGIAO,CO_MESORREGIAO,NO_MESORREGIAO,CO_UF,NO_UF,SG_UF)
VALUES
(-1, 'Não informado', -1,'Não informado', -1, 'Não informado',-1, 'Não informado', 'NI'), 
(-2, 'Não se aplica', -2,'Não se aplica', -2, 'Não se aplica',-2, 'Não se aplica', 'NA') 

INSERT INTO DW.DIM_TIPO_CATEGORIA_ADMINISTRATIVA	
(TP_CATEGORIA_ADMINISTRATIVA,NO_CATEGORIA_ADMINISTRATIVA)
VALUES
(-1, 'Não informado'), (
-2, 'Não se aplica')

INSERT INTO DW.DIM_TIPO_DIMENSAO					
(TP_DIMENSAO,NO_DIMENSAO)
VALUES
(-1, 'Não informado'),
(-2, 'Não se aplica')

INSERT INTO DW.DIM_TIPO_GRAU_ACADEMICO				
(TP_GRAU_ACADEMICO,NO_GRAU_ACADEMICO)
VALUES
(-1, 'Não informado'), 
(-2, 'Não se aplica')

INSERT INTO DW.DIM_TIPO_MODALIDADE_ENSINO			
(TP_MODALIDADE_ENSINO, NO_MODALIDADE_ENSINO)
VALUES
(-1, 'Não informado'),
(-2, 'Não se aplica')

INSERT INTO DW.DIM_TIPO_NIVEL_ACADEMICO				
(TP_NIVEL_ACADEMICO,NO_NIVEL_ACADEMICO)
VALUES
(-1, 'Não informado'),
(-2, 'Não se aplica')

INSERT INTO DW.DIM_TIPO_ORGANIZACAO_ACADEMICA		
(TP_ORGANIZACAO_ACADEMICA, NO_ORGANIZACAO_ACADEMICA)
VALUES
(-1, 'Não informado'),
(-2, 'Não se aplica')

INSERT INTO DW.DIM_TIPO_REDE						
(TP_REDE,NO_REDE)
VALUES(-1, 'Não informado'), (-2, 'Não se aplica')

-- ajustes de registros de exceção

update fto set 	FTO.CO_CURSO				=  -1 from DW.FTO_DADOS_CURSO		FTO	where FTO.CO_CURSO				is null
update fto set 	FTO.CO_MUNICIPIO			=  -1 from DW.FTO_DADOS_CURSO		FTO	where FTO.CO_MUNICIPIO			is null
update fto set 	FTO.CO_IES					=  -1 from DW.FTO_DADOS_CURSO		FTO	where FTO.CO_IES				is null
update fto set 	FTO.CO_CINE_ROTULO			=  -1 from DW.FTO_DADOS_CURSO		FTO	where FTO.CO_CINE_ROTULO		is null
update fto set 	FTO.TP_DIMENSAO				=  -1 from DW.FTO_DADOS_CURSO		FTO	where FTO.TP_DIMENSAO			is null
update fto set 	FTO.TP_GRAU_ACADEMICO		=  -1 from DW.FTO_DADOS_CURSO		FTO	where FTO.TP_GRAU_ACADEMICO		is null
update fto set 	FTO.TP_REDE					=  -1 from DW.FTO_DADOS_CURSO		FTO	where FTO.TP_REDE				is null
update fto set 	FTO.TP_MODALIDADE_ENSINO	=  -1 from DW.FTO_DADOS_CURSO		FTO	where FTO.TP_MODALIDADE_ENSINO	is null
update fto set 	FTO.TP_NIVEL_ACADEMICO		=  -1 from DW.FTO_DADOS_CURSO		FTO	where FTO.TP_NIVEL_ACADEMICO	is null



update fto set 	FTO.CO_MUNICIPIO				=  -1 from DW.FTO_DADOS_IES			FTO	where	FTO.CO_MUNICIPIO					is null
update fto set 	FTO.TP_ORGANIZACAO_ACADEMICA	=  -1 from DW.FTO_DADOS_IES			FTO	where	FTO.TP_ORGANIZACAO_ACADEMICA		is null
update fto set 	FTO.TP_CATEGORIA_ADMINISTRATIVA	=  -1 from DW.FTO_DADOS_IES			FTO	where	FTO.TP_CATEGORIA_ADMINISTRATIVA		is null
update fto set 	FTO.CO_IES						=  -1 from DW.FTO_DADOS_IES			FTO	where	FTO.CO_IES							is null

update fto set 	FTO.CO_CURSO					=  -1 from DW.FTO_DADOS_fluxo		FTO	where	FTO.CO_CURSO						is null
update fto set 	FTO.CO_MUNICIPIO				=  -1 from DW.FTO_DADOS_fluxo		FTO	where	FTO.CO_MUNICIPIO					is null
update fto set 	FTO.TP_DIMENSAO					=  -1 from DW.FTO_DADOS_fluxo		FTO	where	FTO.TP_DIMENSAO						is null
update fto set 	FTO.TP_REDE						=  -1 from DW.FTO_DADOS_fluxo		FTO	where	FTO.TP_REDE							is null
update fto set 	FTO.CO_IES						=  -1 from DW.FTO_DADOS_fluxo		FTO	where	FTO.CO_IES							is null
update fto set 	FTO.CO_CINE_ROTULO				=  -1 from DW.FTO_DADOS_fluxo		FTO	where	FTO.CO_CINE_ROTULO					is null
update fto set 	FTO.TP_GRAU_ACADEMICO			=  -1 from DW.FTO_DADOS_fluxo		FTO	where	FTO.TP_GRAU_ACADEMICO				is null
update fto set 	FTO.TP_MODALIDADE_ENSINO		=  -1 from DW.FTO_DADOS_fluxo		FTO	where	FTO.TP_MODALIDADE_ENSINO			is null
update fto set 	FTO.TP_NIVEL_ACADEMICO			=  -1 from DW.FTO_DADOS_fluxo		FTO	where	FTO.TP_NIVEL_ACADEMICO				is null

-- verificação de membro inferido		-- ANALISAR MEMBRO INFERIDO DE COD_IES 
select distinct	fto.CO_CURSO					from 	DW.FTO_DADOS_CURSO	FTO		LEFT JOIN	DW.DIM_CURSO					C		ON	FTO.CO_CURSO			=	C.CO_CURSO					where C.CO_CURSO				is null
select distinct	fto.CO_MUNICIPIO				from 	DW.FTO_DADOS_CURSO	FTO		LEFT JOIN	DW.DIM_REGIAO					RG		ON	FTO.CO_MUNICIPIO		=	RG.CO_MUNICIPIO				where RG.CO_MUNICIPIO			is null
select distinct	fto.CO_IES						from 	DW.FTO_DADOS_CURSO	FTO		LEFT JOIN	DW.DIM_IES						IES		ON	FTO.CO_IES				=	IES.CO_IES					where IES.CO_IES				is null
select distinct	fto.CO_CINE_ROTULO				from 	DW.FTO_DADOS_CURSO	FTO		LEFT JOIN	DW.DIM_CINE						CINE	ON	FTO.CO_CINE_ROTULO		=	CINE.CO_CINE_ROTULO			where CINE.CO_CINE_ROTULO		is null
select distinct	fto.TP_DIMENSAO					from 	DW.FTO_DADOS_CURSO	FTO		LEFT JOIN	DW.DIM_TIPO_DIMENSAO			TDM		ON	FTO.TP_DIMENSAO			=	TDM.TP_DIMENSAO				where TDM.TP_DIMENSAO			is null
select distinct	fto.TP_GRAU_ACADEMICO			from 	DW.FTO_DADOS_CURSO	FTO		LEFT JOIN	DW.DIM_TIPO_GRAU_ACADEMICO		TGA		ON	FTO.TP_GRAU_ACADEMICO	=	TGA.TP_GRAU_ACADEMICO		where TGA.TP_GRAU_ACADEMICO		is null
select distinct	fto.TP_REDE						from 	DW.FTO_DADOS_CURSO	FTO		LEFT JOIN	DW.DIM_TIPO_REDE				TRD		ON	FTO.TP_REDE				=	TRD.TP_REDE					where TRD.TP_REDE				is null
select distinct	fto.TP_MODALIDADE_ENSINO		from 	DW.FTO_DADOS_CURSO	FTO		LEFT JOIN	DW.DIM_TIPO_MODALIDADE_ENSINO	TME		ON	FTO.TP_MODALIDADE_ENSINO=	TME.TP_MODALIDADE_ENSINO	where TME.TP_MODALIDADE_ENSINO	is null
select distinct	fto.TP_NIVEL_ACADEMICO			from 	DW.FTO_DADOS_CURSO	FTO		LEFT JOIN	DW.DIM_TIPO_NIVEL_ACADEMICO		TNA		ON	FTO.TP_NIVEL_ACADEMICO	=	TNA.TP_NIVEL_ACADEMICO		where TNA.TP_NIVEL_ACADEMICO	is null

select distinct FTO.CO_MUNICIPIO				from	DW.FTO_DADOS_IES	FTO		LEFT JOIN	DW.DIM_REGIAO							RG		ON	FTO.CO_MUNICIPIO				=	RG.CO_MUNICIPIO					WHERE RG.CO_MUNICIPIO					IS NULL
select distinct FTO.TP_ORGANIZACAO_ACADEMICA	from	DW.FTO_DADOS_IES	FTO		LEFT JOIN	DW.DIM_TIPO_ORGANIZACAO_ACADEMICA		TOA		ON	FTO.TP_ORGANIZACAO_ACADEMICA	=	TOA.TP_ORGANIZACAO_ACADEMICA	WHERE TOA.TP_ORGANIZACAO_ACADEMICA		IS NULL
select distinct FTO.TP_CATEGORIA_ADMINISTRATIVA	from	DW.FTO_DADOS_IES	FTO		LEFT JOIN	DW.DIM_TIPO_CATEGORIA_ADMINISTRATIVA	TCA		ON	FTO.TP_CATEGORIA_ADMINISTRATIVA	=	TCA.TP_CATEGORIA_ADMINISTRATIVA	WHERE TCA.TP_CATEGORIA_ADMINISTRATIVA	IS NULL
select distinct FTO.CO_IES						from	DW.FTO_DADOS_IES	FTO		LEFT JOIN	DW.DIM_IES								IES		ON	FTO.CO_IES						=	IES.CO_IES						WHERE IES.CO_IES						IS NULL


-- ANALISAR CASOS DE FLUXO SEM DADOS DE CENSO E INDICADORES
SELECT COUNT(ISNULL(NU_ANO_CENSO,0)), CO_CATALOGO FROM  DW.VW_FTO_DADOS_FLUXO	WHERE NU_ANO_CENSO IS NULL
GROUP BY CO_CATALOGO 


