-- use tcc_evasao
SELECT file_id,
       name,
       CAST(FILEPROPERTY(name, 'SpaceUsed') AS bigint) * 8 / 1024. AS space_used_mb,
       CAST(size AS bigint) * 8 / 1024. AS space_allocated_mb,
       CAST(max_size AS bigint) * 8 / 1024. AS max_file_size_mb
FROM sys.database_files
WHERE type_desc IN ('ROWS','LOG');



SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME LIKE 'MICRODADOS_CADASTRO_CURSOS%'

CREATE CLUSTERED INDEX IXC_MICRODADOS_CADASTRO_CURSOS_2010 ON MICRODADOS_CADASTRO_CURSOS_2010 (CO_CURSO)
CREATE CLUSTERED INDEX IXC_MICRODADOS_CADASTRO_CURSOS_2011 ON MICRODADOS_CADASTRO_CURSOS_2011 (CO_CURSO)
CREATE CLUSTERED INDEX IXC_MICRODADOS_CADASTRO_CURSOS_2012 ON MICRODADOS_CADASTRO_CURSOS_2012 (CO_CURSO)
CREATE CLUSTERED INDEX IXC_MICRODADOS_CADASTRO_CURSOS_2013 ON MICRODADOS_CADASTRO_CURSOS_2013 (CO_CURSO)
CREATE CLUSTERED INDEX IXC_MICRODADOS_CADASTRO_CURSOS_2014 ON MICRODADOS_CADASTRO_CURSOS_2014 (CO_CURSO)
CREATE CLUSTERED INDEX IXC_MICRODADOS_CADASTRO_CURSOS_2015 ON MICRODADOS_CADASTRO_CURSOS_2015 (CO_CURSO)
CREATE CLUSTERED INDEX IXC_MICRODADOS_CADASTRO_CURSOS_2016 ON MICRODADOS_CADASTRO_CURSOS_2016 (CO_CURSO)
CREATE CLUSTERED INDEX IXC_MICRODADOS_CADASTRO_CURSOS_2017 ON MICRODADOS_CADASTRO_CURSOS_2017 (CO_CURSO)
CREATE CLUSTERED INDEX IXC_MICRODADOS_CADASTRO_CURSOS_2018 ON MICRODADOS_CADASTRO_CURSOS_2018 (CO_CURSO)
CREATE CLUSTERED INDEX IXC_MICRODADOS_CADASTRO_CURSOS_2019 ON MICRODADOS_CADASTRO_CURSOS_2019 (CO_CURSO)
CREATE CLUSTERED INDEX IXC_MICRODADOS_CADASTRO_CURSOS_2020 ON MICRODADOS_CADASTRO_CURSOS_2020 (CO_CURSO)
CREATE CLUSTERED INDEX IXC_MICRODADOS_CADASTRO_CURSOS_2021 ON MICRODADOS_CADASTRO_CURSOS_2021 (CO_CURSO)


SELECT * FROM DW.DIM_IES WHERE NO_IES ='nÃO CADASTRADO'

 SELECT * FROM STG.STG_MICRODADOS_CADASTRO_CURSOS_SP WHERE CO_CURSO IN (SELECT CO_CURSO FROM DW.DIM_curso WHERE NO_CURSO ='nÃO CADASTRADO')
 SELECT * FROM STG.STG_MICRODADOS_CADASTRO_ies_SP WHERE CO_ies IN (SELECT co_ies FROM DW.DIM_ies WHERE NO_IES ='nÃO CADASTRADO')
 
 




DROP TABLE IF EXISTS STG.STG_MICRODADOS_CADASTRO_CURSOS_SP
SELECT * INTO stg.STG_MICRODADOS_CADASTRO_CURSOS_SP
		 FROM  MICRODADOS_CADASTRO_CURSOS_2010 WHERE SG_UF = 'SP' UNION 
SELECT * FROM  MICRODADOS_CADASTRO_CURSOS_2011 WHERE SG_UF = 'SP' UNION 
SELECT * FROM  MICRODADOS_CADASTRO_CURSOS_2012 WHERE SG_UF = 'SP' UNION 
SELECT * FROM  MICRODADOS_CADASTRO_CURSOS_2013 WHERE SG_UF = 'SP' UNION 
SELECT * FROM  MICRODADOS_CADASTRO_CURSOS_2014 WHERE SG_UF = 'SP' UNION 
SELECT * FROM  MICRODADOS_CADASTRO_CURSOS_2015 WHERE SG_UF = 'SP' UNION 
SELECT * FROM  MICRODADOS_CADASTRO_CURSOS_2016 WHERE SG_UF = 'SP' UNION 
SELECT * FROM  MICRODADOS_CADASTRO_CURSOS_2017 WHERE SG_UF = 'SP' UNION 
SELECT * FROM  MICRODADOS_CADASTRO_CURSOS_2018 WHERE SG_UF = 'SP' UNION 
SELECT * FROM  MICRODADOS_CADASTRO_CURSOS_2019 WHERE SG_UF = 'SP' UNION 
SELECT * FROM  MICRODADOS_CADASTRO_CURSOS_2020 WHERE SG_UF = 'SP' UNION 
SELECT * FROM  MICRODADOS_CADASTRO_CURSOS_2021 WHERE SG_UF = 'SP' 


drop INDEX IXC_STG_MICRODADOS_CADASTRO_CURSO_SP ON STG.STG_MICRODADOS_CADASTRO_CURSOS_SP
alter table [stg].[STG_MICRODADOS_CADASTRO_CURSOS_SP] alter column nu_ANO_CENSO	smallint
CREATE CLUSTERED INDEX IXC_STG_MICRODADOS_CADASTRO_CURSO_SP ON STG.STG_MICRODADOS_CADASTRO_CURSOS_SP(NU_ANO_CENSO, CO_CURSO, CO_IES)


SELECT DISTINCT CO_IES INTO #IES_SP FROM [stg].[STG_MICRODADOS_CADASTRO_CURSOS_SP]
CREATE CLUSTERED INDEX IXC_IES_SP ON #IES_SP  (CO_IES) 

SELECT DISTINCT CO_CURSO INTO #CURSO_SP FROM [stg].[STG_MICRODADOS_CADASTRO_CURSOS_SP]
CREATE CLUSTERED INDEX IXC_CURSO_SP ON #CURSO_SP  (CO_CURSO) 

drop table if exists stg.STG_MICRODADOS_CADASTRO_IES_SP
SELECT MC.NU_ANO_CENSO,MC.NO_REGIAO_IES,MC.CO_REGIAO_IES,MC.NO_UF_IES,MC.SG_UF_IES,MC.CO_UF_IES,MC.NO_MUNICIPIO_IES,MC.CO_MUNICIPIO_IES,MC.IN_CAPITAL_IES,MC.NO_MESORREGIAO_IES,MC.CO_MESORREGIAO_IES,MC.NO_MICRORREGIAO_IES,MC.CO_MICRORREGIAO_IES,MC.TP_ORGANIZACAO_ACADEMICA,MC.TP_CATEGORIA_ADMINISTRATIVA,MC.NO_MANTENEDORA,MC.CO_MANTENEDORA,MC.CO_IES,MC.NO_IES,MC.SG_IES,MC.DS_ENDERECO_IES,MC.DS_NUMERO_ENDERECO_IES,MC.DS_COMPLEMENTO_ENDERECO_IES,MC.NO_BAIRRO_IES,MC.NU_CEP_IES,MC.QT_TEC_TOTAL,MC.QT_TEC_FUNDAMENTAL_INCOMP_FEM,MC.QT_TEC_FUNDAMENTAL_INCOMP_MASC,MC.QT_TEC_FUNDAMENTAL_COMP_FEM,MC.QT_TEC_FUNDAMENTAL_COMP_MASC,MC.QT_TEC_MEDIO_FEM,MC.QT_TEC_MEDIO_MASC,MC.QT_TEC_SUPERIOR_FEM,MC.QT_TEC_SUPERIOR_MASC,MC.QT_TEC_ESPECIALIZACAO_FEM,MC.QT_TEC_ESPECIALIZACAO_MASC,MC.QT_TEC_MESTRADO_FEM,MC.QT_TEC_MESTRADO_MASC,MC.QT_TEC_DOUTORADO_FEM,MC.QT_TEC_DOUTORADO_MASC,MC.IN_ACESSO_PORTAL_CAPES,MC.IN_ACESSO_OUTRAS_BASES,MC.IN_ASSINA_OUTRA_BASE,MC.IN_REPOSITORIO_INSTITUCIONAL,MC.IN_BUSCA_INTEGRADA,MC.IN_SERVICO_INTERNET,MC.IN_PARTICIPA_REDE_SOCIAL,MC.IN_CATALOGO_ONLINE,MC.QT_PERIODICO_ELETRONICO,MC.QT_LIVRO_ELETRONICO,MC.QT_DOC_TOTAL,MC.QT_DOC_EXE,MC.QT_DOC_EX_FEMI,MC.QT_DOC_EX_MASC,MC.QT_DOC_EX_SEM_GRAD,MC.QT_DOC_EX_GRAD,MC.QT_DOC_EX_ESP,MC.QT_DOC_EX_MEST,MC.QT_DOC_EX_DOUT,MC.QT_DOC_EX_INT,MC.QT_DOC_EX_INT_DE,MC.QT_DOC_EX_INT_SEM_DE,MC.QT_DOC_EX_PARC,MC.QT_DOC_EX_HOR,MC.QT_DOC_EX_0_29,MC.QT_DOC_EX_30_34,MC.QT_DOC_EX_35_39,MC.QT_DOC_EX_40_44,MC.QT_DOC_EX_45_49,MC.QT_DOC_EX_50_54,MC.QT_DOC_EX_55_59,MC.QT_DOC_EX_60_MAIS,MC.QT_DOC_EX_BRANCA,MC.QT_DOC_EX_PRETA,MC.QT_DOC_EX_PARDA,MC.QT_DOC_EX_AMARELA,MC.QT_DOC_EX_INDIGENA,MC.QT_DOC_EX_COR_ND,MC.QT_DOC_EX_BRA,MC.QT_DOC_EX_EST,MC.QT_DOC_EX_COM_DEFICIENCIA
INTO   stg.STG_MICRODADOS_CADASTRO_IES_SP
																																																																																																																																																																																																																																																																																																																																																																																																																																												FROM 	MICRODADOS_CADASTRO_IES_2010 MC INNER JOIN  #IES_SP  IES ON MC.CO_IES = IES.CO_IES UNION			
SELECT MC.NU_ANO_CENSO,MC.NO_REGIAO_IES,MC.CO_REGIAO_IES,MC.NO_UF_IES,MC.SG_UF_IES,MC.CO_UF_IES,MC.NO_MUNICIPIO_IES,MC.CO_MUNICIPIO_IES,MC.IN_CAPITAL_IES,MC.NO_MESORREGIAO_IES,MC.CO_MESORREGIAO_IES,MC.NO_MICRORREGIAO_IES,MC.CO_MICRORREGIAO_IES,MC.TP_ORGANIZACAO_ACADEMICA,MC.TP_CATEGORIA_ADMINISTRATIVA,MC.NO_MANTENEDORA,MC.CO_MANTENEDORA,MC.CO_IES,MC.NO_IES,MC.SG_IES,MC.DS_ENDERECO_IES,MC.DS_NUMERO_ENDERECO_IES,MC.DS_COMPLEMENTO_ENDERECO_IES,MC.NO_BAIRRO_IES,MC.NU_CEP_IES,MC.QT_TEC_TOTAL,MC.QT_TEC_FUNDAMENTAL_INCOMP_FEM,MC.QT_TEC_FUNDAMENTAL_INCOMP_MASC,MC.QT_TEC_FUNDAMENTAL_COMP_FEM,MC.QT_TEC_FUNDAMENTAL_COMP_MASC,MC.QT_TEC_MEDIO_FEM,MC.QT_TEC_MEDIO_MASC,MC.QT_TEC_SUPERIOR_FEM,MC.QT_TEC_SUPERIOR_MASC,MC.QT_TEC_ESPECIALIZACAO_FEM,MC.QT_TEC_ESPECIALIZACAO_MASC,MC.QT_TEC_MESTRADO_FEM,MC.QT_TEC_MESTRADO_MASC,MC.QT_TEC_DOUTORADO_FEM,MC.QT_TEC_DOUTORADO_MASC,MC.IN_ACESSO_PORTAL_CAPES,MC.IN_ACESSO_OUTRAS_BASES,MC.IN_ASSINA_OUTRA_BASE,MC.IN_REPOSITORIO_INSTITUCIONAL,MC.IN_BUSCA_INTEGRADA,MC.IN_SERVICO_INTERNET,MC.IN_PARTICIPA_REDE_SOCIAL,MC.IN_CATALOGO_ONLINE,MC.QT_PERIODICO_ELETRONICO,MC.QT_LIVRO_ELETRONICO,MC.QT_DOC_TOTAL,MC.QT_DOC_EXE,MC.QT_DOC_EX_FEMI,MC.QT_DOC_EX_MASC,MC.QT_DOC_EX_SEM_GRAD,MC.QT_DOC_EX_GRAD,MC.QT_DOC_EX_ESP,MC.QT_DOC_EX_MEST,MC.QT_DOC_EX_DOUT,MC.QT_DOC_EX_INT,MC.QT_DOC_EX_INT_DE,MC.QT_DOC_EX_INT_SEM_DE,MC.QT_DOC_EX_PARC,MC.QT_DOC_EX_HOR,MC.QT_DOC_EX_0_29,MC.QT_DOC_EX_30_34,MC.QT_DOC_EX_35_39,MC.QT_DOC_EX_40_44,MC.QT_DOC_EX_45_49,MC.QT_DOC_EX_50_54,MC.QT_DOC_EX_55_59,MC.QT_DOC_EX_60_MAIS,MC.QT_DOC_EX_BRANCA,MC.QT_DOC_EX_PRETA,MC.QT_DOC_EX_PARDA,MC.QT_DOC_EX_AMARELA,MC.QT_DOC_EX_INDIGENA,MC.QT_DOC_EX_COR_ND,MC.QT_DOC_EX_BRA,MC.QT_DOC_EX_EST,MC.QT_DOC_EX_COM_DEFICIENCIA	FROM	MICRODADOS_CADASTRO_IES_2011 MC INNER JOIN  #IES_SP  IES ON MC.CO_IES = IES.CO_IES  UNION 
SELECT MC.NU_ANO_CENSO,MC.NO_REGIAO_IES,MC.CO_REGIAO_IES,MC.NO_UF_IES,MC.SG_UF_IES,MC.CO_UF_IES,MC.NO_MUNICIPIO_IES,MC.CO_MUNICIPIO_IES,MC.IN_CAPITAL_IES,MC.NO_MESORREGIAO_IES,MC.CO_MESORREGIAO_IES,MC.NO_MICRORREGIAO_IES,MC.CO_MICRORREGIAO_IES,MC.TP_ORGANIZACAO_ACADEMICA,MC.TP_CATEGORIA_ADMINISTRATIVA,MC.NO_MANTENEDORA,MC.CO_MANTENEDORA,MC.CO_IES,MC.NO_IES,MC.SG_IES,MC.DS_ENDERECO_IES,MC.DS_NUMERO_ENDERECO_IES,MC.DS_COMPLEMENTO_ENDERECO_IES,MC.NO_BAIRRO_IES,MC.NU_CEP_IES,MC.QT_TEC_TOTAL,MC.QT_TEC_FUNDAMENTAL_INCOMP_FEM,MC.QT_TEC_FUNDAMENTAL_INCOMP_MASC,MC.QT_TEC_FUNDAMENTAL_COMP_FEM,MC.QT_TEC_FUNDAMENTAL_COMP_MASC,MC.QT_TEC_MEDIO_FEM,MC.QT_TEC_MEDIO_MASC,MC.QT_TEC_SUPERIOR_FEM,MC.QT_TEC_SUPERIOR_MASC,MC.QT_TEC_ESPECIALIZACAO_FEM,MC.QT_TEC_ESPECIALIZACAO_MASC,MC.QT_TEC_MESTRADO_FEM,MC.QT_TEC_MESTRADO_MASC,MC.QT_TEC_DOUTORADO_FEM,MC.QT_TEC_DOUTORADO_MASC,MC.IN_ACESSO_PORTAL_CAPES,MC.IN_ACESSO_OUTRAS_BASES,MC.IN_ASSINA_OUTRA_BASE,MC.IN_REPOSITORIO_INSTITUCIONAL,MC.IN_BUSCA_INTEGRADA,MC.IN_SERVICO_INTERNET,MC.IN_PARTICIPA_REDE_SOCIAL,MC.IN_CATALOGO_ONLINE,MC.QT_PERIODICO_ELETRONICO,MC.QT_LIVRO_ELETRONICO,MC.QT_DOC_TOTAL,MC.QT_DOC_EXE,MC.QT_DOC_EX_FEMI,MC.QT_DOC_EX_MASC,MC.QT_DOC_EX_SEM_GRAD,MC.QT_DOC_EX_GRAD,MC.QT_DOC_EX_ESP,MC.QT_DOC_EX_MEST,MC.QT_DOC_EX_DOUT,MC.QT_DOC_EX_INT,MC.QT_DOC_EX_INT_DE,MC.QT_DOC_EX_INT_SEM_DE,MC.QT_DOC_EX_PARC,MC.QT_DOC_EX_HOR,MC.QT_DOC_EX_0_29,MC.QT_DOC_EX_30_34,MC.QT_DOC_EX_35_39,MC.QT_DOC_EX_40_44,MC.QT_DOC_EX_45_49,MC.QT_DOC_EX_50_54,MC.QT_DOC_EX_55_59,MC.QT_DOC_EX_60_MAIS,MC.QT_DOC_EX_BRANCA,MC.QT_DOC_EX_PRETA,MC.QT_DOC_EX_PARDA,MC.QT_DOC_EX_AMARELA,MC.QT_DOC_EX_INDIGENA,MC.QT_DOC_EX_COR_ND,MC.QT_DOC_EX_BRA,MC.QT_DOC_EX_EST,MC.QT_DOC_EX_COM_DEFICIENCIA	FROM	MICRODADOS_CADASTRO_IES_2012 MC INNER JOIN  #IES_SP  IES ON MC.CO_IES = IES.CO_IES  UNION 
SELECT MC.NU_ANO_CENSO,MC.NO_REGIAO_IES,MC.CO_REGIAO_IES,MC.NO_UF_IES,MC.SG_UF_IES,MC.CO_UF_IES,MC.NO_MUNICIPIO_IES,MC.CO_MUNICIPIO_IES,MC.IN_CAPITAL_IES,MC.NO_MESORREGIAO_IES,MC.CO_MESORREGIAO_IES,MC.NO_MICRORREGIAO_IES,MC.CO_MICRORREGIAO_IES,MC.TP_ORGANIZACAO_ACADEMICA,MC.TP_CATEGORIA_ADMINISTRATIVA,MC.NO_MANTENEDORA,MC.CO_MANTENEDORA,MC.CO_IES,MC.NO_IES,MC.SG_IES,MC.DS_ENDERECO_IES,MC.DS_NUMERO_ENDERECO_IES,MC.DS_COMPLEMENTO_ENDERECO_IES,MC.NO_BAIRRO_IES,MC.NU_CEP_IES,MC.QT_TEC_TOTAL,MC.QT_TEC_FUNDAMENTAL_INCOMP_FEM,MC.QT_TEC_FUNDAMENTAL_INCOMP_MASC,MC.QT_TEC_FUNDAMENTAL_COMP_FEM,MC.QT_TEC_FUNDAMENTAL_COMP_MASC,MC.QT_TEC_MEDIO_FEM,MC.QT_TEC_MEDIO_MASC,MC.QT_TEC_SUPERIOR_FEM,MC.QT_TEC_SUPERIOR_MASC,MC.QT_TEC_ESPECIALIZACAO_FEM,MC.QT_TEC_ESPECIALIZACAO_MASC,MC.QT_TEC_MESTRADO_FEM,MC.QT_TEC_MESTRADO_MASC,MC.QT_TEC_DOUTORADO_FEM,MC.QT_TEC_DOUTORADO_MASC,MC.IN_ACESSO_PORTAL_CAPES,MC.IN_ACESSO_OUTRAS_BASES,MC.IN_ASSINA_OUTRA_BASE,MC.IN_REPOSITORIO_INSTITUCIONAL,MC.IN_BUSCA_INTEGRADA,MC.IN_SERVICO_INTERNET,MC.IN_PARTICIPA_REDE_SOCIAL,MC.IN_CATALOGO_ONLINE,MC.QT_PERIODICO_ELETRONICO,MC.QT_LIVRO_ELETRONICO,MC.QT_DOC_TOTAL,MC.QT_DOC_EXE,MC.QT_DOC_EX_FEMI,MC.QT_DOC_EX_MASC,MC.QT_DOC_EX_SEM_GRAD,MC.QT_DOC_EX_GRAD,MC.QT_DOC_EX_ESP,MC.QT_DOC_EX_MEST,MC.QT_DOC_EX_DOUT,MC.QT_DOC_EX_INT,MC.QT_DOC_EX_INT_DE,MC.QT_DOC_EX_INT_SEM_DE,MC.QT_DOC_EX_PARC,MC.QT_DOC_EX_HOR,MC.QT_DOC_EX_0_29,MC.QT_DOC_EX_30_34,MC.QT_DOC_EX_35_39,MC.QT_DOC_EX_40_44,MC.QT_DOC_EX_45_49,MC.QT_DOC_EX_50_54,MC.QT_DOC_EX_55_59,MC.QT_DOC_EX_60_MAIS,MC.QT_DOC_EX_BRANCA,MC.QT_DOC_EX_PRETA,MC.QT_DOC_EX_PARDA,MC.QT_DOC_EX_AMARELA,MC.QT_DOC_EX_INDIGENA,MC.QT_DOC_EX_COR_ND,MC.QT_DOC_EX_BRA,MC.QT_DOC_EX_EST,MC.QT_DOC_EX_COM_DEFICIENCIA	FROM	MICRODADOS_CADASTRO_IES_2013 MC INNER JOIN  #IES_SP  IES ON MC.CO_IES = IES.CO_IES  UNION 
SELECT MC.NU_ANO_CENSO,MC.NO_REGIAO_IES,MC.CO_REGIAO_IES,MC.NO_UF_IES,MC.SG_UF_IES,MC.CO_UF_IES,MC.NO_MUNICIPIO_IES,MC.CO_MUNICIPIO_IES,MC.IN_CAPITAL_IES,MC.NO_MESORREGIAO_IES,MC.CO_MESORREGIAO_IES,MC.NO_MICRORREGIAO_IES,MC.CO_MICRORREGIAO_IES,MC.TP_ORGANIZACAO_ACADEMICA,MC.TP_CATEGORIA_ADMINISTRATIVA,MC.NO_MANTENEDORA,MC.CO_MANTENEDORA,MC.CO_IES,MC.NO_IES,MC.SG_IES,MC.DS_ENDERECO_IES,MC.DS_NUMERO_ENDERECO_IES,MC.DS_COMPLEMENTO_ENDERECO_IES,MC.NO_BAIRRO_IES,MC.NU_CEP_IES,MC.QT_TEC_TOTAL,MC.QT_TEC_FUNDAMENTAL_INCOMP_FEM,MC.QT_TEC_FUNDAMENTAL_INCOMP_MASC,MC.QT_TEC_FUNDAMENTAL_COMP_FEM,MC.QT_TEC_FUNDAMENTAL_COMP_MASC,MC.QT_TEC_MEDIO_FEM,MC.QT_TEC_MEDIO_MASC,MC.QT_TEC_SUPERIOR_FEM,MC.QT_TEC_SUPERIOR_MASC,MC.QT_TEC_ESPECIALIZACAO_FEM,MC.QT_TEC_ESPECIALIZACAO_MASC,MC.QT_TEC_MESTRADO_FEM,MC.QT_TEC_MESTRADO_MASC,MC.QT_TEC_DOUTORADO_FEM,MC.QT_TEC_DOUTORADO_MASC,MC.IN_ACESSO_PORTAL_CAPES,MC.IN_ACESSO_OUTRAS_BASES,MC.IN_ASSINA_OUTRA_BASE,MC.IN_REPOSITORIO_INSTITUCIONAL,MC.IN_BUSCA_INTEGRADA,MC.IN_SERVICO_INTERNET,MC.IN_PARTICIPA_REDE_SOCIAL,MC.IN_CATALOGO_ONLINE,MC.QT_PERIODICO_ELETRONICO,MC.QT_LIVRO_ELETRONICO,MC.QT_DOC_TOTAL,MC.QT_DOC_EXE,MC.QT_DOC_EX_FEMI,MC.QT_DOC_EX_MASC,MC.QT_DOC_EX_SEM_GRAD,MC.QT_DOC_EX_GRAD,MC.QT_DOC_EX_ESP,MC.QT_DOC_EX_MEST,MC.QT_DOC_EX_DOUT,MC.QT_DOC_EX_INT,MC.QT_DOC_EX_INT_DE,MC.QT_DOC_EX_INT_SEM_DE,MC.QT_DOC_EX_PARC,MC.QT_DOC_EX_HOR,MC.QT_DOC_EX_0_29,MC.QT_DOC_EX_30_34,MC.QT_DOC_EX_35_39,MC.QT_DOC_EX_40_44,MC.QT_DOC_EX_45_49,MC.QT_DOC_EX_50_54,MC.QT_DOC_EX_55_59,MC.QT_DOC_EX_60_MAIS,MC.QT_DOC_EX_BRANCA,MC.QT_DOC_EX_PRETA,MC.QT_DOC_EX_PARDA,MC.QT_DOC_EX_AMARELA,MC.QT_DOC_EX_INDIGENA,MC.QT_DOC_EX_COR_ND,MC.QT_DOC_EX_BRA,MC.QT_DOC_EX_EST,MC.QT_DOC_EX_COM_DEFICIENCIA	FROM	MICRODADOS_CADASTRO_IES_2014 MC INNER JOIN  #IES_SP  IES ON MC.CO_IES = IES.CO_IES  UNION 
SELECT MC.NU_ANO_CENSO,MC.NO_REGIAO_IES,MC.CO_REGIAO_IES,MC.NO_UF_IES,MC.SG_UF_IES,MC.CO_UF_IES,MC.NO_MUNICIPIO_IES,MC.CO_MUNICIPIO_IES,MC.IN_CAPITAL_IES,MC.NO_MESORREGIAO_IES,MC.CO_MESORREGIAO_IES,MC.NO_MICRORREGIAO_IES,MC.CO_MICRORREGIAO_IES,MC.TP_ORGANIZACAO_ACADEMICA,MC.TP_CATEGORIA_ADMINISTRATIVA,MC.NO_MANTENEDORA,MC.CO_MANTENEDORA,MC.CO_IES,MC.NO_IES,MC.SG_IES,MC.DS_ENDERECO_IES,MC.DS_NUMERO_ENDERECO_IES,MC.DS_COMPLEMENTO_ENDERECO_IES,MC.NO_BAIRRO_IES,MC.NU_CEP_IES,MC.QT_TEC_TOTAL,MC.QT_TEC_FUNDAMENTAL_INCOMP_FEM,MC.QT_TEC_FUNDAMENTAL_INCOMP_MASC,MC.QT_TEC_FUNDAMENTAL_COMP_FEM,MC.QT_TEC_FUNDAMENTAL_COMP_MASC,MC.QT_TEC_MEDIO_FEM,MC.QT_TEC_MEDIO_MASC,MC.QT_TEC_SUPERIOR_FEM,MC.QT_TEC_SUPERIOR_MASC,MC.QT_TEC_ESPECIALIZACAO_FEM,MC.QT_TEC_ESPECIALIZACAO_MASC,MC.QT_TEC_MESTRADO_FEM,MC.QT_TEC_MESTRADO_MASC,MC.QT_TEC_DOUTORADO_FEM,MC.QT_TEC_DOUTORADO_MASC,MC.IN_ACESSO_PORTAL_CAPES,MC.IN_ACESSO_OUTRAS_BASES,MC.IN_ASSINA_OUTRA_BASE,MC.IN_REPOSITORIO_INSTITUCIONAL,MC.IN_BUSCA_INTEGRADA,MC.IN_SERVICO_INTERNET,MC.IN_PARTICIPA_REDE_SOCIAL,MC.IN_CATALOGO_ONLINE,MC.QT_PERIODICO_ELETRONICO,MC.QT_LIVRO_ELETRONICO,MC.QT_DOC_TOTAL,MC.QT_DOC_EXE,MC.QT_DOC_EX_FEMI,MC.QT_DOC_EX_MASC,MC.QT_DOC_EX_SEM_GRAD,MC.QT_DOC_EX_GRAD,MC.QT_DOC_EX_ESP,MC.QT_DOC_EX_MEST,MC.QT_DOC_EX_DOUT,MC.QT_DOC_EX_INT,MC.QT_DOC_EX_INT_DE,MC.QT_DOC_EX_INT_SEM_DE,MC.QT_DOC_EX_PARC,MC.QT_DOC_EX_HOR,MC.QT_DOC_EX_0_29,MC.QT_DOC_EX_30_34,MC.QT_DOC_EX_35_39,MC.QT_DOC_EX_40_44,MC.QT_DOC_EX_45_49,MC.QT_DOC_EX_50_54,MC.QT_DOC_EX_55_59,MC.QT_DOC_EX_60_MAIS,MC.QT_DOC_EX_BRANCA,MC.QT_DOC_EX_PRETA,MC.QT_DOC_EX_PARDA,MC.QT_DOC_EX_AMARELA,MC.QT_DOC_EX_INDIGENA,MC.QT_DOC_EX_COR_ND,MC.QT_DOC_EX_BRA,MC.QT_DOC_EX_EST,MC.QT_DOC_EX_COM_DEFICIENCIA	FROM	MICRODADOS_CADASTRO_IES_2015 MC INNER JOIN  #IES_SP  IES ON MC.CO_IES = IES.CO_IES  UNION 
SELECT MC.NU_ANO_CENSO,MC.NO_REGIAO_IES,MC.CO_REGIAO_IES,MC.NO_UF_IES,MC.SG_UF_IES,MC.CO_UF_IES,MC.NO_MUNICIPIO_IES,MC.CO_MUNICIPIO_IES,MC.IN_CAPITAL_IES,MC.NO_MESORREGIAO_IES,MC.CO_MESORREGIAO_IES,MC.NO_MICRORREGIAO_IES,MC.CO_MICRORREGIAO_IES,MC.TP_ORGANIZACAO_ACADEMICA,MC.TP_CATEGORIA_ADMINISTRATIVA,MC.NO_MANTENEDORA,MC.CO_MANTENEDORA,MC.CO_IES,MC.NO_IES,MC.SG_IES,MC.DS_ENDERECO_IES,MC.DS_NUMERO_ENDERECO_IES,MC.DS_COMPLEMENTO_ENDERECO_IES,MC.NO_BAIRRO_IES,MC.NU_CEP_IES,MC.QT_TEC_TOTAL,MC.QT_TEC_FUNDAMENTAL_INCOMP_FEM,MC.QT_TEC_FUNDAMENTAL_INCOMP_MASC,MC.QT_TEC_FUNDAMENTAL_COMP_FEM,MC.QT_TEC_FUNDAMENTAL_COMP_MASC,MC.QT_TEC_MEDIO_FEM,MC.QT_TEC_MEDIO_MASC,MC.QT_TEC_SUPERIOR_FEM,MC.QT_TEC_SUPERIOR_MASC,MC.QT_TEC_ESPECIALIZACAO_FEM,MC.QT_TEC_ESPECIALIZACAO_MASC,MC.QT_TEC_MESTRADO_FEM,MC.QT_TEC_MESTRADO_MASC,MC.QT_TEC_DOUTORADO_FEM,MC.QT_TEC_DOUTORADO_MASC,MC.IN_ACESSO_PORTAL_CAPES,MC.IN_ACESSO_OUTRAS_BASES,MC.IN_ASSINA_OUTRA_BASE,MC.IN_REPOSITORIO_INSTITUCIONAL,MC.IN_BUSCA_INTEGRADA,MC.IN_SERVICO_INTERNET,MC.IN_PARTICIPA_REDE_SOCIAL,MC.IN_CATALOGO_ONLINE,MC.QT_PERIODICO_ELETRONICO,MC.QT_LIVRO_ELETRONICO,MC.QT_DOC_TOTAL,MC.QT_DOC_EXE,MC.QT_DOC_EX_FEMI,MC.QT_DOC_EX_MASC,MC.QT_DOC_EX_SEM_GRAD,MC.QT_DOC_EX_GRAD,MC.QT_DOC_EX_ESP,MC.QT_DOC_EX_MEST,MC.QT_DOC_EX_DOUT,MC.QT_DOC_EX_INT,MC.QT_DOC_EX_INT_DE,MC.QT_DOC_EX_INT_SEM_DE,MC.QT_DOC_EX_PARC,MC.QT_DOC_EX_HOR,MC.QT_DOC_EX_0_29,MC.QT_DOC_EX_30_34,MC.QT_DOC_EX_35_39,MC.QT_DOC_EX_40_44,MC.QT_DOC_EX_45_49,MC.QT_DOC_EX_50_54,MC.QT_DOC_EX_55_59,MC.QT_DOC_EX_60_MAIS,MC.QT_DOC_EX_BRANCA,MC.QT_DOC_EX_PRETA,MC.QT_DOC_EX_PARDA,MC.QT_DOC_EX_AMARELA,MC.QT_DOC_EX_INDIGENA,MC.QT_DOC_EX_COR_ND,MC.QT_DOC_EX_BRA,MC.QT_DOC_EX_EST,MC.QT_DOC_EX_COM_DEFICIENCIA	FROM	MICRODADOS_CADASTRO_IES_2016 MC INNER JOIN  #IES_SP  IES ON MC.CO_IES = IES.CO_IES  UNION 
SELECT MC.NU_ANO_CENSO,MC.NO_REGIAO_IES,MC.CO_REGIAO_IES,MC.NO_UF_IES,MC.SG_UF_IES,MC.CO_UF_IES,MC.NO_MUNICIPIO_IES,MC.CO_MUNICIPIO_IES,MC.IN_CAPITAL_IES,MC.NO_MESORREGIAO_IES,MC.CO_MESORREGIAO_IES,MC.NO_MICRORREGIAO_IES,MC.CO_MICRORREGIAO_IES,MC.TP_ORGANIZACAO_ACADEMICA,MC.TP_CATEGORIA_ADMINISTRATIVA,MC.NO_MANTENEDORA,MC.CO_MANTENEDORA,MC.CO_IES,MC.NO_IES,MC.SG_IES,MC.DS_ENDERECO_IES,MC.DS_NUMERO_ENDERECO_IES,MC.DS_COMPLEMENTO_ENDERECO_IES,MC.NO_BAIRRO_IES,MC.NU_CEP_IES,MC.QT_TEC_TOTAL,MC.QT_TEC_FUNDAMENTAL_INCOMP_FEM,MC.QT_TEC_FUNDAMENTAL_INCOMP_MASC,MC.QT_TEC_FUNDAMENTAL_COMP_FEM,MC.QT_TEC_FUNDAMENTAL_COMP_MASC,MC.QT_TEC_MEDIO_FEM,MC.QT_TEC_MEDIO_MASC,MC.QT_TEC_SUPERIOR_FEM,MC.QT_TEC_SUPERIOR_MASC,MC.QT_TEC_ESPECIALIZACAO_FEM,MC.QT_TEC_ESPECIALIZACAO_MASC,MC.QT_TEC_MESTRADO_FEM,MC.QT_TEC_MESTRADO_MASC,MC.QT_TEC_DOUTORADO_FEM,MC.QT_TEC_DOUTORADO_MASC,MC.IN_ACESSO_PORTAL_CAPES,MC.IN_ACESSO_OUTRAS_BASES,MC.IN_ASSINA_OUTRA_BASE,MC.IN_REPOSITORIO_INSTITUCIONAL,MC.IN_BUSCA_INTEGRADA,MC.IN_SERVICO_INTERNET,MC.IN_PARTICIPA_REDE_SOCIAL,MC.IN_CATALOGO_ONLINE,MC.QT_PERIODICO_ELETRONICO,MC.QT_LIVRO_ELETRONICO,MC.QT_DOC_TOTAL,MC.QT_DOC_EXE,MC.QT_DOC_EX_FEMI,MC.QT_DOC_EX_MASC,MC.QT_DOC_EX_SEM_GRAD,MC.QT_DOC_EX_GRAD,MC.QT_DOC_EX_ESP,MC.QT_DOC_EX_MEST,MC.QT_DOC_EX_DOUT,MC.QT_DOC_EX_INT,MC.QT_DOC_EX_INT_DE,MC.QT_DOC_EX_INT_SEM_DE,MC.QT_DOC_EX_PARC,MC.QT_DOC_EX_HOR,MC.QT_DOC_EX_0_29,MC.QT_DOC_EX_30_34,MC.QT_DOC_EX_35_39,MC.QT_DOC_EX_40_44,MC.QT_DOC_EX_45_49,MC.QT_DOC_EX_50_54,MC.QT_DOC_EX_55_59,MC.QT_DOC_EX_60_MAIS,MC.QT_DOC_EX_BRANCA,MC.QT_DOC_EX_PRETA,MC.QT_DOC_EX_PARDA,MC.QT_DOC_EX_AMARELA,MC.QT_DOC_EX_INDIGENA,MC.QT_DOC_EX_COR_ND,MC.QT_DOC_EX_BRA,MC.QT_DOC_EX_EST,MC.QT_DOC_EX_COM_DEFICIENCIA	FROM	MICRODADOS_CADASTRO_IES_2017 MC INNER JOIN  #IES_SP  IES ON MC.CO_IES = IES.CO_IES  UNION 
SELECT MC.NU_ANO_CENSO,MC.NO_REGIAO_IES,MC.CO_REGIAO_IES,MC.NO_UF_IES,MC.SG_UF_IES,MC.CO_UF_IES,MC.NO_MUNICIPIO_IES,MC.CO_MUNICIPIO_IES,MC.IN_CAPITAL_IES,MC.NO_MESORREGIAO_IES,MC.CO_MESORREGIAO_IES,MC.NO_MICRORREGIAO_IES,MC.CO_MICRORREGIAO_IES,MC.TP_ORGANIZACAO_ACADEMICA,MC.TP_CATEGORIA_ADMINISTRATIVA,MC.NO_MANTENEDORA,MC.CO_MANTENEDORA,MC.CO_IES,MC.NO_IES,MC.SG_IES,MC.DS_ENDERECO_IES,MC.DS_NUMERO_ENDERECO_IES,MC.DS_COMPLEMENTO_ENDERECO_IES,MC.NO_BAIRRO_IES,MC.NU_CEP_IES,MC.QT_TEC_TOTAL,MC.QT_TEC_FUNDAMENTAL_INCOMP_FEM,MC.QT_TEC_FUNDAMENTAL_INCOMP_MASC,MC.QT_TEC_FUNDAMENTAL_COMP_FEM,MC.QT_TEC_FUNDAMENTAL_COMP_MASC,MC.QT_TEC_MEDIO_FEM,MC.QT_TEC_MEDIO_MASC,MC.QT_TEC_SUPERIOR_FEM,MC.QT_TEC_SUPERIOR_MASC,MC.QT_TEC_ESPECIALIZACAO_FEM,MC.QT_TEC_ESPECIALIZACAO_MASC,MC.QT_TEC_MESTRADO_FEM,MC.QT_TEC_MESTRADO_MASC,MC.QT_TEC_DOUTORADO_FEM,MC.QT_TEC_DOUTORADO_MASC,MC.IN_ACESSO_PORTAL_CAPES,MC.IN_ACESSO_OUTRAS_BASES,MC.IN_ASSINA_OUTRA_BASE,MC.IN_REPOSITORIO_INSTITUCIONAL,MC.IN_BUSCA_INTEGRADA,MC.IN_SERVICO_INTERNET,MC.IN_PARTICIPA_REDE_SOCIAL,MC.IN_CATALOGO_ONLINE,MC.QT_PERIODICO_ELETRONICO,MC.QT_LIVRO_ELETRONICO,MC.QT_DOC_TOTAL,MC.QT_DOC_EXE,MC.QT_DOC_EX_FEMI,MC.QT_DOC_EX_MASC,MC.QT_DOC_EX_SEM_GRAD,MC.QT_DOC_EX_GRAD,MC.QT_DOC_EX_ESP,MC.QT_DOC_EX_MEST,MC.QT_DOC_EX_DOUT,MC.QT_DOC_EX_INT,MC.QT_DOC_EX_INT_DE,MC.QT_DOC_EX_INT_SEM_DE,MC.QT_DOC_EX_PARC,MC.QT_DOC_EX_HOR,MC.QT_DOC_EX_0_29,MC.QT_DOC_EX_30_34,MC.QT_DOC_EX_35_39,MC.QT_DOC_EX_40_44,MC.QT_DOC_EX_45_49,MC.QT_DOC_EX_50_54,MC.QT_DOC_EX_55_59,MC.QT_DOC_EX_60_MAIS,MC.QT_DOC_EX_BRANCA,MC.QT_DOC_EX_PRETA,MC.QT_DOC_EX_PARDA,MC.QT_DOC_EX_AMARELA,MC.QT_DOC_EX_INDIGENA,MC.QT_DOC_EX_COR_ND,MC.QT_DOC_EX_BRA,MC.QT_DOC_EX_EST,MC.QT_DOC_EX_COM_DEFICIENCIA	FROM	MICRODADOS_CADASTRO_IES_2018 MC INNER JOIN  #IES_SP  IES ON MC.CO_IES = IES.CO_IES  UNION 
SELECT MC.NU_ANO_CENSO,MC.NO_REGIAO_IES,MC.CO_REGIAO_IES,MC.NO_UF_IES,MC.SG_UF_IES,MC.CO_UF_IES,MC.NO_MUNICIPIO_IES,MC.CO_MUNICIPIO_IES,MC.IN_CAPITAL_IES,MC.NO_MESORREGIAO_IES,MC.CO_MESORREGIAO_IES,MC.NO_MICRORREGIAO_IES,MC.CO_MICRORREGIAO_IES,MC.TP_ORGANIZACAO_ACADEMICA,MC.TP_CATEGORIA_ADMINISTRATIVA,MC.NO_MANTENEDORA,MC.CO_MANTENEDORA,MC.CO_IES,MC.NO_IES,MC.SG_IES,MC.DS_ENDERECO_IES,MC.DS_NUMERO_ENDERECO_IES,MC.DS_COMPLEMENTO_ENDERECO_IES,MC.NO_BAIRRO_IES,MC.NU_CEP_IES,MC.QT_TEC_TOTAL,MC.QT_TEC_FUNDAMENTAL_INCOMP_FEM,MC.QT_TEC_FUNDAMENTAL_INCOMP_MASC,MC.QT_TEC_FUNDAMENTAL_COMP_FEM,MC.QT_TEC_FUNDAMENTAL_COMP_MASC,MC.QT_TEC_MEDIO_FEM,MC.QT_TEC_MEDIO_MASC,MC.QT_TEC_SUPERIOR_FEM,MC.QT_TEC_SUPERIOR_MASC,MC.QT_TEC_ESPECIALIZACAO_FEM,MC.QT_TEC_ESPECIALIZACAO_MASC,MC.QT_TEC_MESTRADO_FEM,MC.QT_TEC_MESTRADO_MASC,MC.QT_TEC_DOUTORADO_FEM,MC.QT_TEC_DOUTORADO_MASC,MC.IN_ACESSO_PORTAL_CAPES,MC.IN_ACESSO_OUTRAS_BASES,MC.IN_ASSINA_OUTRA_BASE,MC.IN_REPOSITORIO_INSTITUCIONAL,MC.IN_BUSCA_INTEGRADA,MC.IN_SERVICO_INTERNET,MC.IN_PARTICIPA_REDE_SOCIAL,MC.IN_CATALOGO_ONLINE,MC.QT_PERIODICO_ELETRONICO,MC.QT_LIVRO_ELETRONICO,MC.QT_DOC_TOTAL,MC.QT_DOC_EXE,MC.QT_DOC_EX_FEMI,MC.QT_DOC_EX_MASC,MC.QT_DOC_EX_SEM_GRAD,MC.QT_DOC_EX_GRAD,MC.QT_DOC_EX_ESP,MC.QT_DOC_EX_MEST,MC.QT_DOC_EX_DOUT,MC.QT_DOC_EX_INT,MC.QT_DOC_EX_INT_DE,MC.QT_DOC_EX_INT_SEM_DE,MC.QT_DOC_EX_PARC,MC.QT_DOC_EX_HOR,MC.QT_DOC_EX_0_29,MC.QT_DOC_EX_30_34,MC.QT_DOC_EX_35_39,MC.QT_DOC_EX_40_44,MC.QT_DOC_EX_45_49,MC.QT_DOC_EX_50_54,MC.QT_DOC_EX_55_59,MC.QT_DOC_EX_60_MAIS,MC.QT_DOC_EX_BRANCA,MC.QT_DOC_EX_PRETA,MC.QT_DOC_EX_PARDA,MC.QT_DOC_EX_AMARELA,MC.QT_DOC_EX_INDIGENA,MC.QT_DOC_EX_COR_ND,MC.QT_DOC_EX_BRA,MC.QT_DOC_EX_EST,MC.QT_DOC_EX_COM_DEFICIENCIA	FROM	MICRODADOS_CADASTRO_IES_2019 MC INNER JOIN  #IES_SP  IES ON MC.CO_IES = IES.CO_IES  UNION 
SELECT MC.NU_ANO_CENSO,MC.NO_REGIAO_IES,MC.CO_REGIAO_IES,MC.NO_UF_IES,MC.SG_UF_IES,MC.CO_UF_IES,MC.NO_MUNICIPIO_IES,MC.CO_MUNICIPIO_IES,MC.IN_CAPITAL_IES,MC.NO_MESORREGIAO_IES,MC.CO_MESORREGIAO_IES,MC.NO_MICRORREGIAO_IES,MC.CO_MICRORREGIAO_IES,MC.TP_ORGANIZACAO_ACADEMICA,MC.TP_CATEGORIA_ADMINISTRATIVA,MC.NO_MANTENEDORA,MC.CO_MANTENEDORA,MC.CO_IES,MC.NO_IES,MC.SG_IES,MC.DS_ENDERECO_IES,MC.DS_NUMERO_ENDERECO_IES,MC.DS_COMPLEMENTO_ENDERECO_IES,MC.NO_BAIRRO_IES,MC.NU_CEP_IES,MC.QT_TEC_TOTAL,MC.QT_TEC_FUNDAMENTAL_INCOMP_FEM,MC.QT_TEC_FUNDAMENTAL_INCOMP_MASC,MC.QT_TEC_FUNDAMENTAL_COMP_FEM,MC.QT_TEC_FUNDAMENTAL_COMP_MASC,MC.QT_TEC_MEDIO_FEM,MC.QT_TEC_MEDIO_MASC,MC.QT_TEC_SUPERIOR_FEM,MC.QT_TEC_SUPERIOR_MASC,MC.QT_TEC_ESPECIALIZACAO_FEM,MC.QT_TEC_ESPECIALIZACAO_MASC,MC.QT_TEC_MESTRADO_FEM,MC.QT_TEC_MESTRADO_MASC,MC.QT_TEC_DOUTORADO_FEM,MC.QT_TEC_DOUTORADO_MASC,MC.IN_ACESSO_PORTAL_CAPES,MC.IN_ACESSO_OUTRAS_BASES,MC.IN_ASSINA_OUTRA_BASE,MC.IN_REPOSITORIO_INSTITUCIONAL,MC.IN_BUSCA_INTEGRADA,MC.IN_SERVICO_INTERNET,MC.IN_PARTICIPA_REDE_SOCIAL,MC.IN_CATALOGO_ONLINE,MC.QT_PERIODICO_ELETRONICO,MC.QT_LIVRO_ELETRONICO,MC.QT_DOC_TOTAL,MC.QT_DOC_EXE,MC.QT_DOC_EX_FEMI,MC.QT_DOC_EX_MASC,MC.QT_DOC_EX_SEM_GRAD,MC.QT_DOC_EX_GRAD,MC.QT_DOC_EX_ESP,MC.QT_DOC_EX_MEST,MC.QT_DOC_EX_DOUT,MC.QT_DOC_EX_INT,MC.QT_DOC_EX_INT_DE,MC.QT_DOC_EX_INT_SEM_DE,MC.QT_DOC_EX_PARC,MC.QT_DOC_EX_HOR,MC.QT_DOC_EX_0_29,MC.QT_DOC_EX_30_34,MC.QT_DOC_EX_35_39,MC.QT_DOC_EX_40_44,MC.QT_DOC_EX_45_49,MC.QT_DOC_EX_50_54,MC.QT_DOC_EX_55_59,MC.QT_DOC_EX_60_MAIS,MC.QT_DOC_EX_BRANCA,MC.QT_DOC_EX_PRETA,MC.QT_DOC_EX_PARDA,MC.QT_DOC_EX_AMARELA,MC.QT_DOC_EX_INDIGENA,MC.QT_DOC_EX_COR_ND,MC.QT_DOC_EX_BRA,MC.QT_DOC_EX_EST,MC.QT_DOC_EX_COM_DEFICIENCIA	FROM	MICRODADOS_CADASTRO_IES_2020 MC INNER JOIN  #IES_SP  IES ON MC.CO_IES = IES.CO_IES  UNION 
SELECT MC.NU_ANO_CENSO,MC.NO_REGIAO_IES,MC.CO_REGIAO_IES,MC.NO_UF_IES,MC.SG_UF_IES,MC.CO_UF_IES,MC.NO_MUNICIPIO_IES,MC.CO_MUNICIPIO_IES,MC.IN_CAPITAL_IES,MC.NO_MESORREGIAO_IES,MC.CO_MESORREGIAO_IES,MC.NO_MICRORREGIAO_IES,MC.CO_MICRORREGIAO_IES,MC.TP_ORGANIZACAO_ACADEMICA,MC.TP_CATEGORIA_ADMINISTRATIVA,MC.NO_MANTENEDORA,MC.CO_MANTENEDORA,MC.CO_IES,MC.NO_IES,MC.SG_IES,MC.DS_ENDERECO_IES,MC.DS_NUMERO_ENDERECO_IES,MC.DS_COMPLEMENTO_ENDERECO_IES,MC.NO_BAIRRO_IES,MC.NU_CEP_IES,MC.QT_TEC_TOTAL,MC.QT_TEC_FUNDAMENTAL_INCOMP_FEM,MC.QT_TEC_FUNDAMENTAL_INCOMP_MASC,MC.QT_TEC_FUNDAMENTAL_COMP_FEM,MC.QT_TEC_FUNDAMENTAL_COMP_MASC,MC.QT_TEC_MEDIO_FEM,MC.QT_TEC_MEDIO_MASC,MC.QT_TEC_SUPERIOR_FEM,MC.QT_TEC_SUPERIOR_MASC,MC.QT_TEC_ESPECIALIZACAO_FEM,MC.QT_TEC_ESPECIALIZACAO_MASC,MC.QT_TEC_MESTRADO_FEM,MC.QT_TEC_MESTRADO_MASC,MC.QT_TEC_DOUTORADO_FEM,MC.QT_TEC_DOUTORADO_MASC,MC.IN_ACESSO_PORTAL_CAPES,MC.IN_ACESSO_OUTRAS_BASES,MC.IN_ASSINA_OUTRA_BASE,MC.IN_REPOSITORIO_INSTITUCIONAL,MC.IN_BUSCA_INTEGRADA,MC.IN_SERVICO_INTERNET,MC.IN_PARTICIPA_REDE_SOCIAL,MC.IN_CATALOGO_ONLINE,MC.QT_PERIODICO_ELETRONICO,MC.QT_LIVRO_ELETRONICO,MC.QT_DOC_TOTAL,MC.QT_DOC_EXE,MC.QT_DOC_EX_FEMI,MC.QT_DOC_EX_MASC,MC.QT_DOC_EX_SEM_GRAD,MC.QT_DOC_EX_GRAD,MC.QT_DOC_EX_ESP,MC.QT_DOC_EX_MEST,MC.QT_DOC_EX_DOUT,MC.QT_DOC_EX_INT,MC.QT_DOC_EX_INT_DE,MC.QT_DOC_EX_INT_SEM_DE,MC.QT_DOC_EX_PARC,MC.QT_DOC_EX_HOR,MC.QT_DOC_EX_0_29,MC.QT_DOC_EX_30_34,MC.QT_DOC_EX_35_39,MC.QT_DOC_EX_40_44,MC.QT_DOC_EX_45_49,MC.QT_DOC_EX_50_54,MC.QT_DOC_EX_55_59,MC.QT_DOC_EX_60_MAIS,MC.QT_DOC_EX_BRANCA,MC.QT_DOC_EX_PRETA,MC.QT_DOC_EX_PARDA,MC.QT_DOC_EX_AMARELA,MC.QT_DOC_EX_INDIGENA,MC.QT_DOC_EX_COR_ND,MC.QT_DOC_EX_BRA,MC.QT_DOC_EX_EST,MC.QT_DOC_EX_COM_DEFICIENCIA	FROM	MICRODADOS_CADASTRO_IES_2021 MC INNER JOIN  #IES_SP  IES ON MC.CO_IES = IES.CO_IES  

CREATE CLUSTERED INDEX IXC_STG_MICRODADOS_CADASTRO_IES_SP ON STG.STG_MICRODADOS_CADASTRO_IES_SP(NU_ANO_CENSO, CO_IES)



DROP TABLE IF EXISTS STG.STG_INDICADORES_TRAJETORIA_EDUCACAO_SUPERIOR_SP
select T.*,	1  CO_CATALOGO
		into STG.STG_INDICADORES_TRAJETORIA_EDUCACAO_SUPERIOR_SP
			  from indicadores_trajetoria_educacao_superior_2011_2020	t inner join #IES_SP ies on ies.co_ies = t.[Código_da_Instituição]	INNER JOIN #CURSO_SP CURSO ON CURSO.CO_CURSO = T.Código_do_Curso_de_Graduação union
select T.*, 2 from indicadores_trajetoria_educacao_superior_2012_2021	t inner join #IES_SP ies on ies.co_ies = t.[Código_da_Instituição]	INNER JOIN #CURSO_SP CURSO ON CURSO.CO_CURSO = T.Código_do_Curso_de_Graduação union
select T.*, 3 from indicadores_trajetoria_educacao_superior_2013_2021	t inner join #IES_SP ies on ies.co_ies = t.[Código_da_Instituição]	INNER JOIN #CURSO_SP CURSO ON CURSO.CO_CURSO = T.Código_do_Curso_de_Graduação union
select T.*, 4 from indicadores_trajetoria_educacao_superior_2014_2021	t inner join #IES_SP ies on ies.co_ies = t.[Código_da_Instituição]	INNER JOIN #CURSO_SP CURSO ON CURSO.CO_CURSO = T.Código_do_Curso_de_Graduação union
select T.*, 5 from indicadores_trajetoria_educacao_superior_2015_2021	t inner join #IES_SP ies on ies.co_ies = t.[Código_da_Instituição]	INNER JOIN #CURSO_SP CURSO ON CURSO.CO_CURSO = T.Código_do_Curso_de_Graduação union
select T.*, 6 from indicadores_trajetoria_educacao_superior_2016_2021	t inner join #IES_SP ies on ies.co_ies = t.[Código_da_Instituição]	INNER JOIN #CURSO_SP CURSO ON CURSO.CO_CURSO = T.Código_do_Curso_de_Graduação union
select T.*, 7 from indicadores_trajetoria_educacao_superior_2017_2021	t inner join #IES_SP ies on ies.co_ies = t.[Código_da_Instituição]	INNER JOIN #CURSO_SP CURSO ON CURSO.CO_CURSO = T.Código_do_Curso_de_Graduação

drop INDEX IXC_STG_INDICADORES_TRAJETORIA_EDUCACAO_SUPERIOR_SP ON [stg].[STG_INDICADORES_TRAJETORIA_EDUCACAO_SUPERIOR_SP]
CREATE CLUSTERED INDEX IXC_STG_INDICADORES_TRAJETORIA_EDUCACAO_SUPERIOR_SP ON [stg].[STG_INDICADORES_TRAJETORIA_EDUCACAO_SUPERIOR_SP](Código_da_Instituição, Código_do_Curso_de_Graduação, Código_do_Município_do_Curso)






SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME LIKE 'indicadores_trajetoria_educacao_superior%'

DROP TABLE IF EXISTS STG.STG_INDICADORES_TRAJETORIA_EDUCACAO_SUPERIOR_SP
select T.*,	1  CO_CATALOGO
		into STG.STG_INDICADORES_TRAJETORIA_EDUCACAO_SUPERIOR_SP
			from indicadores_trajetoria_educacao_superior_2011_2020 t inner join stg.STG_MICRODADOS_CADASTRO_IES_SP ies on ies.co_ies = t.[Código_da_Instituição] union
select T.*, 2 from indicadores_trajetoria_educacao_superior_2012_2021 t inner join stg.STG_MICRODADOS_CADASTRO_IES_SP ies on ies.co_ies = t.[Código_da_Instituição] union
select T.*, 3 from indicadores_trajetoria_educacao_superior_2013_2021 t inner join stg.STG_MICRODADOS_CADASTRO_IES_SP ies on ies.co_ies = t.[Código_da_Instituição] union
select T.*, 4 from indicadores_trajetoria_educacao_superior_2014_2021 t inner join stg.STG_MICRODADOS_CADASTRO_IES_SP ies on ies.co_ies = t.[Código_da_Instituição] union
select T.*, 5 from indicadores_trajetoria_educacao_superior_2015_2021 t inner join stg.STG_MICRODADOS_CADASTRO_IES_SP ies on ies.co_ies = t.[Código_da_Instituição] union
select T.*, 6 from indicadores_trajetoria_educacao_superior_2016_2021 t inner join stg.STG_MICRODADOS_CADASTRO_IES_SP ies on ies.co_ies = t.[Código_da_Instituição] union
select T.*, 7 from indicadores_trajetoria_educacao_superior_2017_2021 t inner join stg.STG_MICRODADOS_CADASTRO_IES_SP ies on ies.co_ies = t.[Código_da_Instituição]

drop INDEX IXC_STG_INDICADORES_TRAJETORIA_EDUCACAO_SUPERIOR_SP ON [stg].[STG_INDICADORES_TRAJETORIA_EDUCACAO_SUPERIOR_SP]
CREATE CLUSTERED INDEX IXC_STG_INDICADORES_TRAJETORIA_EDUCACAO_SUPERIOR_SP ON [stg].[STG_INDICADORES_TRAJETORIA_EDUCACAO_SUPERIOR_SP](Código_da_Instituição, Código_do_Curso_de_Graduação, Código_do_Município_do_Curso)

----------------------------------------------------------------------------------------


-- LOGICA DE CRIAÇÃO DAS TABELAS 
-- 1 - DROPAR TABELA SE EXISTIR 
-- 2 - CRIAR TABELA A PARTIR DE SELECT DISTINCT (SELECT INTO)
-- 3 - ALTERAR COLUNA DE CODIGO PARA NOT NULL 
-- 4 - CRIAR CHAVE PRIMARIA NA TABELA 


--- HIERARQUIA DE REGIÃO - REGIÃO -> UF -> MESORREGIAO -> _MICRORREGIAO -> MUNICIPIO
--- OBS.: TABELAS CRIADAS INICIALMENTE SEM PK E FK

-- TABELAS COM DADOS DE TODAS OS ESTADOS 
-- DROP TABLE IF EXISTS ODS.ODS_REGIAO
-- SELECT DISTINCT CO_REGIAO, NO_REGIAO
--INTO ODS.ODS_REGIAO
-- FROM 	[stg].[STG_RELATORIO_DTB_BRASIL_DISTRITO]
-- CREATE CLUSTERED INDEX IXC_ODS_REGIAO_IES ON ODS.ODS_REGIAO (CO_REGIAO)

/*
select max(len(co_regiao)) from ODS.ODS_REGIAO
alter table ODS.ODS_REGIAO alter column co_regiao tinyint not null
alter table ODS.ODS_REGIAO alter column no_regiao varchar(20)
*/
/*
DROP TABLE IF EXISTS ODS.ODS_UNIDADE_FEDERATIVA
SELECT DISTINCT CO_UF_IES, NO_UF_IES,SG_UF_IES
INTO ODS.ODS_UNIDADE_FEDERATIVA
FROM 	MICRODADOS_CADASTRO_IES_2010   UNION 
SELECT CO_UF_IES, NO_UF_IES,SG_UF_IES FROM	MICRODADOS_CADASTRO_IES_2011 UNION 
SELECT CO_UF_IES, NO_UF_IES,SG_UF_IES FROM	MICRODADOS_CADASTRO_IES_2012 UNION 
SELECT CO_UF_IES, NO_UF_IES,SG_UF_IES FROM	MICRODADOS_CADASTRO_IES_2013 UNION 
SELECT CO_UF_IES, NO_UF_IES,SG_UF_IES FROM	MICRODADOS_CADASTRO_IES_2014 UNION 
SELECT CO_UF_IES, NO_UF_IES,SG_UF_IES FROM	MICRODADOS_CADASTRO_IES_2015 UNION 
SELECT CO_UF_IES, NO_UF_IES,SG_UF_IES FROM	MICRODADOS_CADASTRO_IES_2016 UNION 
SELECT CO_UF_IES, NO_UF_IES,SG_UF_IES FROM	MICRODADOS_CADASTRO_IES_2017 UNION 
SELECT CO_UF_IES, NO_UF_IES,SG_UF_IES FROM	MICRODADOS_CADASTRO_IES_2018 UNION 
SELECT CO_UF_IES, NO_UF_IES,SG_UF_IES FROM	MICRODADOS_CADASTRO_IES_2019 UNION 
SELECT CO_UF_IES, NO_UF_IES,SG_UF_IES FROM	MICRODADOS_CADASTRO_IES_2020 UNION 
SELECT CO_UF_IES, NO_UF_IES,SG_UF_IES FROM	MICRODADOS_CADASTRO_IES_2021 
*/
-----------------------------------------------------------------------------------------------

-- -- TABELAS COM DADOS DE REGIÃO SOMENTE DO ESTADO DE SP
/*
DROP TABLE IF EXISTS  ODS.ODS_MESORREGIAO_IES
SELECT DISTINCT CO_MESORREGIAO_IES, NO_MESORREGIAO_IES
INTO ODS.ODS_MESORREGIAO_IES
	FROM STG.[STG_MICRODADOS_CADASTRO_IES_SP]
ALTER TABLE ODS.ODS_MESORREGIAO_IES ALTER COLUMN CO_MESORREGIAO_IES INT NOT NULL
ALTER TABLE ODS.ODS_MESORREGIAO_IES ADD CONSTRAINT PK_ODS_MESORREGIAO_IES  PRIMARY KEY (CO_MESORREGIAO_IES)


DROP TABLE IF EXISTS ODS.ODS_MICRORREGIAO_IES
SELECT DISTINCT CO_MICRORREGIAO_IES, NO_MICRORREGIAO_IES, CO_MESORREGIAO_IES, CO_UF_IES
 INTO ODS.ODS_MICRORREGIAO_IES
	FROM STG.[STG_MICRODADOS_CADASTRO_IES_SP]
ALTER TABLE ODS.ODS_MICRORREGIAO_IES ALTER COLUMN CO_MICRORREGIAO_IES INT NOT NULL
ALTER TABLE ODS.ODS_MICRORREGIAO_IES ADD CONSTRAINT PK_ODS_MICRORREGIAO_IES  PRIMARY KEY (CO_MICRORREGIAO_IES)

DROP TABLE IF EXISTS  ODS.ODS_MUNICIPIO_IES
SELECT DISTINCT CO_MUNICIPIO_IES, NO_MUNICIPIO_IES,CO_MESORREGIAO_IES
INTO ODS.ODS_MUNICIPIO_IES
	FROM STG.[STG_MICRODADOS_CADASTRO_IES_SP]
ALTER TABLE ODS.ODS_MUNICIPIO_IES ALTER COLUMN CO_MUNICIPIO_IES INT NOT NULL
ALTER TABLE ODS.ODS_MUNICIPIO_IES ADD CONSTRAINT PK_ODS_MUNICIPIO_IES  PRIMARY KEY (CO_MUNICIPIO_IES)



DROP TABLE IF EXISTS  ODS.ODS_MUNICIPIO
SELECT DISTINCT 
	Código_Município_Completo	CO_MUNICIPIO,
	Nome_Município NO_MUNICIPIO,
	Mesorregião_Geográfica CO_MESORREGIAO_IES
INTO ODS.ODS_MUNICIPIO
	FROM [RELATORIO_DTB_BRASIL_DISTRITO]
	where uf = 35 /*São Paulo*/



select * from ODS.ODS_MESORREGIAO_IES
SELECT distinct 
      [Mesorregião_Geográfica]
      ,[Nome_Mesorregião]     
  FROM [tcc_evasao].[dbo].[RELATORIO_DTB_BRASIL_DISTRITO]
  where uf = 35

  select co_microrregiao_ies, no_microrregiao_ies from ODS.ODS_MICRORREGIAO_IES
  except 
SELECT distinct 
      [Microrregião_Geográfica]
      ,[Nome_Microrregião]
	  ,[Mesorregião_Geográfica]
  FROM [tcc_evasao].[dbo].[RELATORIO_DTB_BRASIL_DISTRITO]
  where uf = 35


 SELECT distinct 
      [Microrregião_Geográfica]
      ,[Nome_Microrregião]
  FROM [tcc_evasao].[dbo].[RELATORIO_DTB_BRASIL_DISTRITO]
  where uf = 35
  except 
  select co_microrregiao_ies, no_microrregiao_ies from ODS.ODS_MICRORREGIAO_IES
*/
drop table if exists #municipio 
 select distinct co_municipio into #municipio from [stg].[STG_MICRODADOS_CADASTRO_CURSOS_SP]
		union 
		select distinct co_municipio_ies from [stg].[STG_MICRODADOS_CADASTRO_ies_SP]
  create clustered index ixc_municipio on #municipio (co_municipio )
  



 -- DROP TABLE IF EXISTS  ODS.ODS_MESORREGIAO
 truncate table ODS.ODS_MESORREGIAO
  insert into ODS.ODS_MESORREGIAO
  SELECT distinct
       CO_MESORREGIAO
      ,NO_MESORREGIAO
	, CO_UF
		 --INTO ODS.ODS_MESORREGIAO
  FROM stg.stg_RELATORIO_DTB_BRASIL_DISTRITO A
  inner join #municipio B on 
  a.CO_MUNICIPIO_completo = b.CO_MUNICIPIO
  
  

  /* -- SEM DUPLICIDADE
  SELECT COUNT(1), CO_MESORREGIAO, CO_UF
  FROM ODS.ODS_MESORREGIAO
  GROUP BY CO_MESORREGIAO, CO_UF
  HAVING COUNT(1) > 1
  select distinct * from ODS.ODS_MESORREGIAO where co_mesorregiao =1 and co_uf = 35
  */

   /*
	 https://www.ibge.gov.br/geociencias/organizacao-do-territorio/divisao-regional/23701-divisao-territorial-brasileira.html?=&t=downloads
  */
--DROP TABLE IF EXISTS ODS.ODS_MICRORREGIAO
--alter table ODS.ODS_MICRORREGIAO add CO_UF int
truncate table ODS.ODS_MICRORREGIAO
insert into ODS.ODS_MICRORREGIAO
SELECT DISTINCT 
       	CO_MICRORREGIAO
      ,	NO_MICRORREGIAO
	  ,	CO_MESORREGIAO
	  ,	CO_UF
      --INTO ODS.ODS_MICRORREGIAO

  FROM [db_evasao].[stg].[stg_RELATORIO_DTB_BRASIL_DISTRITO] A
  inner join #municipio B on 
  a.CO_MUNICIPIO_completo = b.CO_MUNICIPIO

  

  /* -- SEM DUPLICIDADE
  SELECT COUNT(1), CO_MICRORREGIAO, CO_UF
  FROM ODS.ODS_MICRORREGIAO
  GROUP BY CO_MICRORREGIAO, CO_UF
  HAVING COUNT(1) > 1
  */


 -- DROP TABLE IF EXISTS  ODS.ODS_MUNICIPIO
 truncate table ODS.ODS_MUNICIPIO
 --alter table ODS.ODS_MUNICIPIO add CO_UF int
 insert into ODS.ODS_MUNICIPIO
  SELECT DISTINCT 
		 	a.CO_MUNICIPIO_completo
		,	a.NO_MUNICIPIO
		,	a.CO_MICRORREGIAO
		,	a.CO_UF
--		INTO ODS.ODS_MUNICIPIO
   FROM [db_evasao].[stg].[stg_RELATORIO_DTB_BRASIL_DISTRITO] A
  inner join #municipio B on 
  a.CO_MUNICIPIO_completo = b.CO_MUNICIPIO
  where a.co_municipio_completo = 1100205 
  

--  where uf = 35


    /* -- SEM DUPLICIDADE
  SELECT COUNT(1), CO_MUNICIPIO
  FROM ODS.ODS_MUNICIPIO
  GROUP BY CO_MUNICIPIO
  HAVING COUNT(1) > 1
  */
------------------------------------------------------------------------------------------
-- INSTITUIÇÃO MANTENEDORA DA IES

-- TABELA AUXILIAR PARA PEGAR TODAS AS VERSÕES DE NOMENCLATURA DA MANTENEDORA AO LONGO DOS ANOS
DROP TABLE IF EXISTS #ODS_MANTENEDORA_IES
SELECT DISTINCT CO_MANTENEDORA,NO_MANTENEDORA, NU_ANO_CENSO 
INTO #ODS_MANTENEDORA_IES
	FROM STG.[STG_MICRODADOS_CADASTRO_IES_SP]

-- SALVA NA TABELA NOME DA MANTENEDORA DO ULTIMO CENSO EM QUE APARECEU
truncate table ODS.ODS_MANTENEDORA_IES
insert into ODS.ODS_MANTENEDORA_IES
SELECT	IES.CO_MANTENEDORA, 
		IES.NO_MANTENEDORA, 
		IES.NU_ANO_CENSO
-- INTO ODS.ODS_MANTENEDORA_IES
	FROM #ODS_MANTENEDORA_IES IES
	INNER JOIN (
		select CO_MANTENEDORA, MAX(NU_ANO_CENSO)NU_ANO_CENSO FROM  
			#ODS_MANTENEDORA_IES
			GROUP BY CO_MANTENEDORA
		) MX ON IES.CO_MANTENEDORA = MX.CO_MANTENEDORA AND 
				IES.NU_ANO_CENSO = MX.NU_ANO_CENSO
 
 /* -- SEM DUPLICIDADE
  SELECT COUNT(1), CO_MANTENEDORA
  FROM ODS.ODS_MANTENEDORA_IES
  GROUP BY CO_MANTENEDORA
  HAVING COUNT(1) > 1
  */

DROP TABLE IF EXISTS #ODS_IES
SELECT DISTINCT
 CO_IES
, NO_IES
, SG_IES
, NU_ANO_CENSO
, CO_MUNICIPIO_IES
, IN_CAPITAL_IES
, TP_ORGANIZACAO_ACADEMICA
, TP_CATEGORIA_ADMINISTRATIVA
, CO_MANTENEDORA
, DS_ENDERECO_IES
, DS_NUMERO_ENDERECO_IES
, DS_COMPLEMENTO_ENDERECO_IES
, NO_BAIRRO_IES
, NU_CEP_IES
INTO #ODS_IES
	FROM STG.[STG_MICRODADOS_CADASTRO_IES_SP]


/*  --112 IES em cursos que não existem 
SELECT 
	co_ies
 FROM [stg].[STG_MICRODADOS_CADASTRO_CURSOS_SP]
except 
SELECT 
 CO_IES
 	FROM STG.[STG_MICRODADOS_CADASTRO_IES_SP]
*/

CREATE CLUSTERED INDEX IXC_TMP_ODS_IES ON #ODS_IES (CO_IES, NU_ANO_CENSO)

--DROP TABLE IF EXISTS ODS.ODS_IES
truncate table ODS.ODS_IES
insert into ODS.ODS_IES
SELECT distinct 
	IES.CO_IES
,	IES.NO_IES
,	IES.SG_IES
,	IES.NU_ANO_CENSO
,	IES.CO_MUNICIPIO_IES
,	IES.IN_CAPITAL_IES
,	IES.TP_ORGANIZACAO_ACADEMICA
,	IES.TP_CATEGORIA_ADMINISTRATIVA
,	IES.CO_MANTENEDORA
,	IES.DS_ENDERECO_IES
,	IES.DS_NUMERO_ENDERECO_IES
,	IES.DS_COMPLEMENTO_ENDERECO_IES
,	IES.NO_BAIRRO_IES
,	IES.NU_CEP_IES
--INTO ODS.ODS_IES
FROM STG.[STG_MICRODADOS_CADASTRO_IES_SP]	IES
	INNER JOIN 
	(SELECT CO_IES, MAX(NU_ANO_CENSO) NU_ANO_CENSO
		FROM #ODS_IES
		GROUP BY CO_IES
		) MX
	ON IES.CO_IES = MX.CO_IES AND 
		IES.NU_ANO_CENSO = MX.NU_ANO_CENSO


/* -- SEM DUPLICIDADE
  SELECT COUNT(1), CO_IES
  FROM ODS.ODS_IES
  GROUP BY CO_IES
  HAVING COUNT(1) > 1
*/
 
----------------------------------------------------------------------------------------------
--- ODS_CINE 

--DROP TABLE IF EXISTS ODS.ODS_CINE_ROTULO
truncate table ODS.ODS_CINE_ROTULO
insert into ODS.ODS_CINE_ROTULO
SELECT distinct REPLACE(CO_CINE_ROTULO, '"','') CO_CINE_ROTULO, NO_CINE_ROTULO, CO_CINE_AREA_DETALHADA /*INTO ODS.ODS_CINE_ROTULO*/ 
FROM stg.STG_MICRODADOS_CADASTRO_CURSOS_SP


/* SEM DUPLICIDADE
SELECT COUNT(1), CO_CINE_ROTULO
FROM ODS.ODS_CINE_ROTULO
GROUP BY CO_CINE_ROTULO
HAVING COUNT(1) > 1
*/


-- DROP TABLE IF EXISTS ODS.ODS_CINE_AREA_DETALHADA
truncate table ODS.ODS_CINE_AREA_DETALHADA 
insert into ODS.ODS_CINE_AREA_DETALHADA 
SELECT distinct CO_CINE_AREA_DETALHADA, NO_CINE_AREA_DETALHADA, CO_CINE_AREA_ESPECIFICA -- INTO ODS.ODS_CINE_AREA_DETALHADA 
FROM stg.STG_MICRODADOS_CADASTRO_CURSOS_SP  



/* -- SEM DUPLICIDADE
SELECT COUNT(1), CO_CINE_AREA_DETALHADA FROM ODS.ODS_CINE_AREA_DETALHADA
GROUP BY CO_CINE_AREA_DETALHADA
HAVING COUNT(1)> 1
*/

-- DROP TABLE IF EXISTS ODS.ODS_CINE_AREA_ESPECIFICA
truncate table ODS.ODS_CINE_AREA_ESPECIFICA
insert into ODS.ODS_CINE_AREA_ESPECIFICA
SELECT distinct CO_CINE_AREA_ESPECIFICA, NO_CINE_AREA_ESPECIFICA, CO_CINE_AREA_GERAL /*INTO ODS.ODS_CINE_AREA_ESPECIFICA*/
FROM stg.STG_MICRODADOS_CADASTRO_CURSOS_SP  

/* -- SEM DUPLICIDADE
SELECT COUNT(1), CO_CINE_AREA_ESPECIFICA
FROM ODS.ODS_CINE_AREA_ESPECIFICA
GROUP BY CO_CINE_AREA_ESPECIFICA
HAVING COUNT(1)> 1
*/



--DROP TABLE IF EXISTS ODS.ODS_CINE_AREA_GERAL
truncate table ODS.ODS_CINE_AREA_GERAL
insert into ODS.ODS_CINE_AREA_GERAL
SELECT distinct CO_CINE_AREA_GERAL , NO_CINE_AREA_GERAL /*INTO ODS.ODS_CINE_AREA_GERAL*/ 
FROM stg.STG_MICRODADOS_CADASTRO_CURSOS_SP  

/* -- SEM DUPLICIDADE
SELECT COUNT(1), CO_CINE_AREA_GERAL
FROM ODS.ODS_CINE_AREA_GERAL
GROUP BY CO_CINE_AREA_GERAL
HAVING COUNT(1)> 1
*/


/*
SELECT DISTINCT
  CO_CURSO
 , NO_CURSO
 --, REPLACE (CO_CINE_ROTULO, '"', '')CO_CINE_ROTULO
 --, TP_GRAU_ACADEMICO
 --, TP_NIVEL_ACADEMICO
FROM [stg].[STG_MICRODADOS_CADASTRO_CURSOS_SP]
ORDER BY 2
SELECT * FROM [stg].[STG_MICRODADOS_CADASTRO_CURSOS_SP]
WHERE CO_CURSO = 5001026


SELECT   CO_CURSO
 , NO_CURSO, 
 CO_CINE_ROTULO
 FROM [stg].[STG_MICRODADOS_CADASTRO_CURSOS_SP]
where no_curso like 'Ciência%d%Computação'

select * from [stg].[STG_MICRODADOS_CADASTRO_CURSOS_SP]
where co_curso = 48503
order by nu_ano_censo

SELECT   DISTINCT 
		NO_CURSO,
		 CO_CINE_ROTULO, 
		 NO_CINE_ROTULO
 FROM [stg].[STG_MICRODADOS_CADASTRO_CURSOS_SP]

SELECT * FROM ODS.ODS_CINE_ROTULO WHERE CO_CINE_ROTULO = '0614C01'

select * from ods.ods_curso where no_curso like 'Ciência%d%Computação'
*/


drop table if exists #ODS_CURSO
SELECT DISTINCT
   NU_ANO_CENSO
 , CO_CURSO
 , NO_CURSO
 , CO_MUNICIPIO
 , IN_CAPITAL
 , TP_DIMENSAO
 , TP_REDE
 , CO_IES
 , CAST(REPLACE (CO_CINE_ROTULO, '"', '') AS CHAR(7)) CO_CINE_ROTULO 
 , TP_GRAU_ACADEMICO
 , IN_GRATUITO
 , TP_MODALIDADE_ENSINO
 , TP_NIVEL_ACADEMICO
 INTO #ods_curso
FROM [stg].[STG_MICRODADOS_CADASTRO_CURSOS_SP] nolock
CREATE CLUSTERED INDEX IXC_ODS_CURSO ON #ODS_CURSO(CO_CURSO, CO_MUNICIPIO, CO_IES, NU_ANO_CENSO)

select * from [stg].[STG_MICRODADOS_CADASTRO_CURSOS_SP]
where co_curso = 43259

-- DROP TABLE IF EXISTS ODS.ODS_CURSO -- 16665

truncate table ODS.ODS_CURSO
insert into ODS.ODS_CURSO
SELECT DISTINCT  
    C.CO_CURSO
,	TRIM(UPPER(C.NO_CURSO))NO_CURSO
-- ,	IN_CAPITAL
,	TP_DIMENSAO
,	TP_REDE
,	CO_CINE_ROTULO
,	TP_GRAU_ACADEMICO
,	IN_GRATUITO
,	TP_MODALIDADE_ENSINO
,	TP_NIVEL_ACADEMICO
--,    C.CO_IES
--,    C.CO_CINE_ROTULO
--,	C.CO_MUNICIPIO
-- INTO ODS.ODS_CURSO
FROM #ODS_CURSO C

INNER JOIN (SELECT CO_CURSO, /*CO_IES*/ MAX(NU_ANO_CENSO) NU_ANO_CENSO
				FROM #ODS_CURSO
				GROUP BY CO_CURSO--, CO_IES
)MX ON 
		C.CO_CURSO		=	MX.CO_CURSO		AND 
		-- C.CO_MUNICIPIO	=	MX.CO_MUNICIPIO	AND 
		-- C.CO_IES		=	MX.CO_IES		AND
	 	C.NU_ANO_CENSO	=	MX.NU_ANO_CENSO



/*
SELECT COUNT(1), CO_CURSO, CO_MUNICIPIO, TP_DIMENSAO
FROM #ods_curso
GROUP BY CO_CURSO, CO_MUNICIPIO, TP_DIMENSAO
HAVING COUNT(1) > 1

SELECT COUNT(1), CO_CURSO
FROM ODS.ODS_CURSO
GROUP BY CO_CURSO
HAVING COUNT(1) > 1



SELECT * FROM #ods_curso WHERE CO_CURSO = 1524193
SELECT * FROM ODS.ODS_CURSO WHERE CO_CURSO = 1524193


SELECT * FROM #ods_curso WHERE CO_CURSO = 1315345 AND CO_MUNICIPIO = 3518701 AND TP_DIMENSAO = 2

SELECT	DISTINCT CO_CURSO,	NO_CURSO, CO_IES,
		TP_DIMENSAO 
FROM #ods_curso 
WHERE CO_CURSO = 1315345 AND CO_MUNICIPIO = 3518701 AND TP_DIMENSAO = 2
ORDER BY 2, 3, 4

select * FROM [stg].[STG_MICRODADOS_CADASTRO_CURSOS_SP]
where co_curso = 1286528

select * from ods.ods_curso
where co_curso = 1286528

-- SEM DUPLICIDADE
select count(1),     CO_CURSO, CO_MUNICIPIO, CO_IES
FROM  ods.ods_curso
GROUP BY CO_CURSO, CO_MUNICIPIO, CO_IES
HAVING COUNT(1) > 1

select count(1),     CO_CURSO --, CO_IES
FROM  ods.ods_curso
GROUP BY CO_CURSO--, CO_IES
HAVING COUNT(1) > 1

SELECT * FROM ods.ods_curso WHERE CO_CURSO  = 5725
SELECT * FROM ods.ods_curso WHERE CO_CURSO  = 26414
SELECT * FROM ods.ods_curso WHERE CO_CURSO  = 106829

SELECT CO_CURSO, CO_IES, MAX(NU_ANO_CENSO) NU_ANO_CENSO
				FROM #ODS_CURSO
				WHERE CO_CURSO = 68796 AND CO_IES = 54
				GROUP BY CO_CURSO, CO_MUNICIPIO, CO_IES

SELECT * FROM #ODS_CURSO C WHERE CO_CURSO = 68796 AND CO_IES = 54

SELECT * FROM ods.ods_curso WHERE CO_CURSO = 68796 AND CO_IES = 54

SELECT * FROM ods.ods_curso
WHERE CO_CURSO = 52199	AND CO_MUNICIPIO  = 3509502	AND CO_IES = 19
SELECT * FROM #ODS_CURSO C
WHERE CO_CURSO = 52199	AND CO_MUNICIPIO  = 3509502	AND CO_IES = 19
*/

select * from ODS.ODS_DADOS_CURSO 
 WHERE CO_CURSO IN (SELECT CO_CURSO FROM DW.DIM_curso WHERE NO_CURSO ='nÃO CADASTRADO')

 select distinct co_ies  from ODS.ODS_DADOS_CURSO 
 WHERE CO_ies IN (SELECT co_ies FROM DW.DIM_ies WHERE NO_IES ='nÃO CADASTRADO')
 order by 1
 
 select * from [stg].[STG_MICRODADOS_CADASTRO_CURSOS_SP]				where co_ies = 2
 select * from [stg].[STG_MICRODADOS_CADASTRO_IES_SP]					where co_ies = 2
 select * from [stg].[STG_INDICADORES_TRAJETORIA_EDUCACAO_SUPERIOR_SP]	where co_ies = 2
 
 select * from ODS.ODS_DADOS_CURSO where co_ies = 2 
 select * from ODS.ODS_DADOS_IES where co_ies = 2 

  select distinct co_ies from [stg].[STG_MICRODADOS_CADASTRO_CURSOS_SP]
 WHERE CO_ies IN (SELECT co_ies FROM DW.DIM_ies WHERE NO_IES ='nÃO CADASTRADO')

select * from [stg].[STG_MICRODADOS_CADASTRO_CURSOS_SP]
where co_ies = 2 

select * from [stg].[STG_MICRODADOS_CADASTRO_ies_SP]
where co_ies = 2 

-- DROP TABLE IF EXISTS ODS.ODS_DADOS_CURSO
truncate table ODS.ODS_DADOS_CURSO
insert into ODS.ODS_DADOS_CURSO
SELECT distinct CO_CURSO
	,CO_MUNICIPIO
	,CO_IES
	,NU_ANO_CENSO
	,IN_CAPITAL
	,TP_DIMENSAO
	,TP_REDE
	 , CAST(REPLACE(CO_CINE_ROTULO, '"', '') AS CHAR(7)) CO_CINE_ROTULO 
 , TP_GRAU_ACADEMICO
 , IN_GRATUITO
 , TP_MODALIDADE_ENSINO
 , TP_NIVEL_ACADEMICO
, QT_CURSO,QT_VG_TOTAL,QT_VG_TOTAL_DIURNO,QT_VG_TOTAL_NOTURNO,QT_VG_TOTAL_EAD,QT_VG_NOVA,QT_VG_PROC_SELETIVO,QT_VG_REMANESC,QT_VG_PROG_ESPECIAL,QT_INSCRITO_TOTAL,QT_INSCRITO_TOTAL_DIURNO,QT_INSCRITO_TOTAL_NOTURNO,QT_INSCRITO_TOTAL_EAD,QT_INSC_VG_NOVA,QT_INSC_PROC_SELETIVO,QT_INSC_VG_REMANESC,QT_INSC_VG_PROG_ESPECIAL,QT_ING,QT_ING_FEM,QT_ING_MASC,QT_ING_DIURNO,QT_ING_NOTURNO,QT_ING_VG_NOVA,QT_ING_VESTIBULAR,QT_ING_ENEM,QT_ING_AVALIACAO_SERIADA,QT_ING_SELECAO_SIMPLIFICA,QT_ING_EGR,QT_ING_OUTRO_TIPO_SELECAO,QT_ING_PROC_SELETIVO,QT_ING_VG_REMANESC,QT_ING_VG_PROG_ESPECIAL,QT_ING_OUTRA_FORMA,QT_ING_0_17,QT_ING_18_24,QT_ING_25_29,QT_ING_30_34,QT_ING_35_39,QT_ING_40_49,QT_ING_50_59,QT_ING_60_MAIS,QT_ING_BRANCA,QT_ING_PRETA,QT_ING_PARDA,QT_ING_AMARELA,QT_ING_INDIGENA,QT_ING_CORND,QT_MAT,QT_MAT_FEM,QT_MAT_MASC,QT_MAT_DIURNO,QT_MAT_NOTURNO,QT_MAT_0_17,QT_MAT_18_24,QT_MAT_25_29,QT_MAT_30_34,QT_MAT_35_39,QT_MAT_40_49,QT_MAT_50_59,QT_MAT_60_MAIS,QT_MAT_BRANCA,QT_MAT_PRETA,QT_MAT_PARDA,QT_MAT_AMARELA,QT_MAT_INDIGENA,QT_MAT_CORND,QT_CONC,QT_CONC_FEM,QT_CONC_MASC,QT_CONC_DIURNO,QT_CONC_NOTURNO,QT_CONC_0_17,QT_CONC_18_24,QT_CONC_25_29,QT_CONC_30_34,QT_CONC_35_39,QT_CONC_40_49,QT_CONC_50_59,QT_CONC_60_MAIS,QT_CONC_BRANCA,QT_CONC_PRETA,QT_CONC_PARDA,QT_CONC_AMARELA,QT_CONC_INDIGENA,QT_CONC_CORND,QT_ING_NACBRAS,QT_ING_NACESTRANG,QT_MAT_NACBRAS,QT_MAT_NACESTRANG,QT_CONC_NACBRAS,QT_CONC_NACESTRANG,QT_ALUNO_DEFICIENTE,QT_ING_DEFICIENTE,QT_MAT_DEFICIENTE,QT_CONC_DEFICIENTE,QT_ING_FINANC,QT_ING_FINANC_REEMB,QT_ING_FIES,QT_ING_RPFIES,QT_ING_FINANC_REEMB_OUTROS,QT_ING_FINANC_NREEMB,QT_ING_PROUNII,QT_ING_PROUNIP,QT_ING_NRPFIES,QT_ING_FINANC_NREEMB_OUTROS,QT_MAT_FINANC,QT_MAT_FINANC_REEMB,QT_MAT_FIES,QT_MAT_RPFIES,QT_MAT_FINANC_REEMB_OUTROS,QT_MAT_FINANC_NREEMB,QT_MAT_PROUNII,QT_MAT_PROUNIP,QT_MAT_NRPFIES,QT_MAT_FINANC_NREEMB_OUTROS,QT_CONC_FINANC,QT_CONC_FINANC_REEMB,QT_CONC_FIES,QT_CONC_RPFIES,QT_CONC_FINANC_REEMB_OUTROS,QT_CONC_FINANC_NREEMB,QT_CONC_PROUNII,QT_CONC_PROUNIP,QT_CONC_NRPFIES,QT_CONC_FINANC_NREEMB_OUTROS,QT_ING_RESERVA_VAGA,QT_ING_RVREDEPUBLICA,QT_ING_RVETNICO,QT_ING_RVPDEF,QT_ING_RVSOCIAL_RF,QT_ING_RVOUTROS,QT_MAT_RESERVA_VAGA,QT_MAT_RVREDEPUBLICA,QT_MAT_RVETNICO,QT_MAT_RVPDEF,QT_MAT_RVSOCIAL_RF,QT_MAT_RVOUTROS,QT_CONC_RESERVA_VAGA,QT_CONC_RVREDEPUBLICA,QT_CONC_RVETNICO,QT_CONC_RVPDEF,QT_CONC_RVSOCIAL_RF,QT_CONC_RVOUTROS,QT_SIT_TRANCADA,QT_SIT_DESVINCULADO,QT_SIT_TRANSFERIDO,QT_SIT_FALECIDO,QT_ING_PROCESCPUBLICA,QT_ING_PROCESCPRIVADA,QT_ING_PROCNAOINFORMADA,QT_MAT_PROCESCPUBLICA,QT_MAT_PROCESCPRIVADA,QT_MAT_PROCNAOINFORMADA,QT_CONC_PROCESCPUBLICA,QT_CONC_PROCESCPRIVADA,QT_CONC_PROCNAOINFORMADA,QT_PARFOR,QT_ING_PARFOR,QT_MAT_PARFOR,QT_CONC_PARFOR,QT_APOIO_SOCIAL,QT_ING_APOIO_SOCIAL,QT_MAT_APOIO_SOCIAL,QT_CONC_APOIO_SOCIAL,QT_ATIV_EXTRACURRICULAR,QT_ING_ATIV_EXTRACURRICULAR,QT_MAT_ATIV_EXTRACURRICULAR,QT_CONC_ATIV_EXTRACURRICULAR,QT_MOB_ACADEMICA,QT_ING_MOB_ACADEMICA,QT_MAT_MOB_ACADEMICA,QT_CONC_MOB_ACADEMICA
	-- INTO ODS.ODS_DADOS_CURSO_
FROM [stg].[STG_MICRODADOS_CADASTRO_CURSOS_SP]


truncate table ODS.ODS_DADOS_IES
insert into ODS.ODS_DADOS_IES
SELECT distinct CO_IES, NU_ANO_CENSO, 
		QT_TEC_TOTAL,QT_TEC_FUNDAMENTAL_INCOMP_FEM,QT_TEC_FUNDAMENTAL_INCOMP_MASC,QT_TEC_FUNDAMENTAL_COMP_FEM,QT_TEC_FUNDAMENTAL_COMP_MASC,QT_TEC_MEDIO_FEM,QT_TEC_MEDIO_MASC,QT_TEC_SUPERIOR_FEM,QT_TEC_SUPERIOR_MASC,QT_TEC_ESPECIALIZACAO_FEM,QT_TEC_ESPECIALIZACAO_MASC,QT_TEC_MESTRADO_FEM,QT_TEC_MESTRADO_MASC,QT_TEC_DOUTORADO_FEM,QT_TEC_DOUTORADO_MASC,IN_ACESSO_PORTAL_CAPES,IN_ACESSO_OUTRAS_BASES,IN_ASSINA_OUTRA_BASE,IN_REPOSITORIO_INSTITUCIONAL,IN_BUSCA_INTEGRADA,IN_SERVICO_INTERNET,IN_PARTICIPA_REDE_SOCIAL,IN_CATALOGO_ONLINE,QT_PERIODICO_ELETRONICO,QT_LIVRO_ELETRONICO,QT_DOC_TOTAL,QT_DOC_EXE,QT_DOC_EX_FEMI,QT_DOC_EX_MASC,QT_DOC_EX_SEM_GRAD,QT_DOC_EX_GRAD,QT_DOC_EX_ESP,QT_DOC_EX_MEST,QT_DOC_EX_DOUT,QT_DOC_EX_INT,QT_DOC_EX_INT_DE,QT_DOC_EX_INT_SEM_DE,QT_DOC_EX_PARC,QT_DOC_EX_HOR,QT_DOC_EX_0_29,QT_DOC_EX_30_34,QT_DOC_EX_35_39,QT_DOC_EX_40_44,QT_DOC_EX_45_49,QT_DOC_EX_50_54,QT_DOC_EX_55_59,QT_DOC_EX_60_MAIS,QT_DOC_EX_BRANCA,QT_DOC_EX_PRETA,QT_DOC_EX_PARDA,QT_DOC_EX_AMARELA,QT_DOC_EX_INDIGENA,QT_DOC_EX_COR_ND,QT_DOC_EX_BRA,QT_DOC_EX_EST,QT_DOC_EX_COM_DEFICIENCIA
-- INTO ODS.ODS_DADOS_IES
FROM [stg].[STG_MICRODADOS_CADASTRO_IES_SP]


-- DROP TABLE IF EXISTS ODS.ODS_DADOS_FLUXO
truncate table ODS.ODS_DADOS_FLUXO
insert into ODS.ODS_DADOS_FLUXO
SELECT 
	  NU_ANO_REFERENCIA
	, CO_IES
	, CO_CURSO
	, CO_MUNICIPIO
	, NU_ANO_INGRESSO
	, NU_PRAZO_INTEGRALIZACAO
	, NU_ANO_INTEGRALIZACAO
	, NU_PRAZO_ACOMPANHAMENTO
	, NU_ANO_MAXIMO_ACOMPANHAMENTO
	, QT_INGRESSANTE
	, 	QT_PERMANENCIA	
	, 	QT_CONCLUINTE
	, 	QT_DESISTENCIA
	, 	QT_FALECIDO
	, TAP	/1000.												VL_TAP
	, TCA	/1000.												VL_TCA
	, TDA	/1000.												VL_TDA
	, TCAN	/1000.												VL_TCAN
	, TDAN	/1000.												VL_TDAN
	, CO_CATALOGO												CO_CATALOGO
--	INTO ODS.ODS_DADOS_FLUXO
FROM [STG].[STG_INDICADORES_TRAJETORIA_EDUCACAO_SUPERIOR_SP]


/*
SELECT COUNT(1), nu_ano_referencia, CO_IES, CO_CURSO, CO_MUNICIPIO
FROM ODS.ODS_DADOS_FLUXO
GROUP BY nu_ano_referencia, CO_IES, CO_CURSO, CO_MUNICIPIO
HAVING COUNT(1) > 1

SELECT COUNT(1), nu_ano_referencia, CO_IES, CO_CURSO, CO_MUNICIPIO, NU_ANO_INGRESSO
FROM ODS.ODS_DADOS_FLUXO
GROUP BY nu_ano_referencia, CO_IES, CO_CURSO, CO_MUNICIPIO, NU_ANO_INGRESSO
HAVING COUNT(1) > 1
*/


--------------------------------------------------------------------------------------------------------------------------------
-- CREATE SCHEMA DW
--DROP TABLE IF EXISTS DW.DIM_IES
delete from DW.DIM_IES where co_ies >0 
insert into DW.DIM_IES 
SELECT	IES.CO_IES, 
		IES.NO_IES, 
		IES.SG_IES, 
		IES.IN_CAPITAL,
		IES.TP_ORGANIZACAO_ACADEMICA, 
		IES.TP_CATEGORIA_ADMINISTRATIVA, 
		MI.CO_MANTENEDORA, 
		MI.NO_MANTENEDORA
-- 		INTO DW.DIM_IES
FROM ODS.ODS_IES IES
INNER JOIN ODS.ODS_MANTENEDORA_IES MI
ON IES.CO_MANTENEDORA = MI.CO_MANTENEDORA
-- ADD FLG_ATIVO
/*
alter table DW.DIM_IES alter column co_ies int not null
alter table DW.DIM_IES add constraint PK_DIM_IES PRIMARY KEY (CO_IES)
*/


--DROP TABLE IF EXISTS DW.DIM_REGIAO
DELETE FROM DW.DIM_REGIAO WHERE CO_MUNICIPIO >0 
INSERT INTO DW.DIM_REGIAO 
SELECT	MN.CO_MUNICIPIO, 
		MN.NO_MUNICIPIO, 
		MC.CO_MICRORREGIAO, 
		MC.NO_MICRORREGIAO,
		MS.CO_MESORREGIAO, 
		MS.NO_MESORREGIAO, 
		UF.CO_UF, 
		UF.NO_UF, 
		UF.SG_UF,
		RG.CO_REGIAO,
		RG.NO_REGIAO
--		INTO DW.DIM_REGIAO
FROM 
			ODS.ODS_MUNICIPIO				MN 
INNER JOIN	ODS.ODS_MICRORREGIAO			MC	ON	MN.CO_MICRORREGIAO	=	MC.CO_MICRORREGIAO AND 
													MN.CO_UF			=	MC.CO_UF
INNER JOIN	ODS.ODS_MESORREGIAO				MS	ON	MS.CO_MESORREGIAO	=	MC.CO_MESORREGIAO	AND 
													MS.CO_UF			=	MC.CO_UF
INNER JOIN	ODS.ODS_UNIDADE_FEDERATIVA		UF	ON	UF.CO_UF			=	MS.CO_UF
INNER JOIN	ODS.ODS_REGIAO					RG	ON	RG.CO_REGIAO		=	UF.CO_REGIAO


/*
select count(1),CO_CURSO
from DW.DIM_CURSO
group by CO_CURSO
having count(1) > 1
select * from DW.DIM_CURSO where co_curso = 98104	and tp_dimensao = 2

select * from ods.ods_CURSO where co_curso = 98104	and tp_dimensao = 2 order by 1, 2, 3, 4, 5, 6, 7, 8
*/
--DROP TABLE IF EXISTS DW.DIM_CURSO
delete from DW.DIM_CURSO where co_curso >0
insert into DW.DIM_CURSO 
SELECT  DISTINCT 
		CO_CURSO
		, NO_CURSO
--  		, TP_DIMENSAO
--  		, TP_REDE
--  		, TP_GRAU_ACADEMICO
--  		, IN_GRATUITO 
--  		, TP_MODALIDADE_ENSINO
-- 		INTO DW.DIM_CURSO
FROM ODS.ODS_CURSO

/*
alter table DW.DIM_CURSO alter column CO_CURSO int not null
alter table DW.DIM_CURSO add constraint PK_DIM_CURSO PRIMARY KEY (CO_CURSO)
*/
--DROP TABLE IF EXISTS DW.DIM_CINE
delete from DW.DIM_CINE where CO_CINE_ROTULO <> '0'
insert into DW.DIM_CINE 
SELECT	CR.CO_CINE_ROTULO, 
		CR.NO_CINE_ROTULO, 
		CAD.CO_CINE_AREA_DETALHADA, 
		CAD.NO_CINE_AREA_DETALHADA,
		CAE.CO_CINE_AREA_ESPECIFICA, 
		CAE.NO_CINE_AREA_ESPECIFICA,
		CAG.CO_CINE_AREA_GERAL, 
		CAG.NO_CINE_AREA_GERAL
		--INTO DW.DIM_CINE
FROM ODS.ODS_CINE_ROTULO CR
INNER JOIN ODS.ODS_CINE_AREA_DETALHADA CAD
ON CR.CO_CINE_AREA_DETALHADA = CAD.CO_CINE_AREA_DETALHADA
INNER JOIN ODS.ODS_CINE_AREA_ESPECIFICA CAE
ON CAE.CO_CINE_AREA_ESPECIFICA = CAD.CO_CINE_AREA_ESPECIFICA
INNER JOIN ODS.ODS_CINE_AREA_GERAL CAG
ON CAG.CO_CINE_AREA_GERAL =  CAE.CO_CINE_AREA_GERAL

/*
alter table DW.DIM_CINE alter column CO_CINE_ROTULO CHAR(7)  not null
alter table DW.DIM_CINE add constraint PK_DIM_CINE PRIMARY KEY (CO_CINE_ROTULO)
*/

--drop table if exists DW.FTO_DADOS_IES


truncate table DW.FTO_DADOS_IES
insert into DW.FTO_DADOS_IES
SELECT	  IES.CO_IES
		, IES.CO_MUNICIPIO				CO_MUNICIPIO
		, IES.TP_ORGANIZACAO_ACADEMICA
		, IES.TP_CATEGORIA_ADMINISTRATIVA
		, DI.NU_ANO_CENSO
		, DI.QT_TEC_TOTAL
		, DI.QT_TEC_FUNDAMENTAL_INCOMP_FEM
		, DI.QT_TEC_FUNDAMENTAL_INCOMP_MASC
		, DI.QT_TEC_FUNDAMENTAL_COMP_FEM
		, DI.QT_TEC_FUNDAMENTAL_COMP_MASC
		, DI.QT_TEC_MEDIO_FEM
		, DI.QT_TEC_MEDIO_MASC
		, DI.QT_TEC_SUPERIOR_FEM
		, DI.QT_TEC_SUPERIOR_MASC
		, DI.QT_TEC_ESPECIALIZACAO_FEM
		, DI.QT_TEC_ESPECIALIZACAO_MASC
		, DI.QT_TEC_MESTRADO_FEM
		, DI.QT_TEC_MESTRADO_MASC
		, DI.QT_TEC_DOUTORADO_FEM
		, DI.QT_TEC_DOUTORADO_MASC
		, DI.IN_ACESSO_PORTAL_CAPES
		, DI.IN_ACESSO_OUTRAS_BASES
		, DI.IN_ASSINA_OUTRA_BASE
		, DI.IN_REPOSITORIO_INSTITUCIONAL
		, DI.IN_BUSCA_INTEGRADA
		, DI.IN_SERVICO_INTERNET
		, DI.IN_PARTICIPA_REDE_SOCIAL
		, DI.IN_CATALOGO_ONLINE
		, DI.QT_PERIODICO_ELETRONICO
		, DI.QT_LIVRO_ELETRONICO
		, DI.QT_DOC_TOTAL
		, DI.QT_DOC_EXE
		, DI.QT_DOC_EX_FEMI
		, DI.QT_DOC_EX_MASC
		, DI.QT_DOC_EX_SEM_GRAD
		, DI.QT_DOC_EX_GRAD
		, DI.QT_DOC_EX_ESP
		, DI.QT_DOC_EX_MEST
		, DI.QT_DOC_EX_DOUT
		, DI.QT_DOC_EX_INT
		, DI.QT_DOC_EX_INT_DE
		, DI.QT_DOC_EX_INT_SEM_DE
		, DI.QT_DOC_EX_PARC
		, DI.QT_DOC_EX_HOR
		, DI.QT_DOC_EX_0_29
		, DI.QT_DOC_EX_30_34
		, DI.QT_DOC_EX_35_39
		, DI.QT_DOC_EX_40_44
		, DI.QT_DOC_EX_45_49
		, DI.QT_DOC_EX_50_54
		, DI.QT_DOC_EX_55_59
		, DI.QT_DOC_EX_60_MAIS
		, DI.QT_DOC_EX_BRANCA
		, DI.QT_DOC_EX_PRETA
		, DI.QT_DOC_EX_PARDA
		, DI.QT_DOC_EX_AMARELA
		, DI.QT_DOC_EX_INDIGENA
		, DI.QT_DOC_EX_COR_ND
		, DI.QT_DOC_EX_BRA
		, DI.QT_DOC_EX_EST
		, DI.QT_DOC_EX_COM_DEFICIENCIA
--		INTO DW.FTO_DADOS_IES
	FROM ODS.ODS_DADOS_IES DI
	INNER JOIN ODS.ODS_IES IES 
	ON DI.CO_IES = IES.CO_IES


/*
--ADD PKS PARA CRIAR FKS	
ALTER TABLE DW.FTO_DADOS_IES ADD CONSTRAINT FK_FTO_DADOS_IES_DIM_IES						FOREIGN KEY (CO_IES						)REFERENCES DW.DIM_IES
ALTER TABLE DW.FTO_DADOS_IES ADD CONSTRAINT FK_FTO_DADOS_IES_DIM_REGIAO						FOREIGN KEY (CO_MUNICIPIO				)REFERENCES DW.DIM_REGIAO
ALTER TABLE DW.FTO_DADOS_IES ADD CONSTRAINT FK_FTO_DADOS_IES_TIPO_ORGANIZACAO_ACADEMICA		FOREIGN KEY (TP_ORGANIZACAO_ACADEMICA	)REFERENCES DW.DIM_TIPO_ORGANIZACAO_ACADEMICA
ALTER TABLE DW.FTO_DADOS_IES ADD CONSTRAINT FK_FTO_DADOS_IES_TIPO_CATEGORIA_ADMINISTRATIVA	FOREIGN KEY (TP_CATEGORIA_ADMINISTRATIVA)REFERENCES DW.DIM_TIPO_CATEGORIA_ADMINISTRATIVA
*/


DROP TABLE IF EXISTS DW.FTO_DADOS_CURSO
SELECT 
	 DC.NU_ANO_CENSO
	,DC.CO_CURSO
	,DC.CO_MUNICIPIO
	,DC.IN_CAPITAL
	,DC.TP_DIMENSAO
	,DC.TP_REDE
	,DC.CO_IES
	,DC.CO_CINE_ROTULO
	,DC.TP_GRAU_ACADEMICO
	,DC.IN_GRATUITO
	,DC.TP_MODALIDADE_ENSINO
	,DC.TP_NIVEL_ACADEMICO
	,IES.TP_ORGANIZACAO_ACADEMICA
	,IES.TP_CATEGORIA_ADMINISTRATIVA
	,DC.QT_CURSO
	,DC.QT_VG_TOTAL
	,DC.QT_VG_TOTAL_DIURNO
	,DC.QT_VG_TOTAL_NOTURNO
	,DC.QT_VG_TOTAL_EAD
	,DC.QT_VG_NOVA
	,DC.QT_VG_PROC_SELETIVO
	,DC.QT_VG_REMANESC
	,DC.QT_VG_PROG_ESPECIAL
	,DC.QT_INSCRITO_TOTAL
	,DC.QT_INSCRITO_TOTAL_DIURNO
	,DC.QT_INSCRITO_TOTAL_NOTURNO
	,DC.QT_INSCRITO_TOTAL_EAD
	,DC.QT_INSC_VG_NOVA
	,DC.QT_INSC_PROC_SELETIVO
	,DC.QT_INSC_VG_REMANESC
	,DC.QT_INSC_VG_PROG_ESPECIAL
	,DC.QT_ING
	,DC.QT_ING_FEM
	,DC.QT_ING_MASC
	,DC.QT_ING_DIURNO
	,DC.QT_ING_NOTURNO
	,DC.QT_ING_VG_NOVA
	,DC.QT_ING_VESTIBULAR
	,DC.QT_ING_ENEM
	,DC.QT_ING_AVALIACAO_SERIADA
	,DC.QT_ING_SELECAO_SIMPLIFICA
	,DC.QT_ING_EGR
	,DC.QT_ING_OUTRO_TIPO_SELECAO
	,DC.QT_ING_PROC_SELETIVO
	,DC.QT_ING_VG_REMANESC
	,DC.QT_ING_VG_PROG_ESPECIAL
	,DC.QT_ING_OUTRA_FORMA
	,DC.QT_ING_0_17
	,DC.QT_ING_18_24
	,DC.QT_ING_25_29
	,DC.QT_ING_30_34
	,DC.QT_ING_35_39
	,DC.QT_ING_40_49
	,DC.QT_ING_50_59
	,DC.QT_ING_60_MAIS
	,DC.QT_ING_BRANCA
	,DC.QT_ING_PRETA
	,DC.QT_ING_PARDA
	,DC.QT_ING_AMARELA
	,DC.QT_ING_INDIGENA
	,DC.QT_ING_CORND
	,DC.QT_MAT
	,DC.QT_MAT_FEM
	,DC.QT_MAT_MASC
	,DC.QT_MAT_DIURNO
	,DC.QT_MAT_NOTURNO
	,DC.QT_MAT_0_17
	,DC.QT_MAT_18_24
	,DC.QT_MAT_25_29
	,DC.QT_MAT_30_34
	,DC.QT_MAT_35_39
	,DC.QT_MAT_40_49
	,DC.QT_MAT_50_59
	,DC.QT_MAT_60_MAIS
	,DC.QT_MAT_BRANCA
	,DC.QT_MAT_PRETA
	,DC.QT_MAT_PARDA
	,DC.QT_MAT_AMARELA
	,DC.QT_MAT_INDIGENA
	,DC.QT_MAT_CORND
	,DC.QT_CONC
	,DC.QT_CONC_FEM
	,DC.QT_CONC_MASC
	,DC.QT_CONC_DIURNO
	,DC.QT_CONC_NOTURNO
	,DC.QT_CONC_0_17
	,DC.QT_CONC_18_24
	,DC.QT_CONC_25_29
	,DC.QT_CONC_30_34
	,DC.QT_CONC_35_39
	,DC.QT_CONC_40_49
	,DC.QT_CONC_50_59
	,DC.QT_CONC_60_MAIS
	,DC.QT_CONC_BRANCA
	,DC.QT_CONC_PRETA
	,DC.QT_CONC_PARDA
	,DC.QT_CONC_AMARELA
	,DC.QT_CONC_INDIGENA
	,DC.QT_CONC_CORND
	,DC.QT_ING_NACBRAS
	,DC.QT_ING_NACESTRANG
	,DC.QT_MAT_NACBRAS
	,DC.QT_MAT_NACESTRANG
	,DC.QT_CONC_NACBRAS
	,DC.QT_CONC_NACESTRANG
	,DC.QT_ALUNO_DEFICIENTE
	,DC.QT_ING_DEFICIENTE
	,DC.QT_MAT_DEFICIENTE
	,DC.QT_CONC_DEFICIENTE
	,DC.QT_ING_FINANC
	,DC.QT_ING_FINANC_REEMB
	,DC.QT_ING_FIES
	,DC.QT_ING_RPFIES
	,DC.QT_ING_FINANC_REEMB_OUTROS
	,DC.QT_ING_FINANC_NREEMB
	,DC.QT_ING_PROUNII
	,DC.QT_ING_PROUNIP
	,DC.QT_ING_NRPFIES
	,DC.QT_ING_FINANC_NREEMB_OUTROS
	,DC.QT_MAT_FINANC
	,DC.QT_MAT_FINANC_REEMB
	,DC.QT_MAT_FIES
	,DC.QT_MAT_RPFIES
	,DC.QT_MAT_FINANC_REEMB_OUTROS
	,DC.QT_MAT_FINANC_NREEMB
	,DC.QT_MAT_PROUNII
	,DC.QT_MAT_PROUNIP
	,DC.QT_MAT_NRPFIES
	,DC.QT_MAT_FINANC_NREEMB_OUTROS
	,DC.QT_CONC_FINANC
	,DC.QT_CONC_FINANC_REEMB
	,DC.QT_CONC_FIES
	,DC.QT_CONC_RPFIES
	,DC.QT_CONC_FINANC_REEMB_OUTROS
	,DC.QT_CONC_FINANC_NREEMB
	,DC.QT_CONC_PROUNII
	,DC.QT_CONC_PROUNIP
	,DC.QT_CONC_NRPFIES
	,DC.QT_CONC_FINANC_NREEMB_OUTROS
	,DC.QT_ING_RESERVA_VAGA
	,DC.QT_ING_RVREDEPUBLICA
	,DC.QT_ING_RVETNICO
	,DC.QT_ING_RVPDEF
	,DC.QT_ING_RVSOCIAL_RF
	,DC.QT_ING_RVOUTROS
	,DC.QT_MAT_RESERVA_VAGA
	,DC.QT_MAT_RVREDEPUBLICA
	,DC.QT_MAT_RVETNICO
	,DC.QT_MAT_RVPDEF
	,DC.QT_MAT_RVSOCIAL_RF
	,DC.QT_MAT_RVOUTROS
	,DC.QT_CONC_RESERVA_VAGA
	,DC.QT_CONC_RVREDEPUBLICA
	,DC.QT_CONC_RVETNICO
	,DC.QT_CONC_RVPDEF
	,DC.QT_CONC_RVSOCIAL_RF
	,DC.QT_CONC_RVOUTROS
	,DC.QT_SIT_TRANCADA
	,DC.QT_SIT_DESVINCULADO
	,DC.QT_SIT_TRANSFERIDO
	,DC.QT_SIT_FALECIDO
	,DC.QT_ING_PROCESCPUBLICA
	,DC.QT_ING_PROCESCPRIVADA
	,DC.QT_ING_PROCNAOINFORMADA
	,DC.QT_MAT_PROCESCPUBLICA
	,DC.QT_MAT_PROCESCPRIVADA
	,DC.QT_MAT_PROCNAOINFORMADA
	,DC.QT_CONC_PROCESCPUBLICA
	,DC.QT_CONC_PROCESCPRIVADA
	,DC.QT_CONC_PROCNAOINFORMADA
	,DC.QT_PARFOR
	,DC.QT_ING_PARFOR
	,DC.QT_MAT_PARFOR
	,DC.QT_CONC_PARFOR
	,DC.QT_APOIO_SOCIAL
	,DC.QT_ING_APOIO_SOCIAL
	,DC.QT_MAT_APOIO_SOCIAL
	,DC.QT_CONC_APOIO_SOCIAL
	,DC.QT_ATIV_EXTRACURRICULAR
	,DC.QT_ING_ATIV_EXTRACURRICULAR
	,DC.QT_MAT_ATIV_EXTRACURRICULAR
	,DC.QT_CONC_ATIV_EXTRACURRICULAR
	,DC.QT_MOB_ACADEMICA
	,DC.QT_ING_MOB_ACADEMICA
	,DC.QT_MAT_MOB_ACADEMICA
	,DC.QT_CONC_MOB_ACADEMICA
/*	,DF.NU_ANO_INGRESSO
	,DF.NU_PRAZO_INTEGRALIZACAO
	,DF.NU_ANO_INTEGRALIZACAO
	,DF.NU_PRAZO_ACOMPANHAMENTO
	,DF.NU_ANO_MAXIMO_ACOMPANHAMENTO
	,DF.QT_INGRESSANTE
	,DF.QT_PERMANENCIA
	,DF.QT_CONCLUINTE
	,DF.QT_DESISTENCIA
	,DF.QT_FALECIDO
	,DF.VL_TAP
	,DF.VL_TCA
	,DF.VL_TDA
	,DF.VL_TCAN
	,DF.VL_TDAN
	,DF.CO_CATALOGO
*/
	INTO DW.FTO_DADOS_CURSO
FROM 	ODS.ODS_DADOS_CURSO		dc	
left  join ods.ods_ies ies 
on dc.co_ies = ies.co_ies


/*
--ADD PKS PARA CRIAR FKS	
ALTER TABLE DW.FTO_DADOS_CURSO ADD CONSTRAINT FK_FTO_DADOS_IES_DIM_IES					FOREIGN KEY (CO_CURSO				)REFERENCES DW.DIM_IES
ALTER TABLE DW.FTO_DADOS_CURSO ADD CONSTRAINT FK_FTO_DADOS_IES_DIM_REGIAO				FOREIGN KEY (CO_MUNICIPIO			)REFERENCES DW.DIM_REGIAO
ALTER TABLE DW.FTO_DADOS_CURSO ADD CONSTRAINT FK_FTO_DADOS_IES_DIM_REGIAO				FOREIGN KEY (TP_DIMENSAO			)REFERENCES DW.DIM_REGIAO
ALTER TABLE DW.FTO_DADOS_CURSO ADD CONSTRAINT FK_FTO_DADOS_IES_DIM_REGIAO				FOREIGN KEY (TP_REDE				)REFERENCES DW.DIM_REGIAO
ALTER TABLE DW.FTO_DADOS_CURSO ADD CONSTRAINT FK_FTO_DADOS_IES_DIM_REGIAO				FOREIGN KEY (CO_IES					)REFERENCES DW.DIM_REGIAO
ALTER TABLE DW.FTO_DADOS_CURSO ADD CONSTRAINT FK_FTO_DADOS_IES_DIM_REGIAO				FOREIGN KEY (CO_CINE_ROTULO			)REFERENCES DW.DIM_REGIAO
ALTER TABLE DW.FTO_DADOS_CURSO ADD CONSTRAINT FK_FTO_DADOS_IES_DIM_REGIAO				FOREIGN KEY (TP_GRAU_ACADEMICO		)REFERENCES DW.DIM_REGIAO
ALTER TABLE DW.FTO_DADOS_CURSO ADD CONSTRAINT FK_FTO_DADOS_IES_TIPO_MODALIDADE_ENSINO	FOREIGN KEY (TP_MODALIDADE_ENSINO	)REFERENCES DW.DIM_TIPO_MODALIDADE_ENSINO
ALTER TABLE DW.FTO_DADOS_CURSO ADD CONSTRAINT FK_FTO_DADOS_IES_TIPO_NIVEL_ACADEMICO		FOREIGN KEY (TP_NIVEL_ACADEMICO		)REFERENCES DW.DIM_TIPO_NIVEL_ACADEMICO
*/



/*
ODS.ODS_CURSO						C
	INNER JOIN	ODS.ODS_DADOS_CURSO							DC	ON	C.CO_CURSO			=	DC.CO_CURSO		AND 
																	C.CO_MUNICIPIO		=	DC.CO_MUNICIPIO AND 
																	C.CO_IES			=	DC.CO_IES
*/
/*
-- NÃO É POSSÍVEL JUNTAR DADOS DE CURSO E FLUXO NA MESMA TABELA FATO POR HAVER DADOS DE FLUXO PARA O MESMO CURSO COM DIFERENTES ANOS DE INGRESSO; 
-- FAZER UM JOIN ENTRE AS TABELAS DE DADOS DE CURSO E DADOS DE FLUXO PROVOCARIA DUPLICIDADE NOS DADOS DE CURSO
LEFT JOIN ODS.ODS_DADOS_FLUXO								DF ON	DC.NU_ANO_CENSO		=	DF.NU_ANO_CENSO	AND
																	DC.CO_IES			=	DF.CO_IES		AND
																	DC.CO_CURSO			=	DF.CO_CURSO		AND
																	DC.CO_MUNICIPIO		=	DF.CO_MUNICIPIO	


SELECT * FROM	ODS.ODS_DADOS_CURSO		DC	
LEFT JOIN		ODS.ODS_DADOS_FLUXO		DF ON	DC.NU_ANO_CENSO		=	DF.NU_ANO_CENSO	AND
												DC.CO_IES			=	DF.CO_IES		AND
												DC.CO_CURSO			=	DF.CO_CURSO		AND
												DC.CO_MUNICIPIO		=	DF.CO_MUNICIPIO	
WHERE DF.CO_MUNICIPIO IS NULL

SELECT * FROM ODS.ODS_DADOS_CURSO		DC
LEFT JOIN		ODS.ODS_DADOS_FLUXO		DF ON	DC.NU_ANO_CENSO		=	DF.NU_ANO_CENSO	AND
												DC.CO_IES			=	DF.CO_IES		AND
												DC.CO_CURSO			=	DF.CO_CURSO		AND
												DC.CO_MUNICIPIO		=	DF.CO_MUNICIPIO	
 WHERE	DC.CO_CURSO		=	614			AND 
		DC.CO_MUNICIPIO	=	3548906		AND 
		DC.CO_IES		=	7			AND 
		DC.NU_ANO_CENSO	=	2010		

SELECT COUNT(1),  
DC.CO_CURSO,		
DC.CO_MUNICIPIO	,
DC.CO_IES	,	
DC.NU_ANO_CENSO	
FROM ODS.ODS_DADOS_CURSO		DC
LEFT JOIN		ODS.ODS_DADOS_FLUXO		DF ON	DC.NU_ANO_CENSO		=	DF.NU_ANO_CENSO	AND
												DC.CO_IES			=	DF.CO_IES		AND
												DC.CO_CURSO			=	DF.CO_CURSO		AND
												DC.CO_MUNICIPIO		=	DF.CO_MUNICIPIO	
GROUP BY DC.CO_CURSO,		
DC.CO_MUNICIPIO	,
DC.CO_IES,	
DC.NU_ANO_CENSO	*/
alter table dw.dim_regiao alter column SG_UF varchar(3)
select * from dw.dim_regiao

update dw.FTO_DADOS_FLUXO set CO_MUNICIPIO = 1 where CO_MUNICIPIO = 0


-- DROP TABLE IF EXISTS DW.FTO_DADOS_FLUXO
truncate table DW.FTO_DADOS_FLUXO
insert into DW.FTO_DADOS_FLUXO
SELECT 
	 DF.CO_CURSO
	,isnull(df.CO_MUNICIPIO,1)					CO_MUNICIPIO
	,a.IN_CAPITAL
	,c.TP_DIMENSAO
	,c.TP_REDE
	,DF.CO_IES
	,c.CO_CINE_ROTULO
	,isnull(C.TP_GRAU_ACADEMICO,0)				TP_GRAU_ACADEMICO
	,c.IN_GRATUITO
	,isnull(c.TP_MODALIDADE_ENSINO,0)			TP_MODALIDADE_ENSINO
	,isnull(c.TP_NIVEL_ACADEMICO,0)				TP_NIVEL_ACADEMICO
	,isnull(IES.TP_ORGANIZACAO_ACADEMICA,0)		TP_ORGANIZACAO_ACADEMICA
	,isnull(IES.TP_CATEGORIA_ADMINISTRATIVA,0)	TP_CATEGORIA_ADMINISTRATIVA
	,isnull(df.NU_ANO_REFERENCIA,0)				NU_ANO_CENSO
	,DF.NU_ANO_INGRESSO
	,DF.NU_PRAZO_INTEGRALIZACAO
	,DF.NU_ANO_INTEGRALIZACAO
	,DF.NU_PRAZO_ACOMPANHAMENTO
	,DF.NU_ANO_MAXIMO_ACOMPANHAMENTO
	,DF.QT_INGRESSANTE
	,DF.QT_PERMANENCIA
	,DF.QT_CONCLUINTE
	,DF.QT_DESISTENCIA
	,DF.QT_FALECIDO
	,DF.VL_TAP
	,DF.VL_TCA
	,DF.VL_TDA
	,DF.VL_TCAN
	,DF.VL_TDAN
	,DF.CO_CATALOGO
--	INTO DW.FTO_DADOS_FLUXO
FROM 	ODS.ODS_DADOS_FLUXO	DF 
left join ods.ods_curso c
on df.co_curso = c.co_curso
		LEFT JOIN (
			SELECT DISTINCT 
					 DC.CO_IES
					,DC.CO_CURSO
					,DC.CO_MUNICIPIO
					,DC.NU_ANO_CENSO
					,DC.IN_CAPITAL
					,DC.TP_DIMENSAO
					,DC.TP_REDE
					,DC.CO_CINE_ROTULO
					,DC.TP_GRAU_ACADEMICO
					,DC.IN_GRATUITO
					,DC.TP_MODALIDADE_ENSINO
					,DC.TP_NIVEL_ACADEMICO
			FROM ODS.ODS_DADOS_CURSO DC
		) A
									ON	A.CO_IES			=	DF.CO_IES		AND
										A.CO_CURSO			=	DF.CO_CURSO		AND
										A.CO_MUNICIPIO		=	DF.CO_MUNICIPIO	AND 
										A.NU_ANO_CENSO		=	DF.NU_ANO_REFERENCIA
left  join ods.ods_ies ies 
on A.co_ies = ies.co_ies

/*f
select count(1)
,CO_IES			
,CO_CURSO			
,CO_MUNICIPIO, 
NU_ANO_CENSO
from DW.FTO_DADOS_FLUXO
group by 
 CO_IES			
,CO_CURSO			
,CO_MUNICIPIO
, NU_ANO_CENSO
having count(1) > 1

select * from DW.FTO_DADOS_FLUXO  
where co_ies  = 263	
and co_curso = 6330	
and co_municipio = 3550308
and NU_ANO_CENSO = 2017
order by NU_ANO_INGRESSO
*/

/*
UPDATE DW.DIM_IES SET sg_ies = 'Outros' where SG_IES = 'NI'


INSERT INTO DW.DIM_IES (
CO_IES
, NO_IES
, SG_IES
, IN_CAPITAL_IES
, TP_ORGANIZACAO_ACADEMICA
, TP_CATEGORIA_ADMINISTRATIVA
, CO_MANTENEDORA
, NO_MANTENEDORA
)
select distinct dc.co_ies, 'Não cadastrado', 'NC', 0, 0, 0, 0, 'Não cadastrado'
from DW.FTO_DADOS_CURSO dc 
left join DW.DIM_ies	ies
on dc.co_ies = ies.co_ies 
where ies.co_ies is null


INSERT INTO DW.DIM_CURSO
(CO_CURSO, NO_CURSO) 
select distinct df.co_curso, 'Não cadastrado'
from DW.FTO_DADOS_FLUXO df
left join DW.DIM_curso	c
on df.co_curso = c.co_curso
where c.co_curso is null
*/

/*
-- metadados das tabelas do DW/
SELECT *
FROM INFORMATION_SCHEMA.TABLES T 
WHERE t.TABLE_SCHEMA = 'DW' AND 
T.TABLE_TYPE = 'BASE TABLE'
and table_name like 'dim_%'


metadados das tabelas do DW
SELECT C.TABLE_SCHEMA, C.TABLE_NAME, C.COLUMN_NAME, C.ORDINAL_POSITION, C.DATA_TYPE, C.CHARACTER_MAXIMUM_LENGTH
FROM INFORMATION_SCHEMA.COLUMNS C
INNER JOIN INFORMATION_SCHEMA.TABLES T ON C.TABLE_SCHEMA = T.TABLE_SCHEMA AND T.TABLE_NAME = C.TABLE_NAME AND C.TABLE_CATALOG =  T.TABLE_CATALOG
WHERE C.TABLE_SCHEMA = 'DW' AND 
T.TABLE_TYPE = 'BASE TABLE'
and column_name like 'tp_%'
*/



-- ajustes de registros de exceção
/*
update fto set 	FTO.CO_CURSO				=  0 from DW.FTO_DADOS_CURSO		FTO	where FTO.CO_CURSO				is null
update fto set 	FTO.CO_MUNICIPIO			=  0 from DW.FTO_DADOS_CURSO		FTO	where FTO.CO_MUNICIPIO			is null
update fto set 	FTO.CO_IES					=  0 from DW.FTO_DADOS_CURSO		FTO	where FTO.CO_IES				is null
update fto set 	FTO.CO_CINE_ROTULO			=  0 from DW.FTO_DADOS_CURSO		FTO	where FTO.CO_CINE_ROTULO		is null
update fto set 	FTO.TP_DIMENSAO				=  0 from DW.FTO_DADOS_CURSO		FTO	where FTO.TP_DIMENSAO			is null
update fto set 	FTO.TP_GRAU_ACADEMICO		=  0 from DW.FTO_DADOS_CURSO		FTO	where FTO.TP_GRAU_ACADEMICO		is null
update fto set 	FTO.TP_REDE					=  0 from DW.FTO_DADOS_CURSO		FTO	where FTO.TP_REDE				is null
update fto set 	FTO.TP_MODALIDADE_ENSINO	=  0 from DW.FTO_DADOS_CURSO		FTO	where FTO.TP_MODALIDADE_ENSINO	is null
update fto set 	FTO.TP_NIVEL_ACADEMICO		=  0 from DW.FTO_DADOS_CURSO		FTO	where FTO.TP_NIVEL_ACADEMICO	is null



update fto set 	FTO.CO_MUNICIPIO				=  0 from DW.FTO_DADOS_IES			FTO	where	FTO.CO_MUNICIPIO					is null
update fto set 	FTO.TP_ORGANIZACAO_ACADEMICA	=  0 from DW.FTO_DADOS_IES			FTO	where	FTO.TP_ORGANIZACAO_ACADEMICA		is null
update fto set 	FTO.TP_CATEGORIA_ADMINISTRATIVA	=  0 from DW.FTO_DADOS_IES			FTO	where	FTO.TP_CATEGORIA_ADMINISTRATIVA		is null
update fto set 	FTO.CO_IES						=  0 from DW.FTO_DADOS_IES			FTO	where	FTO.CO_IES							is null
update fto set 	FTO.CO_CURSO					=  0 from DW.FTO_DADOS_fluxo		FTO	where	FTO.CO_CURSO						is null
update fto set 	FTO.CO_MUNICIPIO				=  0 from DW.FTO_DADOS_fluxo		FTO	where	FTO.CO_MUNICIPIO					is null
update fto set 	FTO.TP_DIMENSAO					=  0 from DW.FTO_DADOS_fluxo		FTO	where	FTO.TP_DIMENSAO						is null
update fto set 	FTO.TP_REDE						=  0 from DW.FTO_DADOS_fluxo		FTO	where	FTO.TP_REDE							is null
update fto set 	FTO.CO_IES						=  0 from DW.FTO_DADOS_fluxo		FTO	where	FTO.CO_IES							is null
update fto set 	FTO.CO_CINE_ROTULO				=  0 from DW.FTO_DADOS_fluxo		FTO	where	FTO.CO_CINE_ROTULO					is null
update fto set 	FTO.TP_GRAU_ACADEMICO			=  0 from DW.FTO_DADOS_fluxo		FTO	where	FTO.TP_GRAU_ACADEMICO				is null
update fto set 	FTO.TP_MODALIDADE_ENSINO		=  0 from DW.FTO_DADOS_fluxo		FTO	where	FTO.TP_MODALIDADE_ENSINO			is null
update fto set 	FTO.TP_NIVEL_ACADEMICO			=  0 from DW.FTO_DADOS_fluxo		FTO	where	FTO.TP_NIVEL_ACADEMICO				is null


update dw.fto_dados_curso set CO_CINE_ROTULO        = 0 where CO_CINE_ROTULO        is null
update dw.fto_dados_curso set CO_CURSO              = 0 where CO_CURSO              is null
update dw.fto_dados_curso set CO_MUNICIPIO          = 0 where CO_MUNICIPIO          is null
update dw.fto_dados_curso set TP_DIMENSAO           = 0 where TP_DIMENSAO           is null
update dw.fto_dados_curso set TP_GRAU_ACADEMICO     = 0 where TP_GRAU_ACADEMICO     is null
update dw.fto_dados_curso set TP_MODALIDADE_ENSINO  = 0 where TP_MODALIDADE_ENSINO  is null
update dw.fto_dados_curso set TP_NIVEL_ACADEMICO    = 0 where TP_NIVEL_ACADEMICO    is null
update dw.fto_dados_curso set TP_REDE				= 0 where TP_REDE				is null



*/

/*
-- verificação de membro inferido		-- ANALISAR MEMBRO INFERIDO DE COD_IES 
select distinct	fto.CO_CURSO					from 	DW.FTO_DADOS_CURSO	FTO		LEFT JOIN	DW.DIM_CURSO					C		ON	FTO.CO_CURSO			=	C.CO_CURSO					where C.CO_CURSO				is null
select distinct	fto.CO_MUNICIPIO				from 	DW.FTO_DADOS_CURSO	FTO		LEFT JOIN	DW.DIM_REGIAO					RG		ON	FTO.CO_MUNICIPIO		=	RG.CO_MUNICIPIO				where RG.CO_MUNICIPIO			is null
select distinct	fto.CO_CINE_ROTULO				from 	DW.FTO_DADOS_CURSO	FTO		LEFT JOIN	DW.DIM_CINE						CINE	ON	FTO.CO_CINE_ROTULO		=	CINE.CO_CINE_ROTULO			where CINE.CO_CINE_ROTULO		is null
select distinct	fto.TP_DIMENSAO					from 	DW.FTO_DADOS_CURSO	FTO		LEFT JOIN	DW.DIM_TIPO_DIMENSAO			TDM		ON	FTO.TP_DIMENSAO			=	TDM.TP_DIMENSAO				where TDM.TP_DIMENSAO			is null
select distinct	fto.TP_GRAU_ACADEMICO			from 	DW.FTO_DADOS_CURSO	FTO		LEFT JOIN	DW.DIM_TIPO_GRAU_ACADEMICO		TGA		ON	FTO.TP_GRAU_ACADEMICO	=	TGA.TP_GRAU_ACADEMICO		where TGA.TP_GRAU_ACADEMICO		is null
select distinct	fto.TP_REDE						from 	DW.FTO_DADOS_CURSO	FTO		LEFT JOIN	DW.DIM_TIPO_REDE				TRD		ON	FTO.TP_REDE				=	TRD.TP_REDE					where TRD.TP_REDE				is null
select distinct	fto.TP_MODALIDADE_ENSINO		from 	DW.FTO_DADOS_CURSO	FTO		LEFT JOIN	DW.DIM_TIPO_MODALIDADE_ENSINO	TME		ON	FTO.TP_MODALIDADE_ENSINO=	TME.TP_MODALIDADE_ENSINO	where TME.TP_MODALIDADE_ENSINO	is null
select distinct	fto.TP_NIVEL_ACADEMICO			from 	DW.FTO_DADOS_CURSO	FTO		LEFT JOIN	DW.DIM_TIPO_NIVEL_ACADEMICO		TNA		ON	FTO.TP_NIVEL_ACADEMICO	=	TNA.TP_NIVEL_ACADEMICO		where TNA.TP_NIVEL_ACADEMICO	is null

select distinct FTO.CO_MUNICIPIO				from	DW.FTO_DADOS_IES	FTO		LEFT JOIN	DW.DIM_REGIAO							RG		ON	FTO.CO_MUNICIPIO				=	RG.CO_MUNICIPIO					WHERE RG.CO_MUNICIPIO					IS NULL
select distinct FTO.TP_ORGANIZACAO_ACADEMICA	from	DW.FTO_DADOS_IES	FTO		LEFT JOIN	DW.DIM_TIPO_ORGANIZACAO_ACADEMICA		TOA		ON	FTO.TP_ORGANIZACAO_ACADEMICA	=	TOA.TP_ORGANIZACAO_ACADEMICA	WHERE TOA.TP_ORGANIZACAO_ACADEMICA		IS NULL
select distinct FTO.TP_CATEGORIA_ADMINISTRATIVA	from	DW.FTO_DADOS_IES	FTO		LEFT JOIN	DW.DIM_TIPO_CATEGORIA_ADMINISTRATIVA	TCA		ON	FTO.TP_CATEGORIA_ADMINISTRATIVA	=	TCA.TP_CATEGORIA_ADMINISTRATIVA	WHERE TCA.TP_CATEGORIA_ADMINISTRATIVA	IS NULL
select distinct FTO.CO_IES						from	DW.FTO_DADOS_IES	FTO		LEFT JOIN	DW.DIM_IES								IES		ON	FTO.CO_IES						=	IES.CO_IES						WHERE IES.CO_IES						IS NULL

select distinct	fto.CO_IES						from 	DW.FTO_DADOS_CURSO	FTO		LEFT JOIN	DW.DIM_IES						IES		ON	FTO.CO_IES				=	IES.CO_IES					where IES.CO_IES				is null
*/
/*


-- ajustes de caixa de texto
select * from information_schema.tables where table_schema =  'DW' AND TABLE_NAME LIKE 'DIM%'

SELECT TOP 100 * FROM DW.DIM_CINE
SELECT TOP 100 * FROM DW.DIM_CURSO
SELECT TOP 100 * FROM DW.DIM_IES
SELECT TOP 100 * FROM DW.DIM_REGIAO
SELECT TOP 100 * FROM DW.DIM_TIPO_CATEGORIA_ADMINISTRATIVA
SELECT TOP 100 * FROM DW.DIM_TIPO_DIMENSAO
SELECT TOP 100 * FROM DW.DIM_TIPO_GRAU_ACADEMICO
SELECT TOP 100 * FROM DW.DIM_TIPO_MODALIDADE_ENSINO
SELECT TOP 100 * FROM DW.DIM_TIPO_NIVEL_ACADEMICO
SELECT TOP 100 * FROM DW.DIM_TIPO_ORGANIZACAO_ACADEMICA
SELECT TOP 100 * FROM DW.DIM_TIPO_REDE

update dw.dim_ies set no_ies = [ODS].[FS_ODS_PASCALCASE](no_ies)
update dw.dim_ies set no_MANTENEDORA = [ODS].[FS_ODS_PASCALCASE](no_MANTENEDORA )
update dw.dim_ies set SG_ies = upper(SG_ies )


update dw.dim_curso set no_curso = [ODS].[FS_ODS_PASCALCASE](no_curso)
*/


/* GEração de dicionário de dados

SELECT TABLE_CATALOG, TABLE_SCHEMA, TABLE_NAME, COLUMN_NAME, ORDINAL_POSITION, IS_NULLABLE, DATA_TYpE, CHARACTER_MAXIMUM_LENGTH FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = 'DW'
*/

