CREATE TABLE [stg].[STG_MICRODADOS_CADASTRO_IES_SP] (
    [NU_ANO_CENSO]                   SMALLINT      NULL,
    [NO_REGIAO_IES]                  VARCHAR (20)  NULL,
    [CO_REGIAO_IES]                  TINYINT       NULL,
    [NO_UF_IES]                      VARCHAR (50)  NULL,
    [SG_UF_IES]                      VARCHAR (2)   NULL,
    [CO_UF_IES]                      TINYINT       NULL,
    [NO_MUNICIPIO_IES]               VARCHAR (150) NULL,
    [CO_MUNICIPIO_IES]               INT           NULL,
    [IN_CAPITAL_IES]                 TINYINT       NULL,
    [NO_MESORREGIAO_IES]             VARCHAR (100) NULL,
    [CO_MESORREGIAO_IES]             SMALLINT      NULL,
    [NO_MICRORREGIAO_IES]            VARCHAR (100) NULL,
    [CO_MICRORREGIAO_IES]            INT           NULL,
    [TP_ORGANIZACAO_ACADEMICA]       TINYINT       NULL,
    [TP_CATEGORIA_ADMINISTRATIVA]    TINYINT       NULL,
    [NO_MANTENEDORA]                 VARCHAR (100) NULL,
    [CO_MANTENEDORA]                 INT           NULL,
    [CO_IES]                         INT           NULL,
    [NO_IES]                         VARCHAR (200) NULL,
    [SG_IES]                         VARCHAR (20)  NULL,
    [DS_ENDERECO_IES]                VARCHAR (255) NULL,
    [DS_NUMERO_ENDERECO_IES]         VARCHAR (20)  NULL,
    [DS_COMPLEMENTO_ENDERECO_IES]    VARCHAR (150) NULL,
    [NO_BAIRRO_IES]                  VARCHAR (100) NULL,
    [NU_CEP_IES]                     INT           NULL,
    [QT_TEC_TOTAL]                   INT           NULL,
    [QT_TEC_FUNDAMENTAL_INCOMP_FEM]  INT           NULL,
    [QT_TEC_FUNDAMENTAL_INCOMP_MASC] INT           NULL,
    [QT_TEC_FUNDAMENTAL_COMP_FEM]    INT           NULL,
    [QT_TEC_FUNDAMENTAL_COMP_MASC]   INT           NULL,
    [QT_TEC_MEDIO_FEM]               INT           NULL,
    [QT_TEC_MEDIO_MASC]              INT           NULL,
    [QT_TEC_SUPERIOR_FEM]            INT           NULL,
    [QT_TEC_SUPERIOR_MASC]           INT           NULL,
    [QT_TEC_ESPECIALIZACAO_FEM]      INT           NULL,
    [QT_TEC_ESPECIALIZACAO_MASC]     INT           NULL,
    [QT_TEC_MESTRADO_FEM]            INT           NULL,
    [QT_TEC_MESTRADO_MASC]           INT           NULL,
    [QT_TEC_DOUTORADO_FEM]           INT           NULL,
    [QT_TEC_DOUTORADO_MASC]          INT           NULL,
    [IN_ACESSO_PORTAL_CAPES]         TINYINT       NULL,
    [IN_ACESSO_OUTRAS_BASES]         TINYINT       NULL,
    [IN_ASSINA_OUTRA_BASE]           TINYINT       NULL,
    [IN_REPOSITORIO_INSTITUCIONAL]   TINYINT       NULL,
    [IN_BUSCA_INTEGRADA]             TINYINT       NULL,
    [IN_SERVICO_INTERNET]            TINYINT       NULL,
    [IN_PARTICIPA_REDE_SOCIAL]       TINYINT       NULL,
    [IN_CATALOGO_ONLINE]             TINYINT       NULL,
    [QT_PERIODICO_ELETRONICO]        INT           NULL,
    [QT_LIVRO_ELETRONICO]            INT           NULL,
    [QT_DOC_TOTAL]                   INT           NULL,
    [QT_DOC_EXE]                     INT           NULL,
    [QT_DOC_EX_FEMI]                 INT           NULL,
    [QT_DOC_EX_MASC]                 INT           NULL,
    [QT_DOC_EX_SEM_GRAD]             INT           NULL,
    [QT_DOC_EX_GRAD]                 INT           NULL,
    [QT_DOC_EX_ESP]                  INT           NULL,
    [QT_DOC_EX_MEST]                 INT           NULL,
    [QT_DOC_EX_DOUT]                 INT           NULL,
    [QT_DOC_EX_INT]                  INT           NULL,
    [QT_DOC_EX_INT_DE]               INT           NULL,
    [QT_DOC_EX_INT_SEM_DE]           INT           NULL,
    [QT_DOC_EX_PARC]                 INT           NULL,
    [QT_DOC_EX_HOR]                  INT           NULL,
    [QT_DOC_EX_0_29]                 INT           NULL,
    [QT_DOC_EX_30_34]                INT           NULL,
    [QT_DOC_EX_35_39]                INT           NULL,
    [QT_DOC_EX_40_44]                INT           NULL,
    [QT_DOC_EX_45_49]                INT           NULL,
    [QT_DOC_EX_50_54]                INT           NULL,
    [QT_DOC_EX_55_59]                INT           NULL,
    [QT_DOC_EX_60_MAIS]              INT           NULL,
    [QT_DOC_EX_BRANCA]               INT           NULL,
    [QT_DOC_EX_PRETA]                INT           NULL,
    [QT_DOC_EX_PARDA]                INT           NULL,
    [QT_DOC_EX_AMARELA]              INT           NULL,
    [QT_DOC_EX_INDIGENA]             INT           NULL,
    [QT_DOC_EX_COR_ND]               INT           NULL,
    [QT_DOC_EX_BRA]                  INT           NULL,
    [QT_DOC_EX_EST]                  INT           NULL,
    [QT_DOC_EX_COM_DEFICIENCIA]      INT           NULL
);




GO
CREATE CLUSTERED INDEX [ixc_STG_MICRODADOS_CADASTRO_IES_SP]
    ON [stg].[STG_MICRODADOS_CADASTRO_IES_SP]([NU_ANO_CENSO] ASC, [CO_IES] ASC);

