CREATE TABLE [stg].[STG_DADOS_FLUXO] (
    [codigo_ies]                      INT              NULL,
    [nome_ies]                        NVARCHAR (100)   NULL,
    [categoria_administrativa]        INT              NULL,
    [organizacao_academica]           INT              NULL,
    [codigo_curso]                    INT              NULL,
    [nome_curso]                      NVARCHAR (200)   NULL,
    [codigo_regiao_geografica]        INT              NULL,
    [codigo_uf]                       INT              NULL,
    [codigo_municipio]                INT              NULL,
    [grau_academico]                  INT              NULL,
    [modalidade_ensino]               INT              NULL,
    [codigo_area_curso_cine]          NVARCHAR (100)   NULL,
    [nome_area_curso_cine]            NVARCHAR (100)   NULL,
    [codigo_grande_area_curso_cine]   INT              NULL,
    [nome_grande_area_curso_cine]     NVARCHAR (100)   NULL,
    [ano_ingresso]                    INT              NULL,
    [ano_referencia]                  INT              NULL,
    [prazo_integralizacao_anos]       INT              NULL,
    [ano_integralizacao_curso]        INT              NULL,
    [prazo_acompanhamento_curso_anos] INT              NULL,
    [ano_max_acompanhamento]          INT              NULL,
    [qtd_ingressante_curso]           INT              NULL,
    [qtd_permanencia_curso]           INT              NULL,
    [qtd_concluinte_curso]            INT              NULL,
    [qtd_desistencia_curso]           INT              NULL,
    [qtd_falecimentos_curso]          INT              NULL,
    [TAP]                             NUMERIC (18, 10) NULL,
    [TCA]                             NUMERIC (18, 10) NULL,
    [TDA]                             NUMERIC (18, 10) NULL,
    [TCAN]                            NUMERIC (18, 10) NULL,
    [TDAN]                            NUMERIC (18, 10) NULL,
    [origem]                          NVARCHAR (100)   NULL
);

